### ISSUE TITLE
Alliance Nightelf Shadowmeld bugged (PVP)

### ISSUE THREAD

**Issue by Dexra** [chromiecraft/chromiecraft#726] opened 2021-05-29 10:22 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS Chromiecraft client
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

 Shadowmeld doesn't puts you out of Combat in PvP if u have debuffs on you. Very rarely it works tho.
I "tested" this on my warrior "Jarod" the top 5 character of the Month with  around 300 BG's played yet.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
 Shadowmeld should always put you out of combat no matter what or how many debuffs u have on yourself. Dot damage will still break ur stealth but doesn't hinder u from leaving combat ! only exception here is Faerie fire since it doesn't let u use Shadowmeld at all. 

##### STEPS TO REPRODUCE THE PROBLEM:
 1. create a Nelf warrior and make a macro like this:
/cast battle stance
/cast shadowmeld
/cast charge
2. Debuff the warrior with any Debuff (rogue poisons, paladin Judgements etc.
3. use the Shadowmeld/charge macro and see what u can do to make it work 100% of times but not like 20% of times

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment] 2021-05-30 10:40
duplicate of https://github.com/chromiecraft/chromiecraft/issues/483

**Closed by Helias** 2021-05-30 10:40 UTC
Labels: Needs Triage
