### ISSUE TITLE
Private Hendel re: "The missing diplomat" non-functional.

### ISSUE THREAD

**Issue by mr-polar-bear** [chromiecraft/chromiecraft#2019] opened 2021-10-08 05:43 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Private Hendel (Sentry point - outside Theramore) quest NPC is hostile and at 1 hp, cannot be harmed, cannot respond to players for the quest "The missing diplomat". Just keeps attacking & being attacked by guards.

### Expected Blizzlike Behaviour

NPC should be interactive, and spawn the next phase of the quest line. (Turns hostile & two "friends" spawn to defend him)

### Steps to reproduce the problem

1. Be on the quest "The missing diplomat" at the correct phase.
2. Attempt to interact with him. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Daedalus007** [comment] 2021-10-11 00:43
Some missing data here.
NPC in question: https://tbc.wowhead.com/npc=4966/private-hendel#comments
Video of the quest on WoW Classic: https://www.youtube.com/watch?v=1nlDIXYygio
Relevant portion starts around 8 minute 30 second mark and goes from there.  Since another semi-related bug posted above is also involved, it may help resolve that one as well.

**Comment by Shineslippers** [comment] 2021-11-20 21:13
Sorry for inconvenience, but i have to close it as duplicate of https://github.com/chromiecraft/chromiecraft/issues/1683

**Closed by Shineslippers** 2021-11-20 21:13 UTC
Labels: Confirmed, Linked [AC], [30 - 39]
