### ISSUE TITLE
Quest "Stranglethorn Fever" won't trigger the summon for "Mokk"

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#1065] opened 2021-07-03 15:24 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you talk to unbagwa and he tries to summon mokk he'll get stuck trying to summon him.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Unbagwa should be able to summon mokk without a hitch.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Amrx2** [comment] 2021-07-03 18:16
Confirmed that Mokk doesn't currently get summoned. You provide a fang to Unbagwa, he does the summon animation as well as the correct text ("Get ready everyone! Here come de apes!") but nothing further happens.

**Comment by syssneck** [comment] 2021-07-03 20:04
I can't confirm it from my side. I did the quest like two hours ago on chromiecraft without any problems. Maybe we need more tests or steps to reproduce the bug.

**Comment by Stump876** [comment] 2021-07-04 01:59
Thanks for the report. Unfortunately I was unable to duplicate. I do suggest putting steps to reproduce.
![image](https://user-images.githubusercontent.com/68164076/124370865-a9307c00-dc30-11eb-9bcc-95a9e09290ae.png)


Which Doctor Unbagwa GUID 1219  
Quest ID 349

**Comment by Shibath** [comment] 2021-07-04 06:48
![image](https://user-images.githubusercontent.com/82077179/124375838-38ed2d80-dcf8-11eb-9719-fae9fbc8e4d7.png)

When i turned up to the cave he has a summoning action showing but won't interact with my character.

Can't complete next part of the quest

**Comment by syssneck** [comment] 2021-07-04 09:04
Do you have the fang for him? Did you try to relog?

**Comment by Amrx2** [comment] 2021-07-04 13:24
Fangs were present, just want to state in world chat today at least 20 other people have confirmed this quest is bugged for them. It does appear however that a small number have managed to complete the quest somehow yesterday.

**Comment by RuffusCC** [comment] 2021-07-04 17:10
Hello ! Confirmed. I have the same "bug", the NPC is just casting something I guess it's the summon and that's it.

**Comment by gurveleg** [comment] 2021-07-04 21:06
I just went to try and do the quest myself. He is stuck in the summoning state and can't even be interacted with so can't even begin the quest.

**Comment by Shibath** [comment] 2021-07-05 03:27
i went back to him this afternoon, had the blue Question mark and quest could proceed as expected.
Summoned the apes and allowed the quest to be completed

**Comment by temperrr** [comment] 2021-07-06 15:48
Sorry that this took so long. I managed to replicate the bug.
It happens when you hand in the item for a second time to start to summoning. He won't summon the apes and will be stuck.

Thanks for all your inputs, they were very helpful

**Comment by Amrx2** [comment] 2021-07-27 23:24
So this has bugged again, the witch doctor is stuck again in a state of casting. Can confirm it happened to a few players this evening

**Comment by Gromzak** [comment] 2021-07-27 23:31
Bugged again.. witch doctor seems is like perma casting.. and cant talk with him

**Comment by FrancescoBorzi** [comment] 2021-08-05 10:32
@chromiecraft/bug-triaging

**Comment by temperrr** [comment] 2021-08-06 10:01
I tried to replicate the issue again, but I could not. @Gromzak @Amrx2  do you have any information to replicate this bug?

**Comment by Amrx2** [comment] 2021-08-06 10:04
Negative sorry, I am not sure what could have caused this to break again. When I checked it, it was stuck again in the summoning position and nobody can interact, none of the apes get summoned. A server restart didn't resolve it either hence why it was reopened. Potentially another fix elsewhere has resolved this now again, haven't had more reports in the last 3 days about it and seems to have "fixed itself" again.

**Comment by temperrr** [comment] 2021-08-06 10:05
I did the quest just fine as well two days ago as alliance, so it did fix itself indeed.

**Comment by Amrx2** [comment] 2021-08-06 10:07
I'll close this for now, if it happens again it's something else causing it to break. Thanks Temperr.

**Comment by shilofax** [comment] 2021-08-29 16:16
This appears to be bugged still as of 8/29/21

Witch Doctor Unbagwa is stuck and quest cannot be started.

**Comment by TheRiddermark** [comment] 2021-11-17 15:38
@Shineslippers 
22 days ago but right now in this very moment 17.11.2021 - the quest is bugged. I'm right next to the guy, but right clicking him does nothing. I got 9 fangs and what's stranger is that I've done this quest on all my alts so far and never had a problem.

![image](https://user-images.githubusercontent.com/88625031/142231590-40339c9d-8ff7-4a26-bc9d-087060f65e13.png)

**Comment by Maurowin** [comment] 2021-11-17 18:17
Since the migration to the new system, bugs that have been fixed as well as new bugs have appeared/reappeared.

**Comment by Shineslippers** [comment] 2021-11-17 19:07
@TheRiddermark well i can confirm it, but it's mostly about my incompetence. I didn't check quest with fail factor.

**Comment by TheRiddermark** [comment] 2021-11-18 16:48
@Maurowin sounds like I need to level a new character again and pay attention. Need to gather some energy for this! haha
@Shineslippers Thanks again for the lightning reaction!

**Comment by Rykehuss** [comment] 2021-11-20 20:27
Quest still bugged.

**Comment by Shineslippers** [comment] 2021-11-20 20:34
@Rykehuss, yes, but restart/crash restore capability to start it.

**Comment by natnat201193** [comment] 2021-11-28 15:27
This bug is caused by some idiot starting the event and not finishing it.

**Comment by natnat201193** [comment] 2021-12-08 10:53
Just tested this on the retail tbc PTR, also sniffed some data.
- The Gorillas should actually run to the back of the cave, not just Infront of it.
- if no one gets aggro on them or kills them, they will fight Witch Doctor Unbagwa instead and if they kill him, they will stay in the back of the cave for around 60 seconds before despawning.
- The Witch Doctor's faction should be default 35, then set to 495 during the event and back to 35 after.
- The Witch Doctor's respawn time is about 5 minutes.

**Comment by FrancescoBorzi** [comment] 2021-12-15 10:48
@natnat201193 thanks for your feedback, better post it directly on the AC issue next time:

https://github.com/azerothcore/azerothcore-wotlk/issues/6774

that's where we want to keep the technical discussion, here is just to allow players to report the bugs :)

**Comment by Mizffs** [comment] 2021-12-25 19:24
Still bugged. Cant talk to Doctor and he is standing in some kind of summoning mode.

**Comment by davegrier** [comment] 2022-01-23 09:10
Witch Doctor Unbagwa is stuck in summon mode on 1/23/22 
![image](https://user-images.githubusercontent.com/14080595/150671850-84e1e71f-39da-496b-a179-68018cb9814c.png)

**Comment by imp2001** [comment] 2022-01-28 01:44
Confirmed can not interact with the Witch Doctor, so can not start any quest.  I don't see any hands glowing "summoning mode" tho.

**Comment by eTzmNcbkrng** [comment] 2022-02-06 00:02
Appears this quest only works once per server restart.

**Closed** 2022-03-18 22:38 UTC
Labels: Confirmed, Linked [AC], [40 - 49]
