### ISSUE TITLE
Solid Chests in Stranglethorn Vale failing to despawn

### ISSUE THREAD

**Issue by Beastmasterwow** [chromiecraft/chromiecraft#458] opened 2021-04-23 22:37 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [ X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Today I looted several Solid Chest 's In Stranglethorn Vale and several of them didn't despawned after being looted. I waited 2 minutes to see if the chest will eventually despawn but it didn't. After that I clicked on the Solid Chest again in order to loot it but it was empty and after that it disappeared. Yesterday I also encountered this problem but it was in much less cases.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Solid Chest in STV
2. Don't know what that is.
3. Don't know what that is.
4.

##### EXTRA NOTES:

Type here.
Try on several Solid Chest 's to confirm the bug

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-04-24 07:23
Couldn't reproduce this. Just ran around STV on my dwarf for a while and collected about 20 Solid Chests, none of them behaved incorrectly.

Were you in a party at the time? If so it's probably an instance of https://github.com/azerothcore/azerothcore-wotlk/issues/5128

**Comment by Beastmasterwow** [comment] 2021-04-24 15:04
Yes, I was in a party yesterday, but today same happened when I was solo. I'm also a dwarf and when I loot the chest it still appears on my minimap.

**Comment by Azcobu** [comment] 2021-04-25 01:34
In that case, I have more questions:
- Sounds like you're getting this quite often. At a rough guess, how often is it happening? Like, every second chest, every tenth, or somewhere in between?
- Is it happening to any chests in particular, or in some specific area, or is it all over STV?
- Are any other container types like food crates or nectar barrels affected?
- When it happens, do other people in party see the chest behaving weirdly too?

What I might ask you to do is next time it happens, type '.gobject near' (without the quotes and including the full stop) while standing near the chest and take a screenshot of the output. Grab a couple if you can and paste them into one of these editing windows, that might help narrow it down a bit. Cheers.

**Comment by Amrx2** [comment] 2021-04-27 08:45
The follow chest has an extremely short spawn time, ranging from instant up to 2 minutes in STV. .gobject included.

X:-11567.400391 Y:-574.547974

![Chest respawn](https://user-images.githubusercontent.com/80728005/116212940-40fb8080-a73d-11eb-81e3-3f55d8fc66ae.JPG)

**Comment by FrancescoBorzi** [comment] 2021-04-27 15:25
> The following chest has an extremely short spawn time, ranging from instant up to 2 minutes in STV. .gobject included.
> 
> X:-11567.400391 Y:-574.547974
> 
> ![Chest respawn](https://user-images.githubusercontent.com/80728005/116212940-40fb8080-a73d-11eb-81e3-3f55d8fc66ae.JPG)

looks like the same ID has several spawns all going from 15m to 2h of respawn time, except the one pointed by @Amrx2 which has only 2 minutes respawn time.

**Comment by Azcobu** [comment] 2021-05-08 09:17
Closing as per https://github.com/azerothcore/azerothcore-wotlk/pull/5498

**Closed by Azcobu** 2021-05-08 09:17 UTC
Labels: Closed, Fixed, Generic Issues
