### ISSUE TITLE
Mobs loot, while in party with quest items: no skinnable mob

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#563] opened 2021-05-07 16:53 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

To replicate this bug some prehable is needed:

1. make a group, minimum 2 players
2. one of them has auto-loot enabled, other has not
3. group loot is set as active loot method
4. quest that involve into picking up something from skinnable mobs is needed (aka: hearth of raptors or so on)
5. kill the mob, that should have quest item inside his loot
6. let user without auto-loot to loot first (quest item too)
7. loot your loot (if available)
8. now skinnable mob has empty loot, but skinning is forbidden because warning message says that "Some loot is still available"

note: this bug not seems to apply if loot is different from "group loot" and may be "reset" if passing from "group loot" to another kind of loot, than back to group loot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. Kill mob
2. loot mob (with or withous quest items)
3. when everybody has looted the corpse, if it is skinnable from party members -> skin it
4. end

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Hard to reproduce in video, but we reproduced this more than once in this days, even in random groups.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment] 2021-05-15 22:14
@necropola how come there is a fix but not yet an AC issue for this? :)

**Comment by necropola** [comment] 2021-05-15 23:55
@FrancescoBorzi Not sure that it is a fix for this issue, too.

**Comment by necropola** [comment] 2021-05-19 19:07
@lovelord83 Does the issue still exist or was it fixed by one of the recent patches?

**Comment by lovelord83** [comment] 2021-05-19 20:02
I will try to reproduce this in next days and I let you know.Inviato dal mio Galaxy<div>
</div><div>
</div><div>-------- Messaggio originale --------</div><div>Da: Necropola ***@***.***> </div><div>Data: 19/05/21  21:08  (GMT+01:00) </div><div>A: chromiecraft/chromiecraft ***@***.***> </div><div>Cc: lovelord83 ***@***.***>, Mention ***@***.***> </div><div>Oggetto: Re: [chromiecraft/chromiecraft] Mobs loot, while in party with quest items: no skinnable mob (#563) </div><div>
***@***.*** Does the issue still exist or was it fixed by one of the recent patches?

**Comment by skneko** [comment] 2021-05-19 21:07
I have been experiencing this issue the last few days, but today I have not been able to reproduce it anymore. I am not sure if I am breaking one of the assertions without noticing, or if it has been fixed.

**Comment by necropola** [comment] 2021-05-25 05:54
Since nobody seems to be able to reproduce this anymore, I deduce that this issue was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/5774, too. Closing as fixed. Feel free to reopen, if it wasn't.

**Closed by necropola** 2021-05-25 05:54 UTC
Labels: Closed, Fixed
