### ISSUE TITLE
[Eastern Plaguelands Zone] - Untargetable Herb Object

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#3579] opened 2022-06-05 00:18 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Can not target black lotus

### Expected Blizzlike Behaviour

Targetable black lotus

### Steps to reproduce the problem

1. go near 20264 Entry: 176589 - Black Lotus
2. Location 35.6, 20.6

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2de12c79374bdb77396e60b2c44975ed69d8acec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Jinmcx** [comment] 2022-06-05 00:18
![WoWScrnShot_060422_170408](https://user-images.githubusercontent.com/19652090/172029755-9d4e0e27-3f41-4bde-a64d-1e490887d7a6.jpg)

**Comment by DarylBlake21** [comment] 2022-06-07 05:51
I think this was already reported. They haven't fixed it for weeks.

**Comment by Luckdemon** [comment] 2022-06-09 22:07
Duplicate of #3192

**Closed by Luckdemon** 2022-06-09 22:07 UTC
Labels: Needs Triage

**Comment by Gultask** [comment] 2022-06-09 22:15
Ah yes, THAT Black Lotus. The current spawn point is out in the open, which I think it's weird how it can't be seen.
Also the vast majority of spawn locations come from sniffs, and the Black Lotus has a particular mechanic that makes it very time-consuming to force a spawn, so it's difficult to prove where exactly it should be.

Here's a picture of the spawn location found in the database:

![WoWScrnShot_060922_190827](https://user-images.githubusercontent.com/100873791/172954223-82a5d0ad-f3dd-453d-b835-f560443260de.jpg)
