### ISSUE TITLE
[Midsummer Festival] Torch Tossing quest is repeatable/daily

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#956] opened 2021-06-22 07:59 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Torch tossing quest is repeatable daily (https://wowgaming.altervista.org/aowow/?quest=11731).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Torch tossing quest should be only doable 1 time, then opening up the daily quest More Torch Tossing (https://wowgaming.altervista.org/aowow/?quest=11921)

##### SOURCE:

https://tbc.wowhead.com/quest=11731/torch-tossing#comments
##### STEPS TO REPRODUCE THE PROBLEM:

1. Complete Torch Tossing and More Torch Tossing quests
2. Check in next day and see Torch Tossing Available again, but not More Torch Tossing

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by liviu-macovei** [comment] 2021-06-22 09:31
This is even worse, if you logout you can do it right away again. Every time you log in the quest is reset.

**Comment by Azcobu** [comment] 2021-06-22 12:24
Just tried this on redside, and didn't run into any issues. I had done Torch Tossing + More Torch Tossing yesterday, and today when I logged in to check this ticket, only MTT was available. Also, logging out didn't reset the quest for me. Was this the Ally or Horde version of the event?

**Comment by gurveleg** [comment] 2021-06-22 12:47
Ally. Also it was possible to turn in quest to multiple npcs in different city, while only doing the quest 1 time. Somehow it staye din my quest log as completed and I could turn it in in Ironforge, Stromwind and Darnassus while only doing it once. It seems that there was some other issue going on that enabled this behaviour. Same thing was with that totem quest that leads to killing elementals. It reset and had to do it from start again to ge tthe daily quest.

**Comment by gurveleg** [comment] 2021-06-22 12:49
Also, sometimes the midsummer quests stayed in quest log after completing. When manually removing them, I was able to pick all of them up again, even tho i just did them.

**Comment by liviu-macovei** [comment] 2021-06-22 14:16
I  could do them over and over again in Orgrimmar as horde, every time I logged in the quest was available to complete again, the flowers would disappear upon logout but the gold stayed.

**Comment by Azcobu** [comment] 2021-06-22 14:18
So it was basically an infinite gold farm?

**Comment by gurveleg** [comment] 2021-06-22 14:20
Yes, thats why Midsummer was disabled until they fix it.

**Comment by v-mstrs** [comment] 2023-04-19 09:40
Couldn't reproduce ( not me )

**Comment by sudlud** [comment] 2023-11-09 18:27
@Kitzunu 
You closed the corresponding AC issue in https://github.com/azerothcore/azerothcore-wotlk/issues/6623#issuecomment-986284207
So should we close this too?

**Comment by sudlud** [comment] 2023-11-12 18:01
@elthehablo 
imo this can be closed as AC linked issue azerothcore/azerothcore-wotlk#6623 is closed already.

**Closed** 2023-11-12 18:02 UTC
Labels: Confirmed, Linked [AC], Generic Issues
