### ISSUE TITLE
Black Lotus spawn Eastern plaguelands

### ISSUE THREAD

**Issue by Pinio1** [chromiecraft/chromiecraft#3526] opened 2022-05-21 19:58 UTC
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

There is a bug with one single Black Lotus spawn in Eastern plaguelands. Find herb skill shows a black lotus spawn, however once you reach place black lotus cannot be found. I assume that maybe herb is spawned underground, therefore cannot be seen or picked. I noticed it planty of times during last 2 months.  Below you may find screens:

![WoWScrnShot_052122_215121](https://user-images.githubusercontent.com/97834383/169667071-d7ae10a8-8563-42c8-8729-1b075d3d5aeb.jpg)
![WoWScrnShot_052122_215236](https://user-images.githubusercontent.com/97834383/169667073-eee48720-21ac-49db-95ac-cd2d5f7840e5.jpg)
![WoWScrnShot_052122_215432](https://user-images.githubusercontent.com/97834383/169667106-2c88753e-cf16-4f47-8cbe-8ac31dab0b95.jpg)

### Expected Blizzlike Behaviour

black lotos should be available to be picked up if it is found by find herb skill.

### Steps to reproduce the problem

no idea

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment] 2022-05-22 14:39
Hi Pinio! Thanks for contributing to ChromieCraft and AzerothCore!

Oh yes **that** Black Lotus. Unfortunately I'll have to close the issue since it's a duplicate of https://github.com/chromiecraft/chromiecraft/issues/3192.
The issue is that node locations come from sniffs so we'll need another one to pin down the exact location of that herb. And that one in particular seems to have some inconsistencies in its placement, since if I teleport to its exact location it should be in a gatherable spot, so the problem might be a bit deeper than just shifting the position as well.

Thanks again for contributing! And I hope that you'll make more reports in the future! 😄

**Closed by Gultask** 2022-05-22 14:39 UTC
Labels: Needs Triage
