### ISSUE TITLE
[Enchanting Vellum] used on tradeable item in inventory, item tooltip does not display enchant, nor after /reload, only upon restart

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#1709] opened 2021-09-12 19:24 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Using +5 hit to boots enchanting scroll / vellum on a not-soulbound BoE in my inventory consumed the scroll /vellum without showing the additional 5 hit upon mousing over the boot. /reload did not show the hit, only restarting the game did.

### Expected Blizzlike Behaviour

Enchanting gear with a scroll / vellum should immediately display the additional stats granted by the enchant, as well as displaying on character pane when the item is equipped.

### Steps to reproduce the problem

Make a character without enchanting.
Acquire a BoE item, perhaps it is only boots.
Do not equip the item yet.
Use enchanting vellum on the item, perhaps it is only +5 hit to boots.
Mouseover the item & see if it displays the enchant.
Equip the item & see if character pane displays the additional stats.
If the enchant or stats doesn't display, /reload.
If still doesn't display, restart.

### Extra Notes

My character is not an enchanter.

Backlogged report on my part - I do not recall if my character actually ended up with the stats, or if it was display-only (after restart, when stats did finally display).

Did not work with +3 intellect to white weapon from vendor - +3 showed on weapon immediately, and on character pane when equipped.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment] 2021-09-13 11:22
I was playing around with different enchants and gear combos and I was unable to reproduce this bug on local AzerothCore rev. 26aee27f600d

**Comment by Azcobu** [comment] 2021-11-02 10:43
Also unable to reproduce. I tried with `.additem 45628 10` (enchant) and `.additem 10183 10` (boots) and the boots correctly displayed the enchant when it was applied every time:

![WoWScrnShot_110221_210641](https://user-images.githubusercontent.com/81782124/139831394-4e597b1b-bce4-4727-b476-4cf6d541ebd1.jpg)

Will close this accordingly.

**Closed by Azcobu** 2021-11-02 10:43 UTC
Labels: Needs Triage, Unable to Reproduce
