### ISSUE TITLE
Astaia Fishing trainer

### ISSUE THREAD

**Issue by MiszczuLaju** [chromiecraft/chromiecraft#5701] opened 2023-06-01 11:48 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

NPC in Darnassus - https://wowgaming.altervista.org/aowow/?npc=4156
This NPC doesn't respond when clicked, you can't learn to fish

### Expected Blizzlike Behaviour

After clicking teach fishing, a learning window should appear

### Source

WOTLK 3.3.5

### Steps to reproduce the problem

Try to talk
Astaia Darnassus fishing trainer
Try to learn fishing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

W11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-06-02 20:45
Cannot reproduce. Try to walk away after interacting with her the first time and come back.

**Comment by anjachan** [comment] 2023-06-24 20:46
Same thing can happen with other NPCs, such as any interacting Flight Master, Innkeeper and so on. There are 2 possible things that I observed: 1) Interaction window pops, but no button is respond-able, the "fix" is closing the window and trying again (note: it can happen multiple times in a row) 2) Interaction window doesn't pop at all so the only "fix" would be to walk far enough as the "Invisible" window closes on its own

**Comment by Salehyn** [comment] 2023-08-20 23:23
I am consistently experiencing this issue. As Bench said, it's fixed by walking a distance away and going back to the NPC.
It seems to be a range issue to me. If you interact with the NPC at maximum distance, it almost always bugs and I have to try again.

**Comment by Salehyn** [comment] 2023-08-27 23:15
Probably caused by this https://github.com/azerothcore/azerothcore-wotlk/issues/15989 but doesn't have anything to do with Astaia herself and can be easily resolved as mentioned above. Fishing trainer functions just fine.

**Closed** 2023-08-27 23:20 UTC
Labels: Unable to Reproduce
