### ISSUE TITLE
[Quest] "The Sun Gate" missing entire middlestage

### ISSUE THREAD

**Issue by Sathrenor** [chromiecraft/chromiecraft#1162] opened 2021-07-10 23:17 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest objective can be reached and completed right away without any mid-stages.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Before being able to shut down the Sun Gate, player must first disable all 4 Sunhawk Portal Controllers.
_"You must take out their portal controllers before you can destroy the gate itself! "_ as the progress quest line says.
##### STEPS TO REPRODUCE THE PROBLEM:

1.  Complete the entire storyline on Bloodmyst Isle up to [Limits of Physical Exhaustion](https://wowgaming.altervista.org/aowow/?quest=9746)
2. Accept the quest [The Sun Gate](https://wowgaming.altervista.org/aowow/?quest=9740)
3. Go to the objective location
4. Look at the 4 red rays that should came out of floating void-like shards

##### EXTRA NOTES:

**Proof:**
https://www.youtube.com/watch?v=0px1OL4iZP8

**How it should work:**
https://www.youtube.com/watch?v=p7QRvkukiZo

**GUID**: 12164, 12166, 12168, 12173
**Entry**: 184850

_(If You have any complains toward my ticket structure, feel free to correct it. I will gladly improve my reporting skills.)_

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-07-11 06:41
Thanks for the report. If I could make a suggestion about your ticket structure, I would take the "Proof" section you have in "Extra Notes" and put that under "Current Behaviour", as that is showing what is happening on CC right now. Similarly, I would move the Youtube video you have under "How it should work" to the "Source" section, as that is where proof of expected behaviour goes. These are just suggestions though, it's a perfectly fine ticket.

**Comment by Eldarix** [comment] 2021-07-11 07:16
I can't confirm it in my local AzerothCore setup (920825b7594e) It seems therefore something concrete that fails in ChromieCraft.

![WoWScrnShot_071121_100920](https://user-images.githubusercontent.com/82579073/125186042-b7822780-e230-11eb-9073-2a85dd6a652e.jpg)
![WoWScrnShot_071121_101014](https://user-images.githubusercontent.com/82579073/125186065-d41e5f80-e230-11eb-8ea6-22543b5d2ae6.jpg)

Thanks for the detailed report pal.

**Comment by syssneck** [comment] 2021-07-11 08:52
Hi all, I also had no problems with this quest on (458469e). I wasn't able to close the Sun Gate, before disabling the Sunhawk Portal Controllers:
![unknown_2021 07 11-10 48_1](https://user-images.githubusercontent.com/68868567/125188918-f8c90600-e235-11eb-9ffc-de71dced7aad.png)
After I disabled them, I was able to close the Sun Gate (as it should be):
![unknown_2021 07 11-10 49](https://user-images.githubusercontent.com/68868567/125188948-1a29f200-e236-11eb-823f-de4c8d75ab0d.png)

**Comment by Sathrenor** [comment] 2021-07-12 15:31
Could it be for some reason tied to a race You play? As I see You both used draenei, while I was played as a Night Elf when this bug occurred. Or as Eldarix said, it could be more Chromie-related than core itself.
Would appreciate more tests though.

_P.S.
It was the very last quest in the zone I have done. Not sure if it influences the issue at any capacity, but I considered it worth noting._

**Comment by Eldarix** [comment] 2021-07-13 07:57
![WoWScrnShot_071321_105519](https://user-images.githubusercontent.com/82579073/125413763-852ceb69-8109-4269-9114-35a522019282.jpg)

Seems not related to the chosen species neither, at least with the dwarfs are confirmed to work too :D :D

**Comment by temperrr** [comment] 2021-07-26 09:16
I did this quest on Chromiecore as well, I could not press the main thing without destroying the controllers. Seems to be pretty rare. I am going to close this for now. If anyone manages to reproduce, please state so below.

**Closed by temperrr** 2021-07-26 09:16 UTC
Labels: Needs Triage, Needs second opinion, Unable to Reproduce
