### ISSUE TITLE
[Feralas][Quest] Wandering Shay still is bugged

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#3766] opened 2022-07-11 15:59 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Issues seem closed and "fixed", so here's a new one

Still exactly as described here https://github.com/chromiecraft/chromiecraft/issues/1783

> The quest "Wandering Shay" requires us to find Shay and bring her back to the questgiver's camp. It is easy to find her. Getting her back to the camp is the problem. Once you start moving and the NPC starts following you, her whole model disappears and becomes completely invisible. You can see her if you move your camera around but only at certain angles. You can target her and see that when she is "following" you, she jumps around to your location every second, never really running/walking towards you. At the end, bringing her to the camp doesn't trigger anything. No text, no completion, nothing. ![1](https://user-images.githubusercontent.com/89902163/133894426-c377e4e5-ecd8-49ce-b21d-a9ba76592708.png) ![2](https://user-images.githubusercontent.com/89902163/133894429-9918a9a3-3a2c-4506-8984-cdba3b595216.png)

### Expected Blizzlike Behaviour

> I believe it is expected for the NPC to not disappear and still be visible at all times. Also for her not to jump around and actually follow you by running/walking and for the quest to be actually completed once the NPC is in the triggering zone.

### Source

https://youtu.be/2DXOsO7Lv3I

### Steps to reproduce the problem

1. Do the quest

### Extra Notes

Quest - [Wandering Shay](https://wowgaming.altervista.org/aowow/?quest=2845)
Questgiver - [Rockbiter ](https://wowgaming.altervista.org/aowow/?npc=7765) 
NPC to find and bring back - [Shay Leafrunner ](https://wowgaming.altervista.org/aowow/?npc=7774)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment] 2022-08-04 17:45
I was able to complete this quest but the problem with the teleporting is that it's not a bug that's present in a local server, only in Chromiecraft to my knowledge. Looking at it again really quick it's still the same. She follows me normally in a local but not in CC.

**Comment by Sathrenor** [comment] 2022-08-19 01:32
Meanwhile end-of-quest dialogue worked for me, I can confirm the **teleporting** and **missing model** issues _(Although it's visible when she is fighting)_, but there may be an issue with NPC resetting after abandoning the quest as well, since for me she wasn't at the [The Giant Guardian](https://wowgaming.altervista.org/aowow/?quest=2844) marker, but stuck wandering around like during a quest 
_(I have no data who and when did it, so the last part is under a question mark)_.

https://www.youtube.com/watch?v=ay6bcJ3HkgY

Adding data info as well:
[Rockbiter](https://wowgaming.altervista.org/aowow/?npc=7765) _DB Guid:_ **50082** _Entry_: **7765**
[Shey Leafrunner - **AoWoW DB ERROR** ](https://wowgaming.altervista.org/aowow/?npc=7774) _DB Guid_: **50144** _Entry_: **7774**

**Comment by Stump876** [comment] 2022-09-04 22:26
This looks to a duplicate of an existing issue still open https://github.com/chromiecraft/chromiecraft/issues/2186

**Closed** 2022-09-04 22:28 UTC
Labels: Duplicate, Closed
