### ISSUE TITLE
Wandering Shay quest

### ISSUE THREAD

**Issue by simonasbuj** [chromiecraft/chromiecraft#2186] opened 2021-10-24 19:19 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

You have to escort Shay in Feralas.

She doesnt walk, but just teleports around.

You also have an item Shay's Bell, if she dissapears you're supposed to use it and she will come back. When I try to use it channels for millisecond and then says "You can't do it right now"

EDIT: ok the bell actually works, if you use it closer to her? but its impossible to see where she is... but her walking animations are still screwed

### Expected Blizzlike Behaviour

Shay walks instead of teleporting probably?
Also Bell item brings her back to you.

### Steps to reproduce the problem

1. Start quest Wandering Shay
2. You will immediately see she's teleporting instead of walking.
3. Using bell doesnt work.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Jonsse** [comment] 2021-12-09 15:06
This is still an issue.
https://i.imgur.com/FIe8wkJ.mp4

**Comment by Shineslippers** [comment] 2021-12-09 18:22
Still can't repeat. Looks like it's related not to quest, but to server. Need to ask Devs.

**Comment by BeefSteaker** [comment] 2022-09-26 16:39
tested on live and ptr, unable to reproduce.

its a year old bug so something has likely fixed it in the meanitme

**Comment by KuristZero** [comment] 2023-01-21 15:00
Hey folks, just chiming in with the same issue on this quest today - 21st Jan, 2023 on a Windows 10 machine (Ryzen 5900X w 3070 and fibre connection of 100mb/s)

The NPC of Shay does teleport instead of running alongside the character and at certain angles, her character model disappears.
She also appears to swap between a static model while moving and a normal model during combat - don't have enough experience with AC to suggest why that would be the case.

No issue with the bell on my instance (EnUS 3.3.5a), just buggy walking animation.

**Comment by heyitsbench** [comment] 2023-06-03 02:03
Please do not add the 'fixed' label for a still open PR. That label (if I'm not mistaken) should only be applied when the PR has both been merged and pulled into CC's repo on a server update.

**Comment by The-GhostRider** [comment] 2023-06-09 08:47
> Please do not add the 'fixed' label for a still open PR. That label (if I'm not mistaken) should only be applied when the PR has both been merged and pulled into CC's repo on a server update.

Thanks for the clarification, I hadn't noticed it, but it was an oversight, I know very well how these Labels work, since I created most of them in 2021 and I wrote each description. among these created by me, there are just "Fixed" and "Fix Ready". 😀☮✌

**Closed** 2023-06-26 02:44 UTC
Labels: Confirmed, Linked [AC], Fix Ready
