### ISSUE TITLE
[Scholomance & Stratholme] Dying inside these dungeons will get you to The Barrens graveyard [Horde]

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1934] opened 2021-10-02 17:49 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Dying in middle of instance as horde (nor sure for alliance) gets you to The Barrens Graveyard --> Ress sicness is only option
![WoWScrnShot_100221_181725](https://user-images.githubusercontent.com/80590226/135727015-d7880eae-8c64-4f39-afbf-b5b2afc8691a.jpg)

### Expected Blizzlike Behaviour

Graveyard in their zones.

### Steps to reproduce the problem

1. Get to Stratholme or Scholo
2. Die
3. Get to wrong graveyard

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment] 2021-10-03 00:24
I'm unable to reproduce this. I tried dying as a horde at several different parts of the instance, always got ported to Caer Darrow.

**Comment by Elexias** [comment] 2021-10-03 07:16
It is not first time that it happened, we were in 3 stratholmes in 1 scholomance ,each death got us to The Barrens. We did queue via RDF. Not sure if you did check like that.

**Comment by Elexias** [comment] 2021-11-28 06:40
What will happend with this issue? I mean you did not try RDF @Nyeriah, happened in first few days of Stratholme/Scholomance. I was first to report it, and not even linked to AC. People massively talked about this. Also you can see that I got argent dawn reputation few seconds before I was on this graveyard.

**Comment by Elexias** [comment] 2021-11-28 06:40
You can also see other party members on minimap

**Comment by temperrr** [comment] 2022-07-19 04:07
Since we could not reproduce the issue, I will close it.

**Closed by temperrr** 2022-07-19 04:07 UTC
Labels: Needs Triage, Bug Under Evaluation, More Research Needed
