### ISSUE TITLE
Guards in the LV 1-13 Undead Area are not attacking hostile mobs (Tisfal glades, Undead starting area, Brill..)  

### ISSUE THREAD

**Issue by m0ll3art** [chromiecraft/chromiecraft#2551] opened 2021-12-11 15:02 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Guards in the Brill area (Trisfal Glades) are not attacking when mobs arrive. This is also valid for the undead starter area  

### Expected Blizzlike Behaviour

Guards should attack the mobs 

### Source

Retail back in the 3.3.5(a) time period, other azerothcore powered server like sindragosa (ex Sunwell) 

### Steps to reproduce the problem

1. with a character go to Brill or in the Undead starter area 
2. observe guards behavior when a (hostile) mob approaches a guard , stationary or a patrolling one, **nothing happens** guard is not attacking as it is supposed to. 
3. attack a hostile mob and let is chase you and try to pass near a guard, stationary or a patrolling one and observe behavior, which is **not attacking** the mob 

### Extra Notes

normally guards attacking hostile mobs near safe places are lifesaving, in particular in those starting zones LV 1-13 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-13 19:57
Thank you for the report, but you have to specify NPCs. Certain NPCs doesn't attack, but guards doing it.

**Comment by Gultask** [comment] 2022-06-11 03:57
All low-level mobs in starting areas do not bother the guards because the mobs are non-hostile (yellow names). If you pull a red creature to them they'll defend you with their lives.

Since WotLK changed starting area creatures we might need confirmation from WotLK Classic to make sure. The behaviour from other private servers won't help here, since they might not be necessarily blizzlike.

**Comment by FrancescoBorzi** [comment] 2024-11-10 22:52
closing as not easy to reproduce a long time ago and no updates received for a long time. If anyone encounters this issue again, please leave a comment and we will reopen it.

**Closed by FrancescoBorzi** 2024-11-10 22:52 UTC
Labels: WFMD, More Research Needed
