### ISSUE TITLE
[Wrong item category] Ultrasafe Transporter: Gadgetzan 

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#3129] opened 2022-02-23 18:45 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Item [Ultrasafe Transporter: Gadgetzan](https://wotlk-twinhead.twinstar.cz/?item=18986) can't be used at all. Instead of being used as a Gnomish Engineer (260) and then binding to our character when used, it keeps saying "This item cannot be equipped".
By trying to run a command with "/use Ultrasafe Transporter: Gadgetzan", we obtain the text "You must equip that item to use it".

![ 2022-02-23 at 19 44 04](https://user-images.githubusercontent.com/77953030/155386369-83461cd7-cfff-48da-a6bd-f1ca4c418f90.png)

When moving mouse over our Trinket slots while pressing ALT, we can see that the interface displays the item as if it was a Trinket.
The item INDEED used to be a trinket that took a slot during vanilla and also in the Classic revamp, as seen [HERE](https://classic.wowhead.com/item=18986/ultrasafe-transporter-gadgetzan), but it should't be now anymore.

### Expected Blizzlike Behaviour

Any Engineer with skill 260 or more and the Gnomish Specialization should be able to craft and use this item to get teleported to Gadgetzan. Item should get bound to our character upon first use.

### Steps to reproduce the problem

Have a character with Engineering at 260 or more
Complete quests for Gnomish Engineering Specialization
Craft item 18986
Try using item

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment] 2022-03-06 23:39
Horde looks ok. Completed quest and crafted item as intended worked first time.
Tried mage too. Everything works as intended.
Someone else need to try to confirm 100%
![transport](https://user-images.githubusercontent.com/791788/156947270-b66877f3-d666-4810-a009-dd5d17c87902.png)
![gnome](https://user-images.githubusercontent.com/791788/156947272-d139e784-bd97-4ebb-8eb5-ba724eebd41f.png)
.

**Comment by Dejanos** [comment] 2022-03-09 20:05
Can also confirm item worked for me and teleported me to the correct location. Did you try to unequip your trinket before use, it worked for me with no trinkets, will try with trinkets equipped once the cooldown wears off if you wish. But it is working as intended for me right now.
![WoWScrnShot_030922_210116](https://user-images.githubusercontent.com/100415626/157524800-c6dd91de-1ef8-4421-9575-7fdcac9ed771.jpg)
 
![WoWScrnShot_030922_210126](https://user-images.githubusercontent.com/100415626/157524826-e8543991-bf3f-4ac1-9aca-601b3c913b79.jpg)

**Comment by cachocarne** [comment] 2022-03-09 20:19
Thanks a lot for taking the time for testing; it was a good call to try without any trinkets equipped. However, it did not work. I still get the same results.
I also tried sending the item to an alt -since it's still unused and not bound yet- but also didn't help when I got it back.

![Transporter1](https://user-images.githubusercontent.com/77953030/157528061-34581802-d296-408e-bc8a-c2b197e98dbb.png)
![Transporter2](https://user-images.githubusercontent.com/77953030/157528112-63464642-c203-4292-908d-db819d95d3c6.png)
![Transporter3](https://user-images.githubusercontent.com/77953030/157528125-7e45d086-ab1a-43b3-bb51-a6e4e9359739.png)

**Comment by Kosiak** [comment] 2022-03-09 20:46
Can u try cleaning your cache? I dont think its server related. Everything looks ok in database. Thank you

**Comment by cachocarne** [comment] 2022-03-09 23:55
Of course. Also without a single addon. Unfortunately, it seems my character has some dark bug, but I am afraid of switching engineering specialization and lose some of the special recipes.
Thanks all for your time and help.

**Comment by Kosiak** [comment] 2022-03-10 00:48
When i get to lvl 260 engineering and get it on live server. I will try again. As it's not showing up as a trinket when im alt hovering over trinkets.

**Comment by Gultask** [comment] 2022-04-08 17:52
Any updates to this, [cachocarne](https://github.com/cachocarne)? I haven't been able to reproduce the issue as well.

![WoWScrnShot_040822_144953](https://user-images.githubusercontent.com/100873791/162495172-8beb52cf-aedf-40dd-b133-4ad826c1e175.jpg)

https://user-images.githubusercontent.com/100873791/162495299-21fefe00-6249-4397-8895-1e10b1f59cb9.mp4

**Comment by cachocarne** [comment] 2022-04-29 21:36
I gave up, must be some corrupted MPQ file or weird combination. I removed all addons, all skin mods and everything. Still not working. The thing is, this is not a new Client, I have it from before and played on other servers with it, without any issue. The other day I logged from another computer which had lots of addons and skin mods but the item worked. Upon clicking, it told me it was about to get soulbound. I used it and got teleported to Gadgetzan without problem. Now back to mine, item is still soulbound but keeps on saying "this item can't be equipped". Guess I will get a new client and try again. Thanks for the help.

**Comment by Gultask** [comment] 2022-04-29 22:33
@cachocarne You know, I was thinking about this issue just today. I was going to recommend you to reinstall the client or at least the data files. A lot of issues that can't be reproduced can be traced back to modified 3.3.5 clients. 😃

**Comment by cachocarne** [comment] 2022-04-30 17:23
Interestingly enough, replacing all MPQs from Data didn't change a thing. However, the WoW executable file is now different (different size) and that is what didn't let me use the item. I simply replaced the executable file and now it works!

**Comment by Gultask** [comment] 2022-04-30 17:55
I find that so funny for some reason 😆 
I'll close the issue then and I'll tell the other person to also change their client.

**Closed by Gultask** 2022-04-30 17:55 UTC
Labels: Unable to Reproduce
