### ISSUE TITLE
Elder Timberling spam heal 

### ISSUE THREAD

**Issue by MonsterDooty** [chromiecraft/chromiecraft#346] opened 2021-04-05 13:14 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Elder Timberling in Teldrassil will either not cast any heals the entire conflict, cast 1-2 heals or spam lesser heal every opportunity it gets once it gets under a certain HP threshold.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I'm not entirely sure the spamming of lesser heal once below x threshold until death, but it doesn't seem "blizzlike"

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find Elder Timberling
2. Engage in battle and allow it to reach roughly 30% HP
3. Either it will not heal, cast a heal 1x/2x or it will continuously spam heal until you get lucky on a large enough hit to offset the lesser heal.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-04-05 13:31
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/324

**Comment by FrancescoBorzi** [comment] 2021-04-05 14:22
thanks @Azcobu

**Closed by FrancescoBorzi** 2021-04-05 14:22 UTC
Labels: Duplicate
