### ISSUE TITLE
[Western Plaguelands] Blood of Heroes spawn location not possible to reach properly

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2233] opened 2021-11-01 21:17 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I managed to get this one but it is basically bellow ground/hard to reach.
![WoWScrnShot_110121_205309](https://user-images.githubusercontent.com/80590226/139743129-92b5ae44-8b6e-4fc9-bc0f-fe00a112c318.jpg)
![WoWScrnShot_110121_205305](https://user-images.githubusercontent.com/80590226/139743133-e4011c41-a83a-4aad-adfd-6019c0305e56.jpg)
![WoWScrnShot_110121_205258](https://user-images.githubusercontent.com/80590226/139743136-c9be7602-19a8-48de-815c-619d9974663b.jpg)
![WoWScrnShot_110121_205312](https://user-images.githubusercontent.com/80590226/139743137-4628e0be-13c6-4689-b1d4-95c3c2869b01.jpg)

### Expected Blizzlike Behaviour

Should be shown properly like any other spawn, on the ground.
https://wowgaming.altervista.org/aowow/?object=176213

### Steps to reproduce the problem

1. Get to location https://wowgaming.altervista.org/aowow/?object=176213
2. Object spot: (41.8 , 70.6), the southest one on map in Andorhal
3. You can't spot it, just mouse over that hill, object is bellow, not properly visible.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment] 2021-11-02 06:07
Duplicate of #2089.

**Comment by Elexias** [comment] 2021-11-02 06:24
Holy, not sure how but I hadn't seen Andy report even tho I did search..

**Comment by gurveleg** [comment] 2021-11-02 07:31
Thanks for the report, but this was already reported in https://github.com/azerothcore/azerothcore-wotlk/issues/8507 and we are aware of it.

**Closed by gurveleg** 2021-11-02 07:31 UTC
Labels: Needs Triage
