### ISSUE TITLE
Priest blocked melee attack

### ISSUE THREAD

**Issue by Gadixsp** [chromiecraft/chromiecraft#1419] opened 2021-08-14 13:30 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

My priest took reduced damage on an enemy attack by blocking. Obviously no shield was equipped. The enemy in question was an [Elder Brown Bear](https://wowgaming.altervista.org/aowow/?npc=17348)

![WoWScrnShot_081421_080554](https://user-images.githubusercontent.com/10586372/129447761-fff4e67e-8fe5-4f02-be50-0838fdb6ccc4.jpg)

### Expected Blizzlike Behaviour

Blocks should only be possibly by players with shields equipped, which priests are incapable of.

### Source

[Wowwiki article describing the pre-Cataclysm system](https://wowwiki-archive.fandom.com/wiki/Block) which lists Warrior, Paladin, and Shaman as the only classes that can block. I didn't find any source explicitly saying you can't block without a shield but it seems like that might go without saying.

### Steps to reproduce the problem

Be attacked a lot as a priest

### Extra Notes

I wasn't able to reproduce this after some limited testing, so it seems exceedingly rare. It may even just be reporting something like a glancing blow incorrectly. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-08-29 11:44
Thanks for the report. I've just had a priest sit there and be attacked by an Elder Brown Bear for 20 minutes in the hope that it would do this, but I wasn't able to reproduce the block. I have no idea if this was a one in a thousand roll by the attacker that wasn't handled properly by the server, or a client error reporting a glancing blow incorrectly as you suggest. However, if we can't reproduce it there's no way to test or fix it unfortunately, so will have to close this one as a rare/unreproducible bug. However, please feel free to let us know if you see it again.

**Closed by Azcobu** 2021-08-29 11:44 UTC
Labels: Needs Triage
