### ISSUE TITLE
Lua Error - Crushing the Crown

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#82] opened 2021-02-15 20:53 UTC
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
Lua Error on bombing the **Chemical Wagon** when doing (any of) the [Crushing the Crown](https://wotlkdb.com/?quest=24638) quest(s) during [Love is in the Air](https://wotlkdb.com/?event=8) 
![image](https://user-images.githubusercontent.com/7461137/107991333-afea8980-6fd6-11eb-8521-04c1cc8a23e9.png)
Screenshot taken on a clean enUS 3.3.5a client with **Display Lua Errors** enabled in **Options/Interface/Game/Help** and all Addons disabled.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
There should be no Lua Error when doing the quest.

##### CURRENT BEHAVIOUR:
You'll get/see a Lua Error when **Display Lua Errors** is enabled or you are running a bug-catching Addon like **Swatter** from **Auctioneer** (which is how I noticed it).

##### STEPS TO REPRODUCE THE PROBLEM:
0. Either enable **Display Lua Errors** or install a bug-catching Addon
1. Take any (depending on level and/or faction) of the **Crushing the Crown** quests
2.  Approach the corresponding **Chemical Wagon**
3. Drop the bomb (click on the bomb item in the quest log).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment] 2021-02-15 21:49
Is this the only Lua error you get from the client while playing? I thought there would be a bunch of Lua errors, but I haven't tested, so I don't know the expected results.

**Comment by Stifler82** [comment] 2021-02-16 03:37
I would like to understand why you have activated **"Display Lua Error"** is an option that has existed since the time of TBC (probably even before but I'm not sure), it **NEVER** served anything, **except to annoy you while you play**, that error does **NOT** affect the game, and above all (I would not be wrong, I'm 95% sure) that it is not something we can fix, because it is a **Client Bug** (which I repeat) does **NOT** affect the game.

**Comment by illfated** [comment] 2021-02-16 06:44
BTW, I think this type of bug report would only be useful for a Lua-based server.
Maybe https://github.com/ElunaLuaEngine/Eluna is a useful place to report this.
Check with rochet2 to see if that error is anything worth looking into.

**Comment by necropola** [comment] 2021-02-16 07:30
I usually do not have this option enabled, but I run **Auctioneer** with **Swatter** for many, many years, both on retail as well as on private servers. I very rarely encounter Lua Errors and if I do, it's usually (>  90%) an Addon causing it and in more than 90% of thoses cases it's due to an uninitialized variable/value.
If the error is caused by an Addon (and I have access to the source code), I usually just fix it. and If it is (still) maintained on github, I file a pull request. But this Lua Error seemed to be one of the rare cases, where Addons are not to blame. So I enabled **Display Lua Errors** (instead of **Swatter**) to prove that it happens without any Addons enabled.

Now that this is out of the way, how should one handle such a case? Obviously we do not have (much) control over the client, because the source code is not available. But we have full control over the server side. And while it's clear that the client is making asumptions that it shouldn't, can we (or rather do we want to) adjust the server side so that the client does not run into this error?

If I were an AC developer, I would ask myself the following questions:
- How likely is it that the retail server response triggered the Lua Error on the 3.3.5a client, too?
- How many people have been running **Display Lua Errors** or an Addon like **Auctioneer** with a bug-catcher like **Swatter** enabled on retail?  
- Can we fix this error by modifying the server and how much effort would that be? 
- What's the cost (players being annoyed or even bashing the server) of not fixing it?

It's your project and therefore your choice.

**Comment by Stifler82** [comment] 2021-02-16 11:05
> I usually do not have this option enabled, but I run **Auctioneer** with **Swatter** for many, many years, both on retail as well as on private servers. I very rarely encounter Lua Errors and if I do, it's usually (> 90%) an Addon causing it and in more than 90% of thoses cases it's due to an uninitialized variable/value.
> If the error is caused by an Addon (and I have access to the source code), I usually just fix it. and If it is (still) maintained on github, I file a pull request. But this Lua Error seemed to be one of the rare cases, where Addons are not to blame. So I enabled **Display Lua Errors** (instead of **Swatter**) to prove that it happens without any Addons enabled.
> 
> Now that this is out of the way, how should one handle such a case? Obviously we do not have (much) control over the client, because the source code is not available. But we have full control over the server. And while it's clear that the client is making asumptions that it shouldn't, can we (or rather do we want to) adjust the server side so that the client does not run into this error?
> 
> If I were an AC developer, I would ask myself the following questions:
> 
> * How likely is it that the retail server response triggered the Lua Error on the 3.3.5a client, too?
> * How many people have been running **Display Lua Errors** or an Addon like **Auctioneer** with a bug-catcher like **Swatter** enabled on retail?
> * Can we fix this error by modifying the server and how much effort would that be?
> * What's the cost (players being annoyed or even bashing the server) of not fixing it?
> 
> It's your project and therefore your choice.


**You are absolutely right, I agree with you 99%!**
Why do I say 99% !?
Because usually **(more or less)**, those are the questions we ask ourselves, the problem why in this case I am not asked them, is that in this specific case, **it is the 1%** that:
1 - It is not something of **our competence / interest**.
**(And the reasons why it is not of our competence / interest are explained in the points below)**
2 - A **"Lua Error"** **has never prevented a Player from playing**, but as I said in the previous comment, **(it's just annoying if you activate it)**.
3 - The reason why the "Lua Error" usually activates, **happens for 3 reasons**, the first **(as you have well pointed out)** is an **addons that is not perfectly compatible with the version of the Client** or is damaged **(And the fix of the addons is not of our competence / interest)**, or a (corrupt MPQ, but I don't think it's your case since you downloaded a fresh enUS Client), the third reason is that **"WoW Emulators"** so **Mangos, Trinity , AzerothCore, etc...** (just as their **"Definition"** suggests they are **"Emulators"** that emulate the operation of the **"Original" Resource**, therefore, as happens with an "Addons" **which is not exactly "Compatible"** with the Client version, even the **Emulators are NOT EXACTLY compatible with the Client**.

**(Just to give an example)**
Imagine you have 2 "Apparently Identical" Apples **(keyword "Apparently")** and you cut them **"EXACTLY"** both in the middle, if you later try to join the left half of the first Apple with the right half of the second Apple, they will match **by 90% - 99%** but **NEVER! at 100%** there will always be that **1% that doesn't match**. So in the game Client that **1% of the Apple** is the Lua Error that appears, and I believe this is the case.

**Comment by illfated** [comment] 2021-02-16 15:37
@Rochet2 : Could we have a comment from you, based on your experience? Is it at all worth looking into, or is it a waste of time?

**Comment by Rochet2** [comment] 2021-02-16 21:15
@illfated The error is from client-side Lua and is not directly related to Eluna.
It would be great if someone can confirm that with a clean core and no addons the same occurs.
If it does, then I suspect that it is either a client bug or packet sent in the wrong order or not at all.

A further look shows posts like this: https://www.bluetracker.gg/wow/topic/us-en/25833934280-bug-cooldownlua-nil-comparison-error/
Looking at the addon code it seems that indeed the function or where it gets its info is the culprit.
Maybe a look into the packets that are being sent when the error occurs is useful.

```lua
-- WatchFrame.lua
	local start, duration, enable = GetQuestLogSpecialItemCooldown(self:GetID());
	CooldownFrame_SetTimer(itemCooldown, start, duration, enable); -- line 1194
```

```lua
-- cooldown.lua
function CooldownFrame_SetTimer(self, start, duration, enable)
	if ( start > 0 and duration > 0 and enable > 0) then -- line 3
		self:SetCooldown(start, duration);
		self:Show();
	else
		self:Hide();
	end
end
```

**Comment by illfated** [comment] 2021-02-16 21:17
Thank you for replying. Always good to hear from someone who knows practical details related to an issue.

**Comment by FrancescoBorzi** [comment] 2021-02-16 23:37
> It would be great if someone can confirm that with a clean core 

ChromieCraft is quite a clean core

**Comment by Stifler82** [comment] 2021-02-17 14:26
@FrancescoBorzi @illfated @Rochet2
So, can I close this Issue? is it a Game Client Bug, right?

**Comment by FrancescoBorzi** [comment] 2021-02-17 14:33
yes, I would close it. Thanks anyway @necropola for the report.

**Closed by FrancescoBorzi** 2021-02-17 14:33 UTC
Labels: Game Client Bug, Invalid, Waiting for more feedback, [1 - 19]

**Comment by necropola** [comment] 2021-02-17 21:35
Just in case someone gets into the mood of further investigating. The festival is almost over, but the bug will probably be back in a year ...

I noticed that the Lua Error **only occurs when you are tracking the quest while activating the bomb**. Which is pretty much a given when you have **Automatic Quest Tracking** active. When you remove the quest from the objective tracker (by shift-clicking it) and then activate the bomb either directly from the inventory or from your action bar, the Lua Error does not occur.

This leads me to believe that the order of the following events matters.
* The bomb is removed from the inventory
* The quest (text) is updated and no longer references the bomb
Removing the bomb before updating the quest might leave a nil refernce (for a fraction of a second) whiich might be the cause of the Lua Error.

I neither know, if this is what exactly happens, nor do I know whether you have server side control over the event order on the client, but I still wanted to share my finding and my hypothesis.

**Comment by Stifler82** [comment] 2021-02-17 21:48
> Just in case someone gets into the mood of further investigating. The festival is almost over, but the bug will probably be back in a year ...
> 
> I noticed that the Lua Error **only occurs when you are tracking the quest while activating the bomb**. Which is pretty much a given when you have **Automatic Quest Tracking** active. When you remove the quest from the objective tracker (by shift-clicking it) and then activate the bomb either directly from the inventory or from your action bar, the Lua Error does not occur.
> 
> This leads me to believe that the order of the following events matters.
> 
> * The bomb is removed from the inventory
> * The quest (text) is updated and no longer references the bomb
> 
> Removing the bomb before updating the quest might leave a nil refernce (for a fraction of a second) whiich might be the cause of the Lua Error.
> 
> I neither know, if this is what exactly happens, nor do I know whether you have server side control over the event order on the client, but I still wanted to share my finding and my hypothesis.





I may be wrong, but I don't think it needs further investigation.
![image](https://user-images.githubusercontent.com/1884642/108272137-bf4e0c00-7169-11eb-82b9-554555e9d55c.png)

**Comment by illfated** [comment] 2021-02-18 20:03
Yay! Good job tracking down the issue source and its origin, `Interface\FrameXML\Cooldown.lua:3:`

Looks like that error will be reproducible elsewhere in the game even on retail.
