### ISSUE TITLE
Prospecting thorium not giving loot.

### ISSUE THREAD

**Issue by rawrgargar** [chromiecraft/chromiecraft#600] opened 2021-05-10 16:30 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Basically, sometimes when prospecting thorium you get a blank window instead of actually getting loot. I'm assuming this is based on the TBC loot being currently locked, and you have a slight chance (About 10% chance combined) of getting a TBC quality gem. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Just shouldn't give a blank window when prospecting thorium.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Get a bunch of thorium ore
2. Prospect that thorium
3. Watch the not loot happen

##### EXTRA NOTES:
--

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment] 2021-05-11 04:59
I can confirm that this happens occasionally. Testing on 300 thorium ore, I had 5 prospects that came up empty. TBC gems can still be prospected out of thorium at this time.

**Comment by aithdruid** [comment] 2021-05-25 01:23
It seems like what is happening is that prospecting thorium should have a 10% chance to give a tbc gem, and a 90% chance to give a classic gem, but those chances are currently being rolled independently of each other. So currently you have a 81% chance to receive only a classic gem, 9% chance to receive both, 9% chance to receive nothing, and 1% chance to receive only a tbc gem

**Comment by pop-pig** [comment] 2021-06-20 15:34
After testing it again it seems that it's not fixed yet.
I did a pull not long ago and recorded it happening, here is a video: https://youtu.be/12J_pjW8YNs
You can see that after finding the 2 blue sapphires, I prospect again and there is no loot (see chat window).
AzerothCore rev. 80a76bad7155+ 2021-06-20 12:12:30

**Comment by necropola** [comment] 2021-06-20 18:55
Reopening since it's obviously not fixed. See #925.

**Comment by necropola** [comment] 2021-06-20 19:01
@pop-pig The fix has not yet been merged into ChromieCraft

**Comment by pop-pig** [comment] 2021-06-20 19:19
@necropola Yes, I did a pull today to have an up to date core (see the core info in my previous comment).

**Comment by necropola** [comment] 2021-06-21 22:06
@Helias Why does this commit fix/close this and the correspondif AC issue https://github.com/azerothcore/azerothcore-wotlk/issues/5781?

**Comment by Helias** [comment] 2021-06-21 22:10
I think it's a mistake

**Comment by necropola** [comment] 2021-06-22 17:14
@Helias Again?

**Comment by Helias** [comment] 2021-06-23 10:10
sorry, I've just updated my fork repo with the master branch :/

**Comment by gurveleg** [comment] 2021-06-28 19:14
Prospecting Thorium Ore Is also sometimes giving Tbc AND a normal Gem from same prospect.

**Closed** 2021-09-09 09:48 UTC
Labels: Confirmed, Linked [AC]
