### ISSUE TITLE
[High king Maulgar] Charge does not work

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#4810] opened 2023-01-13 14:47 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

High King Maulgar does not gain the charge ability once he is below 50%.

### Expected Blizzlike Behaviour

When boss is under 50 % hp he should gain the Charge ability. It targets random raid member in range, stuns for short duration and does small physical dmg.
This should not a threat reset.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot

### Steps to reproduce the problem

Engage high King Maulgar
Bring Boss under 50 % hp
Wait

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment] 2023-01-13 21:36
relevant line of code
https://github.com/azerothcore/azerothcore-wotlk/blob/0df153b8ddaa8b28002462ce955c509b9fe04aed/src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp#L162

seems implemented. might be affected by
https://github.com/azerothcore/azerothcore-wotlk/blob/0df153b8ddaa8b28002462ce955c509b9fe04aed/src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp#L157

overall, scheduled frequency seems rather low but that is to be verified

**Comment by Contrubius** [comment] 2023-01-19 11:07
I was unable to reproduce, 2 man tested Maulgar, as long as the other character was within 40 yard range, Maulgar would periodically charge the other character and knock him back for a great distance.

**Comment by IskrenPlashkov** [comment] 2023-01-19 11:32
How long did it take him to charge tho ?  In our test raids ( we had 25 ppl) boss always died before charging once, even after we made a call to slow down dps.

**Comment by Contrubius** [comment] 2023-01-19 11:42
In the videos I linked it takes him around 10-20 seconds for the charge after 50% health. In the Asmongold video I linked, he barely managed to do it before dying on around 20%, on Ape guild video here he didn't even get to do a single charge (https://www.youtube.com/watch?v=_pj01ED_xTw ) so I reckon it matters on how long you fight him after 50%.

**Comment by NinesCC** [comment] 2023-04-07 03:22
https://youtu.be/7EYlPgMsrVI?t=66
He does charge, but it took him 50 seconds to charge the first time since he was below 50%.

**Comment by elthehablo** [comment] 2023-07-17 20:37
![image](https://github.com/chromiecraft/chromiecraft/assets/83884799/458f7cff-6204-4bfa-9a44-84cfbc7e3659)
should work

**Comment by elthehablo** [comment] 2023-07-17 21:00
> both the charge and the fear often dont appear to happen.
> similar with doomwalkers earthquake, which also often does not happen

Doomwalker's earthquake works with a coinflip (check code). Whether that is correct? No clue. But there is a difference between the two.

**Comment by elthehablo** [comment] 2023-07-17 21:08
As I understand it, it does work. Closing until further evidence, but timers have been looked at using classic sniffs.

**Closed** 2023-07-17 21:08 UTC
Labels: Needs Triage
