### ISSUE TITLE
Dark Iron Dwarves in Wetlands.

### ISSUE THREAD

**Issue by Jonsse** [chromiecraft/chromiecraft#2091] opened 2021-10-14 14:11 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I was doing a quest: The Dark Iron War(https://wowgaming.altervista.org/aowow/?quest=303) and A Grim Task(https://wowgaming.altervista.org/aowow/?quest=304)

There's several bugs with the Dwarves related to these quests.
1. Gift of Ragnaros(https://wowgaming.altervista.org/aowow/?spell=7891) seems to proc from other actions than melee swings and and procs significantly more than normal. Mobs running after the character were proccing the spell while being way too far away for melee attacks and at a significantly quick interval.
2. Dark Iron Tunnelers(https://wowgaming.altervista.org/aowow/?npc=1053) do not have floating health bars(https://i.imgur.com/o7AvYuV.jpg)
3. And as usual they also run away at 100% movement speed when low health. (I know this is endemic to private servers, but I'll add it here because it's also present in these mobs)

### Expected Blizzlike Behaviour

1. The Gift of Ragnaros spell should proc from melee attacks at a reasonable rate. It should not be 2/3 of the mobs damage.
2. Should have Health plates.
3. Humanoids running away at low health should have reduced movement speed.

### Steps to reproduce the problem

These bugs are apparent when engaging normally with the npc's.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by discorder0** [comment] 2021-10-15 07:44
I quested there today. A few tunnelers do not have name on top of them at all. (Not just health bar. I didn’t have health bar turned on but I displayed NPC name.)

**Comment by Gultask** [comment] 2022-04-21 22:34
Tunnelers currently have nameplates and their names are shown as well.

Since both issues 2 and 3 existed back when you made the report (issue 3 was fixed in December 2021), I'll add the Linked and Confirmed labels to your report so that it's valid for points.

Thanks for reporting!

**Closed by Gultask** 2022-04-21 22:34 UTC
Labels: Bug Under Evaluation, Needs second opinion, More Research Needed
