### ISSUE TITLE
Hakkar fight in sunken temple bugged

### ISSUE THREAD

**Issue by kbloss90** [chromiecraft/chromiecraft#2334] opened 2021-11-15 07:27 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When doing the fight, fight stops and resets after two fires are dowsed with blood

### Expected Blizzlike Behaviour

Fight should continue until all four fires are dowsed and then boss spawns and fights

### Steps to reproduce the problem

1. use needed item to start the fight
2. dowse two fires with bloods dropped from bloodkeepers
3. see that fight stops immediatly after dowsing second fire

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-15 12:34
Thank you for report. On local AC i can't reproduce it. Probably you are failing encounter.

`.q a 3528` or `additem 10465` then `.go ga 99877`
![WoWScrnShot_111521_153039](https://user-images.githubusercontent.com/85256266/141782513-af336bba-6ae3-443d-85a6-219e01a6c406.jpg)

**Comment by Shineslippers** [comment] 2021-12-09 14:02
As there is no respond from player and no new reports about this issue i will close it.

**Closed by Shineslippers** 2021-12-09 14:02 UTC
Labels: Waiting for more feedback, Unable to Reproduce, Bug Under Evaluation
