### ISSUE TITLE
Hunter Pet gets stuck on Maraudon:Purple Crystal waterfalls

### ISSUE THREAD

**Issue by XionDemise** [chromiecraft/chromiecraft#852] opened 2021-06-13 01:50 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

So i went into maraudon this morning with the guild for abit to check it out and we jumped through the waterfall like professionals but my pet got stuck on it? as you can see with the screenshot provided. i couldn't dismiss it either everything was blacked out on my pet bar and the pet itself wouldn't move. nothing could move it but death it seemed like?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I don't think that's supposed to happen maybe the pet clipped into the waterfall? or just bugged out. but that's not supposed to happen and the pet pathing should figure it out.

##### STEPS TO REPRODUCE THE PROBLEM:

1. become a hunter summon pet and jump off one of the purple crystal waterfalls and witness the bug
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by XionDemise** [comment] 2021-06-13 01:50
![WoWScrnShot_061221_085815](https://user-images.githubusercontent.com/85085161/121792883-3fd8c280-cbc8-11eb-882f-96603d4432b7.jpg)

**Comment by Azcobu** [comment] 2021-06-13 06:17
Maybe I'm the wrong person to look at this ticket as I haven't played a hunter in ages, but this looks like expected behaviour to me. My understanding was that If you don't dismiss a pet before jumping down or across a barrier, the pet usually either just stands there or, if you're unlucky, runs to you and aggros half the dungeon, and probably wipes the party. You're lucky in this case - the pet just gets stuck rather than running along the side path with all the slimes and pulling them all onto you. The only nuisance is not being able to dismiss it due to Dismiss Pet's 10 yard range, and moving out of range to despawn the pet should take care of that.

Tested it myself - looking up the waterfall at my stuck pet:
![WoWScrnShot_061321_151458](https://user-images.githubusercontent.com/81782124/121796932-0baee180-cc5c-11eb-8ef1-a7050c632c05.jpg)

I tried to find Youtube clips of other hunters at this spot, and found this one of a 5 x hunter multibox team, which seems to show that dismissing your pet is just what you have to do here:
https://youtu.be/nmMhKwhLSRw?t=3386

So my inclination would be to mark this 'not ideal, but Blizzlike/working as expected.' But like I said, I'm not a hunter expert, so will leave this open for your and other comments.

**Comment by Azcobu** [comment] 2021-06-16 09:44
No other responses or comments, so closing this as per above.

**Closed by Azcobu** 2021-06-16 09:44 UTC
Labels: Needs Triage
