### ISSUE TITLE
[PvP] Damage Control achievement not working correctly

### ISSUE THREAD

**Issue by phonkala** [chromiecraft/chromiecraft#3115] opened 2022-02-21 14:15 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Damage Control achi in battlegrounds requires way more healing than it should. I personally had to do 620k healing to get the achi. I'm kinda guessing it is because of xfaction: healing opposite faction players (even being same side inside the bg) isn't registered for the achi.

![damage-control-bugged](https://user-images.githubusercontent.com/43609330/154971694-cdaff9a7-40b2-43f9-882a-843c6b4a4955.jpg)

### Expected Blizzlike Behaviour

300k healing or dmg to players should trigger the achi.

### Steps to reproduce the problem

Do battleground healing or dmg to players until the achi triggers. Try to do part of the heals/dmg to xfaction players to see it doesn't trigger at 300k (not sure this is the cause, but would sound quite possible).

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment] 2022-04-06 14:14
Unable to reproduce this issue, got Damage Control 2 times after healing player of opposite faction until 300.000 damage.
![Healing](https://user-images.githubusercontent.com/100415626/161995305-0a4fb2b5-81b5-4d56-bbd9-d3814e5e6142.png)

**Comment by Dejanos** [comment] 2022-04-06 15:38
> Must have been fixed then I guess (wonder if it's possible somehow to find this in fix logs or something). I remember doing many bgs where I exceeded 300k healing before getting the achi after healing 620k. Or could be it was just some UI bug too as we did visually get also double kills at some point (in the bg stats).

I would bet it has something to do with the AV fix, I remember even looking at the scoreboard could crash the player or even entire BG. But would also need to see log fix to confirm this, also I do not know if it could be related to the player who reported it above in #2172
You are also welcome to queue and test it yourself if you wish, as I have tried all possible combinations for now and I'm unable to reproduce it,

**Comment by temperrr** [comment] 2022-04-08 18:10
Hey thanks for your report. When you made it we had just had a big BG rewrite, which caused this error to be there.  
It basically doubled any damage or healing done, as well as kills etc but only on the scoreboard, and the achievement was working correctly. 

Meanwhile it is fixed, I am marking it as [Linked] so you will be able to claim points for this bug report next month.

**Closed** 2022-04-08 18:10 UTC
Labels: Confirmed, Linked [AC], PvP
