### ISSUE TITLE
Wailing Caverns Muyoh Escort Broken

### ISSUE THREAD

**Issue by Wumblesnarf** [chromiecraft/chromiecraft#282] opened 2021-03-23 12:13 UTC
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

at the end of wailing caverns, Muyoh doesn't fight anything and just keeps running along towards the boss, pulling several packs without any time to kill them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Muyoh should fight the adds with us

##### STEPS TO REPRODUCE THE PROBLEM:

1. do wailing caverns and start the escort
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Wumblesnarf** [comment] 2021-03-23 12:16
I guess hes labeled Disciple of Naralex during the escort? or maybe the name is from retail, either way the thing is bugged

**Comment by 55Honey** [comment] 2021-03-23 12:26
duplicate of https://github.com/chromiecraft/chromiecraft/issues/281

**Closed by 55Honey** 2021-03-23 12:26 UTC
Labels: Duplicate
