### ISSUE TITLE
Quest Cipher of Damnation - Ar´Tor´s Charge - no spirit hunter

### ISSUE THREAD

**Issue by StepyMandy** [chromiecraft/chromiecraft#5463] opened 2023-04-21 17:47 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Part of the quest to slay Veneratus the Many should spawn spirit hunter by quest giver. There is no spawned spirit hunter.

### Expected Blizzlike Behaviour

Spirit hunter should be spawned when quest is taken, so Veneratus can be spawned and killed to complete quest.

### Source

https://www.wowhead.com/wotlk/quest=10541/the-cipher-of-damnation-the-second-fragment-recovered

### Steps to reproduce the problem

1) Go to [Spirit of Ar'tor](https://www.wowhead.com/wotlk/npc=21318/spirit-of-artor)
2) Accept [The Cipher of Damnation - Ar'tor's Charge](https://www.wowhead.com/wotlk/quest=10540/the-cipher-of-damnation-artors-charge)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by StepyMandy** [comment] 2023-04-23 06:41
Today tried the quest again since I saw server was restarted, and works as intended.

**Comment by Paradigmxd** [comment] 2023-05-14 09:41
I can confirm did this quest X2 times for the past 79 days on my 69 alts and it works as intended perfectly!

**Comment by Rorschach91** [comment] 2024-08-10 09:46
If it's fixed than i close this report. 

Thank you for your report and for saying that the bug has been fixed.

**Closed** 2024-08-10 11:38 UTC
Labels: Fixed, Closed
