### ISSUE TITLE
[Quest] - Call of Earth (Shaman totem quest) - incorrect behaviour

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#2111] opened 2021-10-15 20:10 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Another minor problem to report here.

When you take the quest [Call of Earth](https://wowgaming.altervista.org/aowow/?quest=1517) (part 2) you are sent to a shrine in the nearby hills. There you need to drink the quest item [Earth Sapta](https://wowgaming.altervista.org/aowow/?item=6635) to be able to see the npc [Minor Manifestation of Earth](https://wowgaming.altervista.org/aowow/?npc=5891) and some little earth elementals (can't click on those or see their name to give you a link)

The spell cast on you is [Sapta Sight](https://wowgaming.altervista.org/aowow/?spell=8202).

Currently the NPC seems to be there all the time and not despawning (or phasing?) making the quest item pointless. (I waited a good while and also while making this report and it still didn't despawn/phase out). I also removed the sapta sight effect and was still able to observe them.

### Expected Blizzlike Behaviour

As per [this video](https://youtu.be/nyntgWJHf1s?t=205) linked at the exact moment - it seems expected to:

1. See no mobs at the shrine location.
2. Drink the quest item [Earth Sapta](https://wowgaming.altervista.org/aowow/?item=6635).
3. See and interact with quest mob,

### Steps to reproduce the problem

Take [the quest](https://wowgaming.altervista.org/aowow/?quest=1517) (be mindful it has the same name as the previous one) and observe.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-10-16 05:00
Just had a look at this on my local server and everything seemed to be working correctly. Nothing was visible until the Earth Sapta was used. Removing the Sapta Sight from the first character hid all the NPCs again. 

![WoWScrnShot_101621_151836](https://user-images.githubusercontent.com/81782124/137574185-5bfdf15b-9239-4d50-afc5-c5a21f7ffbf6.jpg)

![WoWScrnShot_101621_152542](https://user-images.githubusercontent.com/81782124/137574285-1ef56455-8628-4647-bb76-29f5279f4e3d.jpg)

Also tried viewing with a second character with the quest active, but they couldn't see anything without drinking the sapta either:

![WoWScrnShot_101621_152632](https://user-images.githubusercontent.com/81782124/137574326-8a582607-d04a-4cbf-88d8-f2c31b0636df.jpg)

So not sure how to reproduce this.

**Comment by TheRiddermark** [comment] 2021-10-16 09:32
This is strange! I will try it today again on the live server creating another character. Will try to grab some footage too.

**Comment by Azcobu** [comment] 2021-10-17 06:42
Not sure at this stage. The NPC is supposed to cast a spell called 'Elemental Spirit Invisibility' (https://tbc.wowhead.com/spell=8203/elemental-spirit-invisibility) when it spawns, but only once. Just checked in-game on CC and it doesn't have that aura active though.

Also went and checked the version of this NPC in Mulgore for the tauren version of the quest, and it's visible as well:
![WoWScrnShot_101721_120407](https://user-images.githubusercontent.com/81782124/137614349-c74330b6-33c9-46e7-ac74-3870e2c854a0.jpg)

**Comment by TheRiddermark** [comment] 2021-10-17 11:57
@Azcobu ah so you seem to have figured it out! I don't want to clutter this topic with useless speculation, but if it's working on your local server could it be a recent fix that broke the NPC behaviour to cast the invisibility spell upon spawn? I would also be interested to test it out after a server restart (if there is one I will try to be on to do so).

Thank you!

**Comment by claudiodfc** [comment] 2021-12-20 12:04
I wonder what causes this, because if you launch AC this is working there. Even if server crashed it would reset. Any ideas?

**Comment by Shineslippers** [comment] 2021-12-20 12:08
I checked CC after restart and ithey are already without stealth. Maybe some conf or something that isn't loading on CC.

**Comment by trapped** [comment] 2022-09-16 21:19
Hey all, reviving this as I just experienced this issue in CC. Would love to help out but I'm a bit clueless about where to look; the other linked issue is closed so it seems unlikely this is related to the auras-breaking PR mentioned there (that I presume was reverted).
If anyone could give me a few pointers I'll try to dig into this.

**Comment by temperrr** [comment] 2022-09-20 17:20
Smart script probably

**Comment by noonrunner** [comment] 2023-05-12 10:32
This bug kills the shaman vibe :(

**Comment by Salehyn** [comment] 2023-05-28 23:23
Confirmed this is still bugged on CC as of today. Elemental is missing the aura which makes him normally only visible with Sapta. (Normally there is a debuff on him)

**Closed** 2023-10-17 18:32 UTC
Labels: Confirmed, Linked [AC], [1 - 19]
