### ISSUE TITLE
Cliff Giant (unarmed elemental) susceptible to Disarm and Rend (bleed effect)

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#2307] opened 2021-11-11 17:55 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_090821_142956](https://user-images.githubusercontent.com/89823720/141345707-30dee0ec-149c-4e06-8e66-8df432098e5f.jpg)

### Expected Blizzlike Behaviour

Unarmed mobs cannot be disarmed, and Elementals are immune to bleeds

### Source

Wow mechanics

### Steps to reproduce the problem

Make a warrior

TP GUID 51696 or 51695, Entry 5358 OR
TP Feralas
Go northwest, here is a map of their location https://classic.wowhead.com/npc=5358/cliff-giant

Attack, disarm & Rend them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment] 2021-11-11 19:44
Regarding bleeds, it seems there is not a lot of consistency, I'm not sure how they will address that. E.G. #579.

**Comment by gurveleg** [comment] 2021-11-12 07:14
As far as I know only mechanical mobs are immune to bleeds, elemental mobs are immune to their respective type damage.

**Comment by Azcobu** [comment] 2021-11-13 11:56
Thanks for the report. Yeah, bleed immunity for elementals is all over the place, and there's an issue open for it here: https://github.com/azerothcore/azerothcore-wotlk/issues/5915. The problem is the absence of any sources, although since May when that ticket was made we've gotten access to some sniffs data from retail Classic which might have helpful information there. Anyway, will close this as a known issue.

**Closed by Azcobu** 2021-11-13 11:56 UTC
Labels: Needs Triage
