### ISSUE TITLE
[NPC] Jademir Boughguard [Ability mechanic issue]

### ISSUE THREAD

**Issue by Evilanemesis** [chromiecraft/chromiecraft#253] opened 2021-03-19 23:05 UTC
##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Jademir Boughguard is doing a ranged Mortal Strike.
https://classicdb.ch/?npc=5320#comments
https://fr.classic.wowhead.com/npc=5320/gardien-des-marais-jademir

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mortal strike must be use within melee range from a melee attack. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Aggro them (#5320) with a mount, no need to get too close.
2. Run away as soon as you get in combat with them.
3. Check debuff, ranged Mortal strike is done (no dmg) but still get the debuff from them.
4.

##### EXTRA NOTES:

https://fr.wowhead.com/spell=12294/frappe-mortelle

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-03-24 00:19
I am closing this report because it is part of a wrong Content Stage! we are not yet in phase 60 - 69.

**Closed by Stifler82** 2021-03-24 00:19 UTC
Labels: Closed, Invalid

**Comment by FrancescoBorzi** [comment] 2021-03-24 12:50
> I am closing this report because it is part of a wrong Content Stage! we are not yet in phase 60 - 69.

actually it's still good to bring this to AC if valid, so some volunteer can fix it meanwhile

**Comment by FrancescoBorzi** [comment] 2021-03-24 13:03
@Evilanemesis are you testing on a local AC server?

**Comment by Evilanemesis** [comment] 2021-03-25 10:05
> @Evilanemesis are you testing on a local AC server?

I am testing on Chromiecraft. And yes the issue is valid... 

I've tested and reported over 340 issues on another 3.3.5 trinity core server somewhere in 2019. I am pretty confident :)
Sadly, the people I was testing for didnt share most of their fix to TC.

Let me know if you need anything,
Evila

**Comment by Stifler82** [comment] 2021-03-25 11:02
> > @Evilanemesis are you testing on a local AC server?
> 
> I am testing on Chromiecraft. And yes the issue is valid...
> 
> I've tested and reported over 340 issues on another 3.3.5 trinity core server somewhere in 2019. I am pretty confident :)
> Sadly, the people I was testing for didnt share most of their fix to TC.
> 
> Let me know if you need anything,
> Evila

@Evilanemesis
Yes, the issue is probably valid, (I say probable because I haven't even checked), but the point is different.

I closed this issue, not on the basis of its "Validity", but on the basis that **WE (ChromieCraft), (CURRENTLY)** , we are in the level range 20 - 29, because we are fixing the world in a **(SECTORAL) way**, we are not doing this because: **"one day we woke up on the left side of the bed instead of the right side"**, or because: **"we wanted to do so at that moment for no reason.."**

We are doing "Sector" fixes for a reason, **so please** respect that reason.
