### ISSUE TITLE
Anti-Venom has no effect

### ISSUE THREAD

**Issue by 123Bug123** [chromiecraft/chromiecraft#113] opened 2021-02-28 21:55 UTC
##### ISSUE: FACTION SIDE:

 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
 ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-25

##### SMALL DESCRIPTION:

Anti-Venom should cure all poisons from a character up to level 25.

Item: [Anti-Venom](https://wotlkdb.com/?item=6452)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All poisons level 25 and lower are removed from character on use

##### CURRENT BEHAVIOUR:

No effect

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Use poison effect on character (Serpent sting ex.)
Step 2 poisoned character uses Anti-Venom
Step 3 Observe no poisons are removed

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 123Bug123** [comment] 2021-02-28 21:57
![image](https://user-images.githubusercontent.com/7958374/109434997-e0fe8d00-79cc-11eb-93b3-adf4cf769c99.png)

**Comment by necropola** [comment] 2021-03-01 10:27
Duplicate of #104

**Comment by FrancescoBorzi** [comment] 2021-03-01 12:06
thanks @necropola , I closed the old one as it was not properly filled

**Comment by Helias** [comment] 2021-03-02 22:32
I tested it too and it does not work, but it seems that in patch 3.2.0 it does not work even in retail reading these comments https://www.wowhead.com/item=6452/anti-venom#comments

I tested strong anti-venom and it works instead.

this is a bit strange

**Comment by necropola** [comment] 2021-03-04 09:01
I like the question this leads to: Does being a blizz-like include emulating known bugs or should you aim for what was obviously meant to be?

**Comment by 55Honey** [comment] 2021-03-04 11:53
> I like the prinicipal question this leads to: Does being blizz-like include emulating known bugs or should you aim for what was obviously meant to be?

I am in the "what was obviously meant to be" faction in this one.

**Comment by Helias** [comment] 2021-03-04 18:28
@necropola lol, ofc we need to fix also the known bugs in retail and do everything in a better way.
I investigated it a lot, I will see together with @Stifler82 the best way to fix it.

**Comment by Stifler82** [comment] 2021-03-04 22:34
Fixed!
-
**Video Test:** [Anti Venom](https://youtu.be/I05VBwLCw6E)

**Closed** 2021-03-07 12:13 UTC
Labels: Confirmed, Fix Ready, Generic Issues, Linked [AC]
