### ISSUE TITLE
Unusable items showing as usable

### ISSUE THREAD

**Issue by jendryk** [chromiecraft/chromiecraft#571] opened 2021-05-08 11:27 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

A shield is showing itself as wearable by my Warlock, but obviously I can't use it.
![WoWScrnShot_050821_132404](https://user-images.githubusercontent.com/7814954/117537410-f1e90180-b000-11eb-9d24-62d02bb6c00f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be red and shown as unusable.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get an item that you can't use
2.  It shows as usable.

##### EXTRA NOTES:
--

I think it's not showing for all items, but quite a lot. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jendryk** [comment] 2021-05-08 11:37
It fixed itself after relogging, but I had this bug quite a lot of times with quest rewards and things like that.

**Comment by Ragundah** [comment] 2021-05-09 02:42
Can confirm that relogging will temporarily fix this issue, but it frequently returns and all items are shown as usable.

**Comment by eTzmNcbkrng** [comment] 2021-05-12 04:40
This is most often caused by a corrupt Cache because you have the `enGB` version of the game.  
See in `Path\To\Warcraft\Data` you should have a folder in here called `enUS`.

The version of WoW available for [download from the ChromieCraft website](https://www.chromiecraft.com/downloads/) is the correct `enUS` version.

**Comment by jendryk** [comment] 2021-05-12 14:36
I have enUS version, as stated in the first post.

**Comment by Ragundah** [comment] 2021-05-14 11:41
I also am using enUS client and clearing Cache is only a temporary solution.

**Comment by necropola** [comment] 2021-05-14 17:54
Has anybody checked whether this is causd by an Addon, e. g. Gearscore?

**Comment by jendryk** [comment] 2021-05-14 18:00
Hard to tell, I'm not seeing this bug anymore. It showed mostly on new characters so maybe gonna check it that way.

**Comment by necropola** [comment] 2021-05-14 18:40
I'll leave this open for a bit, but if we don't find a way to (reliably) reproduce the issue (I never had this on any of my 18 characters on CC), it's going to be closed.

**Comment by eTzmNcbkrng** [comment] 2021-05-15 09:47
> 
> 
> Hard to tell, I'm not seeing this bug anymore. It showed mostly on new characters so maybe gonna check it that way.

Here's how you reproduce it
https://github.com/chromiecraft/chromiecraft/issues/49#issuecomment-777794630

**Comment by necropola** [comment] 2021-05-15 12:07
> > Hard to tell, I'm not seeing this bug anymore. It showed mostly on new characters so maybe gonna check it that way.
> 
> Here's how you reproduce it
> [#49 (comment)](https://github.com/chromiecraft/chromiecraft/issues/49#issuecomment-777794630)

@eTzmNcbkrng
So it is a duplicate of #49 and a few comments below your linked comment you said, you were running an **enGB** client and were unable to reproduce the issue on an **enUS** client.

@jendryk 
I'm closing this as a **Duplicate (enGB) Game Client Bug** . Feel free to repopen, when you can reproduce the issue on an unmodified **enUS** client with **no Addons** installed.

**Closed by necropola** 2021-05-15 12:07 UTC
Labels: Closed, Duplicate, Game Client Bug
