### ISSUE TITLE
Elanaria Quest Cannot Be Completed When Given By Kyra Windblade

### ISSUE THREAD

**Issue by Slysam** [chromiecraft/chromiecraft#3527] opened 2022-05-22 06:47 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When you are given the quest "Elanaria" by Kyra Windblade in Dolanaar at level 10 as a Night Elf, the trainer correctly points you to Elanaria in Darnassus. However, when you arrive at the NPC in question, she is unable to be spoken to, and the quest cannot be turned in or completed. However, when you run back and accept the quest again from Moon Priestess Amara(Several NPCs can give the quest), it is able to be completed and turned in.

### Expected Blizzlike Behaviour

You can talk to the NPC and complete the quest no matter who gives it to you.

### Steps to reproduce the problem

1. Reach Level 10 on a Night Elf character.
2. Accept the quest "Elanaria" from Kyra Windblade in Dolanaar.
3. Run to Darnassus to see that Elanaria cannot be spoken to.
4. Abandon the quest
5. Run back to Dolanaar and accept the same quest from Moon Priestess Amara.
6. Run back to Darnassus and turn the quest in with Elanaria.
7. Observe that the quest could be completed.

### Extra Notes

https://classic.wowhead.com/quest=1684/elanaria
https://classic.wowhead.com/npc=2151/moon-priestess-amara
https://classic.wowhead.com/npc=3598/kyra-windblade
https://classic.wowhead.com/npc=4088/elanaria
https://wowgaming.altervista.org/aowow/?quest=1684
https://wowgaming.altervista.org/aowow/?npc=2151
https://wowgaming.altervista.org/aowow/?npc=3598

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment] 2022-05-22 11:23
Hello, Slysam. After taking the quest from both NPCs and trying to complete them, I had no issues in talking to the NPC in Darnassus. Have you tried exiting the game and re-entering or clearing your cache, sometimes addons, UI configurations or client modifications get in the way of quest completion.

![WoWScrnShot_052222_131751](https://user-images.githubusercontent.com/100415626/169692753-bf7dbb86-6d20-4748-be3d-da4f131a6bd6.jpg)

![WoWScrnShot_052222_131842](https://user-images.githubusercontent.com/100415626/169692760-f956bef0-99b0-40c1-ba33-bfe705105253.jpg)

**Comment by Slysam** [comment] 2022-05-22 11:28
I started a fresh install of the game today and don't have any addons other than whatever the server themselves is running. I downloaded from your site.

I also did exit and re-enter the game between both attempts of taking it from Kyra just to replicate what happened exactly.

**Comment by Gultask** [comment] 2022-05-22 14:49
Hi, Slysam, thanks for contributing!

Unfortunately I've also not been able to reproduce the issue. There is a fairly common UI bug from the game client that causes quest turn-in markers to disappear, making several quests impossible until you relog.

Sorry for it not working out, since you probably spent a lot of time making this issue but I'll have to close it.
Something to keep in mind for any future reports: Although we appreciate as much detail as possible, there is no need to double-check it since we can easily try to reproduce issues like these in seconds, if not just a few minutes.

Thanks again! 😄

**Closed by Gultask** 2022-05-22 14:49 UTC
Labels: Waiting for more feedback, Needs second opinion
