### ISSUE TITLE
Strange sounds in Valley of Trials

### ISSUE THREAD

**Issue by Mitradis** [chromiecraft/chromiecraft#1425] opened 2021-08-15 06:19 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Strange sounds in Valley of Trials
something like "VUK VUK" with a period per minute. I think this is someone's joke leaving as a "gift". **NOTE:** There is NO sound source. That is, it is played as the main sound (music). It is impossible to determine where he is from.
![WoWScrnShot_081521_091524](https://user-images.githubusercontent.com/21084600/129469150-3f0d9ad8-f6a8-42b7-8c8c-c3211a8a397a.jpg)

### Expected Blizzlike Behaviour

no strange funny sounds similar to mockery

### Steps to reproduce the problem

go to Valley of Trials

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Mitradis** [comment] 2021-08-15 22:47
these sounds are heard when you fly on the wyvern

**Comment by Mitradis** [comment] 2021-08-16 10:49
it's not hard to believe just come there and that's it

**Comment by Mitradis** [comment] 2021-08-16 11:25
@syssneck @Sedatyf t's not hard to check just come there and that's it. Or it takes 3 weeks to put the label?

**Comment by Sedatyf** [comment] 2021-08-16 13:46
We're doing what we can as we all are volunteer for this. So everyone have a job, family, friends, ect. So it's not because you're working on CC now that everyone does. 
Furthermore, it won't take 3 weeks to put a label if you report bugs correctly. It took me 5 minutes to see that is a duplicate of https://github.com/chromiecraft/chromiecraft/issues/17. The less we have false reports, the faster we are on good report

I'm closing this one as it's a duplicated from issue #17 previously mentioned

**Closed by Sedatyf** 2021-08-16 13:46 UTC
Labels: Needs Triage

**Comment by Mitradis** [comment] 2021-08-16 20:15
why you close? https://github.com/chromiecraft/chromiecraft/issues/17 is close. But its not client bug.

**Comment by Mitradis** [comment] 2021-08-16 20:17
you are so simple, it's easier for you to close and that's it. No problem - No problem. let's close all objectionable problems.

**Comment by Mitradis** [comment] 2021-08-17 08:29
@Sedatyf I determined the reason. Ok this is a duplicate. But your link is closed. I will seek to open it.

**Comment by Sedatyf** [comment] 2021-08-17 08:33
Post your findings in the closed one and we'll check it if you want

**Comment by Faq** [comment] 2021-08-17 15:24
Actually that is not "VUK VUK" what they say, but work, work before start to cut the tree. Those peons are lot in that zone, so no wonder they can be heard.

The same behavior on:
`TrinityCore rev. 94c03b2107ad 2021-01-01 04:03:52 +0100 (3.3.5 branch), wow client enUS`
