### ISSUE TITLE
Braided Eternium Chain not working for ferals

### ISSUE THREAD

**Issue by Erson33** [chromiecraft/chromiecraft#6143] opened 2023-09-14 19:55 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Presently, the Braided Eternium Chain buff disappears when shifting into Cat Form. I have tested this with both my feral spec (has Leader of the Pack) and my Resto spec (has Master Shapeshifter, crit bonus for cat form). I have not yet tried it with Bear Form (or Travel to see if it is just shapeshifting that is the issue) in either spec however I will, if needed, once the 1hour CD is up. 

### Expected Blizzlike Behaviour

During both TBC and Wrath this buff stacks with LOTP. I confirmed this in the Druid Discord. I do not have an active subscription to classic to test further.
![BEC Discord](https://github.com/chromiecraft/chromiecraft/assets/118743942/1a0d5ef9-8514-4312-bbfb-44b1e584bf7a)

### Source

Once again, please see the linked confirmation.
![BEC Discord](https://github.com/chromiecraft/chromiecraft/assets/118743942/cd7555b6-3019-47c8-9f68-e70940b657f7)

### Steps to reproduce the problem

1. Equip BEC
2. Use BEC
3. Change to feral forms (I would try with various specs however the 1CD is prohibitive and I've already used wasted half the charges on my necklace)
4. Monitor which buffs remove the BEC buff.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Erson33** [comment] 2023-09-14 21:03
Update: Shifting to Bear Form without the talent Leader of the Pack selected also removes the buff from Braided Eternium Chain.

**Comment by UndoUreche** [comment] 2023-11-29 16:49
Confirming: shifting to either cat form or bear form, with no other buffs will remove the necklace buff. Shifting into moonkin form, together with Moonkin aura will NOT remove the buff. Have not tested tree of life.

**Comment by alecsci** [comment] 2024-09-07 20:58
Hi @Erson33,
Thanks for your report!

I will close this for now, since it's a duplicate of https://github.com/chromiecraft/chromiecraft/issues/5449
And more items have been identified there besides Braided Eternium Chain in the initial report.
Also, we are aware of this issue and we will track it via: https://github.com/azerothcore/azerothcore-wotlk/issues/19823

**Closed by alecsci** 2024-09-07 20:58 UTC
Labels: Duplicate
