### ISSUE TITLE
Shadowcraft Cap

### ISSUE THREAD

**Issue by Foxtrot455** [chromiecraft/chromiecraft#2154] opened 2021-10-20 02:23 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

So I have been in scholomance for almost 40 runs and neither me or another player midgetman have seen the shadowcraft cap drop at all and i have a whole set of the lowest drop rate items in the dungeon before i get the cap which has a drop rate of 6.65%  while the items for the Cadaverous set has a below 1% drop rate and i just feel like theres gotta be something up with the drop rate for the cap as i have seen just about everything else drop but that cap

### Expected Blizzlike Behaviour

idk how i would write this but even in classic wow the drop rates werent this unlucky you usually get it pretty fast eventually but for this i feel im never gonna get it so i feel theres something up with it

### Steps to reproduce the problem

have it somehow drop more often 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-10-20 12:56
Thanks for the report. I've had a look at Gandling's drop table, and it shows the Shadowcraft Cap is one of a group of 9 items set to drop automatically, so it has a 1/9 = 11.1% drop rate. This matches the correct rate as shown on Wowhead pretty closely - see https://tbc.wowhead.com/item=16707/shadowcraft-cap.

Just to make sure, I went into Scholo and killed Gandling a few times, and on the 6th kill he dropped it:

![WoWScrnShot_102021_231620](https://user-images.githubusercontent.com/81782124/138095801-3df819b7-1018-44fd-a940-f79fd83269f6.jpg)

So it does seem to be working properly. You've been pretty unlucky, but that's not a bug. Closing this accordingly.

**Closed by Azcobu** 2021-10-20 12:56 UTC
Labels: Needs Triage
