### ISSUE TITLE
Rattlecage soldier melee hitting from ranged

### ISSUE THREAD

**Issue by zephiros25** [chromiecraft/chromiecraft#130] opened 2021-03-05 09:24 UTC
##### ISSUE: Rattlecage soldier melee hitting from ranged
FACTION SIDE: Horde and Alliance

##### CONTENT PHASE:

Level 6-9
Undead leveling in Tirisfal Glades

##### SMALL DESCRIPTION:

NPC: [Rattlecage Soldier](https://wotlk.evowow.com/?npc=1520) 
Zone: [Tirisfal Glades](https://wotlk.evowow.com/?zone=85) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This mob is melee and should not attack from ranged.

##### CURRENT BEHAVIOUR:

When I hit this mob with a frostbolt from max range, the moment my frostbolt hits I get hit with 2 rapid successive melee strikes.
After that the mob will start to run towards me as intended and only strike me when in appropriate melee range.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Attack a rattlecage soldier from ranged
Step 2 Observe 2 rapid melee strikes hitting you even though the mob is still at ranged.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by zephiros25** [comment] 2021-03-05 09:26
![Uploading WoWScrnShot_030521_102517.jpg…]()

**Comment by necropola** [comment] 2021-03-05 10:19
Probably related to or even a duplicate of #115

**Comment by zephiros25** [comment] 2021-03-05 10:20
You're correct, this can be deleted.

**Closed** 2021-03-05 10:29 UTC
Labels: Needs Triage
