### ISSUE TITLE
Discovering Alexston Farmstead from underground, inside Gold Coast Quarry

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#2304] opened 2021-11-11 17:36 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_083121_133558](https://user-images.githubusercontent.com/89823720/141342861-2a3751b5-4964-410e-bac9-4a5d53a1fae1.jpg)

### Expected Blizzlike Behaviour

I don't think this should be possible.

I can't prove it's not possible, no matter how many old videos I watch. I could only hope to find a video where someone in retail Wrath does discover the Farmstead from within the Quarry, which I haven't found, so I am logging it here.

### Source

none

### Steps to reproduce the problem

Create character who has not discovered Alexston Farmstead
TP Westfall
Run northwest to coast, south to Gold Coast Quarry, and then down & through it

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-12 07:59
Cna't reproduce it on local AC. NPC inside node not coo
![WoWScrnShot_111221_105424](https://user-images.githubusercontent.com/85256266/141431372-eb697d67-2e84-45e4-b5ef-90bf916e907d.jpg)
l

**Comment by IntelligentQuantum** [comment] 2021-11-13 06:18
![Screenshot_20211113_094252](https://user-images.githubusercontent.com/14080516/141608330-7a94781f-a2d3-4b6c-8680-27f661abed12.png)

**Comment by ntrna** [comment] 2021-11-13 12:18
IIRC, I was not on that exact location, but perhaps a little earlier in the cave. Perhaps I jumped. It wouldn't have been far from there, however, as the message on screen hadn't faded.

**Comment by Shineslippers** [comment] 2021-11-13 12:32
Sure, but even with this need precise place

https://user-images.githubusercontent.com/85256266/141643929-b8583a9d-de41-4879-bccc-2326aa3f5340.mp4

**Comment by Gultask** [comment] 2022-06-11 05:24
I'll close this because we were unable to reproduce, but I don't doubt you, ntrna, there are a couple of locations like these, one for example is discovering Lost Rigger Cove inside a cave in the middle of Durotar!

**Closed by Gultask** 2022-06-11 05:24 UTC
Labels: Unable to Reproduce, Bug Under Evaluation, More Research Needed
