### ISSUE TITLE
Execute using Rage and going on global cd but no damage

### ISSUE THREAD

**Issue by SGCSN** [chromiecraft/chromiecraft#513] opened 2021-05-02 14:43 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When using the warrior ability execute, sometimes rage is spent and global cd activated, but the execute doesn't go through, as it deals no damage and there is no parry etc and it also doesn't show in the combat log. Tried to force the issue but it appears to be random. It happened 2 times right after another on the same mob, it was a level 40 Wastewander Thief.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you press execute, you lose rage and the spells gets used.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I've tried, but didn't find a reliable way to reproduce the issue.
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Notrox1** [comment] 2021-05-02 18:36
I reported this Issue a Month ago and thought it was fixed but now in the new bracket I expierience the same.
Its definitly the same behaviour then in my Videos. Tested against lvl 40 Mobs now.

**Comment by Amrx2** [comment] 2021-05-03 19:11
This was the previous report - https://github.com/chromiecraft/chromiecraft/issues/235#issue-834444308

Has the fix been altered or not correctly applied in the latest bracket perhaps?

**Comment by necropola** [comment] 2021-05-05 12:02
Duplicate of #235
A fix has been merged into AC, but not yet into CC

**Closed** 2021-05-05 12:41 UTC
Labels: Closed, Duplicate

**Comment by Notrox1** [comment] 2021-05-07 09:46
Sorry I commented the other ticket. Wasnt online for 2 days.
After the merge I never expierienced it again. But with the new bracket releasing it definitly happens again.
I had it happen like 100 times while leveling up to 39 and while farming ogres in badlands it happens all the time.
Maybe some other warrior can provide some footage on this? @SGCSN 
I probably will not be able to play for atleast a week.
