### ISSUE TITLE
Chain of the Scarlet Crusade 6/6 does not add 10 hit

### ISSUE THREAD

**Issue by Jesterial** [chromiecraft/chromiecraft#554] opened 2021-05-06 18:44 UTC
Client - [X ] enUS

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Prior to equipping my 6th piece of "Chain of the Scarlet Crusade" I had 34 Hit Rating, once I equipped the "Scarlet Boots" my hit dropped 5 points (because previous non set boots had 5 hit) to 29 hit. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Upon putting all 6 pieces of "Chain of the Scarlet Crusade" the player should have "Set: increases your hit rating by 10"

##### STEPS TO REPRODUCE THE PROBLEM:
Literally just have to equip and unequip a 6th piece of "chains of the Scarlet Crusade" gear and you will see the stat issue

##### EXTRA NOTES:
This issue took place on a enGB client so I deleted everything and went to ChromieCraft website and downloaded your version and the issue still persisted with your enUS client from the ChromieCraft site.

![Scarlet Gear no hit](https://user-images.githubusercontent.com/83781986/117349288-38abef80-ae79-11eb-8a56-9d3e435fc643.PNG)
![Scarlet Set no hit](https://user-images.githubusercontent.com/83781986/117349340-482b3880-ae79-11eb-8642-77418781e2d9.PNG)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jesterial** [comment] 2021-05-06 22:48
Just in case the gear in question is confusing for some reason.
https://classic.wowhead.com/item-set=163/chain-of-the-scarlet-crusade

**Comment by Azcobu** [comment] 2021-05-08 08:24
Thanks for the report and the links. Unfortunately, I couldn't reproduce this. I tried with two lvl 39 chars, a tauren warrior and a human pally like yours. On both, adding the 6th piece of the Scarlet set correctly added +10 to hit.

With 5 pieces:
![WoWScrnShot_050821_173951](https://user-images.githubusercontent.com/81782124/117532253-b01e8200-b025-11eb-9eae-0ada13fb5e35.jpg)

with 6:
![WoWScrnShot_050821_173956](https://user-images.githubusercontent.com/81782124/117532257-b14faf00-b025-11eb-8e52-b5cc6e0ea288.jpg)

It may be worth removing all your gear and adding just the set, one piece at a time, to see if it's still playing up. I'll close this issue for now, but if you are still getting this on an otherwise unequipped character, let us know and we'll try to narrow down why it's affecting your character in particular.

**Comment by Jesterial** [comment] 2021-05-08 13:14
Ok so I went back and tested it all over again with and without addons. Continued with the same problems. Then I went back and did the same thing but after deleting the wonderful WTF file. Because who doesn't love resetting all the work one did with addons. This solved the problem but I noticed another issue. Before I had 7.1% hit @ 39 with 34 hit and now that I have 7.4% hit @ 39 with 44 hit. Is this a problem with the hit improperly scaling from the 29 bracket? Because 10 hit should have produced far more than .3% hit. Just saying it could become an issue or everyone is just going to have to delete their WTF file after leveling each bracket.

**Comment by Azcobu** [comment] 2021-05-08 14:39
Thanks for the update. Nice work with the addons - if it helps, you can always rename the folder to WTF-OLD or something instead of deleting it. That way you can test and then put the old folder back if you need to, saving all your settings.

As for your hit ratings, again I'd be pretty suspicious about client/addon errors. (Well, maybe not addon if your WTF folder is brand new.) So just to get this straight, you're wearing 5 pieces of Scarlet gear at lvl 39 with 34 hit, generating 7.1% hit chance. You add the 6th piece, get +10 hit rating to 44 hit, and your hit chance only goes to 7.4%? That does sound weird - +10 hit rating should be about 7.1 / 34 * 10 = ~2.1% hit chance for a total of about 9.2%, assuming linear scaling of course. The problem is to calculate the actual expected hit chance given a specified hit rating at level 39 so we can compare it to what you're seeing. I haven't yet found a formula for that, but I'll reopen this issue so I don't forget to chase it up.

**Comment by Jesterial** [comment] 2021-05-08 15:46
Ok so prior to deleting WTF file and addons and so forth. I was 39 with 34 hit with gave me 7.1%. My hit items were Comfortable Leather Hat +18 hit,  Amulet of Truesight +11 hit, and Scarlet Boots enchanted for +5 hit. Then I added the Scarlet Chestpiece to give me to 6 of 6 bonus for +10 hit. That's when I noticed I was still at 34 hit with 7.1%. So fast forward to after deleting my enGB client, reinstall Chromiecraft client, delete WTF file and now I have the proper 44 hit but now my % is 7.38%. I cant go back now and recreate the issue because now the hit% is different than it was. Thats why I brought up the hit% from lvl 29 and maybe something didnt change from the lvl 29 bracket. I was literally in guild complaining about having to fix this to make it to 8% hit or higher and then when it got fixed I see it only went to 7.38%. Its just very suspicious, hope the info helps.

**Comment by Azcobu** [comment] 2021-05-09 07:44
Well, the good news is that replicating your gear leads to the same %hit chance, 7.38% at 44 hit rating. So I'd be a lot more inclined to trust that number than the 7.1% your enGB client was reporting at 34 hit. It seems likely that the 7.1% figure it gave, along with the 6 piece +hit rating not being added, just wasn't reliable, and that what you're seeing now is the correct figure.

Also had a look at hit level scaling by taking my +44 hit rating pally down to lvl 29 and back up to lvl 39 in stages, and didn't notice any issues. The hit chance is on a smooth curve to 80, so +44 hit at lvl 29 will give you 10.9% hit chance, but only 7.38% at lvl 39 (and only 4.4% at lvl 60.)

**Closed** 2021-05-12 10:25 UTC
Labels: Unable to Reproduce, WFMD
