### ISSUE TITLE
Lazy Peon "Work Work" sound effect played in valley of trials

### ISSUE THREAD

**Issue by lambxrt** [chromiecraft/chromiecraft#1524] opened 2021-08-24 18:49 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

In orc/troll starting zone, the Peon "work work" sound effect is played continuously.

### Expected Blizzlike Behaviour

shouldnt hear the sound until clicking on lazy peon.

### Steps to reproduce the problem

1. create orc or troll
2. be in durotar

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Windows 10 pro 64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-08-25 12:31
Thanks for the report. However, this is a duplicate of an issue that has been raised before - see https://github.com/azerothcore/azerothcore-wotlk/issues/4303 for another discussion. It has previously been closed as a client error of some kind, so will follow suit here.

**Closed by Azcobu** 2021-08-25 12:31 UTC
Labels: Needs Triage
