### ISSUE TITLE
Dragon's Call [Weapon] - Dragon Guardian passive and not attacking

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#2141] opened 2021-10-18 09:05 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Dragons Call Dragon spawns and just stays there, not doing anything and being on passive (i guess)

Duplicate to:
https://github.com/chromiecraft/chromiecraft/issues/1933

Issue should have been fixed in this Ticket but its not atm.

### Expected Blizzlike Behaviour

He should attack with fireballs and do some damage

### Source

This is a duplicate to closed ticket : https://github.com/chromiecraft/chromiecraft/issues/1933

### Steps to reproduce the problem

1. Equip Dragon's Call
2. Do auto attacks and wait for the dragon to spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment] 2021-10-18 12:47
Tested on local AC some times it works, some times it doesn't. I think it depends on the faction of the enemy.
I found that it attacks skeletons and others, but not nagas. (Haven't tested all factions)
To reproduce: .go c id 4686

@Notrox1 Does this seem to match your experience? Or does it occur for you with all mobs?

**Comment by Notrox1** [comment] 2021-10-18 16:39
Okay so i went testing a bit and i now can relay to what you are saying.
In BRD, the groups before the endboss. It works on Humans but not on dwarfes. 
Outside it worked on skeletons but not on satyrs.

The tuning and spells its using seems fine.

**Comment by Shineslippers** [comment] 2021-11-24 19:08
I know it's a bit late, but nowdays 24/11 it's working as intended. @Notrox1 can i close it or you have issues? Checked places what you mentioned and nothing.

**Comment by Salehyn** [comment] 2023-09-18 06:33
Seems to work fine as of today.

**Closed** 2023-09-18 06:34 UTC
Labels: Closed, Unable to Reproduce
