### ISSUE TITLE
RDF Ulda locked.

### ISSUE THREAD

**Issue by NidaleeLiadrin** [chromiecraft/chromiecraft#501] opened 2021-05-01 18:23 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Queueing on RDF to uldaman is locked to lvl 50 , when it fails it puts you on a 30 min cooldown

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Uldaman should be allowed to be accessible for the current bracket.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Queue RDF
2. When you get uldaman you'll notice its locked
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by NidaleeLiadrin** [comment] 2021-05-01 19:41
GM announced in world chat that it was fixed, minutes after i posted the issue. To be closed.

**Comment by FrancescoBorzi** [comment] 2021-05-02 00:55
duplicate of: https://github.com/chromiecraft/chromiecraft/issues/500

please look for existing issues before opening new reports

**Closed by FrancescoBorzi** 2021-05-02 00:55 UTC
Labels: Needs Triage
