### ISSUE TITLE
Rogues able to roll "Need" on shields in regular RDF group loot rules

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#535] opened 2021-05-04 13:15 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

During a run of Uldaman through the random dungeon finder, I was able to roll "Need" on a blue shield. For the sake of testing, I rolled Need and won (I did not mean to ninja, offered to reroll the item if a group member wanted to).
At the end of the dungeon in the last chest, another shield was offered for roll, and we can see the "Need" button is white (and clickable).
Here are two screenshots:
![WoWScrnShot_050421_144801](https://user-images.githubusercontent.com/81818678/117008554-24d28300-aceb-11eb-8a3d-fff2dcd7c56e.jpg)
![WoWScrnShot_050421_150834](https://user-images.githubusercontent.com/81818678/117008557-2603b000-aceb-11eb-8da3-9b33d6d48611.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Rogues shouldn't be able to roll "Need" on shields as they can't equip them?
Actually I'm not sure about this since I don't know how the loot rules were implemented in WotLK, but since there are rules regarding armor or weapon type (like pallies and warrior can only roll on mail and not leather or cloth, rogues can't roll on two-handed weapons, etc), I figured this would be a bug.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a rogue.
2. Get a shield to drop.
3. Roll Need and tell people you are not a ninja and are an active beta tester.

##### EXTRA NOTES:

Maybe this is linked to the issue about hunters being able to roll on shields too?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment] 2021-05-05 06:58
Happens for mages too

**Comment by necropola** [comment] 2021-05-05 11:32
Duplicate of #190

**Closed** 2021-05-05 12:39 UTC
Labels: Closed, Duplicate
