### ISSUE TITLE
[PTR][AQ40] The Prophet Skeram problems - part 1

### ISSUE THREAD

**Issue by kerricsson** [chromiecraft/chromiecraft#3805] opened 2022-07-17 19:05 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15263
Boss do not consume mana for his spells thus it's not possible to define real Skeram during image split phase.

### Expected Blizzlike Behaviour

Boss should consume mana for his spells thus it will be possible to define real Skeram during image split phase.

### Source

'https://classic.wowhead.com/guides/the-prophet-skeram-temple-of-ahnqiraj-strategy:
1. You can identify which Skeram is the real one by either leaving a raid marker on the boss before he splits, or by looking at the copies' mana - The copies will always have full mana, while Skeram will deplete his mana through the fight. As these copies deal the same amount of damage as the real boss with their abilities, interrupts must continue, especially with Arcane Explosions.

### Steps to reproduce the problem

1. Go to PTR.
2. Enter AQ40.
3. Engage  The Prophet Skeram and reduce his health till 75% letting him cast some spells.
4. Obserbe that mana didn't reduce and when copies appears, all 3 have full mana.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. cc52712ac12e 2022-07-15 16:11:49 +0200 (master branch) (Unix, Debug, Static)

**Comment by Maelthyrr** [comment] 2022-08-29 19:49
Hi, Thanks for the report. I'm sorry it's late. I've check on local and on PTR and the boss use mana. Probably fix with a rework there are many weeks. So I will close this issue.

**Comment by Gultask** [comment] 2022-09-11 02:47
The spells were previously triggered and not cast. The difference is that triggered spells do not have a cast timer and do not cost any mana. It's working as intended now.
As this was a valid report when it was made I'll mark it as confirmed :)

**Closed by Gultask** 2022-09-11 02:47 UTC
Labels: Closed
