### ISSUE TITLE
Cannot skin Cave Yeti in Hillsbrad Foothills

### ISSUE THREAD

**Issue by pragkun** [chromiecraft/chromiecraft#180] opened 2021-03-09 13:24 UTC
##### ISSUE: FACTION SIDE: 

 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

NPC: [Cave Yeti](https://wotlk.evowow.com/?npc=2248) Cannot skin them, says loot creature, but it does not have any loot 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should be able to skin them

##### CURRENT BEHAVIOUR:

Cannot skin, it says loot the creature first. But it does not have any loot 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Kill Cave Yeti
Step 2 Try Skinning them

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-03-10 08:38
Related to or duplicate of #86

**Closed** 2021-03-10 10:57 UTC
Labels: Closed, Duplicate
