### ISSUE TITLE
[Warlock] Conflagrate has a delay to be activate after immolate is cast on the target

### ISSUE THREAD

**Issue by shadownecro90** [chromiecraft/chromiecraft#1136] opened 2021-07-09 08:46 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Type here.
Conflagrate has a delay to be activate after immolate is cast on the target. The delay is about 1-1.5 sec. I'm not talking about global CD.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
 https://www.youtube.com/watch?v=Wh1gsxmtIzc  6min45sec

Type here.
When you use Immolate, Conflagrate Should be activated immediately.

##### SOURCE:
 https://wotlkdb.com/?spell=17962

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a warlock
2. Put a Destruction Build with CONFLAGRATE on it
3. Train your spells
4. Go to a Dummy or mob and test using Immolate > Conflagrate spells (u'll notice a delay)

##### EXTRA NOTES:

Type here.
Go to a Dummy or mob and test using Immolate > Conflagrate spells (u'll notice a delay)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment] 2021-07-10 06:15
I can't confirm it in my local AzerothCore setup (dc76e6b), no delay at all.

**Comment by Struggler69** [comment] 2021-07-10 23:25
I confirm, I have the same issue, Immolate debuff won't make Conflagrate usable for at least half a second father Immolate has been applied, when it should be instant.

Current OS Windows 10, ChromieCraft's client (downloaded from the official page).

Screenshot: [https://prnt.sc/1a34kzl](url)

**Comment by Azcobu** [comment] 2021-07-14 10:10
Thanks for the report. I can confirm there is a small delay which is preventing Conflag casts immediately after Immolate (and the GCD obviously). However, when this issue has been raised previously, the consensus has been that this is deliberate and Blizz-like behaviour. See 

https://github.com/azerothcore/azerothcore-wotlk/issues/1571
https://github.com/azerothcore/azerothcore-wotlk/issues/2801
https://github.com/azerothcore/azerothcore-wotlk/issues/3458
another summary: https://github.com/SunwellTracker/issues/issues/1254

...and a bunch of other links in those issues. Closing as intended behaviour accordingly.

**Closed by Azcobu** 2021-07-14 10:10 UTC
Labels: Needs Triage, Needs second opinion

**Comment by shadownecro90** [comment] 2021-07-16 19:13
That is not true. I have been playing in blizzard server. There is no delay. This delay ruin the game play and the class specific. This delay is removed by blizzard as soon as they detect it in early wotlk patches.

**Comment by Azcobu** [comment] 2021-07-17 04:54
Please note that we don't operate on bare assertions. If you have checkable evidence for this claim, such as patch notes, videos or other verifiable sources from the WotLK period, please provide links to them in a comment.
