### ISSUE TITLE
"How Big a Threat" Darkshore Quest

### ISSUE THREAD

**Issue by basicparts** [chromiecraft/chromiecraft#4914] opened 2023-01-30 03:04 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

For the quest 'How Big a Threat' (https://www.wowhead.com/classic/quest=985/how-big-a-threat) you have to reach a camp. Once the camp is reached nothing occurs. I used the comments in the wowhead thread about the quest to make sure I was doing the correct thing. I had a higher level player help me clear out the camp so I could walk all around it. Nothing I did ticked the quest off. 

### Expected Blizzlike Behaviour

Walk to the Furbolg Camp (Blizzlike is just get to the vicinity and you're good) to tick the quest off.

### Source

https://www.wowhead.com/classic/quest=985/how-big-a-threat

### Steps to reproduce the problem

No idea

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment] 2023-01-31 14:55
Thanks for the report,
i was able to complete the quest coming in from a few angles. perhaps it was a visual bug where it didnt show progress on your end
![image](https://user-images.githubusercontent.com/11332559/215794524-af31770f-2714-4f9b-970b-35f9715faf34.png)

**Comment by heyitsbench** [comment] 2023-04-29 21:34
@basicparts Please re-test and confirm if possible.

**Comment by Vyperhand** [comment] 2023-05-18 03:19
I can confirm this is an issue.  The northern detection point is much farther south than the blizzlike equivalent.   Done this on two characters now and the northern boundary of the detection range is inside the camp, past the large totem.  On retail, this range was outside physical aggro distance for the furbolg patrols.  For example,  you should detect it at roughly 39, 51.  However, coming in from the north it does not complete until you are closer to 40, 55.  The west boundary is better, the east boundary is much too close again.   West you don't have to enter the camp, but you must go to the same distance from the camp as the western wandering patrols.  

This quest is normally completable from N, E, or W without having to get within physical aggro distance of the outer patrols.

**Comment by Vyperhand** [comment] 2023-06-15 21:11
This remains an issue at this time.  It works, just not quite like it should.  The detection boundaries need adjusting.

**Comment by The-GhostRider** [comment] 2023-12-03 03:41
I did multiple tests, and I was unable to reproduce the alleged Bug in any way, as demonstrated by the video below made by me.

[![Anteprima](https://user-images.githubusercontent.com/1884642/287495251-a0cb77eb-54e0-4cdc-a03f-43294e9aaf1e.png)](https://www.youtube.com/embed/_4vAGruAmyA)

I understand, however, that this has happened to some of you..
There are some reasons for this:
- The Client version; For example, I see that whoever made this report uses the enGB version, (which is the most buggy version of all), the recommended version for playing WoW is enUS, it is the most fixed with fewer bugs than the enGB. (in fact I use enUS and I have not encountered this alleged bug.

Or they could be:
- Addons not perfectly compatible with the client you are using; creating "Visual Bugs" where the quest has actually been completed but instead the client does not show you the completion.

But I'm pretty sure that the problem is the enGB Client.
try using the enUS Client and you will see that the quest works..

For these reasons, I am closing the report.

**Closed by The-GhostRider** 2023-12-03 03:41 UTC
Labels: Unable to Reproduce

**Comment by Vyperhand** [comment] 2023-12-04 19:19
FYI - ENGB is the default auto-select on this form.  So that doesn't mean the submitter is on EnGB, it just means they accepted defaults on the form, unfortunately.
