### ISSUE TITLE
Dungeon Druid cloth,1h maces,shields roll fix

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#190] opened 2021-03-11 10:18 UTC
##### STEPS TO REPRODUCE THE PROBLEM:Go to the dungeon and wait for drops.

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-03-11 15:08
Druids cannot roll need on cloth since patch 3.3.0 and I'm not aware that the chosen role made any difference in RDF of 3.3.5a.
https://wow.gamepedia.com/Need_Before_Greed#Problems_with_Need_before_Greed

**Comment by Narixel** [comment] 2021-03-11 15:46
> 
> 
> Druids cannot roll need on cloth since patch 3.3.0 and I'm not aware (as in: I do not believe) that the chosen role made any difference in RDF of 3.3.5a. On the contrary, I have vivid memory of how annoying I found this restriction myself. So the solution is to simply act as a team, i. e. trade the item to the party member who actually needed it (which you can for a limited amount of time).
> https://wow.gamepedia.com/Need_Before_Greed#Problems_with_Need_before_Greed
> Was the druid actually able to equip the mace (weapon type learned, level not too high)?
> Do you have a screenshot of the need roll on the shield?

No but I will make one,next time I have the chance,I was level high enough,not that it matters when you roll,it was death speaker scepter to be more exact,I couldn't roll need on it as a druid.

**Comment by necropola** [comment] 2021-03-11 17:09
You are right about the level (doesn't matter) and Druids probably (Tauren do) know 1h Maces from the start, so you should be able to roll Need on [Death Speaker Scepter](https://wotlkdb.com/?item=2816)

**Comment by Stifler82** [comment] 2021-03-12 06:36
**Not sure**, but if I'm not mistaken, this is not a BUG, basically prioritizing is given to whoever wears that item as MAIN EQUIP.

I will try to explain myself better..
If in the dungeon there is for example:
**1 Warlock
1 Warrior
1 Priest
1 Paladin
1 Druid**

If a Chest "Cloth" is rolled (for example) even though the Druid can wear that item, priority is given to the Warlock and the Priest because of MAIN Equip they are "Cloth".

**(but I repeat: I'm not 100% sure).**

**Comment by necropola** [comment] 2021-03-12 08:20
I'd consider the **Cloth** part of the issue sorted. It's not a bug. The restriction was added in 3.3.0 and is implemented in AC code as
```C++
        if (_class == CLASS_ROGUE || _class == CLASS_DRUID)
            if (proto->SubClass != ITEM_SUBCLASS_ARMOR_LEATHER)
                return EQUIP_ERR_CANT_DO_RIGHT_NOW;
```
Though the Mace and Shield part of the issue are still open. Druids should be able to roll Need on Maces but not on Shields. Therefore it would be good to have some proof/screenshot and/or an easy way to reproduce it, since I can't tell from inspecting the code why this would happen.

**Comment by AbraKabastard** [comment] 2021-03-16 01:01
Im wondering where the code is that blocks shields unless you know shields?
```c++
    if (proto->RequiredSkill != 0)
    {
        if (!GetSkillValue(proto->RequiredSkill))
            return EQUIP_ERR_NO_REQUIRED_PROFICIENCY;
        else if (GetSkillValue(proto->RequiredSkill) < proto->RequiredSkillRank)
            return EQUIP_ERR_CANT_EQUIP_SKILL;
    }
```
Wont get hit because Shields have 0 in ReqSkill.

```c++
    if (proto->Class == ITEM_CLASS_ARMOR && proto->SubClass > ITEM_SUBCLASS_ARMOR_MISC && proto->SubClass < ITEM_SUBCLASS_ARMOR_BUCKLER && proto->InventoryType != INVTYPE_CLOAK)
    {
        if (_class == CLASS_WARRIOR || _class == CLASS_PALADIN || _class == CLASS_DEATH_KNIGHT)
        {
            if (getLevel() < 40)
```
Wont get hit because Shield subclass is 6 and ITEM_SUBCLASS_ARMOR_BUCKLER  is 5.

**Comment by necropola** [comment] 2021-03-17 06:48
Looks like **All classes can roll need on Shields** (https://github.com/azerothcore/azerothcore-wotlk/issues/4858) is the only valid and reproducable part of this issue. Hence I linked it and will close this one as soon as the fix for the other issue gets merged.

**Closed** 2021-09-02 08:39 UTC
Labels: Confirmed, Linked [AC], Fix Ready
