### ISSUE TITLE
Imp pathfinding in water outside of Sen'Jin village.

### ISSUE THREAD

**Issue by Ragundah** [chromiecraft/chromiecraft#595] opened 2021-05-09 21:38 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Youtube Video - Too Large To Upload To Github](https://www.youtube.com/watch?v=1y2soqPeYOA)

I was able to accidentally re-create and record the issue presented in issue #228 The Makrura Clacker seems to be fixed, but the imp seems to have some pathfinding issue in the water around the Echo-Isle - Sen'Jin Village area. You can see the issue documented in the video attached.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Imp should not get stuck in water jittering. Imp should follow player through the water and get close enough to the enemy to attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Bring imp to coordinates listed (see above character health bar)
2. Swim around in water.
3. Fight nearby Makrura mobs.
4. Sometimes imp will glitch out in pathfinding.

##### EXTRA NOTES:

No additional information.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Ragundah** [comment] 2021-05-09 21:42
[Youtube Video - Too Large To Upload To Github](https://www.youtube.com/watch?v=1y2soqPeYOA)

**Comment by Azcobu** [comment] 2021-05-10 12:00
Thanks for the report. This issue seems to be covered by an existing AC ticket (https://github.com/azerothcore/azerothcore-wotlk/issues/5748), but as that one has no links back to CC, this seems a good place for it.

**Comment by Helias** [comment] 2024-11-09 22:58
the linked issue has been closed because it is not reproducible anymore so probably fixed https://github.com/azerothcore/azerothcore-wotlk/issues/5748#issuecomment-939742892
I think we can close this issue too then.

**Closed by Helias** 2024-11-09 22:58 UTC
Labels: Confirmed, Linked [AC], Class Issue, Vmaps/Mmaps/Pathfinding, Pets System Issues
