### ISSUE TITLE
Mithril Bound Trunk

### ISSUE THREAD

**Issue by azureccgh** [chromiecraft/chromiecraft#1445] opened 2021-08-16 15:14 UTC
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

https://wowgaming.altervista.org/aowow/?item=21228
Fished from Azshara floating wreckages.
After looting the item does not despawn, but remains in the inventory displaying [Empty Slot] within the container.
![WoWScrnShot_081621_174106](https://user-images.githubusercontent.com/89029548/129585707-262d673d-7552-49f5-a96a-e0debbbede81.jpg)

### Expected Blizzlike Behaviour

Upon shift+clicking the item should relinquish what ever it contains into player inventory bag spaced considered and then despawn/disappear. 
Upon Right Clicking only, it should open, and act like an open world chest, only disappearing once the entire content of the Mithril Bound Trunk is manually looted.
[sitations lacking]

### Steps to reproduce the problem

No idea what is meant to be written in here. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None
Elvui

### Server

ChromieCraft

**Comment by jamadaha** [comment] 2021-08-16 19:10
Thanks for the report!

The field "Steps to reproduce the problem" are what someone has to do in order to encounter the same thing. In this case, I think, it would be:
1. Acquire item 'Mithril Bound Trunk' (GM command .additem 21228)
2. Right-click trunk
3. Retrieve all
4. See whether the trunk disappears.

Tested on local server(AC 28a764641)
I followed the steps mentioned above, but it works fine for me. Both opening the trunk, and retrieving each item individually by right-clicking each. And by shift clicking the trunk.
In both cases it works as expected.

**Comment by jamadaha** [comment] 2021-08-16 19:13
As a note: one reason for this bug occurring could be your add-ons. As it is an interface related bug, you using an interface related addon (Which all are?) is the primary suspect.

**Comment by Azcobu** [comment] 2021-08-22 05:15
Yeah, I couldn't reproduce this either. Spawned in 20 Mithril Bound Trunks and shift-right-clicked half, and right clicked the others, and they all behaved properly. That's on a vanilla client with no mods running at all. Will close this as a probable client-side/mod issue, but feel free to let us know if you continue to have problems with an unmodded client.

**Closed by Azcobu** 2021-08-22 05:15 UTC
Labels: Needs Triage, Waiting for more feedback, Unable to Reproduce, Needs second opinion
