### ISSUE TITLE
Berserker stance quest for warriors at level 30 is bugged for me (but not for other players it seems?)

### ISSUE THREAD

**Issue by Invicta1986** [chromiecraft/chromiecraft#1003] opened 2021-06-26 00:18 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Berserker stance quest that you get as a warrior at level 30 is bugged for me for some reason, I dinged level 30, went to talk to warrior trainer in orgrimmar, he gave me the quest "The Islander", that quest tells you to go the island outside Ratchet to talk to the Macleod guy, this Macleod guy is supposed to give you the quest "The Affray" where you have to fight some guys and then fight Big Will, to get berserker stance.

I get to the Island, there is a "?" above Macleods head, but when I talk to him he never gives me the quest "The Affray" to be able to start the fight, nothing happens when I stand on the grate, and I can not even abandon the quest since it is not in my quest log, it kind of got stuck in some limbo between there, idk. Now there is a "!" above Macleods head but he just says "greetings bellatrixx" , nothing more.

Some level 32 warrior also came by randomly while I was trying to do this and he completed quest without problem in front of me, so it seems to be not bugged for everyone..

I tried running with no addons (I don't use addons anyway at the moment) , clearing cache several times, restarting/reloading several times, same problem. I can't even abandon the quest either from Macleod on the island or warrior trainer in Orgrimmar, so I am stuck ! and its a gamebreaking bug to not be able to get berserker stance (and WW weapon in next step of quest chain) as a warrior, so would really appreciate if this could be fixed soon!

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After first talking to Warrior trainer at level 30, and getting the quest "The Islander" , I then will go to talk to Macleod on Fray Island outside Ratchet while being level 30 as a warrior, next step of quest state/chain should be to get the quest "The Affray" from Macleod, to be able to fight "Big Will", this step of the quest never gets active for me.

youtube link here: https://www.youtube.com/watch?v=IaNqmKNum-U

##### STEPS TO REPRODUCE THE PROBLEM:

1.  NPC to teleport to I guess is "Klannoc Macleod" on Fray Island outside Ratchet.
2. No idea what this means, "debug flags on Cmake". ?
3. Dont know what this means, "look at the console while the bug happens." ?
4. All needed info is in the description above I think, when I do ".npc info" while selecting Macleod NPC this info is what I get:

"DB GUID 14137, current GUID 11064"

And a lot of other info that is probably not relevant.

##### EXTRA NOTES:

This is the npc: https://classic.wowhead.com/npc=6236/klannoc-macleod

This is the quest that is supposed to start/be available for me after talking to macleod: https://classic.wowhead.com/quest=1719/the-affray

(and after completing that quest after fighting Big Will, I am supposed to get my berserker stance and then get the quest "the Windwatcher to be able to get my whirlwind weapon: https://classic.wowhead.com/quest=1791/the-windwatcher

again here is youtube clip of me being level 30, macleod NPC having "!" above his head, but not saying anything other than Greetings, Bellatrixx, and never giving me "The Affray" quest, even after /reloading, and I did try clearing cache/reload/restart several times.

https://www.youtube.com/watch?v=IaNqmKNum-U

Hope this could be fixed asap because its a gamebreaking bug and as warrior getting to 30 is a big milestone to get berserker stance and the WW weapon, thanks in advance!

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment] 2021-06-26 07:53
I had no problem completing this mission, but with the next one.

https://github.com/azerothcore/azerothcore-wotlk/issues/6587

**Comment by Invicta1986** [comment] 2021-06-26 08:01
> I had no problem completing this mission, but with the next one.
> 
> [azerothcore/azerothcore-wotlk#6587](https://github.com/azerothcore/azerothcore-wotlk/issues/6587)

great to see its not just me having issues here !

**Comment by Eldarix** [comment] 2021-06-26 08:10
Thanks for the detailed report mate, they will look at it soon for sure ;)

**Comment by Invicta1986** [comment] 2021-06-26 09:45
just want to say a very helpful GM (Roboto) started chat with me today in game and helped me complete the quest by adding it manually to me, after that everything worked fine and I also got the second step in questchain, windwatcher quest without issues, but its quite worrying that this quest seems to work fine for some players, bugged for some players like me, and partially bugged for some players like Eldarix who commented above,

I will update if anything goes wrong in next part(s) of questchain, but big thanks to the quick and awesome support from the GM Roboto !

**Comment by r-o-b-o-t-o** [comment] 2021-06-26 14:32
I was able to pinpoint the source of this issue, it's actually a more general problem and not specific to this quest.

The problem is you cannot accept a quest that has a timer if you already have a quest with a timer in your quest log, whether you completed/failed said quest or not.

In your case @Invicta1986, you had the quest [[Torch Tossing]](https://wotlkdb.com/?quest=11922) in your quest log, which has a timer of 45 seconds.

For bug triagers out there, here is an example to reproduce the issue I'm talking about:
* Create an alliance character
* `.char level 30`
* `.go c id 2696`
* Verify that the NPC gives the quest "MacKreel's Moonshine" (quest with a timer), but don't take it
* `.q add 257` (another quest with timer)
* The NPC doesn't give the quest anymore

**Comment by pop-pig** [comment] 2021-06-28 12:12
On a local AC server, I can confirm what @r-o-b-o-t-o just found out, as a Horde. I tried taking the quest from #1023 after having taken this quest https://wowgaming.altervista.org/aowow/?quest=853 (first on with timer I could think of as Horde, did the pre-quest real quick), and I encounter the same issue as in #1023 .

Good find!

**Comment by Stump876** [comment] 2021-07-22 02:41
Has this issue been linked to AC? Are we good to remove the triage tag? I did a search on AC but couldn't find it. I don't want to close this prematurely, but it's been sitting here a while.

**Comment by r-o-b-o-t-o** [comment] 2021-07-24 12:30
> Has this issue been linked to AC? Are we good to remove the triage tag? I did a search on AC but couldn't find it. I don't want to close this prematurely, but it's been sitting here a while.

I don't think it has been linked yet, but we should create an issue describing the quest timer problem with the reproduction steps I sent in my comment, instead of doing an issue for this specific quest.

**Closed** 2021-08-09 18:53 UTC
Labels: Confirmed, Linked [AC], Generic Issues
