### ISSUE TITLE
Permafrost, Improved Blizzard, Slow effects

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#239] opened 2021-03-18 23:31 UTC
##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Slowed mobs with Permafrost are not moving with reduced movement speed, they are running with normal movement speed

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should be much slower because it's essential for frost mages to play

##### STEPS TO REPRODUCE THE PROBLEM:

1. get a 29 mage
2. let him aoe pull mobs with permafrost, improved talents, frost armor on
3. see how mobs are running too fast compared to blizzlike state
4. done

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment] 2021-03-20 09:19
Strange - pvp wise the slow works as intended also from what i saw the slow also applied to the npc - is it possible to provide more details as to area / npc where you noticed the issue ?

**Comment by Awkakelen** [comment] 2021-03-20 09:30
> 
> 
> Strange - pvp wise the slow works as intended also from what i saw the slow also applied to the npc - is it possible to provide more details as to area / npc where you noticed the issue ?

Yes, try Duskwood's Worgens at Rotten Orchard or Roland's Doom, they behave strangely (in my opinion) when they are slowed, they are moving too fast when they are debuffed.

**Comment by mturca** [comment] 2021-03-20 10:58
Just tested in the Orchard with the following steps:

Gathered a few Night Runners 4 or 5 by running around them and a tree 
Once the caught up the first time - Frost Nova them and waited for the other slow effects to pass (Frost Armor & CoC)
Once there was 1s on the nova timer started to cast blizzard (3/3 improved) and Permafrost 3/3. - the were noticeable slower - more than 50% slower than their normal speed as i was able to distance myself from them by walking. (note that i have movement speed increase on boots - both from the item and from enchant)

Also passed through the ticket details - you never specify if you have improved blizzard or not - you only say improve talent, but i assume that you have it.

**Comment by Helias** [comment] 2021-03-20 11:27
If the bug report is not reproducible I would close this issue

**Closed** 2021-03-23 23:16 UTC
Labels: Closed, Invalid
