### ISSUE TITLE
Dying in High Chief Winterfall's Cave will cause your spirit to release to Alterac Mountains

### ISSUE THREAD

**Issue by gewmi** [chromiecraft/chromiecraft#1265] opened 2021-07-21 17:47 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Dying in High Chief Winterfall's Cave causes your spirit to release to the Alterac Mountains.

### Expected Blizzlike Behaviour

Spirit releases to the Everlook graveyard.

### Steps to reproduce the problem

1. Go to the back of High Chief Winterfall's Cave in Winterspring
2. Die
3. Release your spirit you will be in Alterac Mountains

### Extra Notes

High Chief Winterfall's Cave is at the back of the furblog village in Winterspring.
NPC in the cave: https://classic.wowhead.com/npc=10738/high-chief-winterfall

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by iraizo** [comment] 2021-07-21 18:31
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7014

**Closed by iraizo** 2021-07-21 18:31 UTC
Labels: Needs Triage
