### ISSUE TITLE
Multiple Different Node Spawns on same Spot in Searing Gorge

### ISSUE THREAD

**Issue by Excelsus90** [chromiecraft/chromiecraft#611] opened 2021-05-11 12:17 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In Searing Gorge is a Spot with several Node Spawns on the same Spot. At least 4 at the same Spot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should not spawn into each other.

##### STEPS TO REPRODUCE THE PROBLEM:
At least 4 different Ores in one Spot spawning:
![grafik](https://user-images.githubusercontent.com/83700197/117813479-6a4efd00-b263-11eb-806f-f597b71d59d3.png)
![grafik](https://user-images.githubusercontent.com/83700197/117813519-763abf00-b263-11eb-995f-b3b254f97a62.png)

1. Go to the Spot in Searing Gorge
2. Wait for Respawn, if necessary

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment] 2021-05-11 15:01
duplicate of #450

**Closed** 2021-05-11 16:31 UTC
Labels: Confirmed, Linked [AC], [40 - 49]
