### ISSUE TITLE
[Quest] "The Bloodsail Buccaneers" - Missing POIs for Bloodsail Swashbucklers

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2498] opened 2021-12-07 09:28 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

There are missing POIs for Bloodsail Swashbucklers on the map during the quest "The Bloodsail Buccaneers". It just shows the POI in the area Bloodsail Compound.

![WoWScrnShot_120721_102433](https://user-images.githubusercontent.com/62797536/145002735-f14ac1fd-3ce0-4ba9-96ac-a78fe68e7f26.jpg)

 

### Expected Blizzlike Behaviour

There also should be a POI in the area Wild Shore near Booty Bay.

See: https://wowgaming.altervista.org/aowow/?npc=1563

### Steps to reproduce the problem

1. Accept the quest "The Bloodsail Buccaneers"

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=604
Bloodsail Swashbuckler: https://wowgaming.altervista.org/aowow/?npc=1563

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-12-07 12:07
Thanks for the report. The map seems to show whichever Bloodsail area is closest, and if you head south a bit it will show a POI for this quest on the Wild Shore:

![WoWScrnShot_120721_223130](https://user-images.githubusercontent.com/81782124/145026014-20ad2efc-926c-44d0-ac64-e23db5ce714f.jpg)

In the absence of any other sources, this looks like expected behaviour, so closing accordingly.

**Closed by Azcobu** 2021-12-07 12:07 UTC
Labels: Needs Triage, Triaging in progress
