### ISSUE TITLE
Extremely low droprate? 

### ISSUE THREAD

**Issue by Mojoo1** [chromiecraft/chromiecraft#7160] opened 2024-06-25 11:01 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Greetings. I would like to report couple of problematic low droprate items that seems to work incorrectly.

1) Nethervoid Cloak  (Hyjal trash) https://www.wowhead.com/tbc/item=32590/nethervoid-cloak
Its been my 4th Hyjal raid with full trash cleared, we had a lot of drops of Fists of Molten fury, caster Necks, and all other items, but this Cloak dropped only one per 4 full raids. I mean wtf? 

2) Recipe: Captain Rumsey's Lager https://www.wowhead.com/wotlk/item=34834/recipe-captain-rumseys-lager
I noticed that this item never drops from the quest. I've been playing on the server for a year now and do this task every day.
It really hurts because it is also related to achievement.  Its nothin even close to 3% droprate from Bag of Fishing treasures as per WowHead. 

### Expected Blizzlike Behaviour

More droprate

### Source

Wowhead

### Steps to reproduce the problem

1. not competent towards me
2. not competent towards me
3. not competent towards me
4. not competent towards me

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dbec1a14417a968e6f874a637330ceac8cd16020

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by amed80** [comment] 2024-06-25 12:31
Nethervoid Cloak currently like every other epic item have 0.12% to drop from trash (the latest fix for Fist/Claw drop rate doesn't affect this)

Recipe: Captain Rumsey's Lager currently have only 0.09% chance to drop from Bag of Fishing Treasures.

I don't know how accurate those rates to retail/classic wow but those are the one exist in AC.

Should add notice that the recipe is missing from both Crate of Meat and Barrel of Fish that can get from Shattrath daily cooking quest , unless there is already a progress mod to add it to them with wotlk release.

**Comment by heyitsbench** [comment] 2024-06-25 14:26
I'm going to say Cloak droprate is working as intended, and Lager recipe has already been reported, thus I will close this issue as a duplicate.

**Closed by heyitsbench** 2024-06-25 14:26 UTC
Labels: Needs Triage
