### ISSUE TITLE
Wicked Arrows not sold by vendors that are supposed to in Hellfire Peninsula

### ISSUE THREAD

**Issue by FrodoFragginz** [chromiecraft/chromiecraft#6865] opened 2024-03-17 07:44 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Quartermaster Drake - Sells Jagged and Blackflight, but skips the lvl 55 arrows
Supply Officer Pestle -  Sells Jagged and Blackflight, but skips the lvl 55 arrows

### Expected Blizzlike Behaviour

According to wow head (wotlk)those two vendors should sell Wicked Arrows

### Source

https://www.wowhead.com/wotlk/item=28053/wicked-arrow#sold-by;0+3+12

### Steps to reproduce the problem

1) Go to either Vendor
2) shop and see they don't have wicked arrows

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3bcdc4d23e9b9fa951bf02a74a77a4313078e823

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by FrodoFragginz** [comment] 2024-03-17 07:48
looks like there's a third vendor with this issue Sid Limbardi

**Comment by FrodoFragginz** [comment] 2024-03-17 09:14
Fabian Lanzonelli in Terrokar has the same issue.  You might want to just check all wicked arrows on wowhead and make sure all vendors that should sell it do sell it

**Comment by heyitsbench** [comment] 2024-03-17 14:47
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/5896.

**Closed by heyitsbench** 2024-03-17 14:47 UTC
Labels: Needs Triage
