### ISSUE TITLE
Lightning shield

### ISSUE THREAD

**Issue by reminuz** [chromiecraft/chromiecraft#3375] opened 2022-04-18 13:12 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

It's proc on every damage.

### Expected Blizzlike Behaviour

It's should proc once every few seconds.

### Source

"Only one ball will fire every few seconds"

### Steps to reproduce the problem

Attack a shaman with lightning shield up.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment] 2022-04-18 13:47
Thanks for the report, reminuz!

I wasn't able to reproduce the issue. Could you tell us which class were you playing and what is the attack speed of your weapon?

**Comment by reminuz** [comment] 2022-04-18 20:51
It's procs at every hit vs a player buffed with thorns for example

**Comment by Talthos** [comment] 2022-04-18 22:31
I presume he's talking about the 'internal cooldown' that applied to effects like Lightning Shield, Water Shield, Earth Shield, Bone Shield, etc.

The internal cooldown for those shield effects was a sort of 'grace period', which prevented another shield charge from being consumed right away.

Currently trying to re-locate one of the few Blizzard-backed sources that I distinctly recall finding, at one point...

**Comment by Talthos** [comment] 2022-04-18 23:36
[Aha! I finally found it!](https://www.mmo-champion.com/threads/611321-Beta-Invitations-Wintergrasp-Blue-posts)

Pointing out the relevant quote below, with the critical detail in bold:

"Bone Armor has always had an internal cooldown of 2 sec. **We just changed it to 3.5 sec, same as a shaman."**

**Comment by Gultask** [comment] 2022-04-19 01:46
Thanks a lot, [Talthos](https://github.com/Talthos)! I'll try it out tomorrow morning. I don't know the formal way to check but a few several dozen mobs attacking at the same time should tell me the ICD, heheh.

**Comment by Gultask** [comment] 2022-04-19 11:51
Internal cooldown seems fine to be. Although, I've seen a couple times that it will proc twice at once. I can't seem to replicate that consistently.
![WoWScrnShot_041922_083642](https://user-images.githubusercontent.com/100873791/163996401-7f420f08-1e0c-4c43-b3a4-295833843296.jpg)
![lightningshield](https://user-images.githubusercontent.com/100873791/163997120-bc26037d-a5fb-44b0-b595-1e48b62290d7.jpg)

**Comment by reminuz** [comment] 2022-04-19 16:49
> If I remember correctly, periodic damage ticks from debuffs should 'not' consume charges, either.
> 
> I vaguely recall that certain types of 'pulse AoE' damage (such as Blood Boil) wouldn't consume charges as well, but I'm not as sure about that one.
> 
> Fully absorbed damage (like when Power Word: Shield is active) might prevent charge consumption as well, but I'm even less sure about that being the case during WotLK.
> 
> We might not have 100% certainty until Wrath Classic, in any case.
> 
> Edit: Oh, and for the purpose of testing, I would suggest activating timestamps for the in-game combat log, so you can see _exactly_ how much time passes between procs.

![image](https://user-images.githubusercontent.com/100479737/164054906-1b227a6a-e749-47d1-b9b7-82168fda80a9.png)

**Comment by Talthos** [comment] 2022-04-19 17:33
> > If I remember correctly, periodic damage ticks from debuffs should 'not' consume charges, either.
> > I vaguely recall that certain types of 'pulse AoE' damage (such as Blood Boil) wouldn't consume charges as well, but I'm not as sure about that one.
> > Fully absorbed damage (like when Power Word: Shield is active) might prevent charge consumption as well, but I'm even less sure about that being the case during WotLK.
> > We might not have 100% certainty until Wrath Classic, in any case.
> > Edit: Oh, and for the purpose of testing, I would suggest activating timestamps for the in-game combat log, so you can see _exactly_ how much time passes between procs.
> 
> ![shamano](https://user-images.githubusercontent.com/100479737/164056305-abffe3e3-5dbd-472b-a158-13df853619f2.png)

Based on those timestamps, it looks like the ICD for Lightning Shield is set to just 1 second, rather than 3.5 seconds.

**Comment by Gultask** [comment] 2022-04-19 18:58
Oh yeah that was my mistake, forgetting about turning on the timestamps. But the cat form attack speed was 1s, and you can see at least 3 going off before I get hit by Lightning Shield again.
I'll test out more than just auto-attacks when I can. I'll try the periodic damage and moonfire like you've shown in the screenshot, reminuz, thanks for posting it.

**Comment by Gultask** [comment] 2022-04-20 17:53
I've only noticed it now. In the screenshot reminuz posted, the first Lightning Shield damage comes from the talent [Static Shock](https://wowgaming.altervista.org/aowow/?spell=51527), not from being hit. That *could* explain why I've been seeing Lightning shield deal damage twice in one proc.
I'll search for any info about the relationship with Static Shock and the Lightning Shield ICD.

**Comment by temperrr** [comment] 2022-07-19 04:29
The internal cooldown is 3.5sec
from the screenshot that was the talent Static Shock. (which doesnt have ICD and indeed seems like it shouldnt).

Closing this since it appears to be working correctly.

**Closed by temperrr** 2022-07-19 04:29 UTC
Labels: Needs Triage, Needs second opinion
