### ISSUE TITLE
Quest extinguishing the idol

### ISSUE THREAD

**Issue by dole555** [chromiecraft/chromiecraft#1007] opened 2021-06-26 06:55 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

We started the escort quest Extinguishing the idol and left the NPC go at it alone. Somewhere on route we presume he died, but we could still see the shouts he does, up to "We did it!" as completion.
When we arrived at the completion zone, he wasn't there, quest not complete, and there ware mobs spawned on top of eachother 3 fold.
https://classic.wowhead.com/quest=3525/extinguishing-the-idol

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The escort NPC should die while going alone, shouldnt do the shouts, and mobs shouldnt all spawn at the same place.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Razorven Downs
2. Start quest Extinguishing the Idol
3. Observe behaviour.
4.

##### EXTRA NOTES:

Unfortunately i didnt grab a screenshot.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment] 2021-06-26 08:44
I couldn't reproduce it (Tested on AC HASH/COMMIT: 2a2e54d), I protected him until almost the end and then I walked away to let him die, and he just disappeared, nothing else happened:

![WoWScrnShot_062621_113143](https://user-images.githubusercontent.com/82579073/123507687-6a6c5600-d673-11eb-9d3d-832685d5a77a.jpg)
![WoWScrnShot_062621_113209](https://user-images.githubusercontent.com/82579073/123507696-76581800-d673-11eb-82f4-ac4af359c33f.jpg)
![WoWScrnShot_062621_113610](https://user-images.githubusercontent.com/82579073/123507699-807a1680-d673-11eb-8fbd-f73580e39312.jpg)
![WoWScrnShot_062621_113641](https://user-images.githubusercontent.com/82579073/123507705-8bcd4200-d673-11eb-9ecf-a65f9e3d24b9.jpg)
![WoWScrnShot_062621_113803](https://user-images.githubusercontent.com/82579073/123507708-98ea3100-d673-11eb-97e8-af9b82c2b8e4.jpg)

As a final detail, the quest is not marked as failed:

![WoWScrnShot_062621_114025](https://user-images.githubusercontent.com/82579073/123507744-cafb9300-d673-11eb-84ba-60ca2a479483.jpg)

**Comment by temperrr** [comment] 2021-06-29 16:58
Already reported here: https://github.com/chromiecraft/chromiecraft/issues/682

Thanks for your report!

**Closed by temperrr** 2021-06-29 16:58 UTC
Labels: Needs Triage, Waiting for more feedback
