### ISSUE TITLE
Thorium Prospecting not always yielding gems

### ISSUE THREAD

**Issue by NWKDenmark** [chromiecraft/chromiecraft#925] opened 2021-06-20 14:51 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Prospecting Thorium Ore will occasionally not yield any gem and destroy the 5 ores in the process.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Prospecting ore should ALWAYS yield one gem.

##### SOURCE:

https://wowwiki-archive.fandom.com/wiki/Prospecting

"Patch 2.1.0 (22-May-2007): Prospecting now always yields at least 1 gem."

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Acquire stacks of Thorium Ore for adequate statistical population.
2.  Prospect ores.
3.  Keep an eye for empty loot windows.
4.

##### EXTRA NOTES:

I prospected 500 thorium ores and had about 5% chance of finding an empty loot window.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment] 2021-06-20 15:29
duplicate of #600

**Comment by pop-pig** [comment] 2021-06-20 15:34
It's indeed a duplicate of #600 , but after testing it again it seems that it's not fixed yet.
I did a pull not long ago and recorded it happening, here is a video: https://youtu.be/12J_pjW8YNs
You can see that after finding the 2 blue sapphires, I prospect again and there is no loot (see chat window).
AzerothCore rev. 80a76bad7155+ 2021-06-20 12:12:30

**Comment by necropola** [comment] 2021-06-20 18:54
Indeed a Duplicate of #600 which I'm going to reopen.

**Closed** 2021-06-21 06:35 UTC
Labels: Closed, Duplicate
