### ISSUE TITLE
Lock and Load doesn't proc with Black Arrow / Immolation Trap / Explosive Trap

### ISSUE THREAD

**Issue by dumikachromiecraft** [chromiecraft/chromiecraft#3044] opened 2022-02-14 09:36 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

I have spent around 20 minute trying to get a proc of Lock and Load from the spells mentioned in the title, but I had no luck. It has a 6% proc rate according to talents:

![image](https://user-images.githubusercontent.com/36760053/153835663-cd2f7418-7475-411a-9df5-e8dd5f664642.png)

I tested it on the training dummies in Orgrimmar. Proc works perfectly with Freeze and Frost Traps.

### Expected Blizzlike Behaviour

According to the talent description, it should work. 

### Steps to reproduce the problem

1. Roll a survival hunter
2. Talent Lock and Load
3. Try to use Black Arrow/Immolation Trap/Explosive Trap on NPC (I used target dummy)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment] 2022-02-14 09:55
Thank you for the report, @dumikachromiecraft.

I was not able to reproduce the issue on my local AC. Every named spell's periodic damage procced the talent. 

Immolation Trap:
![image](https://user-images.githubusercontent.com/62797536/153840471-04e0d36b-9dbf-417f-b703-dfd7e8c1d148.png)

Explosive Trap:
![image](https://user-images.githubusercontent.com/62797536/153840597-4ca0e01c-b671-49d9-94ea-d6920480c2ec.png)

Black Arrow:
![image](https://user-images.githubusercontent.com/62797536/153841037-86670f98-f0dd-4321-b746-ea5bd631914c.png)

**Comment by dumikachromiecraft** [comment] 2022-02-14 10:17
I am shifting through my log and it never procced. Are you using the latest ranks?

![image](https://user-images.githubusercontent.com/36760053/153845005-b5ebbc2d-88a7-42d1-865b-f8e62ff33093.png)

![image](https://user-images.githubusercontent.com/36760053/153845025-2f881fd0-7476-45b7-abff-b219ae7f9d83.png)

It has 11 ticks and I am trying it on 3 dummies, I tried it about 30-40 times, and I haven't got a single proc.

**Comment by ishidinho** [comment] 2022-02-14 14:14
@dumikachromiecraft 

I tested it again.

* Explosive Trap (Rank 6) - proc on first cast (4 targets)
* Immolation Trap (Rank 8) - proc on third cast (1 target)
* Black Arrow (Rank 6) - proc on first cast

**Comment by dumikachromiecraft** [comment] 2022-02-14 14:29
Some talent maybe blocking it?

**Comment by dumikachromiecraft** [comment] 2022-02-14 21:54
I tested it on PTR too with multiple races. Still no proc. I spammed .cooldown and Explosive trap for 10 minute straight.

**Comment by ishidinho** [comment] 2022-02-20 18:22
@dumikachromiecraft 

> Some talent maybe blocking it?

I just clicked the shortest way to the talent. Pretty much as you did here.

![image](https://user-images.githubusercontent.com/36760053/153845025-2f881fd0-7476-45b7-abff-b219ae7f9d83.png)

Can you try it again with only the shown talents?
Which ranks of the spells did you use?

**Comment by hofik19** [comment] 2022-03-16 13:11
Did tests on my hunter on main realm with this talents. Used Explosive Trap Rank 3 and Immolation Trap Rank 5 on Dummies for ~30 minutes. No Lock'n'Load proc. Freezing Trap proc works fine.

**Comment by hofik19** [comment] 2022-04-07 12:02
I think that this issue should have "confirmed" status. Are more tests needed?

**Comment by TarekMadara** [comment] 2022-04-10 15:04
i Did test it with those talents, and i confirm that it NEVER procs.

**Comment by ishidinho** [comment] 2022-04-11 11:32
Thank you all for your input.
With the latest AC build I was finally able to reproduce the issue.

**Comment by slicplaya** [comment] 2022-04-14 06:37
I might also mention in case it may be of possible help that when casting a frost trap earlier in a dungeon followed by explosive trap, the mobs would "eat" the trap and it wouldn't even proc or explode(just poof). The problem might be tied to traps or how they're created on the server etc.

**Comment by Gultask** [comment] 2022-06-05 13:10
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/11862

**Closed by Gultask** 2022-06-05 13:10 UTC
Labels: Confirmed, Linked [AC], Generic Issues, Class Issue
