### ISSUE TITLE
[Badlands][Quest] Seal of the Earth - Handing over required quest items to object does not spawn Hematus and Blacklash

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#2485] opened 2021-12-05 19:49 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Handing over quest items:
- Opal Runestone (https://wowgaming.altervista.org/aowow/?item=4844)
- Amethyst Runestone (https://wowgaming.altervista.org/aowow/?item=4843)
- Diamond Runestone (https://wowgaming.altervista.org/aowow/?item=4845)

to 'Seal of the Earth' (https://wowgaming.altervista.org/aowow/?quest=779) object does not spawn Hematus (https://wowgaming.altervista.org/aowow/?npc=2759) and Blacklash (https://wowgaming.altervista.org/aowow/?npc=2757) mobs.
Both mobs drop quest items required for the completion of 'Tremors of the Earth' (https://wowgaming.altervista.org/aowow/?quest=717) quest and right now the quest cannot be completed.

### Expected Blizzlike Behaviour

Completing quest 'Seal of the Earth' spawns Hematus and Blacklash mobs, required for completing 'Tremors of the Earth' quest.

### Steps to reproduce the problem

1. Have a character with at least level 40
2. Start and progress quest chain 'Mirages' (https://wowgaming.altervista.org/aowow/?quest=718) until quest 'Tremors of the Earth' (https://wowgaming.altervista.org/aowow/?quest=717) becomes available
3. Start 'Tremors of the Earth' quest
4. Collect gems for the following pillars:
- Opal Runestone at 72 66
- Amethyst Runestone at 81 64
- Diamond Runestone at 83 32
5. Interact with object 'Seal of the Earth' at 81 50
6. Pay attention to the game

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-06 09:19
Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear.
![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

https://user-images.githubusercontent.com/85256266/144735314-afca3d8a-5df7-425a-9936-da3a4e7a0b6b.mp4

**Comment by ishidinho** [comment] 2021-12-07 16:11
@Shineslippers I can confirm that this issue is still there with the latest build.

**Comment by Shineslippers** [comment] 2021-12-07 16:15
@ishidinho that's same issue like with your quest. Scripts doesn't work on `gameobject_questender` scenario. Basically any object with quests doesn't working.

**Comment by Shineslippers** [comment] 2021-12-15 12:47
Should work after with last update.
![Capture](https://user-images.githubusercontent.com/85256266/146189217-fe57fd0e-0732-4b54-be30-acd18babd99d.PNG)

**Closed by Shineslippers** 2021-12-15 12:47 UTC
Labels: Waiting for more feedback, Unable to Reproduce, Bug Under Evaluation
