### ISSUE TITLE
[Tempest Keep] Kael'thas Sunstrider encounter bugs

### ISSUE THREAD

**Issue by SirenxAA** [chromiecraft/chromiecraft#7592] opened 2024-12-04 15:17 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

1. The damage from Grand Astromancer Capernian is doing much higher than it should be if this is the "nerfed" version. She is now doing 7,000 damage fireballs
2. The transition from phase 2 (weapon phase) to phase 3 (four advisor stage) is about 1m30s longer than it should be
3. The health of advisors in phase 3 is doubled from what it should be.

### Expected Blizzlike Behaviour

1. The damage should be significantly lower if this is the nerfed version
2. The transition from phase 2 to phase 3 should be 2 minutes after weapon spawn
3. The health of the four advisors should be the same in phase 1

### Source

1. I do not have actual source as I am not sure how the tuning should be, but 7k fireball is abnormally high for a nerfed version
2. This TBC guide references a 2 minute phase timer between weapon spawn to advisor resurrection https://www.wowhead.com/tbc/guide/kaelthas-sunstrider-the-eye-tempest-keep-strategy-burning-crusade-classic
3. Many video PoV shows advisor health in P1 and P3 is the same: example: https://www.youtube.com/watch?v=3e19JC9nJ9A

### Steps to reproduce the problem

1. Engage Kael'thas sunstrider in Tempest Keep
2. Go through phase 1, 2 and 3
3. Observe damage from Capernian
4. Observe health of four advisors in phase 1 and then compare in phase 3
![image](https://github.com/user-attachments/assets/9d796ac0-ab84-4f5b-a830-433ca820653c)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment] 2024-12-05 09:31
Regarding points 1 and 3, TK is nerfed but not in the way you think. 
Currently TK tuning is nerfed by something like 25%, which means that raid tuning is still present.
The raid tuning will be completely removed when the wotlk content is released.

**Comment by amed80** [comment] 2024-12-05 11:09
1- Capernian fireball even without any tuning deal 5.5-7.4k , so i don't think it's a bug.
[Fireball](https://wowgaming.altervista.org/aowow/?spell=36971)
![image](https://github.com/user-attachments/assets/0f0b2fca-88f3-431f-ad3e-bb55209ff8de)


2- it has been mentioned before in the comment linked below and was fixed but i guess wrongfully was changed again to 192s in a recent refactor?
https://github.com/chromiecraft/chromiecraft/issues/6886#issuecomment-2024526461

3- following some of the videos in the same comment from videos from wotlk pre patch, advisors should have the same health in phase 3 as phase 1

**Comment by Nyeriah** [comment] 2024-12-05 11:48
> 1- Capernian fireball even without any tuning deal 5.5-7.4k , so i don't think it's a bug. [Fireball](https://wowgaming.altervista.org/aowow/?spell=36971) ![image](https://private-user-images.githubusercontent.com/8395873/392784703-0f0b2fca-88f3-431f-ad3e-bb55209ff8de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTk1MjMsIm5iZiI6MTczMzM5OTIyMywicGF0aCI6Ii84Mzk1ODczLzM5Mjc4NDcwMy0wZjBiMmZjYS04OGYzLTQzMWYtYWQzZS1iYjU1MjA5ZmY4ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMTE0NzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBjZGQ2MTY0N2I5NTI4MjAyZDlkOTM5MWE4M2NmMDZiOTY2YTI4MmFhNmIyOGNiMWE4MDcxYzBmMTBkODhhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MYovKq_SxFSToMIZQE18rmWP5z1PyqkZ8Hu94_C9hCE)
> 
> 2- it has been mentioned before in the comment linked below and was fixed but i guess wrongfully was changed again to 192s in a recent refactor? [#6886 (comment)](https://github.com/chromiecraft/chromiecraft/issues/6886#issuecomment-2024526461)
> 
> 3- following some of the videos in the same comment from videos from wotlk pre patch, advisors should have the same health in phase 3 as phase 1

The resurrection spell Kael uses has as one of the effects +100% health

**Comment by amed80** [comment] 2024-12-05 12:22
> The resurrection spell Kael uses has as one of the effects +100% health

looking at older videos , this is indeed the case with retail as the advisors do resurrect with double health.

https://youtu.be/atATvXfxwPU?t=123 video from retail cataclysm shows the advisors having double health in phase 3

The spell looks like has been changed with classic which mean this is not a bug following 3.3.5a

**Comment by SirenxAA** [comment] 2024-12-05 12:31
Thanks for the comment, I have the wrong memories when compared to previous settings were values are lower than it is recently. It these changes are as intended I shall close the ticket.

Thank you everyone for clarifying these findings =)

**Comment by amed80** [comment] 2024-12-05 12:34
the 2nd point is still a bug as it shouldn't take 192s between phase 2 and phase 3

**Comment by TheSCREWEDSoftware** [comment] 2024-12-07 13:18
> the 2nd point is still a bug as it shouldn't take 192s between phase 2 and phase 3

What time it should be? 120 seconds?

**Comment by amed80** [comment] 2024-12-07 13:33
should be 95s

**Comment by TheSCREWEDSoftware** [comment] 2024-12-09 15:27
Linked to AC: https://github.com/azerothcore/azerothcore-wotlk/issues/20877

**Comment by sogladev** [comment] 2024-12-14 00:03
checked with https://github.com/azerothcore/mod-zone-difficulty

1. Fireball damage:
zone-wide 1.3 spell damage scaling is applied https://github.com/azerothcore/mod-zone-difficulty/blob/9bdc5bd2ac3018885025233f3d4d0fcf98c53f71/data/sql/db-world/zone_difficulty_info_content.sql#L20 with no override so fireball is doing 1.3 times the damage

![astromancer_zone-difficulty](https://github.com/user-attachments/assets/14887cf3-4ccb-4ba9-b0f0-1358516729f1)


`zone_difficulty_spelloverrides`
2. pr open https://github.com/azerothcore/azerothcore-wotlk/pull/20914
3. hp scaling is set to 1.0, hp values are the same as stock AC and are correct

**Comment by sogladev** [comment] 2024-12-27 10:34
> The damage should be significantly lower if this is the nerfed version

fixed with https://github.com/azerothcore/mod-zone-difficulty/commit/8848e7d07d64004a55cb83f60d8f7e25e02c1435

**Closed by sogladev** 2024-12-27 10:34 UTC
Labels: Confirmed, Linked [AC]
