### ISSUE TITLE
Stacking Silver & TIn Node (Silverpine Forest)

### ISSUE THREAD

**Issue by Ragundah** [chromiecraft/chromiecraft#585] opened 2021-05-09 06:27 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Silver and Tin vein spawn on-top of each other.

![image](https://user-images.githubusercontent.com/83891181/117562525-6f8a2d00-b054-11eb-9c0f-3130010b2f8b.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes should not be spawned on the same place.

##### STEPS TO REPRODUCE THE PROBLEM:

Locate the stacked nodes using gobject near info.
Wait for nodes to spawn stacked.
???
Profit.

Tin Vein 35547 (Entry: 1732) - X:-446.868011 Y:957.278015 Z:100.316002 MapID:0
Tin Vein 42971 (Entry: 1733) - X:-446.868011 Y:957.278015 Z:100.316002 MapID:0

##### EXTRA NOTES:

No additional information.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-05-09 14:22
Thanks for the report. However, this is a duplicate of https://github.com/chromiecraft/chromiecraft/issues/474.

**Closed by Azcobu** 2021-05-09 14:22 UTC
Labels: Needs Triage
