### ISSUE TITLE
Paladin: Unable to cast Redemption on opposing faction players in Dungeon Finder party

### ISSUE THREAD

**Issue by TaraKaos** [chromiecraft/chromiecraft#2094] opened 2021-10-14 15:07 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I was running Dire Maul: West and my party pulled Tendris Warpwood aggroing all of the tree adds. I knew it would be a wipe so I stayed out of combat so I could rez them. After combat I was able to cast Redemption on the Alliance players in my party, but not the Horde players. 

### Expected Blizzlike Behaviour

Technically this wouldn't be blizzlike behavior since you can never group with the opposing faction on blizzard servers.

### Steps to reproduce the problem

1. Get into a dungeon finder group with players from the opposing faction.
2. Let one of those players die.
3. Attempt to cast Redemption on them/

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Windows 10 Pro 64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment] 2021-10-14 18:17
Hm, did they release?
This seems to be a duplicate of #1206

**Comment by gurveleg** [comment] 2021-10-14 18:25
Yes, then this is a duplicate report then. Thank you anyway.

**Closed by gurveleg** 2021-10-14 18:25 UTC
Labels: Waiting for more feedback
