### ISSUE TITLE
Spawn at incorrect graveyard when dying in Frostmane Hold, Dun Morogh

### ISSUE THREAD

**Issue by dole555** [chromiecraft/chromiecraft#370] opened 2021-04-07 17:33 UTC
- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When you die in Frostmane Hold, you get ported to the graveyard in Coldridge Valley.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you die in Frostmane Hold, you should be ported to the graveyard south of the Iceflow Lake.
Here is a wowhead comment from 3.0.9 that sais this:
https://www.wowhead.com/quest=287/frostmane-hold#comments:id=215696:reply=84315

##### STEPS TO REPRODUCE THE PROBLEM:

1. Die in Frostmane Hold, in DUn Morogh.
2. 
3. 
4.

##### EXTRA NOTES:

According to the wowhead comments, you should definetly not be ported to that graveyard.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment] 2021-04-08 21:27
confirmed

**Comment by elithaun** [comment] 2021-11-16 22:55
Confirmed.  I spawned at the steel grill's Depo, instead of the Chill breeze Valley ( I had to  corpse walk past the closer graveyard)

**Comment by fendwe** [comment] 2022-03-24 00:50
This is still the case for Alliance characters.
![image](https://user-images.githubusercontent.com/61170874/159819531-a81ed8e3-0f9b-467f-886b-be9bce452829.png)

Horde gets sent to the correct graveyard.
![image](https://user-images.githubusercontent.com/61170874/159819963-4c41d62d-f8f4-4388-8b35-b0ac8c7c0fc1.png)

See also https://github.com/azerothcore/azerothcore-wotlk/pull/8022

**Comment by DavuKnight** [comment] 2022-08-30 23:51
Alliance now goes to the graveyard outside Kharanos. Looks like this is fixed. the AZCore PR appears to have been merged per the AZCore Ticket

**Closed** 2022-08-31 17:38 UTC
Labels: Confirmed, Linked [AC], [1 - 19]
