### ISSUE TITLE
Wrong Price on several crafted Jeweller items (1c only instead of real sale price)

### ISSUE THREAD

**Issue by Rittmeister39** [chromiecraft/chromiecraft#737] opened 2021-05-30 14:08 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

some Jeweller created Items display a sale price of 1c only instead of the real sale price. Fortunately when sold they seem to award the correct price, at least more than 1c. see screenshots.
I noticed this on 2 items, but probably more affected:
Pendant of the Agate Shield
Heavy Golden Necklace of Battle
probably more in that range.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

correct price displazed

##### STEPS TO REPRODUCE THE PROBLEM:

1. jewelcrafting the items and then mouse over.
![WoWScrnShot_053021_160239](https://user-images.githubusercontent.com/78271326/120107415-3af42780-c161-11eb-9eb8-2c10c2f49d15.jpg)
![WoWScrnShot_053021_160312](https://user-images.githubusercontent.com/78271326/120107429-46475300-c161-11eb-8840-747f0ed54551.jpg)
![WoWScrnShot_053021_160305](https://user-images.githubusercontent.com/78271326/120107430-46dfe980-c161-11eb-9a1b-a268a2c038d9.jpg)

2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-05-30 14:15
Thanks for the report. However, this is a duplicate of a known client-side issue - see https://github.com/chromiecraft/chromiecraft/issues/464 and https://github.com/azerothcore/azerothcore-wotlk/issues/4902. As it isn't a server issue, there's nothing we can do to fix it.

**Closed by Azcobu** 2021-05-30 14:15 UTC
Labels: Needs Triage
