### ISSUE TITLE
Omen of Clarity not proccing

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#2265] opened 2021-11-05 13:58 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Omen of clarity (unless i just have bad rng) does not proc of
barskin
mark/gift of the wild
nature's grasp
feral faerie fire

### Expected Blizzlike Behaviour

it should proc off all these abilities 
https://www.youtube.com/watch?v=WuWOFtk6JS4&t=135s&ab_channel=ZybakTV
(at 2:02 barkskins the rogues opener and omen of clarity procs)
https://www.youtube.com/watch?v=4gyy3GSokm0&t=10s&ab_channel=Xk 
(gift of the wild pre pull to proc omen of clarity) 
https://www.youtube.com/watch?v=KFMPEECCAP0&ab_channel=KnifeOfLinoleum
another video of pre casting gift of the wild to save a proc for the fight

### Steps to reproduce the problem

use feral faerie fire on a target dummy with omen of clarity and it doesnt proc in my testing
activate barkskin and no proc
activate natures grasp and no proc
cast mark/gift of the wild and no proc

### Extra Notes

This could just be all bad rng but i dont think 5 minutes of testing on a target dummy without a single omen proc is just bad rng.  The proc rate should be roughly 6% 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-05 15:38
Thank you for report. I can confirm the issue, but i cant say should Barskin or FeralFF give clear casting. There is need some more research.

**Comment by Never6** [comment] 2021-11-05 15:52
with world of logs being down this pains me but someone on another server reported an issue similar to this 
[18:05:42.211] Oranoss's Faerie Fire (Feral) fades from Volatile Ooze
[18:05:44.934] Professor Putricide's Faerie Fire (Feral) is refreshed by Oranoss
[18:05:45.067] Oranoss gains Clearcasting from Oranoss
[18:05:47.980] Oranoss casts Faerie Fire (Feral) on Volatile Ooze
[18:05:48.263] Volatile Ooze afflicted by Faerie Fire (Feral) from Oranoss
this is from the log they posted i would post the real log if i could
barskin and feralFF should give clear casting on this server as they did in retail

**Comment by Never6** [comment] 2021-11-05 15:56
also the video i posted of barkskin proccing clearcasting is from retail wrath

**Comment by VFaleiro** [comment] 2021-11-05 16:16
@Shineslippers I believe anything can/should proc it, literally. From laying campfires to using profession skills. Yes, it is totally ridiculous.

You can see a lot of that on Wowhead:

[224747 on 2008/10/17 (Patch 3.0.2)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409904)
> This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.<

[lordkarthas on 2008/10/22 (Patch 3.0.2)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409904:reply=356110)
> It procs off crafting bandages as well.

[52390 on 2009/04/17 (Patch 3.1.0)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=680908)
> Even pressing the "Learn" button on my talents proc'd Omen of Clarity!

[370776 on 2009/06/23 (Patch 3.1.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=756418)
> Other people have mentioned this can proc when doing professions.
> 
> Omen of Clarity can also proc when switching talent sets.

[613298 on 2010/06/07 (Patch 3.3.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=1054317)
> Since the buff procs off of each application of a spell, its an almost guarantee that casting Typhoon or Gift of the Wild while in a raid will proc it. Idk about mana efficiency, but boom there goes ur Tier ten 2-piece bonus :3

[kojiroh on 2008/10/17 (Patch 3.0.2)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409095)
> I think I might have found a bug, or a glitch with this. This spell procs for EVERY spell, including crafting spells, such as Heavy Clefthoof Boots (Spell).
> I've found that out when I crafted these. I wasn't looking at the screen at the time, and when I heard the sound of the clearcasting state activating, I've turned my eyes at the screen and seen the "<Clearcasting>" text scrolling up.
> I still wonder if it's a known-case or a bug or something.

[289894 on 2009/01/01 (Patch 3.0.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=540774)
> Hurricane has a change to proc on each tick, which make hurricane spam close to mana free in pve!

[296637 on 2009/01/17 (Patch 3.0.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=566125)
> Just had it proc today while cooking :p

And [Wowwiki (archived oct/2010)](https://web.archive.org/web/20101015012504/http://www.wowwiki.com/Omen_of_Clarity)
> Omen of Clarity is a talent in the third tier of the Druid Restoration tree. It causes all of your spells and auto-attacks to give a chance to grant you a Clearcasting buff, which reduces the mana, rage, or energy cost of your next damage or healing spell or offensive ability to zero. Despite what the tooltip says, virtually any spell cast can trigger the Clearcasting, including ones with no mana cost, though not all spells will benefit from it.

> Some abilities may cause Clearcasting to trigger, but will not benefit from it or consume the buff when cast. This includes spells such as Mark of the Wild and Nature's Grasp. Thorns is considered a damage spell for this purpose, and as such will benefit from (and consume) the Clearcasting state when cast.

> Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.

@Never6 have you checked [Archive Wayback Machine](https://web.archive.org/) for World of Logs? Maybe someone saved something?

**Comment by Never6** [comment] 2021-11-05 16:20
@VFaleiro I have checked and the post i want is not archived sadly.

**Comment by Shineslippers** [comment] 2021-11-05 16:26
@VFaleiro, yes i saw this comments. It's going too far and looks like a joke. I'm oposite of it. Boys you talking to me like i closed this report. Everything what we need time and some more info. I added more lables and anyone from triage team can come and report it to AC.

**Comment by VFaleiro** [comment] 2021-11-05 16:57
@Shineslippers Oops, if I sounded rude, it was not my intention.

**Comment by Orixim** [comment] 2021-11-05 18:59
I have not played WotLK retail version, so I cannot say how it was. I can only say how it is here and how I interpret the skill.

Those comments clearly look like jokes to me ("_This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.<_", why would it not take the reagents? Looks like a simple joke).

I know the tooltips are many times misleading, but this one says:

> Each of the Druid's damage, healing spells and auto attacks has a chance of causing the caster to enter a Clearcasting state. The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage, healing spell or offensive ability by 100%.

I had it triggered while auto attack and while casting damaging/healing spells. So what the tooltip says do work as a trigger. Now, other skills like shapeshifting, Barkskin, Faerie Fire, Entangling Roots and so on, I have never seen it trigger. However, those are not damaging spells in my opinion (the Entangling Roots deal damage but it is not a damaging spell, otherwise its own damage would break it).

Also, I have noticed that my Starfire, Wrath, Moonfire, Hurricane, Entangling Roots, Thorns, Rejuvenation, Regrowth, Swiftmend, Tranquility, Maul, Swipe, Bash consume the Clearcasting, but Faerie Fire, Abolish Poison, Mark of the Wild, Cower, Shapeshifting, Faerie Fire (Feral), Shadowmeld, Stealth, Dash, Growl, Challenging Roar, Innervate do not. If it is relevant, I can test other skills, just say it.

All that being said, I can't say how it was in retail, but from what the tooltip says, it makes sense to work the way it is currently.

**Comment by VFaleiro** [comment] 2021-11-05 19:59
> Those comments clearly look like jokes to me ("_This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.<_", why would it not take the reagents? Looks like a simple joke).
Well, that's just common on Wowhead since it is the resource most people new to the game have. It's how people playing retail find out/used to find out what was working as it should, and what wasn't because a blueposter said it would get fixed soon, since it's way easier to navigate Wowhead than Battle.net forums.

**Comment by VFaleiro** [comment] 2021-11-05 20:01
> Those comments clearly look like jokes to me ("_This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.<_", why would it not take the reagents? Looks like a simple joke).

Well, that's just common on Wowhead since it is the resource most people new to the game have. It's how people playing retail find out/used to find out what was working as it should, and what wasn't (because a comment would describe a blueposter saying it would get fixed soon), since it's way easier to navigate Wowhead than Battle.net forums.

It may sound like a joke to you, but believe me, these kinds of things are legit questions for newbies.

**Comment by VFaleiro** [comment] 2021-11-09 17:03
One more:

According to [Wowwiki: Feral DPS Guide (archived in Oct/2010)](https://web.archive.org/web/20101010040647/http://www.wowwiki.com/Feral_DPS_guide), Nature's Grasp can proc Clearcasting.
> 6. If you have less than 35 Energy, use [Tiger's Fury] (or [Nature's Grasp] - which can proc [Omen of Clarity]).

**Comment by Shineslippers** [comment] 2021-11-09 17:16
@VFaleiro  Thank you. I will finish BRS issues and then will pick up those one if noone will do it before me.

**Comment by xebr0s** [comment] 2021-11-09 22:43
Can confirm, from all the dungeon runs It didn't proc once while using Hurricane.

**Closed** 2021-11-30 15:48 UTC
Labels: Confirmed, Linked [AC], Generic Issues

**Comment by Hogofogo1** [comment] 2022-05-24 06:46
From wotlkdb and other wotlk databases there is a "Modifies" column for Clearcasting.
Seems like all the abilities that are described in Omen of clarity tooltip are there.
