### ISSUE TITLE
Innkeeper Coryth Stoktron is facing the wrong way

### ISSUE THREAD

**Issue by nicedraeger** [chromiecraft/chromiecraft#5579] opened 2023-05-10 02:08 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Innkeeper Coryth Stoktron at Cenarion Refuge in Zangarmarsh should be facing toward Naka. Both characters perform the /say emote over and over, as if having a conversation. There's no dialogue, but it's a teency bit immersion-breaking.

### Expected Blizzlike Behaviour

Coryth should be facing Naka, not giving her the cold shoulder (while still carrying on the conversation...lol)

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/107259343/8e7d7b09-f5df-45f3-8957-46b9a0369677)

### Steps to reproduce the problem

1. enter cenarion refuge inn
2. Naka has the correct facing, Coryth is facing away

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-05-10 02:38
Duplicate of #4620.

Also, not how the source field is meant to be filled. A screenshot/video/comment referring to Blizzard servers should go there, not a CC screenshot.

**Closed by heyitsbench** 2023-05-10 02:38 UTC
Labels: Needs Triage
