### ISSUE TITLE
[Quest] Call of Water - Minor Manifestation of Water doesn't spawn

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#2474] opened 2021-12-04 19:51 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

https://classic.wowhead.com/quest=100/call-of-water

After destroying the Corrupted Manifestation of Water, looting its bracers, and turning the quest in at the Brazier, the Brazier offers this quest, but the Minor Manifestation of Water that is supposed to spawn does not spawn, even with Sapta Sight active.

I arrived some time after another shaman who was stuck on the same part. This should have given him a second chance to see the NPC spawn and interact with it, but it never showed up, leaving us both stuck. 

![WoWScrnShot_120421_143855](https://user-images.githubusercontent.com/20717737/144722753-d60cbb1c-6dc8-4cec-8d62-fa8cc398895d.jpg)

Here we both are, Sapta Sight active, with nothing to see.

### Expected Blizzlike Behaviour

The Minor Manifestation of Water should spawn and accept the quest turn-in.

### Source

https://classic.wowhead.com/quest=100/call-of-water

Comments here describe the above behavior.

### Steps to reproduce the problem

1. Complete the previous quest.
2. Accept the new quest from the brazier.
3. Nothing appears.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by CameronWoof** [comment] 2021-12-04 20:06
It is currently possible to work around this bug by bringing a new sapta to the troll a short distance away, which will force the event to trigger and spawn the minor manifestation of water. The event should be triggered by doing the quests normally, however, and should not require a second trip to the barrens and back to force.

**Comment by Shineslippers** [comment] 2021-12-05 05:47
Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear.
![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

https://user-images.githubusercontent.com/85256266/144735314-afca3d8a-5df7-425a-9936-da3a4e7a0b6b.mp4

**Comment by Shineslippers** [comment] 2021-12-15 12:48
Should work after with last update.
![Capture](https://user-images.githubusercontent.com/85256266/146189217-fe57fd0e-0732-4b54-be30-acd18babd99d.PNG)

**Closed by Shineslippers** 2021-12-15 12:48 UTC
Labels: Waiting for more feedback, Unable to Reproduce, Bug Under Evaluation
