### ISSUE TITLE
A Thoroughly Read Copy of "Nat Pagle's Extreme' Anglin." shouldn't drop

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#2708] opened 2021-12-31 10:33 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

A Thoroughly Read Copy of "Nat Pagle's Extreme' Anglin." drops from 14 mobs
![image](https://user-images.githubusercontent.com/84640316/147818505-400979bb-4ebe-4553-b0aa-82620664714f.png)

### Expected Blizzlike Behaviour

A Thoroughly Read Copy of "Nat Pagle's Extreme' Anglin." shouldn't drop

### Source

https://tbc.wowhead.com/item=18365/a-thoroughly-read-copy-of-nat-pagles-extreme-anglin#contained-in-object

### Steps to reproduce the problem

keira3 or mysql

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance 
from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.entry 
where creature_loot_template.item="18365";  

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-31 15:15
Thank you for report, but this one is duplicate of https://github.com/chromiecraft/chromiecraft/issues/2707. As i see 4 thoose items shouldn't drop from NPCs.

**Closed by Shineslippers** 2021-12-31 15:15 UTC
Labels: Needs Triage
