### ISSUE TITLE
Nagrand VMaps

### ISSUE THREAD

**Issue by HasieEST** [chromiecraft/chromiecraft#4761] opened 2023-01-05 21:00 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Upon being feared, there is a chance to clip through the ground and into the void. Same problem may arise while charging or getting Psychic Horrored

### Expected Blizzlike Behaviour

Get cc that renders your character unresponsive but still able to move  and stay above the ground, not falling into your death.

### Source

*Would add something, but generally cant say anything beyond idea that same problems were generally fixed in Blizzard client, when found*

### Steps to reproduce the problem

Best spots - around Halaa Wyvern camps near bridges (eastern one for example)
Get Feared, charge or Psychic Horrored
Observe
Repeat within reasonable timeframe to confirm the bug.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment] 2023-01-10 11:02
To anyone helping triage these, use a macro to help you find consistent spots for this:

.gps
.aura 5782

This way you'll get feared and your exact position will be logged in the chat

**Comment by Salehyn** [comment] 2023-09-18 07:02
Same issue as https://github.com/chromiecraft/chromiecraft/issues/774 
Happens all over the world not only in Nagrand

There is an issue closed on AC for the fear causing the problem as well https://github.com/azerothcore/azerothcore-wotlk/issues/12079 but it seems to be only for battlegrounds.

Do we triage all locations separately @Gultask ?

**Comment by FrancescoBorzi** [comment] 2024-11-10 22:59
> Do we triage all locations separately?

we definitely don't, closing this one. The issue is pretty generic and does not depend on a specific area. Also the report on AC has been closed.

**Closed by FrancescoBorzi** 2024-11-10 22:59 UTC
Labels: Known issue
