### ISSUE TITLE
[Incorrect Drop] Kurzen Commando

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#888] opened 2021-06-18 10:39 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Kurzen Commando drops Frostreaver Crown.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Kurzen Commando shouldn't drop Frostreaver Crown according to the wowhead tbc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to STV
2. Kill Kurzen Commando on repeat
3. Wait for it to drop Frostreaver Crown

##### EXTRA NOTES:

Kurzen Commando: https://tbc.wowhead.com/npc=938/kurzen-commando#drops
Frostreaver Crown: https://tbc.wowhead.com/item=13127/frostreaver-crown#dropped-by;0+3-10-9+1

![WoWScrnShot_061321_143409](https://user-images.githubusercontent.com/84775498/122548908-37eaa980-d032-11eb-8ba7-94b377f4a02c.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-06-18 15:13
Thanks for the report. However, after some thought, I'm going to close this as 'Will Not be Fixed.'

This isn't because you are wrong. Your report is correct, and the item in question should not be in the NPC's loot tables. 

The problem is that fixing it would require a massive overhaul of how the loot DB works. To summarise, a lot of loot for mobs of the same level is contained in what are called reference loot tables (RLTs). These are sort of common pools of loot that are shared across a lot of mobs of around the same level. I don't know where they came from or who put them together, but they are the basis for much of the way loot works on AC/CC.

What's causing this specific problem is that the Kurzen Commandos have RLT 24051 as part of their loot table. This is a small table of 10 items, mostly blues, that they can drop. Half the items on RLT 24051 are valid drops for the Kurzen Commando - Holy Shroud, Girdle of Golem Strength, Harpyclaw Bow, etc. Half are not - Combat Claymore, River Pride Choker, and of course, the Frostreaver Crown.

So you'd think the obvious solution would be just to delete the wrong items from the RLT. The problem is that this RLT is shared across 248 creatures in the DB - and those items are correct for many of those other NPCs. So if we 'fix' the Kurzen Commando's drops by editing RLT 24051, we will break who knows how many of those 247 other creatures, and remove drops that they should have. If we tried splitting RLTs, we're now dealing with tens or hundreds of combinations of loot tables, all of which need to relinked to those 248 creatures.

So that's why this probably won't get fixed without a major overhaul to the loot system. You weren't wrong to report this, but the current limitations of the loot system mean that realistically the issue won't be addressed.

**Closed by Azcobu** 2021-06-18 15:13 UTC
Labels: Needs Triage

**Comment by mserajnik** [comment] 2021-06-19 02:43
@Azcobu 

Sorry if there is an obvious answer to this question, but I'm fairly new to AC (and WoW server emulation in general) and was wondering:

From how you explain it, I can see that it would be an infeasible amount of work to break up the RLT for all creatures that share it at once.

But is there any particular reason why it couldn't be done step-by-step as issues like these are discovered?

E.g., in this particular instance, we now know that Kurzen Commando shouldn't drop Frostreaver Crown.

Couldn't we just copy RLT 24051, remove Frostweaver Crown from the copy and then assign Kurzen Commando to that RLT instead of 24051?

If we then discover that there's another mob that should have the same drops as Kurzen Commando, we can assign it to that RLT too.

Over time, there will be more and more smaller RLTs, resulting in an increasingly cleaner loot situation.

Is there perhaps a technical reason why this isn't feasible? Because, in a per instance basis, it doesn't sound like too much work required to set up that copied RLT minus some items and then re-assign the mob in question.

And, if you can answer that, what would the overhaul you mention entail that would make it simpler to fix this big data issue than what I just proposed?

**Comment by Azcobu** [comment] 2021-06-19 19:01
@mserajnik - it's a perfectly reasonable question, and why I had a hard time deciding what to do with this. 

The concern I have with creating lots of smaller RLTs, besides dev workload, mostly comes down to DB design intent and performance. A design consideration for using RLTs was to save DB space. There are just under 30,000 creatures in the DB, but only 885 RLTs, because they are used rather sparingly to aggregate items. (So if we have 20 creatures, each with 400 items in their drop tables, that's 8000 entries. But if half those entries are common, we split those off into an RLT and save 3800 entries by just including a reference to the RLT in their drop tables instead.) But if we start creating RLTs for every individual creature with an incorrect table, the number of RLTs will increase dramatically, and we lose the space/performance savings RLTs give us. The tradeoff of course, is that we gain greater loot accuracy.

For example, Wowhead shows the Frostreaver Crown dropping from 66 mobs. On AC it's 248. So there's a minimum of 182 NPCs that will need new RLTs made, and likely all 248. Let's be optimistic and say there's only 20 combinations of blue/rare loot items for this level range, although the actual number would probably be a lot higher. So we make 20 new 5-item RLTs where there was 1 10-item RLT before. The new RLTs are now taking up 10 times more space than before.

This is to fix a small 10-item RLT. But now look at one of the other issues, https://github.com/chromiecraft/chromiecraft/issues/891. With this one you have an incorrect green item in RLT 24039, with 93 items in it, shared by 511 creatures. I'd expect we would need as many new corrected RLTs as we have creatures, and the benefits from using RLTs disappear. 

As for the overhaul, as I understand it there's two approaches being explored for improving the DB. One is through 'sniffing' (capturing data packets as they move from your Wow client to the retail servers.) If enough people do this long enough as they quest and gather loot, you get a pretty accurate picture of Wow's DB. This results in data that's as reliable as Wowhead's, as they did roughly the same thing, only using client-submitted data their mod gathered. But the sniffed data is also easily accessible to us, whereas Wowhead's data needs to be scraped from their site.

The other approach is looking into using or adapting other open source Wow project DBs. This is hardly a unique problem, many other projects have suffered from it, and apparently older or larger projects may have developed better solutions. But I'm not the one to ask on the specifics there as I don't know much about it. But either approach makes piecemeal fixing of individual issues somewhat pointless when one large re-organization of the data would fix most of this in one go. 

However, I was asking our DB authority about the overhaul, and was told that nobody is actually working on it right now. That means my objection on the grounds that small incremental changes would be made obsolete by a large overall fix doesn't apply. So at @necropola's suggestion, I'll create a[ meta-issue on CC](https://github.com/chromiecraft/chromiecraft/issues/907) and [AC ](https://github.com/azerothcore/azerothcore-wotlk/issues/6438)to deal with items being in RLTs that they shouldn't be. That preserves the information if someone wants to have a go at fixing them.
