### ISSUE TITLE
The quest Hidden Enemies points to wrong location in quest log

### ISSUE THREAD

**Issue by Eistorm** [chromiecraft/chromiecraft#120] opened 2021-03-02 20:42 UTC
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Hidden Enemies](https://wotlk.evowow.com/?quest=5726)
 NPC_Start: [Thrall](https://wotlk.evowow.com/?npc=4949)

 NPC: [Burning Blade Apprentice](https://wotlk.evowow.com/?npc=3198)
 NPC: [Burning Blade Fanatic](https://wotlk.evowow.com/?npc=3197)

 Item: [Lieutenant's Insignia](https://wotlk.evowow.com/?item=14544) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Thrall sends you on a quest, Hidden Enemies, to Skull Rock, to the East of Org., for an item that drops off of Burning Blade Apprentices and Fanatics.

##### CURRENT BEHAVIOUR:

I think every 3.3.5 server I've ever seen has marked the quest location on your map to the Southwest of Org.
Yes, technically there are a couple of mobs there that Could drop the quest item. But nowhere near the number of mobs at the place the quest text actually directs you. 

##### STEPS TO REPRODUCE THE PROBLEM:

To reproduce this issue, just check your map after picking up the quest Hidden Enemies.

Of course this isn't even a bug, it's just an improperly placed quest marker. Certainly a minor issue.

On the screenshot I've circled the quest, the quest marker on the map, the quest text that says to go to Skull Rock, and the location of Skull Rock on the map.
![hidden](https://user-images.githubusercontent.com/79746568/109711891-fe665f00-7b64-11eb-8bab-c6f7d46f7b16.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment] 2021-03-02 23:33
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/54
The NPCs are also located where there is the point 1, not only near the entrance of Orgrimmar, I don't think that this is a proper issue

**Closed by Helias** 2021-03-02 23:33 UTC
Labels: Needs Triage

**Comment by illfated** [comment] 2021-03-03 20:52
Fair point. Maybe there was a time when the NPCs dropping the Lieutenant's insignia could only be found in Skull Rock, but most of the time during TBC & WotLK it could drop from humanoid NPCs in Dustwind Cave (entrance facing Razor Hill, (also a site for warlock quest?)), from Burning Blade NPCs near Fizzle Darkstorm in Thunder Ridge, and from the named Skull Rock inhabitants.
