### ISSUE TITLE
[Magtheridon] Middle cube doesn't work

### ISSUE THREAD

**Issue by Plasmashield** [chromiecraft/chromiecraft#6299] opened 2023-11-02 21:11 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

After some last update, middle cube no longer works

### Expected Blizzlike Behaviour

Should work the same as the other 4 cubes

### Source

123

### Steps to reproduce the problem

1. Wait until the cast
2. Try to use all 5 cubes

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-11-02 22:44
When was the last time you remember the cube working?

**Comment by Plasmashield** [comment] 2023-11-03 00:31
> When was the last time you remember the cube working?

Last Friday

**Comment by heyitsbench** [comment] 2023-11-03 02:35
> Last Friday 

There have been no changes to the cube between then and now.

**Comment by avarishd** [comment] 2023-11-03 07:18
none of the cubes work on my local

**Comment by shaszun** [comment] 2023-11-03 08:20
Wednesday evening the cubes were working.

**Comment by Nyeriah** [comment] 2023-11-03 11:28
The grid searchers probably got messed up

**Comment by heyitsbench** [comment] 2023-11-03 13:11
Color me a liar.

**Comment by AGandrup** [comment] 2023-11-03 15:37
Need more info. What about it does not work?
I just tested it, and I can click all of the cubes just fine and all of them triggers the channeling effect as intended.

**Comment by snoozecc** [comment] 2023-11-03 15:45
happened to us in a Limbo raid last night. trying to see if anyone has any footage that I can upload to show yall. We started on Mythic mode. With 2 clickers assigned to each cube every other cube except the cube closest to entrance of Mag's room was working. We tried a second time on mythic still didnt work. Dropped it to normal mode also didnt work so we just had to out heal the blast nova damage.

**Comment by Nyeriah** [comment] 2023-11-03 16:15
I tried it on my local and one of the cubes also didn't work either

**Comment by AGandrup** [comment] 2023-11-03 16:19
You can't click it or what?

**Comment by AGandrup** [comment] 2023-11-03 16:41
https://www.youtube.com/watch?v=_SW_Djbbz8Y
Quick test on a single character, but here you can see that all cubes seems to work as intended. (Video still being processed so quality might be bad).

**Comment by avarishd** [comment] 2023-11-03 17:03
clicking works, anything after that doesn't (no beam/channel to the boss) and no auras on the boss (need x5 to trigger the stopcast event)

**Comment by heyitsbench** [comment] 2024-07-04 13:16
I highly doubt it.

**Closed** 2024-07-04 13:32 UTC
Labels: Confirmed, Linked [AC]
