### ISSUE TITLE
Learning a profession causes duplicates of skills to appear

### ISSUE THREAD

**Issue by MeltdownKitten** [chromiecraft/chromiecraft#1507] opened 2021-08-22 06:36 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I was somehow able to learn duplicates of every starting skill of a profession. Examples included in screenshots. To trigger the bug all I did was simply learn a profession from a trainer, as per usual.

![WoWScrnShot_082221_082552](https://user-images.githubusercontent.com/89332860/130344897-c0299348-8670-48a5-ac3c-dd778744020a.jpg)
![WoWScrnShot_082221_082545](https://user-images.githubusercontent.com/89332860/130344900-bbbba667-7ba3-4ec5-9852-258cee947b29.jpg)

### Expected Blizzlike Behaviour

I would expect to learn only a single copy of the skill.

### Source

Unfortunately I do not understand the question so you can close it, whatever.

### Steps to reproduce the problem

Learn a profession

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Windows 10 LTSC 

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None
.

### Server

ChromieCraft

**Comment by syssneck** [comment] 2021-08-22 06:55
[See AC issue #7415](https://github.com/azerothcore/azerothcore-wotlk/issues/7415)

**Comment by cachocarne** [comment] 2021-08-23 04:15
Woah, that's weird. Could this be something just from the client? I have alchemy and cooking and did not get such bug.

**Comment by Snufflenose** [comment] 2021-09-29 20:42
I can confirm this bug.

I learned mining today and not only did I learn a duplicate of "Smelting Copper", but also a duplicate **ability** of "Find Minerals" and "Smelting".

After deleting the WDB folder the duplicates disappeared, but this shouldn't happen in the first place.

![Bildschirmfoto 2021-09-29 um 21 56 50](https://user-images.githubusercontent.com/91610030/135345274-4e37f95c-4638-4219-8c09-339e31d92a54.png)

**Closed** 2021-09-30 23:16 UTC
Labels: Confirmed, Linked [AC], Generic Issues, Known issue
