### ISSUE TITLE
[Item] Hammer of the Vesper is part of loot table outside boss loot tables from Scholomance instance

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#4602] opened 2022-12-18 19:04 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

Hammer of the Vesper (https://wowgaming.altervista.org/aowow/?item=18683), which should drop only from the selected bosses in Schlomance dungeon (https://wowgaming.altervista.org/aowow/?item=18683#dropped-by) can also drop from container Waterlogged Crate (https://wowgaming.altervista.org/aowow/?item=6352) received from fishing.
![WoWScrnShot_121822_200252](https://user-images.githubusercontent.com/71841180/208314668-353d44b4-1fe5-4f7b-a93c-99a857a62ae4.jpg)

### Expected Blizzlike Behaviour

Hammer of the Vesper (https://wowgaming.altervista.org/aowow/?item=18683) can drop only from the selected bosses in Schlomance dungeon (https://wowgaming.altervista.org/aowow/?item=18683#dropped-by).

### Source

https://www.wowhead.com/wotlk/item=18683/hammer-of-the-vesper
https://wowwiki-archive.fandom.com/wiki/Hammer_of_the_Vesper

### Steps to reproduce the problem

1. Prepare a character with Fishing skill enough to fish Waterlogged Crate and any fishing rod
2. Find any spot rewarding with Waterlogged Crate when fished https://wowgaming.altervista.org/aowow/?item=6352#fished-in-zone
3. Start fishing the spot until Waterlogged Crate is obtained (or use command .additem 6352)
4. Open obtained Waterlogged Crate, paying attention to its drops
5. Repeat fishing and looting until Hammer of the Vesper is received 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment] 2023-01-08 10:06
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/8670 and https://github.com/chromiecraft/chromiecraft/issues/2162

**Closed by Pyromanihack** 2023-01-08 10:06 UTC
Labels: Closed
