### ISSUE TITLE
[Progression] [TBC] - Mercurial Stone

### ISSUE THREAD

**Issue by Cooties-cc** [chromiecraft/chromiecraft#6565] opened 2024-01-18 17:45 UTC
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

God, this is going to upset all tanks. 

Currently [Mercurial Stone](https://wowgaming.altervista.org/aowow/?item=31080) is showing the item with stats on it like a trinket. 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/a99f9bee-450f-40a3-b897-60dd8f1f00e3)

### Expected Blizzlike Behaviour

The item was not converted to a trinket until patch 3.1. 
Patch 3.1; alchemy - https://wowpedia.fandom.com/wiki/Patch_3.1.0#Alchemy
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/01316c5d-2ee6-4bdb-9286-3a5d2b1ead6e)

### Source

https://www.wowhead.com/tbc/item=31080/mercurial-stone - TBC classic ver
https://www.wowhead.com/wotlk/item=31080/mercurial-stone - Wotlk classic ver
https://wowpedia.fandom.com/wiki/Patch_3.1.0#Alchemy - wowpedia 3.1 patch notes
https://web.archive.org/web/20090417033401/http://forums.worldofwarcraft.com/thread.html?topicId=16403300172&sid=1 - wayback link to actual post
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/5f1bae22-80de-45d7-a91a-42f585b27d26)

### Steps to reproduce the problem

1. Log into live or PTR client
2. Give self a Mercurial Stone ; item= `31080`
3. The item has stats and is not simply a alchemy tool

### Extra Notes

I'm SORRY tank bros. It had to be done. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment] 2024-01-19 20:15
> i think the easiest approach would be simply locking the recipe like it is done with brilliant glass - if the merc isnt needed for any other alchemy thing

It's sorta hard to tell by what devs want to do with patch phasing. Mercurial Stone works similar to a Philosopher's Stone, in that it is a tool used in alchemy transmutations, but is also used by jewelcrafters to craft Mercurial Adamantite. I believe Mercurial Adamantite crafting still required the Mercurial Stone to be crafted, however for alchemists, you can still use a Philosopher's Stone for transmutations. This also can be a place to bring up that the Philosopher's Stone shouldn't have had stats on it either, until patch 2.4. 
So if the prog mod removed the item as locked till patch 3.1, instead of some kind of stat change, it would negatively impact JC because they would have no source to craft Mercurial Adamantite, whereas alchemists could still do transmutes via Philosopher's Stone. Sorta odd spot to deal with based on progression.

**Comment by amed80** [comment] 2024-01-19 20:53
> I believe Mercurial Adamantite crafting still required the Mercurial Stone to be crafted

JC don't need Mercurial Stone to craft Mercurial Adamantite.

**Comment by balleny** [comment] 2024-01-19 22:04
in tbc, what we are talking about, it did
https://www.wowhead.com/tbc/spell=38068/mercurial-adamantite

**Comment by Cooties-cc** [comment] 2024-01-19 22:04
> JC don't need Mercurial Stone to craft Mercurial Adamantite.

I know that's the case right now, but it's something that opposes the prog mod itself, which is a branch of the problem with Mercurial Stone too. This is because _it is required as a tool_ until patch **3.0.9** (https://wowpedia.fandom.com/wiki/Patch_3.0.9_(undocumented_changes)). 
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/e611a07c-1e76-4e04-80b0-fe0f69b7a26d)
How accurate wowpedia is something to consider too, since this might just have been added as a short precursor to patch 3.1, which is when the change might have really taken place. However wowhead comments also indicate that this is a correct timeline of events, and it was at 3.0.9 or 3.1 that it wasn't a tool anymore. Up until then, it was required as a tool. If its not atm, it either means it was missed by the devs in the prog mod since no one reported it. Or they are aware of it, and decided to not include/fix it since they saw it as "not a big deal". 
Either way, prog mod is there to have these, and be correct according to patch data. It's the devs choice to include or not include these changes, but regardless the data provided isn't "_incorrect_". 



> in tbc, what we are talking about, it did

REEEE I WAS JUST ABOUT TO POST THIS

**Comment by amed80** [comment] 2024-01-20 02:43
I know it was needed , i just added that it's not needed anymore referring to what balleny suggested at first about locking the recipe which wouldn't have any negative impact on JC.

Also this subject is kinda confusing for me because i don't know what is the limit or how far is the plan for devs of making everything similar to the original TBC form , like if that item should be changed to basic TBC form , should every other item have the same change ? like surefooted enchant crit bonus or Boots of the protector stats adjustment or the transporter devices go back to being trinkets ? unless i misunderstood this report completely.

**Comment by Rorschach91** [comment] 2024-11-10 23:06
I doubt that progress module permit to also change the items effect. I close this because it is not a bug.

**Closed** 2024-11-10 23:05 UTC
Labels: Needs Triage, Needs second opinion, Staff Review

**Comment by balleny** [comment] 2024-11-23 17:37
> I doubt that progress module permit to also change the items effect. I close this because it is not a bug.

changing items is a matter of simple SQL statements. Every sufficient progression module can apply item changes
