### ISSUE TITLE
Delay/lag when interrupting position (charge, intercept, sap, etc...)

### ISSUE THREAD

**Issue by Korghan905** [chromiecraft/chromiecraft#1725] opened 2021-09-14 19:27 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When interrupting the movement of an enemy with a skill (like charge, intercept, sap, stun, etc...) there's a delay, like a lag, and the enemy interrupted appears after this delay way from the point he was interrupted.
It's even more obvious when he's on a mount as the distance he moves during that delay is longer.

It creates a real broken system for warriors for example, as we often have to charge, then intercept, to catch up on a player evading with a mount.

### Expected Blizzlike Behaviour

No delay or lag : the enemy appears where he is when casting charge, intercept, sap, etc...

### Steps to reproduce the problem

charge a moving enemy on a mount, very obvious

### Extra Notes

don't understand how it is not already listed here... unless it's more than a bug ?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment] 2021-09-14 20:01
Already known issue, https://github.com/chromiecraft/chromiecraft/issues/657.

**Comment by jamadaha** [comment] 2021-09-14 22:19
Tried replicating the stun with charge, but the behaviour is the same as linked issue in above comment. So I'll close this as a duplicate. If the issue is dissimilar, please comment, and it will be reopened if they are not the same.

**Closed by jamadaha** 2021-09-14 22:19 UTC
Labels: Needs Triage, Triaging in progress

**Comment by Korghan905** [comment] 2021-09-14 22:28
it is the same indeed. It's just maybe that the problem isn't so well described, and imo much more general. 
i'm afraid that it's more than just a bug
