### ISSUE TITLE
Juvenile Snow Leopards walk on roads like dwarf npcs do 

### ISSUE THREAD

**Issue by Aggidemise** [chromiecraft/chromiecraft#516] opened 2021-05-02 16:09 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [ X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Juvenile snow leopards would take the brick roads as if they were allied npcs in dun morogh near kharanos and this specific one is always here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It shouldn't be on the roads as their considered somewhat safe in starter zones. at least not so linear like this specific npc does like its a dwarf guard.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I used (.npc info) )Juvenile Snow Leopard location:-5398.438477 -516.418518 391.964722)
2. Yes
2. Yes
3. 
4. DB GUID:3596

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-05-02 16:15
This is related to / caused by the changes applied in repsonse to issue #59. Before the change the guards/mountaineers would have taken care of wildlife walking through Kharanos. But they took their job a bit too serious and started chain killing stuff far away from the roads they were patrolling. Hence the change.

**Comment by Si1ker** [comment] 2021-05-03 21:26
Nothing wrong here, this will be closed after a couple of days.

![image](https://user-images.githubusercontent.com/61223313/116935683-ee7e0080-ac23-11eb-9ae2-90ad0c35cc94.png)

**Comment by necropola** [comment] 2021-05-05 19:09
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5629

**Comment by Si1ker** [comment] 2021-05-06 19:37
Confirmed with
.go c 3596

![image](https://user-images.githubusercontent.com/61223313/117355688-224d6600-ae70-11eb-8bde-d0603b4a91ca.png)

**Closed** 2021-05-07 05:27 UTC
Labels: Confirmed, Fix Ready, Linked [AC], [1 - 19]
