### ISSUE TITLE
[Searing Gorge] Multiple Ore Veins spawned into each other

### ISSUE THREAD

**Issue by syssneck** [chromiecraft/chromiecraft#1291] opened 2021-07-26 12:07 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

I found two locations, where Veins spawned into each other with the exact same position. I was able to mine multiple times at the exact same spot.
Location 1 (2 Veins with same position spawned into each other):
![2 Veins](https://user-images.githubusercontent.com/68868567/126985744-fde45764-1608-4139-a245-94fe2e9daac8.jpg)

Very close to the first location, Location 2 (4 Veins with same position spawned into each other):
![4 veins](https://user-images.githubusercontent.com/68868567/126985762-9de56747-85d6-4bf1-87dc-94cff45a2a2a.jpg)

Location 3 (2 Veins):
![3 location 2 Veins](https://user-images.githubusercontent.com/68868567/126987671-4508ef97-98c3-45b8-bff7-73234be141eb.jpg)

Location 4 (2 Veins)
![location 4 2 Veins](https://user-images.githubusercontent.com/68868567/126989344-0ddd7ace-4b61-4087-89e7-a41a01ae2626.jpg)

### Expected Blizzlike Behaviour

Veins shouldn't spawn into each other

### Steps to reproduce the problem

1. `.go go 5850` (check the other guid's in the screenshots)
2. check with `.gobject near` that there are indeed multiple spawn locations with the exact same coordinates (see the images above)
3. it is very likely, that only one or even none is spawned on a freshly started local AC

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment] 2021-07-26 14:27
Duplicate of #450  and #769

**Closed** 2021-07-26 15:55 UTC
Labels: Closed by Author, Duplicate, Known issue
