### ISSUE TITLE
Battleground Crossfaction HK's

### ISSUE THREAD

**Issue by thom4466** [chromiecraft/chromiecraft#2371] opened 2021-11-22 17:57 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Currently HK's from same faction that has been swapped to otherside wont count in your PVP stats, but it does count in summary of battle.

### Expected Blizzlike Behaviour

Should count towards your Total HK aswell.

### Steps to reproduce the problem

1. Queue BG
2. Be on your own faction side.
3. Have same faction on other side.
4. Try and kill them to see if you get any HK.

### Extra Notes

![AanAZ3d](https://user-images.githubusercontent.com/11156207/142911466-820c0b70-714e-498f-9d52-540f488c60db.jpeg)
![cngxoEE](https://user-images.githubusercontent.com/11156207/142911470-78640ffe-2d05-42d3-8c6b-3a3612123c46.jpeg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-21 12:06
There is some scenario that i can't reproduce. Did try to kill faction changed player, but got proper statistic.

**Comment by Salehyn** [comment] 2023-09-08 01:13
I could sort of reproduce this but not steadily. Normally when I'd queue up 2 hordies, one of them who lands on the alliance faction would be transformed into an alliance race. Killing the player would then award HK as intended.
However, it did happen that the horde toon just remained the ugly orc she is despite being assigned alliance side. Killing her in the original orcish shape would count to the BG statistics but not as a HK in general. However, after killing the orc, it immediately transformed into a draenei while lying there as a corpse, so subsequent kills would properly award HKs.

![WoWScrnShot_090823_015336](https://github.com/chromiecraft/chromiecraft/assets/134880284/8d147b64-43ee-47d9-9988-302894482012)
As seen on the screens, I killed the orc twice as per BG statistics.
The first one didn't award a HK
![WoWScrnShot_090823_014646](https://github.com/chromiecraft/chromiecraft/assets/134880284/6bff0123-5076-4c9f-8449-61cf1028a500)

The second one did and my char was left with 1 HK after a BG with 2 kills:
![WoWScrnShot_090823_015341](https://github.com/chromiecraft/chromiecraft/assets/134880284/1e42f530-a182-4400-a48c-81a47dfc77d7)

Problem being: I have no idea why my orc wasn't transformed that one time. I could not find the specific reason for that yet. But it's safe to say if the character fails to transform somehow, then it won't award HK.

**Comment by FrancescoBorzi** [comment] 2024-11-10 22:40
Closing this as it was unable to reproduce a long time ago and no new reports since then. If anyone still encounters this issue, please leave a comment here and we will reopen the report.

**Closed by FrancescoBorzi** 2024-11-10 22:40 UTC
Labels: Needs Triage, Bug Under Evaluation, PvP, Rare Bug, More Research Needed
