### ISSUE TITLE
[Quest] NPC Mist is stuck where it should not be.

### ISSUE THREAD

**Issue by rugzoneruk** [chromiecraft/chromiecraft#6302] opened 2023-11-03 20:12 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

the npc is stuck in a weird place, attached and the npc is where the mouse cursor is.
![mist2](https://github.com/chromiecraft/chromiecraft/assets/98256817/6319c29b-aa42-4b20-8e2d-ab1ac0048b5c)

### Expected Blizzlike Behaviour

https://wotlk.evowow.com/?npc=3568#starts should be at (31.5,31.6) as a questgiver. 

### Source

https://wotlk.evowow.com/?npc=3568#starts
https://wowgaming.altervista.org/aowow/?npc=3568 aowow doesn't have the npc listed.

### Steps to reproduce the problem

Go to teldrassil as any alliance character.
Go to (31.5,31.6).
https://wowgaming.altervista.org/aowow/?npc=3568 npc called mist should be there.
Go to where the cursor is in the screenshot on the current behaviour tab above.
Observe that the npc is there and won't reset.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by rugzoneruk** [comment] 2023-11-04 09:54
npc is not at the place where it was last night, also not in the spot it should be.

**Comment by rugzoneruk** [comment] 2023-11-06 08:06
npc is standing in front of the teleport to the rutheran village in darnasus :D

**Comment by Wonderboy-chromie** [comment] 2024-01-24 16:08
I think this is a conqequence of #2903 
Because of #2903 the creature will follow some player around until they go through the portal.

**Comment by BeefSteaker** [comment] 2024-05-14 11:36
Closing as it's caused by https://github.com/chromiecraft/chromiecraft/issues/2903

**Comment by alecsci** [comment] 2024-08-27 21:58
@BeefSteaker I will close this if we handle it in #2903 
On a fresh server you find it where it should be.

**Closed by alecsci** 2024-08-27 21:58 UTC
Labels: Needs Triage
