### ISSUE TITLE
[Quest] "Proving Allegiance" - You cannot summon NPC Lillith Nefara

### ISSUE THREAD

**Issue by ishidinho** [chromiecraft/chromiecraft#2470] opened 2021-12-04 13:27 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

During the quest "Proving Allegiance" you cannot summon the NPC Lillith Nefara at the butcher table on the small island in Brightwater Lake in Tirisfal.

![proving_allegiance](https://user-images.githubusercontent.com/62797536/144711170-b39aba7d-d4bd-4d4e-8e22-9e78acf0b25a.jpg)

### Expected Blizzlike Behaviour

After looting the item [Candle of Beckoning] you should be able to spawn the quest NPC Lillith Nefara at the butcher table.

### Steps to reproduce the problem

1. Accept quest "Proving Allegiance"
2. Loot [Candle of Beckoning]
3. Go to butcher table
4. Turn in the summoning quest

### Extra Notes

Quest: https://wowgaming.altervista.org/aowow/?quest=409
Lillith Nefara: https://wowgaming.altervista.org/aowow/?npc=1946
Butcher table: https://wowgaming.altervista.org/aowow/?object=1557
Quest to summon Lillith: https://wowgaming.altervista.org/aowow/?quest=410
Item [Candle of Beckoning]: https://wowgaming.altervista.org/aowow/?item=3080

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-05 09:27
Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear. Let me know if it will not happend.
![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

https://user-images.githubusercontent.com/85256266/144741035-6c12bbb7-17ef-422e-a370-9ccbdc1780cf.mp4

**Comment by ishidinho** [comment] 2021-12-07 15:19
@Shineslippers We are now at `2021-12-07` update. No changes, issue is still there.

**Comment by Shineslippers** [comment] 2021-12-07 15:29
Thank you for info. I will check it again and ping to Devs

**Comment by Shineslippers** [comment] 2021-12-07 16:06
@ishidinho thank you once again. New update didn't fix it, but this is same sort of issue. Update of the script loader still causing issues. Devs aware about it and i hope it will be fixed soon. I will keep this report open until issue is here and let you know about fix.

**Comment by Winfidonarleyan** [comment] 2021-12-07 21:00
https://github.com/azerothcore/azerothcore-wotlk/pull/9574

**Comment by Shineslippers** [comment] 2021-12-10 19:24
@Winfidonarleyan, nope it doesn't work

**Comment by temperrr** [comment] 2022-07-19 04:17
Seems to be working right now:

![image](https://user-images.githubusercontent.com/20357406/179663594-9f05e9fa-4a7b-4662-b468-ac767edc59d3.png)

**Closed by temperrr** 2022-07-19 04:17 UTC
Labels: Needs Triage
