### ISSUE TITLE
Blue Pearl not having correct drop rate from Giant Clams

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#1371] opened 2021-08-09 14:11 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Giant Clams (https://wowgaming.altervista.org/aowow/?object=2744) have 50% or less drop rate for Blue pearl (https://wowgaming.altervista.org/aowow/?item=4611#contained-in-object)

### Expected Blizzlike Behaviour

Blue Pearl should be contained 100% of the time in Giant Clam.

<html><body>
<div class="comment-header">

By bwhipp on 2007/12/27 (Patch 2.3.0) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en">Just
 farmed a bunch of these for alts - the giant clams in the Vile Reef in 
STV have a 100% drop rate (78 out of 78).  Not sure if they drop in 
other giant clams elsewhere.</div>
</body>
</html>

### Source

https://classic.wowhead.com/item=4611/blue-pearl#contained-in-object

https://www.wowhead.com/item=4611/blue-pearl#comments

### Steps to reproduce the problem

1. go to Giant clams (https://wowgaming.altervista.org/aowow/?object=2744) in STV
2. Open a few of them and observe the blue pearl drop chance

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-08-09 14:48
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/533.

**Closed by Azcobu** 2021-08-09 14:48 UTC
Labels: Needs Triage

**Comment by gurveleg** [comment] 2021-08-10 13:45
I brought shame to my clan by not spotting this myself.
