### ISSUE TITLE
Pathfinding bug on Makrura Clacker swimming on Scuttle Coast

### ISSUE THREAD

**Issue by bilakispa** [chromiecraft/chromiecraft#334] opened 2021-04-03 21:36 UTC
A mob "Makrura Clacker bugged it's pathfinding AI on Scuttle Coast at Durotar, it keeps jittering around it's self.
Happened at Coords: 62.5, 50.8

Here is a video capture:

https://user-images.githubusercontent.com/4154032/113491956-3acb0900-94dd-11eb-8866-edd7942c9ef5.mp4

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-04-07 09:43
Had no luck trying to replicate this on my test server. Went to the indicated position, pulled every Makrura within range to the surface multiple times, but none of them did anything unusual. Were there any buffs/debuffs on the mob when this was recorded? Did it happen once or multiple times?

**Comment by mdawx** [comment] 2021-04-07 15:31
@Azcobu It is same as issue #300. 

I've put video showing that Makrura has no buffs: https://youtu.be/zc5RG1iK7NI

I think, there is no known method to replicate this bug.

**Comment by Stifler82** [comment] 2021-04-09 22:18
I can't confirm the specific Bug, but i can confirm that we have some Pathfinding trouble, and we are already working on it..
So, I close this issue because the problem isn't the specific NPC but something that we are already working on..

**Closed by Stifler82** 2021-04-09 22:18 UTC
Labels: Needs Triage
