### ISSUE TITLE
Pet - Dies if you dismiss during dungeon. Also not working whilst on flight path.

### ISSUE THREAD

**Issue by Iramtempus** [chromiecraft/chromiecraft#1473] opened 2021-08-20 03:24 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If in dungeon with a pet, you cannot dismiss it.
If you do the call pet wont work and you have to revive pet to get it back.

Not sure what is causing this. Had a similar problem of being on a flight path in between dungeons where my pet then dissapeared and once more had to be revived to get back.

### Expected Blizzlike Behaviour

For the dismiss/call to function properly.

For the game to see that the pet is alive in between dungeons.

### Steps to reproduce the problem

1. Be a hunter
2. Be on a FP
3. Get Ported to dung
4. Have to revive pet

1. Dismiss a pet in dungeon
2. See that call pet doesnt work.
3. Revive pet

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment] 2021-08-20 12:08
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/1302

It's already fixed but its awaiting merging with Chromiecraft. Please keep an eye out for the next update.

**Closed** 2021-08-20 12:09 UTC
Labels: Duplicate, Closed
