### ISSUE TITLE
Shareable quest cannot be shared

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#291] opened 2021-03-25 10:48 UTC
Searching for the Lost Satchel is unable to be shared

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When in a group and sharing a quest, there are several possible system messages that appear in the Chat box, such as:
  $n is already on that quest
  Sharing quest with $n
  $n is not eligible for that quest

[Searching for the Lost Satchel](https://www.wowhead.com/quest=5722) is marked as Shareable in WoWhead for both Live (though removed in Cata) and Classic. It also has a Flag of 8 in the AzerothCore database which is the bitmask for a shareable quest, however when sharing this quest, there is no system text that appears and group members do not receive a prompt to accept the quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Sharing quest should work

##### STEPS TO REPRODUCE THE PROBLEM:

Logon to two characters
required level for quest is 10 so `.levelup 10`
Both characters `.go creature Rahauro`
One character accepts Searching for the Lost Satchel from Rahauro
Invite the other character to group
Open Quest Log
Right click quest and select Share

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-03-25 11:35
I don't sure if I understood your problem correctly, this problem you are reporting has nothing to do with https://github.com/chromiecraft/chromiecraft/issues/216?

Because if we are talking about the same problem, then your report is a Duplicate and theoretically the Fix is ready.

**Comment by eTzmNcbkrng** [comment] 2021-03-25 19:47
Yeah could be a duplicate, this quest just has you go find an NPC to turn it in so it's probably a completed quest as soon as it's picked up.

My local server is about a week old, but I did get this issue on ChromieCraft last night.
Is there a schedule for ChromieCraft pulling from Origin or does it depend on the number and severity of bug fixes?
Just wondering when the fix might go live on ChromieCraft.

**Comment by Stifler82** [comment] 2021-03-25 19:59
> Just wondering when the fix might go live on ChromieCraft.

When you see a PR with the flag "Merged" and not "To be Merged" in CC instead when it is "Fixed" and not "Fix Ready"
you are asking this, right?

**Comment by eTzmNcbkrng** [comment] 2021-03-26 05:47
Yes, that's what I am asking. Cheers, I'll keep an eye on the other ticket.

**Comment by Stifler82** [comment] 2021-03-26 08:28
Since I noticed that I made a bit of a mess between Flags and Labels in my explanation I made you a video that "should" be more exhaustive..

https://user-images.githubusercontent.com/1884642/112603133-79413380-8e0c-11eb-9e92-5d861035e663.mp4

**Comment by Stifler82** [comment] 2021-03-26 08:29
@eTzmNcbkrng
So, can i Close this report?
it is a duplicate, right?

**Comment by eTzmNcbkrng** [comment] 2021-03-27 09:37
I guess it's kind of a duplicate, but not completely and it can't be closed because it's not resolved.
If I encountered this situation in my job, ITIL principles would apply.

The larger Issue you quoted would be considered the overarching P1 or P2 ticket and each individual smaller issue would be placed on hold pending the big one.
After resolving the big issue, each child needs to be checked to ensure it resolved the issue for each one.

**Comment by Stifler82** [comment] 2021-04-07 22:34
Fixed here https://github.com/azerothcore/azerothcore-wotlk/pull/4880
and duplicate of this https://github.com/chromiecraft/chromiecraft/issues/216

**Closed by Stifler82** 2021-04-07 22:34 UTC
Labels: Confirmed, Fix Ready, Linked Issue
