### ISSUE TITLE
[Searing Gorge] Heavy War Golem spawns underground.

### ISSUE THREAD

**Issue by vexima** [chromiecraft/chromiecraft#1189] opened 2021-07-14 05:53 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Heavy War Golem with DB GUID 5687 spawns underground inside bridge pillar.
![bug_report_071421_094217](https://user-images.githubusercontent.com/87258853/125570096-8d321b9e-cb17-49e8-9049-f8fc8379c897.jpg)

### Expected Blizzlike Behaviour

NPC should either spawn above the ground or not spawn at all.

### Steps to reproduce the problem

1. Teleport to NPC GUID 5687

**Comment by gurveleg** [comment] 2021-07-14 06:33
Duplicate of #881

**Closed** 2021-07-14 10:24 UTC
Labels: Closed, Duplicate, Linked [AC]
