### ISSUE TITLE
[Quest] Investigate the alchemist shop impossible

### ISSUE THREAD

**Issue by Kahaniel** [chromiecraft/chromiecraft#1544] opened 2021-08-26 12:49 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The level 15 horde mage quest "Investigate the Alchemist shop" in Undercity is bugged.
While the mobs are stunned when beaten, it is impossible to capture them, the item saying that the target is not valid. The quest is therefore impossible to complete due to that.

### Expected Blizzlike Behaviour

Mages are supposed to summon the mobs with the quest item "Cantation of Manifestation" in undercity near the alchemists, then beat them and once beaten they are not supposed to despawn but be stunned in order to be captured with the quest item 'Chest of Containment Coffers", ghostbusters style which gives the mage the "Filled Containment Coffer".

### Source

Expected behavior : https://classic.wowhead.com/quest=1960/investigate-the-alchemist-shop

### Steps to reproduce the problem

Needs a level 15 or more mage to get the quest
Get the quest from the mage trainers in Undercity
Get the items from behind the quest giver
Use the item to summon the mobs in front of the alchemist shop in Undercity
Beat the mobs (they're tough)
Try to use the chest of containment in your inventory to capture the beaten mob

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-08-28 06:56
Thanks for the report. I just ran through this on a test mage character a couple of times and it seemed to work fine:

Stunning the NPC
![WoWScrnShot_082821_155836](https://user-images.githubusercontent.com/81782124/131208730-c8900b0b-0fa0-4548-b942-ebb44d28ab17.jpg)

Placing the trap:
![WoWScrnShot_082821_155838](https://user-images.githubusercontent.com/81782124/131208733-e1e789f1-b734-41f7-83fb-31b31206441e.jpg)

trap activated:
![WoWScrnShot_082821_155846](https://user-images.githubusercontent.com/81782124/131208735-9d01b2f6-4a96-471f-ae8d-e5fbdfb40251.jpg)

Quest item spawned:
![WoWScrnShot_082821_155850](https://user-images.githubusercontent.com/81782124/131208738-1206c523-985b-4e18-a353-d532e4d3c7e9.jpg)

I did notice one of the Rift Spawns who didn't display a swirly stunned animation after reducing its health down to 0, but another firebolt set the stun state properly and it went into a containment box with no problems. I'll close this as un-reproduceable for now, but perhaps if it happens to you again let us know (and maybe take some screenshots to illustrate it if possible, please).

**Closed by Azcobu** 2021-08-28 06:56 UTC
Labels: Needs Triage

**Comment by Juggalo187** [comment] 2021-09-17 01:19
I spent an hour trying to do this quest and they never get stunned.
 I'm using enUS
 https://www.youtube.com/watch?v=eWQj_TCPZMs

**Comment by Azcobu** [comment] 2021-09-17 11:01
I think that's because you used the Frost Nova to hit them first instead of the quest item provided, the Cantation of Manifestation. I found when testing this (see https://github.com/azerothcore/azerothcore-wotlk/issues/7715) that NPCs hit with the Frost Nova first seemed to be a lot harder to stun, if they were ever stunned at all. This was because the internal smart_script running the NPCs didn't seem to take the possibility of being revealed by anything other than the Cantation into account, so wasn't setting them into the right phase when they were. However, as they're clearly still not working properly, will try to take another look at the script and see if there's something that can be done to make them handle Frost Nova hits a bit better.

**Comment by Juggalo187** [comment] 2021-09-17 13:03
Yeah that was it, I didn't realize I had "Cantation of Manifestation" and that I needed to use it. All the guides and videos I saw it looked like people were using arcane explosion or frost nova to bring them out of stealth or whatever.

**Comment by TheRiddermark** [comment] 2021-11-04 23:54
@Azcobu - Sorry to post in a closed threat but this might be possibly related.
There was an immortal lvl 17 Rift Spawn in Undercity just hanging about. I attacked it and it was stuck at 1 hp.
On the plus side I was able to level up my staves, unarmed and defense skill to 260/260 from engaging it (im at lvl 51 though)
https://pasteboard.co/YxrFRURcJmq4.jpg

It was spawned at this location and when I ran away to lose combat, it went back here and despawned.
https://pasteboard.co/cv3pVKro4UI2.jpg

**Comment by Azcobu** [comment] 2021-11-06 03:09
@TheRiddermark - thanks for the update, glad you managed to find a use for the Rift Spawn. Also a bit relieved it actually reset on its own. The script has a SMART_EVENT_RESET event which makes it go invisible again after combat is over, but from what you said about one just hanging around, was a bit concerned that wasn't working either. Possibly it was left over from someone doing the quest (or just letting off an AoE in the wrong place) and you found it before it had time to reset on its own.
