### ISSUE TITLE
Dire Maul North --> Knot thimblejack's cache

### ISSUE THREAD

**Issue by Maz93** [chromiecraft/chromiecraft#2174] opened 2021-10-23 12:58 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Hello,

The problem I've experienced is the following: yesterday (23rd October) I did a few Dire Maul North runs, dropped "Gordok Shackle Key" (https://wowgaming.altervista.org/aowow/?item=18250) and used it to free Knot in order to get his cache. Everything worked out perfeclty.
Today I did at least 4 runs, maybe more, but when I gave to Knot the key, nothing happened. He didn't leave the cache a single time

### Expected Blizzlike Behaviour

https://classic.wowhead.com/object=179501/knot-thimblejacks-cache#comments

### Steps to reproduce the problem

1. Enter inside Dire Maul North with RDF
2. Drop the Gordok Shackle Key from mobs/bosses
3. Proceed until you meet Knot
4. Talk with him and push the option on giving him the key
5. At this point, nothing will happen

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-09 14:03
As there is new reports about this issue and we're unable to reproduce it i have close it.

**Closed by Shineslippers** 2021-12-09 14:03 UTC
Labels: Waiting for more feedback, Unable to Reproduce
