### ISSUE TITLE
Scripting for Draenei Shaman class quest "Call of Water" Step 5/6 not working - Water Elemental script is not activating

### ISSUE THREAD

**Issue by Fergus01** [chromiecraft/chromiecraft#810] opened 2021-06-08 12:15 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Quest in chain: https://wowgaming.altervista.org/aowow/?quest=9508#see-also

Currently able to click barrel and spawn hostile and friendly NPCs. Hostile NPC will follow scripting with statements then attack. Does not appear to take damage or utilise mana for spells when attacked. Friendly water elemental NPCs are not making their statements then attacking hostile NPC.

On quest failure water elementals are not de-spawning.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=gd_7Wv9zHLc

##### STEPS TO REPRODUCE THE PROBLEM:

1.  GUID for Water Elementals: 10428, 10429
2. 
3. 
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-06-08 14:54
Thanks for the report. Just tested this one and didn't run into any of the above problems, apart from Tel'athion's mana usage being almost nil. He certainly took damage, and the two friendly water elementals said their lines and attacked correctly. When I failed the quest, the water elementals were then killed by Tel, so didn't need to be despawned on their own.

https://user-images.githubusercontent.com/81782124/121207573-8c668a00-c8b8-11eb-8eb0-4d9f045bd3eb.mp4

Closing as I'm not seeing any significant issues here.

**Comment by Eller1** [comment] 2021-06-29 20:23
Summoned elementals do not help in the fight, Tel'athion's spells use no mana as of 2021-06-29 on ChromieCraft's server.

**Comment by Azcobu** [comment] 2021-06-30 13:50
Just ran through it again and the water elementals attacked fine on a vanilla AC server. 

![WoWScrnShot_063021_225919](https://user-images.githubusercontent.com/81782124/123969064-004b0c80-d9f7-11eb-8d04-4dc38ea754eb.jpg)

However, I do agree that the mage's mana use is pretty questionable. It's a bit difficult to find a source on what it should be, but it shouldn't be nothing at all. Checking CastFlags in his SmartAI, looks like the four spells he cycles through have SMARTCAST_TRIGGERED flag set, which makes spells cost zero mana and have no cast time. However, that was probably set for a reason, so will have bit of an experiment with that flag and see if it can be removed without breaking anything else.

**Comment by Eller1** [comment] 2021-07-01 15:10
Screenshot from the 06-29 test, showing Tel'athion having attacked and damaged me, and elementals doing nothing.

![WoWScrnShot_062921_220240](https://user-images.githubusercontent.com/86687206/124146164-2d9ac780-da96-11eb-9ca3-8fdbcaf657a5.jpg)

Additional information: I have not tried it, but mousing over elementals changed mouse cursor to sword icon, indicating its was possible to attack them.

This bug somewhat impacts shaman player experience, since its harder to solo Tel'athion without elemental help, thus possibly delaying getting water totem.

**Comment by bjcrow12** [comment] 2021-08-16 02:24
Confirmed that the water elementals just stand there and do not help attack...it is bugged

**Comment by gruntsrb** [comment] 2021-09-26 21:23
Just tried to do this today on Chromiecraft and it is still bugged. Water elemental mobs just stand there and the NPC hits like a truck I am lvl 23 with solid gear and he kills me in few sec and I can't even take 1/3 of his HP that is broken for sure.

**Comment by Shineslippers** [comment] 2021-11-18 00:31
@Azcobu Got atleast one stacked. The key is do damage to NPC right after spawn.

https://user-images.githubusercontent.com/85256266/142313877-e613ae9e-26a6-49d0-997c-848e59b53269.mp4

**Comment by Shineslippers** [comment] 2021-11-18 00:53
Able to reproduce.

**Comment by drislands** [comment] 2022-03-23 18:39
Issue #3052 was opened about a month ago for this same problem. Can probably be closed/merged into this one.

Additionally, I can confirm on March 23rd 2022 that this is still an issue as described with no changes.

**Comment by Tebec** [comment] 2022-06-08 17:43
June 8th, it's still broken, he also doesn't move so I can range his casts but his range is more than mine so can't just use range to kill him.  I spawned the elementals the first 2 times I used the barrel, the third time did not spawn any additional ones though.

**Closed** 2022-06-18 12:21 UTC
Labels: Confirmed, Linked [AC], [1 - 19], Class Issue
