### ISSUE TITLE
Un'goro Discover pylons quest not completing.

### ISSUE THREAD

**Issue by Zhowd** [chromiecraft/chromiecraft#1981] opened 2021-10-05 00:31 UTC
when clicking pylons to complete discover the pylon quest of each cardinal direction, none are completing the quest and being able to turn in to continue in the chain.

**Comment by VFaleiro** [comment] 2021-10-05 02:45
Hi.

I'm afraid the triagers will close this issue because you did not fill the form for reporting bugs.

Please, try reporting this again by clicking on the "New issue" green button, then "Get started".
Or, alternatively, using [this link](https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml).

**Comment by gurveleg** [comment] 2021-10-05 07:18
Hi, this is a known issue, duplicate of #1932 . I'll close tihs accordingly.

**Closed by gurveleg** 2021-10-05 07:18 UTC
Labels: Needs Triage
