### ISSUE TITLE
Winter Veil's presents can be gotton infinitely after log out and log in

### ISSUE THREAD

**Issue by eusss** [chromiecraft/chromiecraft#2659] opened 2021-12-23 09:29 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Winter's Veil presents under the tree in Ironforge respawn after logging out and logging in. Therefore, the presents can be obtained infinitely by relogging.
https://www.wowhead.com/quest=8744/a-carefully-wrapped-present
https://wowhead.com/quest=8767/a-gently-shaken-gift
https://www.wowhead.com/quest=8803/a-festive-gift
https://www.wowhead.com/quest=52965/a-winter-veil-gift
https://www.wowhead.com/quest=8768/a-gaily-wrapped-present
https://www.wowhead.com/item=21327/ticking-present#contains

### Expected Blizzlike Behaviour

Not sure, don't have any documentation. Should it not spawn after Greatfather Winter yells that the presents are under the tree?

### Source

<img width="1577" alt="Screenshot 2021-12-23 at 10 27 35" src="https://user-images.githubusercontent.com/96571151/147219410-3d1fddab-c607-43b9-8fc5-fad4fa6506e7.png">
<img width="1577" alt="Screenshot 2021-12-23 at 10 28 24" src="https://user-images.githubusercontent.com/96571151/147219545-28fb9f81-7cd1-40c4-aa78-42bdfe49c01f.png">

### Steps to reproduce the problem

1. Open all quests from presents under the tree
2. Relog
3. Repeat from step 1

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by eusss** [comment] 2021-12-23 09:35
Reports say that it is a daily respawn?

Source: https://www.wowhead.com/item=21327/ticking-present#comments

In Ironforge and Orgrimmar, there will be a big Christmas tree with a pile of presents underneath (during Winter Veil, of course). In IF, it's right outside the bank. In Org, it will be somewhat between the AH and the bank.

From December 25 to January 1, there will be 6 presents under the tree that will have a big yellow "!" over each. You can click on each to accept them like quests, but in lieu of actual quests you get gifts/ presents. (As they behave like quests, it's okay if other people are also clicking on them to accept them. You can still get yours.)

Links to all the possible gifts and presents you can get:

1. Carefully Wrapped Present : gives food
Winter Veil Cookie
2. Gaily Wrapped Present : gives pets! (yay)
Green Helper Box
Red Helper Box
Snowman Kit
Jingling Bell
3. Ticking Present : mainly gives a 3-time-use combat pet or a buff item
Mechanical Greench
Preserved Holly
You have like a tiny chance to get patterns, etc., but the patterns are just normal non-event patterns. You can view the documented list here.

4. Gently Shaken Gift : gives a drink
Winter Veil Eggnog
5. Festive Gift : gives a 10-day item that makes people laugh (has a 2 minute cooldown)
Wand of Holiday Cheer
6. Crashin' Thrashin' Racer Controller : basically a toy that you can control to fight other toys. No duration or limited use on this one.

**Comment by ishidinho** [comment] 2021-12-23 10:10
Thank you, @eusss.

This issue has already been report five hours ago. ;)
Please have a closer look on the issues next time.

Duplicate of: https://github.com/chromiecraft/chromiecraft/issues/2657

**Closed** 2021-12-23 10:18 UTC
Labels: Duplicate, Closed
