### ISSUE TITLE
[Molten Core] Runes being extinguished without player intervention

### ISSUE THREAD

**Issue by j-hdt** [chromiecraft/chromiecraft#2744] opened 2022-01-07 22:59 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Runes of bosses are automatically extinguished overnight if you dont extinguished them actively.

### Expected Blizzlike Behaviour

As of 3.3.5, this should happen immediately after a boss is defeated.
After the re-implementation for CC, the runes shouldnt be extinguished automatically.

### Steps to reproduce the problem

clear e.g. 4 bosses in MC.
Wait one night (maybe wait a server restart)
defeat the remaining bosses.
Extinguish only the runes of the bosses killed last.
Majordomo script starts and spawns.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment] 2022-01-08 10:07
This is intended behavior for when restarts or crashes happen, to minimize the bother to players when those unfortunate events happen during a run. However, if this becomes a problem, I can change that so they'll always require dousing.

**Comment by j-hdt** [comment] 2022-01-08 11:00
right now its contradicting the announcement of the reintroduction of the dousing requirement.
atleast an information should be given to avoid confusion for raid groups

**Comment by Shineslippers** [comment] 2022-01-08 19:17
Due to Nyeriah comment above i have to close this report. This is intended behavior.  I guess in this case better leave your message in suggestion channel on Discord.

**Closed by Shineslippers** 2022-01-08 19:17 UTC
Labels: Needs Triage
