### ISSUE TITLE
Clicking any other zones on the map brings you back to the current zone you are in

### ISSUE THREAD

**Issue by KevinFromProduce** [chromiecraft/chromiecraft#2387] opened 2021-11-24 00:32 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Opening the map [M] then zooming out any amount of times [RMB] then clicking on any other zone will only bring you back to the zone you are currently in, rather than showing the zone you wanted to view.

I.e. I am in Felwood. I open the map and zoom out to show my friend where the flight path is in Western Plaguelands, clicking on Western Plaguelands (or even the Eastern Kingdoms) sends me right back to Felwood.

### Expected Blizzlike Behaviour

Opening the map and clicking on any zone should show you the specified zone and not the zone you are currently in.

### Steps to reproduce the problem

1. Open Map [M]
2. Zoom out any amount of times [RMB]
3. Click on any zone other than your own [LMB]
4. Only the zone you are currently in will be shown

### Extra Notes

Sorry if I did this wrong I'm new and don't know what I'm doing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-24 11:54
Thank you for the report. It's absolutelly clear what issue you have. Anyway i can't repet it on local AC. In thi case i have you to delete `cache` folder and disable addon. It's not server issue so far.

https://user-images.githubusercontent.com/85256266/143233618-301e4505-ad4e-4866-89bb-a1a01c10065a.mp4

**Comment by cachocarne** [comment] 2021-11-24 17:24
I just have a related situation. Doing a Warlock quest in Ashenvale and clicking on "show map" brings me to Stormwind (where I will eventually turn the quest in when I complete it). Also there is no POI marker or anything.
![ 2021-11-24 at 16 19 15](https://user-images.githubusercontent.com/77953030/143284534-12a85465-9b98-49c1-857c-48735103e405.png)
![ 2021-11-24 at 16 19 19](https://user-images.githubusercontent.com/77953030/143284585-b26b3dcb-d779-4b49-a5ac-ff50d69a886f.png)

**Comment by Orixim** [comment] 2021-12-02 16:26
@KevinFromProduce  perhaps you are using a faulty addon? There are so many addons that affects the Map that you might not even be aware you have it.

**Comment by Orixim** [comment] 2021-12-03 00:52
So I actually have managed to reproduce the problem. I've made a short clip for you guys to see. If it is the same problem as the one I got, it is due to the option of always showing the small map. I am using ElvUI here, but I believe that is a native feature as well. I hope this helps out. @Shineslippers can you please re-assess this ticket?

The video is too big, so I'm using [WeTransfer ](https://we.tl/t-kNBpVSeEqA) here (it will expire within a week).

**Comment by Shineslippers** [comment] 2021-12-03 20:28
@Orixim Thank you. Indeed issue exist, but candidate to Client issue.

**Comment by Orixim** [comment] 2021-12-05 06:46
I have done some more testing based on what you have showned (I've noticed you are using the Mapster addon?). This time I've also disabled my ElvUI (I have no other map addon).

[WeTransfer video](https://we.tl/t-vCd4XUokKR)

Apparently, it would work nice after a reopening like you did, but only on "full" window map. If I had it in "window" map, it would not work. Funny thing happened while clicking on the zone of the main city I was. I've also tried it outside the city and the behaviour was the same.

I am no idea if it is a client side bug, probably it is. I was also not the one who reported this and it has never affected my personal experience. I've only ever noticed it because of the bug report and I've got curious and tried it out.

**Comment by Shineslippers** [comment] 2021-12-05 07:23
Yes, i'm using Mapster. Same as you i'm ofc did check it without addons before. To summirize. Using `Always show` zone map call this issue. 

https://user-images.githubusercontent.com/85256266/144737650-e2f2fc1c-251f-4919-94c0-98f931f3f3a0.mp4

**Comment by Orixim** [comment] 2021-12-18 15:43
After some more digging around, I've found this comment:

> Beware that the Blizzard zone map, when visible, will force the current zone you are in to be selected, which is a global game setting. That setting is also used by Carbonite to determine what zone is selected, which means you will have problems mousing over other zones on the Carbonite map to view them.

So I guess this might be a limitation that existed as well.

**Comment by Shineslippers** [comment] 2021-12-18 15:59
I guess i will close it. Since this interface issue that server do not related to .

**Closed by Shineslippers** 2021-12-18 15:59 UTC
Labels: Bug Under Evaluation, Needs second opinion
