### ISSUE TITLE
Tome Of Divinity - Dwarf Paladin

### ISSUE THREAD

**Issue by Orivanz** [chromiecraft/chromiecraft#3196] opened 2022-03-12 10:47 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Brandur Ironhammer gave me the first quest (https://classic.wowhead.com/quest=1646/the-tome-of-divinity) in the chain for Redemption spell to talk to Tiza Battleforge. After completing that quest she does not have an "!" to give the next quest (https://classic.wowhead.com/quest=1647/the-tome-of-divinity).

### Expected Blizzlike Behaviour

NPC should provide the next quest to talk to John Turner in Iron Forge, https://classic.wowhead.com/quest=1647/the-tome-of-divinity

### Steps to reproduce the problem

Level 12 Dwarf Paladin talks to Paladin Trainer, Brandur Ironhammer, in Ironforge to get quest "Tome of Divinity"
Talk to Tiza Battleforge to complete step one in chain and receive next quest

### Extra Notes

Tried to get quest without addons enabled, relogged and tried again, also did not work after server restarts

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a775ddcb5b935be3358644be27df282fc29a9936

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment] 2022-03-13 06:46
Hey @Orivanz. Thank you for the report.

As you can see, a fix for the issue is already in the pipeline.

**Comment by Orivanz** [comment] 2022-03-13 07:40
Thanks, not sure exactly what all that means in the linked thread, Guessing the fix goes in place on next server restart?

**Comment by ishidinho** [comment] 2022-03-13 07:51
It will not be that fast, sorry. But let me explain.

Kosiak implemented a fix for the issue. Now a review by another developer is required to ensure AzerothCores quality. If the reviewer approves the implementation the fix will be "merged" into the project and is niw available for all servers using AzerothCore, like ChromieCraft.

The ChromieCraft staff regulary schedules updates of the server. During that updates, the fix finally finds its way to ChromieCraft.

**Comment by Orivanz** [comment] 2022-03-13 09:27
Fair enough. There isn't a command that a gm/dev can use to add the spell to my spell book is there? We had them on a FFXI private server I GM'd for, not sure if you guys have that with AC.

**Comment by 55Honey** [comment] 2022-03-13 09:36
https://github.com/chromiecraft/chromiecraft/issues/3133

**Closed** 2022-03-18 21:30 UTC
Labels: Confirmed, Linked [AC], [1 - 19]
