### ISSUE TITLE
Snowing in Loch Modan

### ISSUE THREAD

**Issue by Superducked** [chromiecraft/chromiecraft#1766] opened 2021-09-16 16:01 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When coming from Dun Morogh into Loch Modan through the north passage, the snow weather effect doesn't turn off when entering Loch Modan. As far as i'm aware this is not supposed to happen.
![WoWScrnShot_091621_173435](https://user-images.githubusercontent.com/90856199/133643083-7b9c4911-7192-4c6b-94a3-530aba4d2d7d.jpg)
![WoWScrnShot_091621_173551](https://user-images.githubusercontent.com/90856199/133643120-16759ab5-0924-483b-ba30-a6a27fbc1202.jpg)

### Expected Blizzlike Behaviour

Loch Modan zone should not show a snowing weather effect, or at least i have never seen it in any official build.

### Steps to reproduce the problem

1: Travel to Dun Morogh
2: Take the north passage into Loch Modan
3: Enter Loch Modan

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by discorder0** [comment] 2021-09-18 18:37
Today (server time 18:15-18:20, 2021/09/18), I ran from Dun Morogh to Loch Modan through south gate pass, went to the bunker to accept quests (defend king’s land or something like that), then ran to Thelsamar, and then all the way to the western shore of the Loch.

I can confirm that it was snowing throughout this whole trip. Cannot speak for other subzones in Loch Modan and don’t know whether it is a bug.

**Comment by Snufflenose** [comment] 2021-09-30 20:12
I can confirm this bug - and yeah, I've never seen snow in Loch Modan before.

![Bildschirmfoto 2021-09-30 um 22 08 24](https://user-images.githubusercontent.com/91610030/135523661-59aaecb0-bc93-48d5-b02d-f99caada6aae.png)

**Comment by ntrna** [comment] 2021-10-03 15:16
I thought that wasn't a bug, or I wanted to think so, because I liked it. However, when taking off from Tanaris during a sandstorm, I landed in Menethil to a sandstor
![WoWScrnShot_100321_111314](https://user-images.githubusercontent.com/89823720/135760397-5a1c1778-4626-444a-9162-69664df176e4.jpg)
m.

**Comment by Snufflenose** [comment] 2021-10-13 09:18
This seems to be a general issue on CC with ambient visuals and sounds persisting through zones.

Not only does it happen with weather effects - it also happened during Brewfest when ambient festival sounds continued after leaving the Brewfest area and even travelling to different zones..

**Comment by Shineslippers** [comment] 2021-11-22 15:21
Thank you for the report. Issue is exist, but anyway i have to close it. It was already reported https://github.com/azerothcore/azerothcore-wotlk/issues/6341

**Closed by Shineslippers** 2021-11-22 15:21 UTC
Labels: Needs Triage
