### ISSUE TITLE
[TK] Alar idles after platform change

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6910] opened 2024-03-27 22:11 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

when alar flies to a new platform (except for the first one), he idles and doesnt attack the target unless taunted.

it is sufficient, to have a pet or player within reach to stop the flame buffet, but alar will not start attacking the closest target

### Expected Blizzlike Behaviour

P1: should attack the closest target. if no target in reach, should cast flame buffet

### Source

.

### Steps to reproduce the problem

Alar fight
2 chars required.
place char 1 on platform 1 and char 2 on platform 2
engage alar. build some threat with char 1 while alar is at platform 1.
when alar flies to platform 2, dont move any char.

Alar should attack player 2 and not cast any flame buffet once he reached platform 2. But, I think he will do nothing, not casting flame buffet and not attacking char 2.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-03-27 22:50
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/6731.

**Closed by heyitsbench** 2024-03-27 22:50 UTC
Labels: Needs Triage
