### ISSUE TITLE
[Black Temple] problem during Tidal Shield

### ISSUE THREAD

**Issue by Capoguerra** [chromiecraft/chromiecraft#7299] opened 2024-08-22 09:52 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

When High Warlord Naj'entus activates his shield (Tidal Shield) if he targets a player within the shield animation (melee range) to impale him with Impaling Spine, the golden wheel to free the impaled one is not clickable.

### Expected Blizzlike Behaviour

The wheel to free the player affected by Impaling Spine should always be clickable.

### Source

https://www.wowhead.com/wotlk/it/npc=22887/high-warlord-najentus#english-comments;mode:n25

### Steps to reproduce the problem

1. Pull High Warlord Naj'entus (keeping him in aggro) and place a second player in melee range
2. Wait for the first cast of the Tidal Shield and impale the second player within the range of the Tidal Shield
3. Try clicking on the wheel located inside the Tidal Shield animation

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/de1e42bd83fe149b9d24239df05e4d5ae7f72d38

### Operating system

Win 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment] 2024-09-03 14:48
Unable to reproduce. I close this issue. Thank you anyway.

**Closed by Rorschach91** 2024-09-03 14:48 UTC
Labels: Closed, Unable to Reproduce
