### ISSUE TITLE
[Western Plaguelands] Blood of Heroes spawn can be seen but not fully

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2238] opened 2021-11-02 05:55 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Not like the last one, you can see parts of it, but it's not fully shown like it should
![WoWScrnShot_110221_065008](https://user-images.githubusercontent.com/80590226/139793547-26f34f42-5daf-4d5b-aa4a-4d21c13e5513.jpg)

### Expected Blizzlike Behaviour

Should be shown properly like any other spawn, on the ground.
https://wowgaming.altervista.org/aowow/?object=176213
https://wow.zamimg.com/uploads/screenshots/normal/1917-blood-of-heroes-blood-of-heroes.jpg

### Steps to reproduce the problem

1. Get to location https://wowgaming.altervista.org/aowow/?object=176213
2. Object spot: (42.9 , 64.1), the top one on map in Andorhal
3. You can't spot it, just mouse over that hill, object is bellow, not properly visible.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment] 2021-11-02 06:07
Duplicate of #2089.

**Comment by gurveleg** [comment] 2021-11-02 07:28
Thanks for the report, but just as VFalerio said, this is a known issue already reported.

**Closed by gurveleg** 2021-11-02 07:28 UTC
Labels: Duplicate, Closed
