### ISSUE TITLE
Netherstorm: Shutting Down Manaforge Coruu cant be finished

### ISSUE THREAD

**Issue by Riichzz** [chromiecraft/chromiecraft#5102] opened 2023-02-28 21:19 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

65-69

### Current Behaviour

NPC Caledis Brightdown gives you the quest: Shutting down manaforge coruu.

you need to kill overseer seylanna and get  [Coruu Access Crystal], then click in the manaforge mechanism to shutdown the manaforge..
As i said before i did all those steps and get the yellow "Quest complete" announce, then i go to the npc to finish the quest but he ask me for [Coruu Access Crystal] i dont know why because it is my bag.

### Expected Blizzlike Behaviour

It should let me finish the quest because i have the item in my bag and i already shutdown the manaforge.

### Source

![WoWScrnShot_022823_164730](https://user-images.githubusercontent.com/114109105/221982099-d2abe4c0-3639-411b-bb15-c7b7b3491678.jpg)
![WoWScrnShot_022823_164756](https://user-images.githubusercontent.com/114109105/221982135-06b60f64-d4be-49e3-bf25-65806cce43bb.jpg)

### Steps to reproduce the problem

1. Kill overseer Seylanna and pick [Coruu Access Crystal].
2. Click the mechanism to shut down manaforge coruu.
3. Defend the mechanism while it is shutting down (even when you have invisible npc hitting you).
4. go back to NPC Caledis Brightdown.
5. Finish the quest without problem.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Frodhi** [comment] 2023-03-02 18:52
Ive had the same problem on aldor side.
Karja doesnt give me the next step

**Comment by Yarusha-ret** [comment] 2023-03-07 20:23
I can confirm it's not working for me either. Horde, Scryers.

**Comment by Depe79** [comment] 2023-03-15 12:13
I have encountered the same bug, i have completed the conquest but the npc doesn't recognize the item.

**Comment by Samsequel** [comment] 2023-04-07 12:39
You gotta kill the spawning NPCs then it works

**Comment by woosting** [comment] 2023-08-02 18:07
Same problem (alliance / Aldor). Completed the shutdown procedure; got the quest update (and marking in the quest log that the quest is complete). Tried turning it in and the quest complete button (at the NPC) was non-responsive. After closing the window the quest I _was_ on was gone, but now XP and now follow-up quest for the  chain was given.

Anyone found a workaround and/or how can we now get the (chain final) rewards?

**Comment by foo-17** [comment] 2023-11-12 17:40
tested with AzerothCore rev. 68263b773daa 2023-11-07 (master branch).

- At first, could not reproduce this issue. On first trial, as Alliance level 255, I could hand in the quest properly. 

- The second time, I repeated at level 69, and after finishing quest objective, I messed up some gm commands and logged out and in. After logging in again, I encountered same issue as in description - I could not hand in quest bc quest item from my bag was not recognized.

![image](https://github.com/chromiecraft/chromiecraft/assets/150605164/af4edf9f-3bf1-4e83-ba0a-b1cce4637c0f)

- I tried another time without relogging in between - same result, quest item was not recognized form bag.

There may be a genuine issue here, however, issue only seems to arise under specific circumstances.

**Comment by foo-17** [comment] 2023-11-22 16:30
This issue is likely the one reporte din https://github.com/azerothcore/azerothcore-wotlk/issues/15303 : all Manaforge quests were bugged so that when done in a group, only the person initiating the shutdown could turn in the quest (though quest was marked as completed for all members). Was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/15393

**Comment by BeefSteaker** [comment] 2024-03-01 18:28
> This issue is likely the one reported in [azerothcore/azerothcore-wotlk#15303](https://github.com/azerothcore/azerothcore-wotlk/issues/15303) : all Manaforge quests were bugged so that when done in a group, only the person initiating the shutdown could turn in the quest (though quest was marked as completed for all members). Was fixed by [azerothcore/azerothcore-wotlk#15393](https://github.com/azerothcore/azerothcore-wotlk/pull/15393)

Closing as fixed by this

**Closed by BeefSteaker** 2024-03-01 18:28 UTC
Labels: Needs Triage
