### ISSUE TITLE
[Quest - Hellfire - Exorcism of Colonel Jules is completely broken and spawns insane amount of NPCs]

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#5635] opened 2023-05-18 23:07 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

Boy - where do we start...

1. The Quest starts ok with dialogues and everything, but then NPCs begin to spawn at an insane rate, resulting in overwhelming and a wipe.
2. After the wipe you can speak to Colonel and get the quest Completeld???? LOL
3. The Priest also dies and the ritual continues.

### Expected Blizzlike Behaviour

1. NPCs spawn at a slower pace, giving time between spawns, it is practically impossible to even clear adds with AOE.
My druid used innervate and x2 pots, including early shadowmeld lmao.
2.  If priest dies, event SHOULD FAIL...... because you know, there is no NPC to perform the ritual.

### Source

https://www.youtube.com/watch?v=eoknRTJ2MY0 - Take a look at the spawn rate and number of spawns..

On CC you get 3-5 spawns every 2 seconds or so ....

### Steps to reproduce the problem

1. start quest ID 10935 Exorcism of Colonel Jules
2. Observe if 3-5 NPCs spawn instantly at the same time
3. Observe if frequency is super fast (every 2-3 seconds or so)
4. Die and see if you and the PRiest are dead, the quest still completable by clicking on the Colonel.....

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Hogofogo1** [comment] 2023-05-19 21:26
Can confirm
Finished the quest just standing behind a wall and waiting for few minutes.

**Comment by mkirkpatrick** [comment] 2023-05-22 09:51
Can Confirm. Only quest I cannot complete in Hellfire. Just spews a hilarious amount of enemies.

**Comment by The-GhostRider** [comment] 2023-11-07 11:20
I'm closing this report because it's a duplicate of the same issue.
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/f8a44503-7c56-4d91-9a58-3969ccd28141)
I'm closing this report for the benefit of the first one that was opened.
This one: https://github.com/chromiecraft/chromiecraft/issues/4565

**Closed by The-GhostRider** 2023-11-07 11:20 UTC
Labels: Confirmed, Known issue
