### ISSUE TITLE
[Shaman] Totems combat bug

### ISSUE THREAD

**Issue by leandro2000vieira** [chromiecraft/chromiecraft#4681] opened 2022-12-28 03:24 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Totems with tick time will be in combat when "tick  proc" on target in combat.
tremor totem, cleasing totem, healing stream totem and stoneclaw totem (maybe mana tide totem too).

### Expected Blizzlike Behaviour

Totems will never be in combat

### Source

https://youtu.be/I6SGzR8mvzA

### Steps to reproduce the problem

Example with healing stream totem,
1.call healing stream totem, 
2.start combat with one mob or player
3.wait for tick
4.leave combat
Now the totem will be in combat forever

### Extra Notes

because that there are many bugs with combat, imagine when your totems tick one friendly player in combat, etc...

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment] 2023-06-12 10:27
Hi, thanks for the report. I have not been able to reproduce the error. If you want to give me some more details, I will try to test again. Or maybe, the bug has already been fixed and currently this report should close for you. I look forward to more information. Thank you. @leandro2000vieira

**Comment by Salehyn** [comment] 2023-09-18 06:21
I can reproduce this steadily however i lack evidence for how this is supposed to work. Totems entering combat is normal IIRC, they are capable of pulling mobs, attacking them, etc, so it's safe to say they are meant to be in combat when there are enemies engaged.
The problem seems to be that they won't leave combat together with the player upon killing or resetting the enemies. This combat is difficult to transfer back to the player, since the totems are essentially immune to everything, but I can imagine theoretically this could cause problems.

**Comment by FrancescoBorzi** [comment] 2024-11-10 23:05
> I can reproduce this steadily however i lack evidence for how this is supposed to work.

Closing as not enough evidence to proceed with confirming this. If anyone can provide such evidence, feel free to post it here and we will reopen the issue.

**Closed by FrancescoBorzi** 2024-11-10 23:05 UTC
Labels: Needs Triage, Class Issue, WFMD, More Research Needed
