### ISSUE TITLE
Major server side bug with interrupting CASTER MOBS

### ISSUE THREAD

**Issue by Paradigmxd** [chromiecraft/chromiecraft#3144] opened 2022-02-28 16:12 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When shear (shaman spell) used to interrupt various mobs located in different zones (for statistical purposes: Arathi Highlands, Southshore, Duskwood, Dungeons like Weilling caverns) the MOB does not move to you to come to hit.

### Expected Blizzlike Behaviour

ANY interruption on a caster mob will always trigger the mob to run to the user to MELE while the GCD is refreshed.. as we all know from playing Retail for the past years.

### Source

Not sure how to show you this - I suppose I can link gaming videos from WOTLK showing when a caster mob gets interrupted? 

### Steps to reproduce the problem

1. Find a caster mob
2. use interrupt spell
3. Observe whether caster mob executes follow up mechanism to come and hit you in mele range while cooldown wares off.

### Extra Notes

None.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment] 2022-03-13 13:46
Just tested this on the PTR, tested it on casting mobs in Duskwood, Westfall and Wailing Caverns. The spell and mobs seem to behave as expected, There was one instance in Wailing Caverns when mob just stood there on the second Wind Shear and didn't come to me, but the counterspell only lasts for 2 seconds. so I don't think that was an issue, as it came to me on the third Wind Shear cast, as on the first one.

Test video: https://streamable.com/yrzm6i

**Comment by ishidinho** [comment] 2022-03-19 15:07
Hey @Paradigmxd. Since @Dejanos was not able to reproduce the problem, can you please provide some more information? May a video, screenshot or even links in the [WotLK database](https://wowgaming.altervista.org/aowow/) to the affected NPCs.

**Comment by Tereneckla** [comment] 2022-06-21 19:42
Happens everytime I interrupt Thundering Exiles (entry 2762) with counterspell
they stand still for the whole 8 seconds

**Comment by Paradigmxd** [comment] 2022-06-24 14:53
Yes, its a server sided issue to be fair. When you interrupt mobs on ChromieCraft they never walk to you to mele. Much of the interruption in the open world and dungeons is super scuffed, but such is the nature of the core. It reminds me of Sunwell-Wotlk realms before Fall 2021 releases which had same issues in northrend (I can speak more about that since they had super high rates so you passed vanilla and TBC super quick)

**Comment by djobf** [comment] 2023-01-18 01:52
Any chance this gets fixed ? It still happens in current content. Caster mobs in Blood Furnace have this behaviour too (Shadowmoon Warlock, Shadowmoon Summoner). IMO it's an important mechanic that should be focused on if possible

**Comment by Paradigmxd** [comment] 2023-01-18 10:56
Yeah, I also opened another issue, caster mobs are now super broken on Chromiecraft. I dont know why PTR difference and Llive is so great ...... that is crazy stuff

**Comment by Paradigmxd** [comment] 2023-01-18 10:58
> Any chance this gets fixed ? It still happens in current content. Caster mobs in Blood Furnace have this behaviour too (Shadowmoon Warlock, Shadowmoon Summoner). IMO it's an important mechanic that should be focused on, if possible

https://github.com/chromiecraft/chromiecraft/issues/4832 here is my newly discovered bug building on top of the already broken caster NPCs.. this issue has been present on Azerothcore for ages i think, because I have played many servers and they alrways end up fixing this (Reference include; Warmane 2016, Sunwell pl 2018,2019)

**Comment by Salehyn** [comment] 2023-08-27 14:58
https://github.com/azerothcore/azerothcore-wotlk/issues/3740
This is a known issue since 2020.

**Comment by heyitsbench** [comment] 2024-01-13 05:40
I believe this has been resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/8f127f9e2135a70cdb5573d052f50304d1b3875c.

**Comment by avarishd** [comment] 2024-07-03 17:44
It has, in the cases where it "hasn't" it's due to the lack of cast flag 64 in SAI.

**Comment by Nyeriah** [comment] 2024-07-04 11:21
I’ll be closing this in that case as those mobs will need to be reported individually as otherwise this issue will never see an ending

**Closed by Nyeriah** 2024-07-04 11:21 UTC
Labels: Confirmed, Linked [AC], Generic Issues, Known issue
