### ISSUE TITLE
[Quest] Ending Their World

### ISSUE THREAD

**Issue by CyberneticCC** [chromiecraft/chromiecraft#250] opened 2021-03-19 22:25 UTC
##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Quest: [Ending Their World](https://www.wowhead.com/quest=9759/ending-their-world)
Npc_start: [Demolitionist Legoso](https://www.wowhead.com/npc=17982/demolitionist-legoso#starts) [Guid and ID](https://prnt.sc/10qaqm4)
Zone: [Bloodmyst Isle](https://www.wowhead.com/bloodmyst-isle)

I tried this quest a couple times (do not try this at home, not recommended for people with cardiovascular disease). 
The first time I did it I escorted him all the way up at the very end (got lvl 20 along the way from killing bunch elites) and I failed. He died. I died. End credits. ( [So close no matter how faaaar...](https://www.youtube.com/watch?v=x7bIbVlIqEc&ab_channel=YefteArcade) ) So I used the Spirit healer at Vindicator's rest (the starting point of the quest). Hearthstoned to Exodar to train for stronger spells and logged out for a few hours (screw it i'll do it later).
I come back after solid 5-6 hours, go to the place of quest start, he's not there... 
[What?](https://miscmedia-9gag-fun.9cache.com/images/thumbnail-facebook/1557310702.1267_UgysAp_n.jpg)
Searching through google [I find this](http://prntscr.com/10qc1zj) . I kept my friend locked away from other players the entire time... Sorry guys!
I go to the place where we both got killed in cold blood and died painfully (i die once again along the way, fucking rogue elites). I go back to starting point of the quest and he's there. Standing. Watching over the horizon questioning himself where the hell am I.
We both go on an adventure together once again (this time I have stronger spells, we got this!). 

...we don't... 

He dies at the very start again... I let down my traveling companion die painfully cause I'm an amateur learning mage.
As I mourn his death watching his dead body for 5 minutes, he disappears. I go back to starting point of the quest again and wait another 10 minutes. He shows up! Ah the joy and happiness overwhelms me, we're ready for adventure again!
I start the quest again (third time) aaaaaand we both die along the way again.... 
Legoso: "dude wtf?! we almost made it the first time with you being weaker and now we can't even make halfway through?!"
"I know...", I tell him, "Considering the state of affairs that I AM in fact stronger now I keep bringing shame upon my family over and over again... But we must keep trying! For the sake of bugs!" -Legoso: "what bugs?! 1-19 stable remember?!" -"yeah I guess... or maybe the zugzugs are workworking sloppy..." Legoso sighs in disappointment as he tells me: "let's just finish this... I am tired of you already."
As I leave my dead Legoso rotting there I didn't even wait for his despawn of the corpse, I went straight to Vindicator's rest to wait for him. Time goes by. Initial 15 minutes became 20.... then 25... Where is he?! 
So I go to the place of our skeletons chilling on the ground as the flowers kept growing through them. I go back to quest start point and there he is. Waiting for me in disgust once again.

[Judging from this](http://prntscr.com/10qcsx4) it makes it understandable his respawn timer is instant and free of bugs cause it's a long way uphill fighting through all those elites that consume a lot of time. So going all the way back and retaking the quest with a certain free path if you're alone makes it reasonable. I guess.

Another problematic interference that occurs is that his pathing crosses the pathing of Matis the Cruel [the bug which I previously reported](https://github.com/chromiecraft/chromiecraft/issues/241) and keeps attacking him until Matis dies thus screwing the quest progression of other players that are behind. He should either be uninteractable if you don't have quest or his pathing changed to avoid the clash between the two.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Escort Legoso to the top, killing bunch of elites along the way. If he dies (shame on you) he should respawn instantly at the quest starting place. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the traveling companion [Demolitionist Legoso](https://www.wowhead.com/npc=17982/demolitionist-legoso#:~:text=This%20guy%20respawn%20after%200.1sec%20after%20he%20dies.)
2. if you let him die and don't want for his despawn you won't be able to pick up a quest again this locking it away from others.
3. workaround is to go to his place of death and then retake the quest.
4. Legoso... if you read this... I am sorry.

##### EXTRA NOTES:

I apologize for this satire I have started going insane of wasting too much time on this stupid quest.
4th adventure is about to begin. Wish me luck!

Edit: fifth... Fifth adventure...

Edit2: https://ih1.redbubble.net/image.239760373.7193/st,small,507x507-pad,600x600,f8f8f8.u3.jpg

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-03-23 23:04
Duplicate of: https://github.com/chromiecraft/chromiecraft/issues/205
and Fixed.

**Closed by Stifler82** 2021-03-23 23:04 UTC
Labels: Closed, Duplicate, Fixed, Linked Issue
