### ISSUE TITLE
[CoT2] Blackfang Tarantuala damage to high

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5154] opened 2023-03-11 09:07 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

hitting for about 1000 on cloth wearers

### Expected Blizzlike Behaviour

should be around 350 damage

### Source

https://youtu.be/fw_JbjLbB-Q?t=50

there is some armor buff up, but that typically increases the damage reduction from ~8% to 14% only

### Steps to reproduce the problem

.

### Extra Notes

https://www.wowhead.com/wotlk/npc=18983/blackfang-tarantula

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03d47897ece3e0a615aac05222d9fbd98b33717d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment] 2023-09-07 06:45
I tested with this revision dd647da913ef 2023-09-04 and actually an almost naked cloth wearer receive about 400 damage, like shown in the combat log below
![WoWScrnShot_090723_084226](https://github.com/chromiecraft/chromiecraft/assets/82369562/b67d5806-e12e-4e95-ab52-1c6b1334fdf8)

**Comment by balleny** [comment] 2023-09-07 06:55
the issue was already resolved a while ago with a large update to npcs baseline damage cherrypicked from a different project

**Comment by Pyromanihack** [comment] 2023-09-07 07:10
So it's Fixed instead of Unable to Reproduce, my bad, I didn't know this

**Closed** 2024-11-12 22:19 UTC
Labels: Fixed, Closed
