### ISSUE TITLE
Warrior's Charge animation replaced with a "blink"

### ISSUE THREAD

**Issue by kuzaan** [chromiecraft/chromiecraft#6194] opened 2023-09-29 13:52 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Casting Charge after breaking free from root (or maybe charm / sleep, needs testing) cancels Warrior's charge animation and replaces it with a "blink", where the warrior appears instantly at the Charge's destination. 

Here are 3 examples on a good latency: 

https://github.com/chromiecraft/chromiecraft/assets/72312283/ef9ad30a-aec0-490e-965c-a9fd89d678f9

### Expected Blizzlike Behaviour

Charge's animation should not be replaced by a blink under any circumstances. 

### Source

-

### Steps to reproduce the problem

1. As a warrior, get rooted
2. Cast Charge as soon as you break free from root
3. Test with charm / sleep and other similar effects

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cythisiax** [comment] 2024-11-25 01:00
Hello, as of https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e this appears to no longer be an issue. Was unable to replicate this dueling a warrior on PTR, and casting entangling roots. The charge itself, as well as the graphical effect was very visible.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-25 01:01
Tested this with @Cythisiax and we couldn't reproduce the issue, will be closing this.

**Closed by TheSCREWEDSoftware** 2024-11-25 01:01 UTC
Labels: Unable to Reproduce
