### ISSUE TITLE
Karazhan: Nightbane - Event Start / End is Incorrect

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5606] opened 2023-05-15 06:53 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

- [x] Nightbane lands and just stands in the middle of the Balcony without aggroing. 
- [x] Combat only starts once Nightbane is damage, no proximity aggro at all.
- [ ] Doors don't close when the event starts.
- [x] If there is a wipe, Nightbane stays on the balcony
- [ ] If there is a wipe while there are Restless Skeletons alive, they don't despawn.
- [x] If you interact with the Urn again while Nightbane is already up he will fly away and make the Urn not work anymore locking the boss from starting again.

Progress edits by: elthehablo
Additional note: I think the skeleton despawn might work. Not 100% sure anymore

**Edited quick example**
https://youtu.be/F5D6PrbQtFs

**Footage from PTR test run**
https://youtu.be/6Gu8jrJ_TrU?t=3705

### Expected Blizzlike Behaviour

This should work as an event were you use the Blackened Urn to summon Nightbane. He should come flying from the horizon into the balcony, landing and immediately entering combat upon land.

### Source

TBC Classic
https://youtu.be/mVb6CCxBMA8?t=1263
Here they wipe

https://youtu.be/mVb6CCxBMA8?t=1489
Here they restart the event, you can see Nightbane comes flying again

https://wowpedia.fandom.com/wiki/Restless_Skeleton

### Steps to reproduce the problem

1. .tele kara
2. Go to Nightbane (Faster through the back door).
3. Use the Blackened Urn to start the event
4. Wait for Nightbane to aggro or start the event by damaging the boss.
5. Damage the boss to 75% to trigger the Air Phase
6. Wait for Restless Skeletons to be summoned.
7. Kill yourself while Skeletons are up. I used .modify hp 1
8. Watch Nightbane chill on the balcony instead of flying away
9. Watch if the Skeletons despawn.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kerricsson** [comment] 2023-10-28 18:54
Good day, I'll be grateful if devs/cc contributors can have a look at this issue because this fix is needed to fix/tune DBM version for AC. DBM is used by majority of CC raiders (more that 500 players) use on weekly basis. Thank you in advance.

**Comment by alecsci** [comment] 2024-08-26 20:35
✅ Tested and to me seems fixed by now.
- I can confirm that doors close when the event starts.
- The skeletons despawn after wipe

**Closed by alecsci** 2024-08-26 20:35 UTC
Labels: Needs Triage
