### ISSUE TITLE
Goblin and Gnomish engineering accessible at same time

### ISSUE THREAD

**Issue by NidaleeLiadrin** [chromiecraft/chromiecraft#443] opened 2021-04-19 08:41 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

As an engineering  225 you can learn both Goblin and Gnomish engineering at the same .

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only one engineering option should be train-able at the time. having both goblin and gnomish engineering should not be possible.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Take any character with engineering skill +200
2.  You should be able to learn both gnomish and goblin engineering at the same time.

##### EXTRA NOTES:

This is a kind of game-breaking bug that can create advantages and needs confirmation.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-04-19 11:08
Can you elaborate **how** to learn both, since I wasn't even able to learn one of the two although I got the fetch quest for "Goblin Engineering" from UC at level 20 and skill 200 and already had all items crafted that are later needed. I could hand in the quest at Nixx Sprockethead, but he did not offer the followup "The Pledge of Secrecy (3638)"  and therefore also not "Show Your Work (3639)".

Interestingly "The Pledge of Secrecy (3638)" is marked as obsolete with a level requirement of 30 in AC's World DB, but it's the `PrevQuestID` in `quest_template_addon` for "Show Your Work (3639)". To me it looks like the level requirement for quest 3638 shoudl be changed to 20 and the  UNAVAILABLE flag (16384) should be rmoved. 

I'm basing this on https://wowpedia.fandom.com/wiki/The_Pledge_of_Secrecy_(Tanaris)?oldid=2262558 from May 2010 (before cata), but I think the level change (30 -> 20) probably came with patch 3.2.0 which introduced the option to switch between specializations for 150g.

I also found a wowhaed comment which states that Goblin Engineering was available before level 30: https://www.wowhead.com/quest=3638/the-pledge-of-secrecy#comments:id=907253

Note that the fetch quest requirement of level 10 and skill 200 is equivalent to level 20 and skill 200 since you cannot get to skill 200 before level 20.

Similar for Gnomish Engineering, I assume.

**Comment by Azcobu** [comment] 2021-04-19 12:14
Just levelled a character to 30 and 225 engineering and found that even without doing the prereq quests (Goblin Engineering or Gnomish Engineering, both from Graham Van Talen in UC), both the gnomish and goblin trainers will teach you their recipes. You can even learn from one after learning from the other, giving you access to both sets of recipes. Again, this is without doing any pre-requisite quests at all.

To replicate:
1. Level a char to 30 and a minimum of 205 engineering. (I went to 225 as only 2 gnomish recipes are available at 205.)
2. .go c 387 - this gets you to Oglethorpe Obnoticus in Booty Bay, who is the gnomish eng trainer. Learn all his recipes:

![WoWScrnShot_041921_211925](https://user-images.githubusercontent.com/81782124/115233859-90e3b180-a157-11eb-9b1e-3bab5ea77342.jpg)

3. .go c 23414 - this takes you to Nixx Sprocketspring, goblin eng trainer in Gadgetzan. He will also teach you all goblin recipes without any pre-req quests done:

![WoWScrnShot_041921_211857](https://user-images.githubusercontent.com/81782124/115233785-7ad5f100-a157-11eb-8bef-5dfd6b5610ba.jpg)

4. Now you have access to both sets:

![WoWScrnShot_041921_212305](https://user-images.githubusercontent.com/81782124/115233911-a2c55480-a157-11eb-813e-ce31474c6b62.jpg)

This was on AzerothCore rev. b8b5f68f98ff+ 2021-04-19 06:49:48 +0000 (master branch) (Unix, Release)

**Comment by necropola** [comment] 2021-04-19 12:15
Yeah, but on CC nobody can be level 30 yet, right?

**Comment by Azcobu** [comment] 2021-04-19 12:18
I've also tested this with a level 25 character, and it worked for them as well.

**Comment by necropola** [comment] 2021-04-19 13:08
To me it looks like you only learned the Goblin/Gnome Engineering recipes that are taught by the Goblin/Gnome Engineering trainers but **do not require to actually be a Goblin/Gnomish Engineer**.
What does your spell book (General Tab) say? Are you a Goblin/Gnome Engineer?

**Comment by necropola** [comment] 2021-04-19 18:22
The membership cards have been removed during WotLK.
https://wowpedia.fandom.com/wiki/Goblin_Engineer_Membership_Card
I'm pretty sure that since then the Goblin/Gnome Engineering Trainers worked very similar to Weapon and Armorsmith trainers, i. e. you could access/llearn some of the recipes without having the/any specialization and some not.

**Comment by Azcobu** [comment] 2021-04-20 12:46
Well, at the moment you can access and craft all of them without any specialization or pre-requisite quests at all. And if you go through the full chain and actually get a specialization, nothing changes on either of the trainers. They both show the exact same recipes before learning one spec as afterwards, no matter which you pick.

To test this, I made three characters with 300 eng (to catch as many recipes as possible). One was Goblin eng, one was Gnomish eng, and one was neither. Then I visited each of the trainers and counted how many recipes each was teaching. 

For both goblin and gnomish trainers, the recipes they taught were identical no matter what specialization I had, and identical to no specialization at all. In other words, specializing doesn't unlock any new recipes or do anything at all that I could tell. I thought it might affect crafting (i.e. you could learn opposite recipes but not make them) but it turned out my goblin engi could craft gnomish recipes too.

It seems clear that the two trainers are simply not checking for quest completion of their respective quests, and are giving out recipes when they shouldn't. Wowpedia specifically says "Gnome Engineering items require specialization in Gnome Engineering to craft" (https://wowpedia.fandom.com/wiki/Gnome_Engineering?oldid=2299320) which is not the case on CC right now.

**Comment by necropola** [comment] 2021-04-20 13:15
Which would mean you can learna and craft all specialization recipes and use the created item reagardless of whether you have the/any engineering specialization? Correct?
This would make bekoming a Gioblin or Gnome engineer completly useless.

**Comment by Azcobu** [comment] 2021-04-20 13:20
Yep, exactly.

**Comment by necropola** [comment] 2021-04-20 18:41
While I agree that the engineering specializations are pretty much useless, I do not agree that the cause is a bug in AzerothCore. I'm leaning more towards "Blizzard made it useless in WotLK".

I found exactly one recipe <= skill 300 that actually requires "Goblin Engineering" and that is the "Dimensional Ripper - Everlook"  which I could only learn because I **became** a "Goblin Engineerr". The equivalent is the "Ultrasafe Transporter - Gadgetzan" which only a "Gnome Engineer" can learn (I couldn't).

Then there are one transporter each in Outlands that require specialization and four recipes each (I only checked Goblin) at Engineering >= 350 that actually require specialization. That's it.

The only bug that I found is that the "Pledge of Secrecy" quests require level 30 instead of 20 (see above).

**Comment by Azcobu** [comment] 2021-04-21 10:15
>  I'm leaning more towards "Blizzard made it useless in WotLK (or maybe already in TBC)".

But this is directly contradicted by WotLK sources. Wowpedia, in an entry dated as close to 3.3.5 as we can get, specifically says:

"Gnome Engineering items require specialization in Gnome Engineering to craft" - and then lists all the schematics given by the gnome trainer, not just a few transporters. (https://wowpedia.fandom.com/wiki/Gnome_Engineering?oldid=2299320)

https://wowpedia.fandom.com/wiki/Gnome_engineering_schematics - "A type of schematic that requires skill within Gnome Engineering proficiency."

https://wowwiki-archive.fandom.com/wiki/Engineering_recipes#Gnome_engineering - "These schematics require specialization in Gnome Engineering to learn."

The Goblin Engineering pages say the same thing. You could use the other spec's items if they were BoE, but you couldn't learn the recipes for it. Note that none of these pages list just the transporter recipes - they list all recipes taught by the two trainers and clearly state they are restricted to that specialization only. I think this clearly shows that the current situation on Chromie is not how the 'real' Wrath-era Wow worked.

If you disagree, I would ask you to show a WotLK source of some kind - a wiki page, a guide, whatever - where it says that all of these recipes, both goblin and gnome, could be learned and crafted by one engineer without regard to specialization. Because so far, I haven't found any sources for WotLK that say anything other than "specializations were separate and meaningful." (or as meaningful as vanilla content could be in Wrath, anyway.)

There are other trainers that do work properly, as you pointed out - the ones selling transporters. What I'm saying is that the transporter trainers are how the others should work as well - and the links and evidence above show that historically, that's how they did.

**Comment by mdawx** [comment] 2021-04-21 11:02
Thanks @Azcobu and @necropola, let me now if i extracted all important notes from your discussion.

**Comment by Azcobu** [comment] 2021-04-21 11:26
Thanks @mdawx, looks good. I'm sure anyone who wants more details can refer back here.

**Comment by necropola** [comment] 2021-04-21 11:45
@Azcobu I agree with you 100% that it woudl be better and probably also more blizz-like, if becoming a Goblin/Gnome Engineer would have some meaning.

Currently on AC/CC the specialized trainers teach all recipes regardless of whether you are specialized or not. Only the transporter devices which are taught by different NPCs actually require you to be specialized to **learn** them. I haven't ckecked whether there are dropped recipes that should require a specialization to learn, too.

I also went through the history on Wowpedia to figure out how it actually was at the end of WotLK (3.3.5a) and found inconsistencies there, too. E. g. The level requirement for Gnome Engineering is listed as 20 (correct) and for Goblin Engineering as 30 (wrong). I also went though pages and pages of officiall and undocumented patch notes, but could not find definitive answers to some of these open questions. It's a mess.

I also don't think that the best way to fix this is to limit access to the specialized trainers. The recipes they teach (and the recipes that may drop) should have an explicit specilization requirement to be learnable.  I think I was able to learn a few of the Goblin recipes without being specialized on retail, but I don't remember which. And we all know what they say about memory ... 😸

Summary:
* It's not true that you can actually **become** a Gnome and a Goblin Engineer at the same time on AC/CC (no bug here)
 * The level requirement for actually learning the specialization should be 20 and not 30 (bug)
 * At least some of the recipes being taught or being dropped should have an explicit Gnome or Goblin engineering skill requirement (bug)

**Comment by Azcobu** [comment] 2021-04-21 13:17
Thanks for the overview from your perspective. I do agree with a fair bit of what you say here - certainly, finding correct information about a decade-old game is not easy. We'll only get definitive answers when Blizz releases Classic Wrath and we can just copy everything from Wowhead...

I like your suggestion about checking the other crafting professions with specializations too. Engineering may have been the first profession encountered on CC that had some specialization issues, but as we move up the level brackets, it probably won't be the last.

**Comment by apav** [comment] 2021-04-23 15:42
I do not remember the behavior in retail WotLK, so I decided to check how it is on DalaranWoW (another WotLK private server). After learning Gnomish Engineering I'm still able to learn from the Goblin Engineering trainer.

![1](https://user-images.githubusercontent.com/8137930/115894383-33858400-a427-11eb-812a-213e611b446b.png)
![2](https://user-images.githubusercontent.com/8137930/115894387-34b6b100-a427-11eb-85c6-5308c0d9292d.png)

I don't think this is a bug with TrinityCore because in this list there are some that require Goblin Engineering in the tooltip, and some that do not. 

Requires Goblin Engineering on DalaranWoW:
![3](https://user-images.githubusercontent.com/8137930/115895129-13a29000-a428-11eb-84ab-a390fcdc7d2a.png)

Does not require Goblin Engineering on DalaranWoW:
![4](https://user-images.githubusercontent.com/8137930/115895185-21581580-a428-11eb-973e-afc52503aeb7.png)

[TBCDB](https://tbcdb.com/?item=23827) also lists Super Sapper Charge as not having a Goblin Engineering requirement, which isn't based off TrinityCore.

These items are the same on ChromieCraft as they are in DalaranWoW.

Requires Goblin Engineering on ChromieCraft:
![5](https://user-images.githubusercontent.com/8137930/115896006-0043f480-a429-11eb-824d-b9c82366118e.png)

Does not require Goblin Engineering on ChromieCraft:
![6](https://user-images.githubusercontent.com/8137930/115896025-033ee500-a429-11eb-8759-689b522ea017.png)

**Closed** 2021-12-16 10:18 UTC
Labels: Confirmed, Linked [AC], Generic Issues
