### ISSUE TITLE
Quest: Nolkai's Word -  Quest completion does not reward Nolka's Box as intended

### ISSUE THREAD

**Issue by CMHWoody** [chromiecraft/chromiecraft#2480] opened 2021-12-05 07:30 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

When completing Nolkai's Word by clicking on the dirt mound the quest text says that you find an old box, however, all you receive is experience.

### Expected Blizzlike Behaviour

Based on the quest text, I would expect to have received a box, which is what made me go research. However, I find conflicting information, where some sites show no box, while at least two sites show it should reward:

https://tbc.wowhead.com/?item=23846

I would note that the above site is a burning crusade version of wowhead, so perhaps the box reward was removed later, which doesn't make a lot of sense, given the quest text. 

wowpedia.fandom.com/wiki/Nolkai%27s_Words also shows that it should reward the box which is probably retail information.  So that suggests that the box was rewarded, then not for a while and then maybe added (fixed?) again later.  It's hard to tell. 

### Steps to reproduce the problem

It is a lengthy series to get to this quest:

Progression
A [1-30] Explorers' League, Is That Something for Gnomes?
introduces you to Clopper Wizbang, who gives you both of the following:
A [1-30] Pilfered Equipment
A [1-30] Artifacts of the Blacksilt
Completing Artifacts of the Blacksilt earns you a [Weathered Treasure Map], which starts you off on the following quest chain.

A [1-30] A Map to Where?
A [1-30] Deciphering the Book
A [1-30] Nolkai's Words

To duplicate, pick up Nolkia's Words from Anchorite Paethus, travel to the dirt mound at 61.3, 49.6, click on the mound to complete quest.

### Extra Notes

Related links:
https://wowpedia.fandom.com/wiki/Nolkai%27s_Words
https://wowpedia.fandom.com/wiki/Nolkai%27s_Box
https://tbc.wowhead.com/quest=9561/nolkais-words

The above indicate the box should be rewarded, along with 250 Darnassus rep

This site seem to show there is only xp and no box nor rep:

https://wotlkdb.com/?quest=9561

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-05 11:48
Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear.
![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

![WoWScrnShot_120521_144701](https://user-images.githubusercontent.com/85256266/144745245-f1e9c415-3383-40cd-84c0-ffd306057cfc.jpg)

**Comment by Shineslippers** [comment] 2021-12-15 12:48
Should work after with last update.
![Capture](https://user-images.githubusercontent.com/85256266/146189217-fe57fd0e-0732-4b54-be30-acd18babd99d.PNG)

**Closed by Shineslippers** 2021-12-15 12:48 UTC
Labels: Closed, Known issue
