### ISSUE TITLE
[Ashenvale] Close Ore Spawns

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1319] opened 2021-07-31 15:48 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Copper ore spawning too close to each other in Ashenvale.
Number 1
![WoWScrnShot_073121_114243](https://user-images.githubusercontent.com/5192790/127745256-fba8b413-ecb9-4a89-8ba4-1c452973218e.jpg)
Number 2
![WoWScrnShot_073121_115854](https://user-images.githubusercontent.com/5192790/127745566-d7437961-3392-4b83-9feb-21f4be0684fa.jpg)

Number 3
![WoWScrnShot_073121_120226](https://user-images.githubusercontent.com/5192790/127745720-67ce4264-a8a1-459e-92ab-e23cfbf5d09d.jpg)

Number 4 -- May not constitute "too close"
![image](https://user-images.githubusercontent.com/5192790/127745734-b96b5e8a-0e4b-42a1-a028-1f17d2a36024.png)

Number 5
![WoWScrnShot_073121_120720](https://user-images.githubusercontent.com/5192790/127745800-90034b26-2d09-4234-9ffd-b74a36d094de.jpg)

Number 6
![WoWScrnShot_073121_121559](https://user-images.githubusercontent.com/5192790/127745980-6abb813e-feef-4ca8-8d0f-eb6d1b16580a.jpg)

Number 7
![WoWScrnShot_073121_122252](https://user-images.githubusercontent.com/5192790/127746163-d2884e9c-013e-4b6c-bb50-8a81b2a7a4db.jpg)

Number 8
![WoWScrnShot_073121_122451](https://user-images.githubusercontent.com/5192790/127746199-d7052968-2098-4cd1-9499-64aea4ad5174.jpg)

Number 9
![image](https://user-images.githubusercontent.com/5192790/127746326-f402050b-8c3b-4e70-a799-10d3b5ea5ff5.png)

Number 10
![WoWScrnShot_073121_130811](https://user-images.githubusercontent.com/5192790/127747369-c67090f6-1673-4bd3-b51b-acba9978757c.jpg)

Number 11
![WoWScrnShot_073121_131011](https://user-images.githubusercontent.com/5192790/127747420-d6615999-271e-4005-8718-f485c169605b.jpg)

### Expected Blizzlike Behaviour

Ore shouldn't spawn this close together. 

### Steps to reproduce the problem

1. Turn Find Minerals on and run around
2. Teleport to the GUID

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Server

ChromieCraft

**Comment by Asipdk** [comment] 2021-07-31 16:06
Edits: Added 3 more nodes while exploring the zone so far.

**Comment by gurveleg** [comment] 2021-07-31 18:11
Many of them are a duplicate of #252 

Its a known issue with abundance of ore spawns across the majority of the zones because they are not pooled yet.

**Comment by Azcobu** [comment] 2021-08-02 12:47
Thanks for the report. Of the 11, 7 had been previously reported in https://github.com/chromiecraft/chromiecraft/issues/252, and I discarded numbers 4 and 10 because they seemed tolerable, if not ideal. That leaves two others, numbers 2 and 11, which I have reported. As gurveleg says, this is mostly due to the pooling system not being fully implemented in Ashenvale yet.

**Comment by heyitsbench** [comment] 2024-06-20 03:05
Almost certainly resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/25797238026ca87a9a3906add11ebfc9cc9802d4.

**Closed by heyitsbench** 2024-06-20 03:05 UTC
Labels: Confirmed, Linked [AC], [20 - 29]
