### ISSUE TITLE
[Zul'Farrak] when opening a grave in the zombies area with a full inventory, the zombies will infinitly keep spawning every time you click the grave

### ISSUE THREAD

**Issue by Spookyia** [chromiecraft/chromiecraft#7005] opened 2024-04-17 00:42 UTC

**Comment by heyitsbench** [comment] 2024-04-17 02:33
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/3816 as well as unfilled issue template.

**Closed by heyitsbench** 2024-04-17 02:33 UTC
Labels: Needs Triage
