### ISSUE TITLE
Quest: "Becoming a Spellfire Tailor" - Item Nether-wraith Beacon does not work in Netherstorm

### ISSUE THREAD

**Issue by Pille95** [chromiecraft/chromiecraft#7390] opened 2024-10-02 00:26 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The Quest "Becoming a Spellfire Tailor" seems bugged. The item "Nether-wraith Beacon" does not work in Netherstorm.
When i use the item anywhere in Netherstorm or in Area 52 as most guides suggest, it just shows the error message "You need to be in Azure Dragonshrine".
The Azure Dragonshrine is in Northend iirc.

### Expected Blizzlike Behaviour

I should be able to use the item in Area 52 to finish the quest.

### Source

![Screenshot 2024-10-02 022220](https://github.com/user-attachments/assets/e42c676f-4099-43c7-b9ec-169888e09112)

### Steps to reproduce the problem

1. Get lvl 70
2. Get Tailoring to lvl 350
3. Accept the Quest "Becoming a Spellfire Tailor" from Gidge Spellweaver in Shattrath City
4. Fly to Netherstorm Area 52
5. Try to use the item "Nether-wraith Beacon" you got for the quest

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment] 2024-10-02 13:52
Quoting the text: "_Bring a sample of Nether-wraith Essence to Gidge Spellweaver in Shattrath's Lower City._"

Working as Intended in AC and CC.

**Comment by heyitsbench** [comment] 2024-10-02 13:56
This definitely seems to be something wrong either with your client's cache or with a patch on your client, either way I cannot reproduce the issue, same as TheSCREWEDSoftware. Closing as such.

**Closed by heyitsbench** 2024-10-02 13:56 UTC
Labels: Closed, Unable to Reproduce
