### ISSUE TITLE
Shaman Class Quest Elementals Visible To All Classes (And Without Quest Item Consumable)

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#6128] opened 2023-09-08 18:21 UTC
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Currently the earth elementals corresponding to the shaman beginner area quests are visible to all classes and the shaman without having to drink the quest item. This bug occurs in both the orc starting areas and the tauren from what I've seen and have reason to assume it is the same in Draenei if it is a similar quest template.

### Expected Blizzlike Behaviour

Elementals should only appear to the shaman after drinking the quest item given as part of the shaman class quest for the earth totem. 

### Source

![Screenshot from 2023-09-07 15-26-10](https://github.com/chromiecraft/chromiecraft/assets/143937215/28cee92f-dc7d-4323-9258-ff635eb4667f)

### Steps to reproduce the problem

Go to the earth elementals location in either starter area for tauren or orc and see for yourself. (May be the same for draenei).

### Extra Notes

In the attached source picture I am playing a druid and can see the earth elementals.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment] 2023-10-13 10:10
duplicate of https://github.com/chromiecraft/chromiecraft/issues/2111

**Closed by avarishd** 2023-10-13 10:10 UTC
Labels: Needs Triage
