### ISSUE TITLE
Fire Breath and Energy Flux still do too much damage.

### ISSUE THREAD

**Issue by krutoj87** [chromiecraft/chromiecraft#7278] opened 2024-08-15 16:41 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

This is related to this issue I opened earlier.
[https://github.com/chromiecraft/chromiecraft/issues/7263](url)
It seems the fix for this issue has been implemented on Chromiecraft, so I tested it on the server and it didn't seem to have worked for "Fire Breath" an "Energy Flux".
![Fire Breath](https://github.com/user-attachments/assets/8695df3e-3b9b-41ae-a4d7-3b25a83ab617)
![EnergyFlux](https://github.com/user-attachments/assets/68e43e18-a713-4eea-bda1-3ca94d41645b)
Fire Breath still does 3k per tick and Energy Flux ticks with 5k.

In the other issue I wrote, the Wyrmcult Acolytes do the Fire Ball. That was incorrect. It's the Wyrmcult Zealots and the Wyrmcult Scouts. I tested it on Chromiecraft and both of them actually do the Fire Ball there.
https://www.wowhead.com/wotlk/npc=21637/wyrmcult-scout#abilities
https://www.wowhead.com/wotlk/npc=21382/wyrmcult-zealot

The change seem to have worked for the Fire Ball though, because it only does between 1-2k damage now. 

The Fire Breath and Energy Flux still aren't working correctly though. That's why I opened this issue.

### Expected Blizzlike Behaviour

I am not sure how much damage they are supposed to do per tick, but 3k and 5k is ridiculously high. Maybe they are supposed to do like 2-3k if they completely tick to the end. But I am not sure and don't know how to find out.

### Source

https://www.wowhead.com/wotlk/npc=20458/ethereum-archon#abilities

https://www.wowhead.com/wotlk/npc=20502/eclipsion-dragonhawk#abilities;mode:n10

### Steps to reproduce the problem

1. Fight Eclipsion Dragon Hawk
2.  Wait for him to do his Dragon Breath
3.  Look at the Combat Log

1. Fight Ethereum Archon
2. Damage him enough to start Nether Flux
3. Look at Combat Log

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-08-15 17:34
The fix has not been implemented yet. Please check back next week or after a restart if it happens sooner, I apologize for the issue staying as long as it has.

**Comment by heyitsbench** [comment] 2024-08-17 23:24
Tested on live realm, the issue is fixed. Closing as a duplicate of https://github.com/chromiecraft/chromiecraft/issues/7263.

**Closed by heyitsbench** 2024-08-17 23:24 UTC
Labels: Confirmed, Pending Update
