### ISSUE TITLE
Normal Botanica not giving rep past 5999 friendly

### ISSUE THREAD

**Issue by Xallog** [chromiecraft/chromiecraft#6047] opened 2023-08-16 12:58 UTC
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

I joined Botanica normal via RDF, was clearing everything as normal and I was close to hitting honored, we killed last boss and I got 72 rep instead of the usual 125 from killing a boss, this put me at 5999/6000 instead of simply hitting honored. 2nd to last boss in Botanica gave usual amount of rep.

### Expected Blizzlike Behaviour

Tempest Keep dungeons (normal and heroic) should give rep until Exalted

### Source

https://imgur.com/a/q4QNrw6 (first picture is Laj, second picture is last boss)
https://www.wowhead.com/tbc/guide/the-shatar-reputation-rewards-burning-crusade-classic-wow 

### Steps to reproduce the problem

Make a character and grant it 5999/6000 rep with sha'tar, kill a mob (unsure if it's just bosses or mobs that don't give rep past friendly) or boss, check rep.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment] 2023-08-18 13:21
likely an addon / user interface issue. IIRC there was also no adjustment to shatar reputation and normal dungeons to not go past certain reputation level for the purpose of progression, so an issue seems unlikely

**Comment by cachocarne** [comment] 2023-08-20 09:47
https://wowpedia.fandom.com/wiki/Sha%27tar#Reputation
![ 2023-08-20 a las 12 47 10](https://github.com/chromiecraft/chromiecraft/assets/77953030/458f377b-9399-4e59-a3e7-ff84397ea8c9)

**Comment by Salehyn** [comment] 2023-08-21 03:03
Cannot reproduce issue, mobs properly give rep at 5999/6000 inside Botanica. 
This seems to be some one time glitch specific to your character which was resolved by relogging.

**Closed** 2023-08-21 06:35 UTC
Labels: Unable to Reproduce
