### ISSUE TITLE
Hunter's mend pet ability removes aggro from hunter

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#761] opened 2021-06-02 07:52 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hunter's mend pet ability removes aggro from hunter

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mend pet should increase aggro towards hunter

##### STEPS TO REPRODUCE THE PROBLEM:

1. Turn off all active ability on pet including growl
2. Use Mend pet
3. Engage in combat
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jinmcx** [comment] 2021-06-02 07:53
![WoWScrnShot_060221_014501](https://user-images.githubusercontent.com/19652090/120444876-4b64f780-c345-11eb-813c-0cf2d14ac6c2.jpg)

**Comment by madexr12** [comment] 2021-06-02 11:55
This problem doesn't occur on Feoricty pets for me. On other pets it does

**Comment by rdallastra** [comment] 2021-06-29 23:54
The Mend Pet skill does not actually remove aggro from hunter, it just generates a huge amount of threat. Take a look at the amount of threat generated by my pet (with Mend Pet ticking) and my hunter:

![Threat meter](https://user-images.githubusercontent.com/45319286/123880845-7c6b2480-d911-11eb-832a-8f3e13d06ae2.jpg)

The Mend Pet ability generated 50x more threat than my hunter with auto-attack and arcane shot. The pet used is a bear (Tenacity) with BM [talent tree](https://wotlkdb.com/?talent#ctbMzxtRV:fZz), and pet [talent tree](https://wotlkdb.com/?petcalc#0Rd0b). Please note I'm using the mend pet minor glyph as per the talent tree, could be related to that.

**Comment by necropola** [comment] 2021-07-25 04:22
Duplicate of #532

**Closed** 2021-08-04 14:56 UTC
Labels: Confirmed, Linked [AC]
