### ISSUE TITLE
[Paladin] Divine Purpose

### ISSUE THREAD

**Issue by mussy44** [chromiecraft/chromiecraft#7367] opened 2024-09-18 20:24 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

divine purpose sometimes fails to remove stuns

### Expected Blizzlike Behaviour

divine purpose when fully talented should have a 100% chance to remove stuns

### Source

https://www.wowhead.com/wotlk/spell=31872/divine-purpose

### Steps to reproduce the problem

1. make a paladin
2. put 2 talent points in divine purpose
3. godhealth yourself and go to kazrogal
4. cast hand of freedom on yourself after he stuns you and see if the stun consistently gets removed

### Extra Notes

N/A

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment] 2024-09-21 18:18
Can confirm this behaviour not exclusive to the boss, some npcs stun and "stun" for some reason. and when i quote "stun" says you're stunned but than isn't a normal stun.

**Comment by armchairrockstar1** [comment] 2024-09-27 05:59
I sometimes had to press Hand of Freedom twice or thrice to remove some of the PvP stuns in battlegrounds. This might be related.

**Comment by armchairrockstar1** [comment] 2024-11-08 13:16
This bug needs attention.

**Comment by armchairrockstar1** [comment] 2024-11-16 06:32
@TheSCREWEDSoftware Why was this labeled "Waiting for more feedback". I think enough feedback is already given and OP provided a way to reproduce the bug easily.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-16 07:05
Because I need more feedback. There's a source that leads to the ability description, and sure the Boss stuns you and you can't remove the stun. But it's a boss, wouldn't be suprised at all that his stun woudn't be removable, even if a talent says so. Or could be the boss itself that using the wrong stomp ability as another example.

Everytime abiliy and item description has to taken a grain of salt when reading them. 

@heyitsbench do you have any sniff of NPC `17888` casting `31480` or `40936`?

**Comment by armchairrockstar1** [comment] 2024-11-19 10:54
@TheSCREWEDSoftware if you read OP carefully, it says "divine purpose SOMETIMES fails to remove stuns". This means this talent is usually working as intended but (sometimes) it takes 2 or 3 pushes of the button to work. The ability should always fire on first press. This is especially important in PvP because paladins are losing precious seconds in stuns. It doesn't matter which stun you're testing it with. You can try it on the aforementioned boss or use a rogue to cheap shot you or a druid to pounce etc.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-19 11:52
Refering to the boss using or not the correct ability, it has to do as that's the testing conditions / steps to reproduce given by the author. Also being a boss, once again i don't know at which extend, it's removalble or not.

And I just tested on a fresh version of AC and CC PTR, the only missing here would be a CC Live testing, which I can't do because i dont have any Paladin or Mage (even if i did) at enough level to have the abilites and talents used for the same testing. Nor do I've GM permissions for such testing in Live. I do Triaging so it means testing this in AC than CC PTR, and having someone from the staff reflect that test in Live if it doesn't happen in either AC or CC.

The test performed was everyone with PVP enabled, 1 Horde Mage (with all talents, including Deep Freeze learnt), 1 Alliance Warrior (with and without talents) and 1 Alliance Paladin (with all talents, including Divine Purpose learnt). I wasn't able to replicate the issue related of divine purpose NOT removing stuns. Always removed the stuns (including the ones the image below) From the target (friendly) or myself

But at the same this issue could be EXCLUSIVE to CC Live, which I personally can't test. And I will leave this post for the staff to look at it when they can. 

And at the same time, I've done this test, I wasn't able to test the boss issue. Which was the report method to reproduce the issue.

I tried all the crossed options in AC

![image](https://github.com/user-attachments/assets/0cdd9b8d-ef7a-4d6f-b08f-3b30a308bc58)

**Comment by armchairrockstar1** [comment] 2024-11-19 13:26
I was curious so I went to Quartermaster Zigris in LBRS who has a 5 sec stun to test it out on PTR. I had the same results as you, it reliably removed the stun ALL the time so it works well on PTR. I previously commented because I had this issue happen on live servers in bgs. But I'm not so sure anymore. Maybe I was silenced during those times or my skills were on global cooldown. I might try to find a rogue on live server to test there as well. Anyway, thank you for your work.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-20 11:15
Tested the issue related to the boss stunning and not being removed in AC and CC PTR couldn't achieve the issue reported, I will report to the staff to test this in the Live Server.

Steps to reproduce: 

- Make a paladin
- Select yourself `.level 79`
- `.learn all my class`
- `.tele hyjalsummit`
- Get inside of the Raid
- `.instance setbossstate 0 3`
- `.instance setbossstate 1 3`
- `.go xyz 5462 -2729 1485 534 2.6`
- `.cheat god` (`.cheat cooldown`, `.cheat power` and Select yourself `.modify speed all 5`, are optional, tho recommended)
- Talk to thrall and do all the waves.
- Wait for Kazrogal to do his stun
- Use `Hand of Freedom`
- And if working as intended, you should not be stunned (issue states you can't remove it)

**Comment by Nyeriah** [comment] 2024-11-20 13:54
I've reliably removed Kazrogal stun over 30 times on the live server as requested

**Comment by TheSCREWEDSoftware** [comment] 2024-11-20 14:02
Closing this after the both issues refered in this issue weren't able to be reproduced in AC, CC PTR or CC Live

**Closed by TheSCREWEDSoftware** 2024-11-20 14:02 UTC
Labels: Unable to Reproduce
