### ISSUE TITLE
AQ20 - General Rajaxx Kaldorei Elites are Neutral 

### ISSUE THREAD

**Issue by NoodlestheNoble** [chromiecraft/chromiecraft#4006] opened 2022-08-28 16:24 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

The Kalorei Elites are Neutral and therefor consecration from a paladin or other class cleaves will kill them.

### Expected Blizzlike Behaviour

They should, as far as recall, be friendly targets and therefor not attackable

### Source

Didn't manage to take and Screenshots before they died, if you need them let me know I will get them during my next raid lock out!

### Steps to reproduce the problem

Start the fight for Rajaxx and the Elites comes with yellow names and die very quickly to any aoe/cleave from the raid

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment] 2022-08-28 18:09
Hey NoodlestheNobel! I can confirm! 
Looks like its only for Alliance. I tried with both factions on PTR, both neutral with Cenarion Circle.

https://user-images.githubusercontent.com/103856689/187087838-057b1340-c5e0-4c1f-adbc-e1ab34378277.mp4

![image](https://user-images.githubusercontent.com/103856689/187087945-95dda4f4-0ec3-4552-9551-832c3c07532c.png)


Note: For the Horde character, [Andorov](https://classic.wowhead.com/npc=15471/lieutenant-general-andorov) and the[ Elite's](https://classic.wowhead.com/npc=15473/kaldorei-elite) show as friendly even though  neutral with Cencarion Circle. 
For the Alliance character only Andorov show as friendly when reaching Friendly reputation with Cenarion Circle.

**Comment by Maelthyrr** [comment] 2022-08-29 17:40
I will close this issue. Same answers than this: https://github.com/chromiecraft/chromiecraft/issues/3987
Was sniffed on ptr classic. You can kill them because at begin you don't the rep to be frienbdly. It's the classic behavior.

**Comment by Maelthyrr** [comment] 2022-08-29 19:04
Reopen. I'm sorry, I didn't read the extra with the horse faction. Only this part is a bug.

**Closed** 2022-09-03 08:12 UTC
Labels: Confirmed, Linked [AC]
