### ISSUE TITLE
Debuff maintained after you left the BG

### ISSUE THREAD

**Issue by Cromisaid** [chromiecraft/chromiecraft#265] opened 2021-03-20 18:21 UTC
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

 After you leave a Battleground, if you have some debuffs on you, these will be maintained and that is very annoying!
 (watch the video and the picture)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After leaving a Battleground  you should not have Debuffs or Dots on your toon.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join Battleground
2. Let someone dots you or get a generic debuff 
3. Wait until the end of the battleground (be sure to have dots or debuff on you)
4. Leave Battleground
5. Check your debuffs

##### EXTRA NOTES:

Type here.

**Link to the video:**
[Snared after BG due to Debuff of Flag Bearer](https://youtu.be/AP56qjdzbzg)

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mturca** [comment] 2021-03-20 19:31
Also this applies for the Flag carrier debuff (100% dmg taken and cannot move faster than 100% movement speed)

**Comment by AbraKabastard** [comment] 2021-03-22 14:08
Taken from Discord

> Well, I'm curious because this isn't the only bug related to a BG finishing. If you're a ghost and it ends, you get ported out alive but you can walk on water (like ghost SPOOKY) and if you're a druid in a shapeshift form you become permanently stuck in that form (despite your client showing you're not in that form)
> 
> There's a big issue with aura cleanup on remove from BG. I started looking at the code but I couldn't see what the frig was happening!
> https://github.com/chromiecraft/chromiecraft/issues/265
> https://github.com/chromiecraft/chromiecraft/issues/60
> https://github.com/chromiecraft/chromiecraft/issues/179
> https://github.com/chromiecraft/chromiecraft/issues/178

**Comment by Stifler82** [comment] 2021-03-24 01:46
Closed
-
Duplicate of: https://github.com/chromiecraft/chromiecraft/issues/179

**Closed by Stifler82** 2021-03-24 01:46 UTC
Labels: Closed, Confirmed, Duplicate, Generic Issues, Known issue, Linked Issue, PvP
