### ISSUE TITLE
[Orgrimar] Troll Roof Stalker attacks not logged in combat log

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#952] opened 2021-06-21 15:49 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I was hanging out in Orgrimar as a couple of human ladies, on my way to the bonfire, and the Troll Roof Stalker killed both my characters, and no attacks were logged in the combat log.
After ghost walking and rezzing, I was again killed and the damage done was still not logged.

![WoWScrnShot_062121_174317](https://user-images.githubusercontent.com/81818678/122791192-50202a00-d2b9-11eb-83d7-f710b08af95a.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All damage taken should be recorded in the combat log.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Orgrimar as an Alliance character.
2. Go on top of the house/hut of the tauren lady NPC selling ammo, near the AH (left side of the AH when coming from the bank).
3. Die (rip).
4. Look at your combat log.

##### EXTRA NOTES:

I'll try to reproduce on a local AC core later and record it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment] 2021-06-21 17:09
It seems to be working correctly on my local AC server. The attacks are correctly recorded.
Could a GM try this on the live ChromieCraft server?

**Comment by Azcobu** [comment] 2021-06-22 14:10
Confirming the attacks are logged on an AC server.

**Comment by Eldarix** [comment] 2021-06-24 09:48
![WoWScrnShot_062421_124704](https://user-images.githubusercontent.com/82579073/123242078-58ab7700-d4ea-11eb-9793-75f1276f7daf.jpg)

I think after 3 confirmations we can safely close this, thanks for the report likewise pal.

**Comment by eTzmNcbkrng** [comment] 2021-06-27 11:39
I can reproduce this on the ChromieCraft PTR server, in addition the NPCs are not dropping stealth when they enter combat so you can't see what's hitting you.
Still needs investigation though.

**Comment by Stump876** [comment] 2021-08-28 22:14
Has this been resolved? I'm just looking at some of the older reports with the `Needs Triage` tag.

**Comment by gurveleg** [comment] 2021-09-09 15:52
No, it was not. I tested on Local AC. If you aggro the troll and are near him, you will see him stealthed, but will log the attacks, the dmg etc. If you move away a bit so you lose the sight on him, he turns invisble/stealthed and the log does not log attacks, only dazes that you get.

https://user-images.githubusercontent.com/80769357/132719644-dbf1e925-761a-4426-811a-43cf964dbd75.mp4


https://user-images.githubusercontent.com/80769357/132719675-273ca4b8-cf58-430e-8d1f-397274a7bc99.mp4

**Comment by temperrr** [comment] 2021-09-12 08:38
Yea I cant  find if he should drop stealth or not. (as if he drops stealth it shows in combat logs)

**Comment by gurveleg** [comment] 2021-09-13 09:58
https://tbc.wowhead.com/npc=23090/troll-roof-stalker#abilities
Also comments don't say they go out of stealth, and the ability stealth they have says Puts the caster in stealth mode. Lasts until cancelled. I'm pretty sure its working as intended and we can close this.

**Comment by temperrr** [comment] 2021-09-23 09:34
Well, Ashenvale Outrunners also are not coming out of stealth when shooting (and not showing combat logs when they are shooting in stealth), which is wrong. Can we agree that the roof stalkers should follow the same principle

**Comment by gurveleg** [comment] 2021-09-30 09:22
Hm, good point. The damage should be logged regardless if you see them or not.

**Closed** 2021-11-07 19:41 UTC
Labels: Confirmed, Linked [AC], Generic Issues
