### ISSUE TITLE
[Warrior] Juggernaut doesn't stack with Recklesness

### ISSUE THREAD

**Issue by Hogofogo1** [chromiecraft/chromiecraft#5625] opened 2023-05-16 12:21 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Talent Juggernaut should stack with Recklesness buff.
Therefore there should be 100% to crit on next Mortal Strike/Slam.
That isn't the case as non-crit Mortal Strike/Slam can happen.

### Expected Blizzlike Behaviour

Juggernaut 25% + Recklesness 100% should stack
Therefore Mortal strike non-crits shouldn't ever occur.

In that case Juggernaut and 1 stack of Recklesness is consumed - that part works if Mortal strike crits.

### Source

Wrath Classic

### Steps to reproduce the problem

1. Cast Recklesness
2. Charge with Juggernaut talent
3. Use Mortal Strike
4. If it doesn't crit, thats an issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment] 2023-05-19 06:06
duplicate of https://github.com/chromiecraft/chromiecraft/issues/5625 as far as i can tell

**Comment by Hogofogo1** [comment] 2023-05-19 21:29
You posted this issue #number

**Comment by Never6** [comment] 2023-05-21 23:15
> You posted this issue #number
> 

Don't sweat it this bug has been reported like 4 or 5 times

**Comment by Maria-sequel** [comment] 2023-09-01 09:36
Duplicate of #5042

**Closed by Maria-sequel** 2023-09-01 09:36 UTC
Labels: Needs Triage
