### ISSUE TITLE
Noggenfogger anti auto atk bug

### ISSUE THREAD

**Issue by Solmar1** [chromiecraft/chromiecraft#2118] opened 2021-10-16 06:38 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When you take a noggenfogger, sometimes it will permanently light up on your bars and you will not be able to auto atk. You can use all offensive and defensive spells but auto atk seems disabled for some reason even with a "/startattack" macro.

### Expected Blizzlike Behaviour

It should not be disabling your auto atk

### Steps to reproduce the problem

1. buy noggenfogger
2. use noggenfogger until it lights up on your bars
3. try to auto atk.
4. Note that I did this on a belf paladin

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by algardo** [comment] 2021-10-16 23:55
Maybe this could be useful to understand the problem: https://youtu.be/HWPFARSbmac

**Comment by Ragelezz** [comment] 2021-11-03 18:18
Can't aswell to reproduce on local but this wasn't fixed here? https://github.com/chromiecraft/chromiecraft/issues/1350

**Comment by Shineslippers** [comment] 2021-12-09 14:05
Since there is no new reports about this issue and we're unable to reproduce it i will close this report.

**Closed by Shineslippers** 2021-12-09 14:05 UTC
Labels: Waiting for more feedback, Unable to Reproduce
