### ISSUE TITLE
bug 1 with costumes

### ISSUE THREAD

**Issue by Kirishiki** [chromiecraft/chromiecraft#4035] opened 2022-09-05 15:06 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

If you use noggenfogger to turn small and then use costumes bought from site: turns your character upside down underground, and if youre jumping around you might end up in flying state and can keep jumping to fly in the air. this upside down state wont fix simply by relogging, have to log other char to fix it. tried this with 2 different costumes (ghost and kel thuzad) so i assume its the case with all of them.

### Expected Blizzlike Behaviour

i assume u shouldnt turn upside down lol.

### Source

?

### Steps to reproduce the problem

noggenfogger to small->use costume->remove costume= done

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment] 2022-09-05 17:54
Hi Kirishiki, Thanks for the report.  I can confirm this while using the ghost costume.  I used the litch costume before the noggenfogger and I can't figure out how bypass the cooldown on the costume so I'm stuck waiting to test that one.  I haven't go through all of the costumes either, but I think you're correct in assuming it's the same for all of them
![image](https://user-images.githubusercontent.com/68164076/188496933-28d66243-153e-439e-b4d5-09ac7c816f88.png)
I even took a flight
![image](https://user-images.githubusercontent.com/68164076/188497115-ca5ae62f-5d87-4a7c-ba2d-462b7a19c2b8.png)
![image](https://user-images.githubusercontent.com/68164076/188497566-886b9c8b-e085-4e93-82db-8d6f63e5c0ea.png)
This is a fun bug.

**Comment by r-o-b-o-t-o** [comment] 2022-09-06 19:56
Fixed by https://github.com/azerothcore/mod-costumes/pull/15

**Comment by r-o-b-o-t-o** [comment] 2022-09-06 19:58
> I can't figure out how to bypass the cooldown on the costume

For any triagers passing by, you can't cheat the costume cooldowns with `.cooldown` or `.cheat cooldown` unfortunately because of how the module works. You can however head to the PTR where the costumes are available and use the item IDs in the range `200000` - `200129`

**Comment by alecsci** [comment] 2024-08-25 21:25
Hey guys, multiple issues have been reported.
I will close this one, and maintain the latest one since it's related to ALL the costumes.

**Closed** 2024-08-25 21:26 UTC
Labels: Duplicate, Confirmed, Linked [AC], Generic Issues
