### ISSUE TITLE
Riding a raptor mount (Troll racial mount) changes the camera height after dismounting

### ISSUE THREAD

**Issue by Tachtzehn** [chromiecraft/chromiecraft#1002] opened 2021-06-25 20:28 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Riding a raptor mount changes the camera height from the default after you dismount.
![WoWScrnShot_062521_145027](https://user-images.githubusercontent.com/83389835/123481015-c5953e80-d5c8-11eb-9ef2-3af573d307a6.jpg)

Left shot shows camera height before mounting, right shot shows camera height after dismounting.
![mount_height_beforeafter](https://user-images.githubusercontent.com/83389835/123481834-e6aa5f00-d5c9-11eb-831a-4097840baf0a.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The on-foot camera height should be the same after mounting as it is before.

##### STEPS TO REPRODUCE THE PROBLEM:

1. As a Troll character, reach at least Lv20 and have appropriate riding skill and a Raptor mount
2. Before mounting, observe the camera's height
3. Get on your mount, the camera height should adjust higher
4. Dismount, and you will notice that the camera height doesn't lower all the way back down to the default position it was in before you mounted.

##### EXTRA NOTES:

This bug doesn't occur for my Tauren on a kodo mount. I don't have any other mount types to test with currently.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment] 2021-06-26 04:43
Can't reproduce it, works normal to me, and seems related to this one:

https://github.com/chromiecraft/chromiecraft/issues/593#issuecomment-838626838

**Comment by Tachtzehn** [comment] 2021-06-26 05:14
Happens to me even with a freshly deleted cache and all addons disabled.
/reload fixes it, but it's a bit much to /reload after every dismount.

**Comment by Eldarix** [comment] 2021-06-26 05:34
Seems client side issue, not sure what can we do, for now wait for a second opinion, thx for the report pal ;)

**Comment by Ziedge** [comment] 2021-06-26 08:55
Happens too on my side, (frFR)
https://user-images.githubusercontent.com/82708448/123507971-faf36800-d66c-11eb-9b0f-40f7b174e96a.mp4

**Comment by Ziedge** [comment] 2021-06-26 08:58
Also on wolf and kodo, so I think the issue is the fact that your kodo does not reproduce it ?

https://user-images.githubusercontent.com/82708448/123508049-5c1b3b80-d66d-11eb-9282-e5473aad14db.mp4

https://user-images.githubusercontent.com/82708448/123508043-56255a80-d66d-11eb-82a5-5eb4094fb13f.mp4

**Comment by Tachtzehn** [comment] 2021-06-26 16:15
Ziedge, your videos are not demonstrating the bug, your videos are how things _should_ work. Your camera goes back to the default position after you dismount, on my troll/raptor, mine does not, but on tauren/kodo it works fine, just like your videos.
![mount_height_beforeafter](https://user-images.githubusercontent.com/83389835/123519267-c1702c00-d66f-11eb-9e50-52b596b78e4b.jpg)

**Comment by Ziedge** [comment] 2021-06-26 16:21
Oh yeah sorry, I missunderstood !

**Comment by Tachtzehn** [comment] 2021-06-30 21:27
Happens with night elf/nightsaber too, but the effect is very subtle compared to troll/raptor. Tauren/kodo still seems to be fine, I notice no difference.

**Comment by Shineslippers** [comment] 2021-12-09 14:09
I have to close this report as Client-side. Something that we can not fix.

**Closed by Shineslippers** 2021-12-09 14:09 UTC
Labels: Waiting for more feedback, Unable to Reproduce
