### ISSUE TITLE
Hunter Pet Threat Bug

### ISSUE THREAD

**Issue by CamIsKing** [chromiecraft/chromiecraft#532] opened 2021-05-03 22:30 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

My pet randomly jumps to 10k-50k threat.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Don't jump to 50k threat randomly at level 39.

##### STEPS TO REPRODUCE THE PROBLEM:

I really don't know. See attached video where we try all our ideas and it still seems random.

##### EXTRA NOTES:

https://youtu.be/QG9THiQS-HM

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by rdallastra** [comment] 2021-06-29 00:38
I just found out that using mend pet before pulling makes the pet get 10k threat per mend pet tick. I am using a bear, with growl off, and still get 10k threat per tick on lvl 47 mobs

**Comment by temperrr** [comment] 2021-07-05 15:19
Confirmed! This is due to the Glyph of Mend Pet.

**Comment by necropola** [comment] 2021-07-25 04:22
Duplicate of #761

**Closed** 2021-07-25 09:16 UTC
Labels: Closed, Confirmed, Duplicate, Generic Issues, Linked [AC]
