### ISSUE TITLE
Wretched Ring Leader Quest

### ISSUE THREAD

**Issue by xian117** [chromiecraft/chromiecraft#453] opened 2021-04-21 15:36 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When obstructing line of sight on the npc Aldaron he moved to regain line of sight and fell through the floor. I was still able to kill him and collect his head for the loot. Not game breaking just aesthetic.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I'm pretty sure mobs aren't supposed to fall through the floor.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Initiate combat with Aldaron.
2. Use pillar to obstruct line of sight.
3. Watch Aldaron fall through the floor.
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-04-23 04:21
Reproduced on AzerothCore rev. b385878e4a5b 2021-04-22 22:25:19.

Aldaron's GUID is 56994.

![WoWScrnShot_042321_134246](https://user-images.githubusercontent.com/81782124/115817588-4a81a180-a43a-11eb-8997-d4bfb703f882.jpg)

**Comment by FrancescoBorzi** [comment] 2021-04-23 12:27
@Azcobu thanks for your feedback. If you have a local AC running you can actually help with triaging (you partially did it already), here's how:

https://github.com/chromiecraft/chromiecraft#for-contributors-how-to-triagereport-bugs

so basically after reproducing it in your own local AC, you have to open the report on the AC bugtracker.

You can ping us if you need any help! cc @Helias

**Comment by Azcobu** [comment] 2021-04-23 12:51
Copied the issue across to the AC tracker, but someone else will have to fix up the proper labels and things because I can't modify them.

**Comment by FrancescoBorzi** [comment] 2021-04-23 12:55
@Azcobu thank you. I've invited you to join our team on GitHub (please visit [this page](https://github.com/chromiecraft) and accept the invite), so you will be able to:

- change labels accordingly
- click on "edit" on the issues so you can easily copy the raw text and paste on AC (then feel free to adjust them or add any relevant information before posting them on the AC side)

**Comment by fendwe** [comment] 2022-03-24 01:39
Seems to be working correctly now.

**Comment by Helias** [comment] 2022-03-24 14:47
Thanks for the feedback, then I am closing it

**Closed by Helias** 2022-03-24 14:47 UTC
Labels: Confirmed, Linked [AC], [1 - 19]
