### ISSUE TITLE
[AI] Line of Sight bugged AI

### ISSUE THREAD

**Issue by Asipdk** [chromiecraft/chromiecraft#1328] opened 2021-08-02 06:54 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Found in Dun Garok in Hillsbrad Foothills an issue with the AI of npcs there. I was able to get these guys stuck while trying to los the casters into melee range. They are still in combat with me and and tracking my movement and copying it, the video is trash but you can see it there as I move back and forth they do the same. 

https://user-images.githubusercontent.com/5192790/127816684-32ca9ac5-8a06-49e0-8ba2-52f55f9ca132.mp4

![image](https://user-images.githubusercontent.com/5192790/127816698-75bb7860-a968-4065-9dce-b223feb7ed45.png)
![image](https://user-images.githubusercontent.com/5192790/127816707-c4f8c7f6-7d03-426c-9e18-cfeb0ad4d57e.png)

They will not move any further towards me from their current positions as well.

### Expected Blizzlike Behaviour

Mobs should run towards the player to get in line of sight. 

### Steps to reproduce the problem

1. Go to Dun Garok
2. Get in combat w/ the mobs in the downstairs section
3. Attempt to LOS them in a staircase room
4. Watch them get stuck

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asipdk** [comment] 2021-08-02 06:57
Just to update, once I left the staircase room they all unstuck and ran to me but for whatever reason around that wall they just couldn't do it when I was standing there.

**Comment by JamesHoffer** [comment] 2021-08-02 17:52
? This happens from level 1 all the way, the LOS mechanics seem broken with casters and throwing NPC's. If you go behind objects, they either stay back 20-30 yds and will just stay there, or, if they have room, like outside, they will circle around until they see you, and keep distance. It's the only thing that really is annoying on this server, or core, I'm not too familiar with Azeroth core, I've been using Trinity since it came out. I asked in game if the LOS mechanics were intended to be this way with this server/core, but no one ever answered.

**Comment by Stump876** [comment] 2021-08-03 03:07
This does appear to be a known issue, but a lot of them are closed. https://github.com/chromiecraft/chromiecraft/issues/775 The issue in AC https://github.com/azerothcore/azerothcore-wotlk/issues/5022 is still open with  `High Priority` and `Work in Progress` tags but looks like it was closed as well. I'm thinking nobody answered because nobody knew.
I'll poke the devs to see what's up. In the mean time I'm going to remove the Triage tag and put known issue. Thanks for the report.

**Comment by Salehyn** [comment] 2023-09-05 14:27
As of today I cannot reproduce this behavior on CC PTR. These mobs generally have a proper LOS AI. 
They occasionally pause in spots where they don't have los and can't cast but seem to recalculate their position every time they attempt to cast, so they will move in LOS with a 6-8sec delay when their next cast is due to happen (this is observed on the priests)
I can confirm they prefer to move a little sideways to get into line of sight and only run up to melee if there is no position at their current range from which they could shoot at you, however that is most certainly intended. That behavior mimics what a player with an extra braincell would do. They don't go out of their way to walk behind you on the other side of the wall to maintain range, but opt for the shortest possible route into LOS, which is still most often the melee.

This doesn't mean there can't be issues with the los AI elsewhere in the game, but specifically Dun Garok is working as intended at the moment.

**Closed by Salehyn** 2023-09-05 14:27 UTC
Labels: Bug Under Evaluation, More Research Needed
