### ISSUE TITLE
[Hyjal] Azgalor Trash Wave Giant Infernals' stun not triggering combat

### ISSUE THREAD

**Issue by andovcr** [chromiecraft/chromiecraft#7251] opened 2024-08-03 18:38 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Azgalor Trash Waves #3 & #7 include 8 Giant Infernal who seem to do some sort of stun when they spawn, that can interrupt eating/drinking, but the player is not actually put into combat, so they can resume eating/drinking.  I'm not certain what ability they are using, but it seems odd that an enemy interrupting drinking doesn't actually enter the player into combat.

### Expected Blizzlike Behaviour

I don't know for certain how Blizzard handles it, but I would think if drinking is interrupted by an enemy, then the player would be entering combat.

### Source

No stun abilities are listed on WoWHead, so I'm not certain what causes it: [https://www.wowhead.com/wotlk/npc=17908/giant-infernal#abilities;mode:n25](https://www.wowhead.com/wotlk/npc=17908/giant-infernal#abilities;mode:n25)

### Steps to reproduce the problem

finish Azgalor Trash Wave #2 or #6, exit combat, begin drinking until the Giant Infernals spawn

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment] 2024-09-15 09:42
I tried this issue, but my character goes in combat if it is stunned. Maybe it has been fixed.

I close this report for now, if someone can confirm the issue is still present, i'll re-open it.

**Closed** 2024-09-16 08:27 UTC
Labels: Invalid, Closed, Unable to Reproduce
