### ISSUE TITLE
NPC Caster AI seems 'off' - Gnarlpine Mystic (Video)

### ISSUE THREAD

**Issue by KaelangWoW** [chromiecraft/chromiecraft#289] opened 2021-03-24 23:19 UTC
Alliance Night Elf 1-19

When fighting the Gnarlpine Mystics in the Night Elf starting zone, I noticed that you could manipulate the AI of spell casters by simply LoSing them. Normally the casters will come to you after a specific time, however in this instance they stay at range and simply wait for you to go back into LoS. 

I can't remember 100% if this is how this worked on the Blizzard servers, however for me to have played WoW this much and find this odd suggests that it isn't working as intended. 

See videos attached - I have yet to attempt this on other caster NPC's.

https://www.youtube.com/watch?v=FIJyxrH65mA
https://www.youtube.com/watch?v=zXXJPLnQyYQ

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment] 2021-03-25 08:06
This will be rejected - see #254 also probably a duplicate of #16

**Comment by Stifler82** [comment] 2021-03-25 12:27
> This will be rejected - see #254 also probably a duplicate of #16

@eTzmNcbkrng @KaelangWoW 

Bravo, I see that you are understanding how it works, and for this reason I am starting to love you! (LOL)
(Jokes aside)

I add (to @eTzmNcbkrng's comment), that this is not a Bug and in any case it has little to do with those 2 other reports linated by @eTzmNcbkrng, because this is a correct mechanic, for the simple reason that it seems to me rather normal than if between you and an NPC there is an obstacle neither you nor the NPC are able to cast any spell through an obstacle, right? this is called "Physics of the Game".

**Closed** 2021-03-25 12:29 UTC
Labels: Closed, Invalid

**Comment by KaelangWoW** [comment] 2021-03-25 13:16
Although I would agree that the LoS should stop the mob from being able to cast a spell (such being Physics of the Game). The NPC in this instance should proceed to walk towards the player and get in range, or LoS to cast such a spell and/or start melee combat? It's pulling mechanics in WoW, if you LoS a spell caster, the NPC will come to you in melee range, no?

The video here shows the NPC's do not come towards the player, they instead wait idle until the player shows themselves. I believe this is the issue and not what you're referring to as LoS casting.

**Comment by Stifler82** [comment] 2021-03-25 13:27
> Although I would agree that the LoS should stop the mob from being able to cast a spell (such being Physics of the Game). The NPC in this instance should proceed to walk towards the player and get in range, or LoS to cast such a spell and/or start melee combat? It's pulling mechanics in WoW, if you LoS a spell caster, the NPC will come to you in melee range, no?
> 
> The video here shows the NPC's do not come towards the player, they instead wait idle until the player shows themselves. I believe this is the issue and not what you're referring to as LoS casting.

As long as the npc (has mana) he will try to get in line with you, and cast the spell he wants to cast on you.

When he runs out of mana, he'll start melee attacking you!

**Comment by KaelangWoW** [comment] 2021-03-25 13:32
> > Although I would agree that the LoS should stop the mob from being able to cast a spell (such being Physics of the Game). The NPC in this instance should proceed to walk towards the player and get in range, or LoS to cast such a spell and/or start melee combat? It's pulling mechanics in WoW, if you LoS a spell caster, the NPC will come to you in melee range, no?
> > The video here shows the NPC's do not come towards the player, they instead wait idle until the player shows themselves. I believe this is the issue and not what you're referring to as LoS casting.
> 
> As long as the npc (has mana) he will try to get in line with you, and cast the spell he wants to cast on you.
> 
> When he runs out of mana, he'll start melee attacking you!

Which is correct, the NPC will try to get in line with you. I.E the NPC will navigate a path to reach LoS, which means they should come melee to you (if you’re blocking LoS). 

In the video, the NPC doesn’t react once he’s been LoS’d and instead goes idle waiting for the player to move, instead of trying to navigate a new path to get into LoS.

**Comment by Stifler82** [comment] 2021-03-25 13:58
> > > Although I would agree that the LoS should stop the mob from being able to cast a spell (such being Physics of the Game). The NPC in this instance should proceed to walk towards the player and get in range, or LoS to cast such a spell and/or start melee combat? It's pulling mechanics in WoW, if you LoS a spell caster, the NPC will come to you in melee range, no?
> > > The video here shows the NPC's do not come towards the player, they instead wait idle until the player shows themselves. I believe this is the issue and not what you're referring to as LoS casting.
> > 
> > 
> > As long as the npc (has mana) he will try to get in line with you, and cast the spell he wants to cast on you.
> > When he runs out of mana, he'll start melee attacking you!
> 
> Which is correct, the NPC will try to get in line with you. I.E the NPC will navigate a path to reach LoS, which means they should come melee to you (if you’re blocking LoS).
> 
> In the video, the NPC doesn’t react once he’s been LoS’d and instead goes idle waiting for the player to move, instead of trying to navigate a new path to get into LoS.

@KaelangWoW 

https://github.com/chromiecraft/chromiecraft/issues/97#issuecomment-786368074 1
https://github.com/chromiecraft/chromiecraft/issues/254#issuecomment-805386500 1 **(Same Report different comment)**
https://github.com/chromiecraft/chromiecraft/issues/254#issuecomment-805662958 2 **(Same Report different comment)**
https://github.com/chromiecraft/chromiecraft/issues/254#issuecomment-805780802 3 **(Same Report different comment)**
https://github.com/chromiecraft/chromiecraft/issues/254#issuecomment-806074116 4 **(Same Report different comment)**
https://github.com/chromiecraft/chromiecraft/issues/128#issuecomment-791655880 1 

**And this video to conclude:**
**Video:** [TW](https://youtu.be/qtMonPL9-wQ)

**it is important that you look at the things I linked to you in the order of how I linked them to you.**

**Comment by Stifler82** [comment] 2021-03-25 14:00
I had forgotten the label

**Comment by Stifler82** [comment] 2021-03-25 15:03
> So I've reviewed the comments, and I we're on the same page. There is an issue there and it's with the vmaps / pathfinding. But, you've been getting a varied set of reports which all redirect to the same issue that you're already working on.
> 
> Whichever way we spin it, you're aware of the problem and it's being worked on, so closing this or keeping it open etc, irrelevant as it's on your radar already.
> 
> Ty.

I'm glad to see you got the point..

**Comment by Stifler82** [comment] 2021-03-27 10:48
https://github.com/chromiecraft/chromiecraft/issues/303
