### ISSUE TITLE
[Quest] Mother's Milk - Burning Steppes

### ISSUE THREAD

**Issue by Kindrack** [chromiecraft/chromiecraft#2925] opened 2022-02-03 03:48 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

After fighting the boss and getting the debuff, when you return to the quest giver, there is no option for him to milk the player, therefore the quest can't be completed.
![WoWScrnShot_020322_033057](https://user-images.githubusercontent.com/98931994/152276807-3aa3f681-2162-4afa-9073-305111d261b4.jpg)
Notice in the screenshot the debuff is active and the option to be milked isn't there.

### Expected Blizzlike Behaviour

When talking to the quest giver, if you have the debuff 'Mother's Milk' there should be a gossip option to ask him to milk the player, to complete the objective of the quest.
Quest walkthrough: https://youtu.be/z1xa943Ofxg?t=530 timestamped to quest turn in.

### Steps to reproduce the problem

1. QuestGiver - Ragged John in Burning Steppes
![image](https://user-images.githubusercontent.com/98931994/152277269-71bb59f3-fe2d-4835-af48-27bdb1e9119e.png)
2. Fight Mother Smolderweb in Lower Blackrock Spire until the player has the debuff
3. Talk to quest giver (1)

### Extra Notes

Disabled all addons, reloaded and relogged, it still wouldn't work.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10 64-bit

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ishidinho** [comment] 2022-02-14 10:15
Hey @Kindrack. Thank you for the report.

I was not able to reproduce the issue, too.

* `.quest add 4866`
* `.go creature 44342`
* get infected
* `.go creature 125`
* follow the dialogue and turn quest in

![WoWScrnShot_021422_111018](https://user-images.githubusercontent.com/62797536/153844623-5ba341de-e081-406e-97d8-c6dcecd5440a.jpg)

![WoWScrnShot_021422_111013](https://user-images.githubusercontent.com/62797536/153844618-74511d06-82a3-4cdf-b96f-c784801eda03.jpg)

Can you please try again after deleting the "Cache" folder in your ChromieCraft installation directory?

**Comment by nJDOA** [comment] 2022-02-15 15:45
Got the exact same Problem. The Option to getting milked is non-existent. Tried deleting Cache and disabling all Addons.

**Comment by Jalehandro** [comment] 2022-02-23 12:32
> Got the exact same Problem. The Option to getting milked is non-existent. Tried deleting Cache and disabling all Addons.

Same for me today.

**Comment by ZhengPeiRu21** [comment] 2022-02-23 15:41
Will you give more information of your character? I am still not able to reproduce this issue but it is seem that there is something wrong because for so many it is not work.

**Comment by Jalehandro** [comment] 2022-02-23 15:44
Ally dudu named Synia

**Comment by nJDOA** [comment] 2022-02-23 20:22
Also Druid on alliance side.

**Comment by Jalehandro** [comment] 2022-02-23 20:24
But there was a human priest with me, who had same problem

**Comment by Nyeriah** [comment] 2022-02-23 20:29
It probably is related to the progression module, perhaps something got deleted that shouldn't have been

**Comment by Falathr1m** [comment] 2022-02-25 06:50
I have the same problem.

**Comment by GjorgjiKirovski** [comment] 2022-03-04 11:32
Same problem here
![WoWScrnShot_030422_122643](https://user-images.githubusercontent.com/32839875/156756049-8950eb65-4899-4e4e-b1cd-8b70961a3038.jpg)

**Comment by jackravenn** [comment] 2022-03-04 11:38
Same issue here
![WoWScrnShot_030422_122643](https://user-images.githubusercontent.com/100936778/156756828-2e592513-306c-439b-ab4b-8f665042dc0b.jpg)

**Comment by ZhengPeiRu21** [comment] 2022-03-04 16:54
Thank you for continued helpful reports. I was able to identify the issue in progression module; it is related to Ragged John's changed gossip during The Masquerade questline. I have open a PR that will fix the issue. Soon when it is merged you will be able to complete this quest!

**Closed** 2022-03-04 18:34 UTC
Labels: Waiting for more feedback, Unable to Reproduce
