### ISSUE TITLE
Readiness no longer refreshing Rapid fire

### ISSUE THREAD

**Issue by waiora** [chromiecraft/chromiecraft#1977] opened 2021-10-04 20:45 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Readiness isnt refreshing the cooldown of Rapid Fire

### Expected Blizzlike Behaviour

Should reset the cooldown of Rapid fire

### Source

NA

### Steps to reproduce the problem

Cast Rapid fire

Cast Readiness

Rapid fire still on 2min CD

### Extra Notes

This wasnt bugged in 40-49 bracket. Currently have 2 points into Rapid Killing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by waiora** [comment] 2021-10-04 20:48
Guild mate tested, his was working, i did a respec and relog, seems to be working again -_-

**Comment by Nyeriah** [comment] 2021-10-13 22:07
This is related to latency, and you will never be able to reproduce it when testing alone. It was a pretty low profile issue, in the sense that it was never reported, probably because it couldn't be easily reproduced.

It was fixed with Shauren's spellhistory/cooldown rewrite, or at some point around that time, so it was fixed without ever being reported.

**Closed** 2021-10-14 12:13 UTC
Labels: Fixed, Closed

**Comment by Stump876** [comment] 2021-10-14 12:58
I'm confused now. Is the issue fixed? I had reopend this because it was closed with a triage tag on it. 

> This is related to latency, and you will never be able to reproduce it when testing alone (_on your local server_). It was a pretty low profile issue, in the sense that it was never reported, probably because it couldn't be easily reproduced.
> 
> It was fixed with Shauren's spellhistory/cooldown rewrite, or at some point around that time, so it was fixed without ever being reported.

Here it says it was fixed. But its reopened again?

**Comment by Nyeriah** [comment] 2021-10-14 13:03
> I'm confused now. Is the issue fixed? I had reopend this because it was closed with a triage tag on it.
> 
> > This is related to latency, and you will never be able to reproduce it when testing alone (_on your local server_). It was a pretty low profile issue, in the sense that it was never reported, probably because it couldn't be easily reproduced.
> > It was fixed with Shauren's spellhistory/cooldown rewrite, or at some point around that time, so it was fixed without ever being reported.
> 
> Here it says it was fixed. But its reopened again?

It was a note for the other devs, we don't have the updates that fixed it yet and the structure needs to be ported from TC (or some other fix implemented to circumvent that).

The first part of my comment was directed to the people who come across this, it's pointless to test on local servers because with no latency this will never happen, but in a duplicate of this report: https://github.com/chromiecraft/chromiecraft/issues/2004 you can see images that confirm this issue

I'm sorry for the misunderstanding, I kind of got things crossed, I suppose my comment would better fit the AC tracker instead
