### ISSUE TITLE
Antivenom not working

### ISSUE THREAD

**Issue by Hemingway1970** [chromiecraft/chromiecraft#104] opened 2021-02-24 20:58 UTC
##### SMALL DESCRIPTION:
<!-Antivenom from first aid not working.
________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________
Add a bug description line, then fill in the required fields for your problem (based on the needs of your problem)
Delete the "

N/A

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Create antivenom
Step 2 Get poisoned (I used lvl 13 spiders near loch modan for testing)
Step 3 Use antivenom

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment] 2021-02-24 22:39
@Hemingway1970

**WoooooW**

**Comment by necropola** [comment] 2021-03-01 10:27
Duplicate of #113

**Comment by FrancescoBorzi** [comment] 2021-03-01 12:06
closing this in favour of the new one, as it's more detailed.

@Hemingway1970 thanks for your report, however next time please try to properly fill the template

**Closed** 2021-03-01 12:05 UTC
Labels: Missing Information, Waiting for more feedback
