### ISSUE TITLE
Raptors in Raptor Ridge are stuck in place

### ISSUE THREAD

**Issue by serioussam113** [chromiecraft/chromiecraft#355] opened 2021-04-06 10:15 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x  Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Some raptors in Raptor Ridge in Wetlands are stuck in place when you aggro them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All raptors should run towards you when you aggro them.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-04-06 14:36
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/215

**Closed** 2021-04-06 15:56 UTC
Labels: Needs Triage
