### ISSUE TITLE
Karazhan: Nightbane - Spectral Sentry aggro from another room

### ISSUE THREAD

**Issue by NinesCC** [chromiecraft/chromiecraft#5605] opened 2023-05-15 06:05 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Spectral Sentries are aggroing through the floor, presumably the adds from the room over Nightbane's stables. We don't know what pulled them, but we do know Starfall was being used.

https://youtu.be/6Gu8jrJ_TrU?t=3601

### Expected Blizzlike Behaviour

No additional enemies should be pulled from the floor on this fight.

### Source

https://wowpedia.fandom.com/wiki/Nightbane_(tactics)
No Spectral Sentry is mentioned as any mechanic for this boss.

**Original TBC Footage:**
https://www.youtube.com/watch?v=-wuoR90jfjM
You can see that the only adds they fight are called Restless Skeletons, which 5 of them spawn when Nightbane is on it's _Air Phase_.

### Steps to reproduce the problem

1. .tele kara
2. Go to Nightbane (Faster through the back door).
3. Cast Starfall or an AoE spell that usually pulls things from other rooms.
4. Watch for Spectral Sentries.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment] 2024-08-26 19:49
:x: Tested and cannot reproduce on https://github.com/azerothcore/azerothcore-wotlk/commit/4ed1815de64e97a373bacf075073b7e2cde46dc5

I used a boomkin and started nightbane.
I perma casted Starfall and tested all nightbane's phases.
There were no mobs aggroed from outside the doors. 
Maybe it was fixed in the meantime, maybe it's specific to CC.
If you still encounter this issue, please reopen.

**Closed by alecsci** 2024-08-26 19:49 UTC
Labels: Needs Triage
