### ISSUE TITLE
[BRD] Doors to the Throneroom getting stuck sometimes

### ISSUE THREAD

**Issue by syssneck** [chromiecraft/chromiecraft#1938] opened 2021-10-02 19:07 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Sometimes the doors do not open, even when both fires are lit, making it impossible to finish the dungeon:

![unknown_2021 10 02-19 40](https://user-images.githubusercontent.com/68868567/135729034-d8e350d1-0ad8-47f7-9725-b4d668bfe020.png)

### Expected Blizzlike Behaviour

The doors should always open, when the fires are lit.

### Steps to reproduce the problem

Currently, Idk how to reproduce the issue. I suspect, that it has something to do with having more than two torches and one player starts using his torch, while another player finishes the cast with his torch.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by phonkala** [comment] 2021-10-02 20:05
Same happened to me, someone told to just use ONE torch, second one now closes the door and there's nothing to do but kick people out after that.

**Comment by syssneck** [comment] 2021-10-03 08:56
> EDIT: Actually, we did have 3 torches and another guy started to also light the first fire when I was already doing it. 

This is also what happened to us and what I suspected might cause the bug.

> EDIT: More info, was told if you light the right torch door won't open, only light the one on the left side.

I'm pretty sure the door will never open, when only one fire was lit, but I can check again.

**Comment by phonkala** [comment] 2021-10-03 10:04
Was in BRD once more, used torch on the left fire first and then right one, everything worked fine. Door didn't open if only first torch was used. So I guess the problem was that while I was using first torch on fire, another one also started using a torch on same fire (not sure if that alone opened the door and then 3rd one closed it). Either that or the order.

**Comment by Nyeriah** [comment] 2021-10-03 10:55
I can confirm this, I've also ran into this issue a couple of years ago in my former work place. I'm working on it, adding a flavor line I noticed on retail as well.

**Comment by phonkala** [comment] 2021-10-03 11:05
Did 4th run now, now the doors opened using ONLY ONE torch on the left fire.

**Comment by Trajor** [comment] 2021-10-03 18:11
Two runs in a row where doors stay closed in Lyceum.  Lit right fire first, left fire second.  Only one player clicked the torch each fire.

**Closed** 2021-10-07 20:20 UTC
Labels: Confirmed, Linked [AC], [50 - 59]
