### ISSUE TITLE
[Botanica HC] Commander Sarannis add summoning

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5793] opened 2023-06-17 14:38 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

boss should summon reinforcements. in hc its casted first after 60 seconds and repeated after 60 seconds.

### Expected Blizzlike Behaviour

in hc, reinforcement should be summoned after 30 seconds, and then every 60 seconds again
(normal mode its percentage based)

### Source

https://wowwiki-archive.fandom.com/wiki/Commander_Sarannis

> Summons Groups of 4 NPC's During the Fight. (Normal: 1 Time Summons at 55% HP). (Heroic: Summons After 30 Seconds / Repeats Summon Every 60 Seconds)
> HEROIC: After 30 Seconds into the fight (and every subsequent minute the encounter might take) she will spawn four adds that need to be dealt with quickly, 1 elite (healer) and 3 non-elites.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment] 2023-06-17 21:58
![image](https://github.com/chromiecraft/chromiecraft/assets/47818697/bcfe49f2-aba9-4aa4-aa69-64d861637b67)

Doesn't seem to be the case. She summoned them after 1 minute

**Comment by Nyeriah** [comment] 2023-06-17 22:01
Thanks for your report but this seems to be working as intended, closing

**Closed by Nyeriah** 2023-06-17 22:01 UTC
Labels: Needs Triage

**Comment by Si1ker** [comment] 2023-06-18 00:11
@Nyeriah re-open / check pr

**Comment by balleny** [comment] 2023-06-18 05:35
@Nyeriah @Si1ker checked some tbc classic videos and they arent summoned 30 secs after pull. wowwiki seems to be inaccurate in that regard

**Comment by Si1ker** [comment] 2023-06-18 10:21
> @Nyeriah @Si1ker checked some tbc classic videos and they arent summoned 30 secs after pull. wowwiki seems to be inaccurate in that regard

Thanks for the confirmation @balleny .
I also took a look at this vid, pull was at 0:12 and adds should have spawned at 0:42 or around if the info was correct.
This is already closed so no further action is required here.
