### ISSUE TITLE
[NPC]Dalinda Malem missing her scripted text quotes when doing her escort quest

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#628] opened 2021-05-12 07:29 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

While doing the Return to Vahlarriel quest (https://wowgaming.altervista.org/aowow/?quest=1440) Dalinda Malem (https://wowgaming.altervista.org/aowow/?npc=5644) is not using the scripted text quotes when starting and finishing her escort 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When starting the quest and when getting to the finish point, Dalinda should use her quotes.

https://youtu.be/wFAZ9JDunp0?t=705
https://youtu.be/wFAZ9JDunp0?t=802

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be lvl 30+
2. Do the quest chain starting with https://wowgaming.altervista.org/aowow/?quest=1437 (then quest ID 1465, 1438 and 1439)
3. Start https://wowgaming.altervista.org/aowow/?quest=1440 and escort Dalinda
4. Observe no quotes when starting and finishing the escort

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-05-12 14:40
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5636 - I really should have used the NPC's name when naming that issue.

**Closed by Azcobu** 2021-05-12 14:40 UTC
Labels: Needs Triage
