### ISSUE TITLE
Black Lotus (35.7, 20.6) from Eastern Plaguelands

### ISSUE THREAD

**Issue by Wayran-is-typing** [chromiecraft/chromiecraft#3192] opened 2022-03-10 20:06 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The herb is invisible, under the ground or inside the cauldron, doing it impossible to grab.

https://wowgaming.altervista.org/aowow/?object=176589

### Expected Blizzlike Behaviour

The herb should be grabbable

### Steps to reproduce the problem

I went to coordinate 35.7, 20.6 from Eastern Plaguelands and i tried to grab the Black Lotus tracked on the minimap and it wasn't possible.

### Extra Notes

https://wowgaming.altervista.org/aowow/?object=176589

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Yurimir** [comment] 2022-07-04 13:57
Still present.
![WoWScrnShot_070422_115319](https://user-images.githubusercontent.com/35487260/177169590-dd5e830f-d417-4606-add5-15e95ec7f6f8.jpg)

**Comment by smiloom** [comment] 2023-01-11 14:42
Today I had the same issue . found a blacklotus spawned under ground. cannot be gathered. used .gobject to determine location :  X: 3152.229980  Y:-3727.0000  z: 133.804001  MAPid:0  . Its in EPL , plagewood northern cauldron .
![WoWScrnShot_011123_152531](https://user-images.githubusercontent.com/122462826/211835159-5a163577-619b-45bb-a166-ecf30e2d50d6.jpg)

**Comment by The-GhostRider** [comment] 2023-05-28 12:57
I'm closing because:
- Issue Fix failed: https://github.com/azerothcore/azerothcore-wotlk/pull/13094
- Duplicated multiple times:
- - https://github.com/azerothcore/azerothcore-wotlk/issues/10370
- - https://github.com/azerothcore/azerothcore-wotlk/issues/10446
- - https://github.com/chromiecraft/chromiecraft/issues/2868
- And it was closed in the Label, but not in the post.

- And Among other things, I tested the bug and I can't reproduce it, indeed, currently the "GameObj" in question is not underground but "slightly" raised from the ground (as spawn level), then in reality, the Player will see it in the ground.
![image](https://github.com/chromiecraft/chromiecraft/assets/1884642/15c874c7-19b9-4ca6-8779-dea7550f3ebe)

**Closed by The-GhostRider** 2023-05-28 12:57 UTC
Labels: Duplicate, Confirmed, Linked [AC], Closed, [60]
