### ISSUE TITLE
[Quest/Object] Healing the Lake - Azuremyst Isle - crystal range indicator and error

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#5687] opened 2023-05-29 00:59 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

This quest requires you to click a single crystal (object https://www.wowhead.com/tbc/object=181433/irradiated-power-crystal) in the middle of a lake to apply the neutralizing agent https://www.wowhead.com/tbc/item=22955/neutralizing-agent and cast the spell https://www.wowhead.com/tbc/spell=28700/disperse-neutralizing-agent in order to receive credit.

The problem is that the effective range of the crystal is much smaller than indicated by the gear icon when you mouse over it. As you approach the crystal, when the icon turns golden, if you click it will return an error "You can't do that yet" as though someone is already using the crystal. Moving an inch left or right won't help this, only if you move right on top of the crystal.

The quest is absolutely doable, this is a small visual glitch.

### Expected Blizzlike Behaviour

The range indicator should properly signal when the player is in appropriate range to use the object. 

### Source

https://www.wowhead.com/tbc/quest=9294/healing-the-lake

### Steps to reproduce the problem

Go near the crystal object and attempt to click it as soon as the icon indicates you're in range. It will return an error message "You can't do that yet" 
Move closer and closer until the error stops and the spell actually casts.

### Extra Notes

https://www.wowhead.com/tbc/quest=9294/healing-the-lake

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment] 2024-09-26 18:22
Hi, deleted user, thanks for you report !

I tested and, yes, I can confirm that the gear icon gets enabled starting with 40 yards and you can click on it, and get the message "You can't do that yet!"
The gear icon should be triggered starting with 10 yards in order to activate the crystal.

imo, I thinks it's a non-issue, just move a bit closer to the object and interact with the gameobject.  
From my investigations, this is not SAI driven, and it's core related, a possible fix might affect all these "gobber" objects.
I will close it for now. If anyone from the staff would think otherwise, feel free to re-open the issue.

**Closed** 2024-09-26 18:23 UTC
Labels: Confirmed, Closed

**Comment by heyitsbench** [comment] 2024-09-26 19:34
If the issue is valid, there should be no reason to close it.
