### ISSUE TITLE
zhCN Client cannot log in

### ISSUE THREAD

**Issue by cjl3230** [chromiecraft/chromiecraft#3467] opened 2022-05-06 08:26 UTC
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

I use zhTW client 3.3.5a(12340)
but I can't select Game Server
![新建位图图像](https://user-images.githubusercontent.com/2327445/167095149-2f56f89f-a6e0-41ba-b1f9-5047e956433e.png)

### Expected Blizzlike Behaviour

I use zhTW client 3.3.5a(12340)
but I can't select Game Server

### Steps to reproduce the problem

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2e13ad75e22b5f70b2e45033ba05bd6349a1ea11

### Operating system

Windows 10 x64
Wow client 3.3.5(12340) zhTW

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cjl3230** [comment] 2022-05-06 08:29
I can login Test Server

**Comment by Gultask** [comment] 2022-05-06 15:22
Hi, cjl3230, thanks for the report!

First of all, sorry that I can't be of too much help, I've never seen this problem before.
Have you tried using a zhCN client? It's nearly the same as the zhTW one.

**Comment by cjl3230** [comment] 2022-05-07 01:10
zhCN client version is 3.3.5a (13930) not 12340
and I can connect chromiecraft **Test Server** and play normal
I think it may be caused by the setting of the RealmZone field in the configuration file worldserver.conf

**Comment by Gultask** [comment] 2022-05-07 02:40
Hey, cjl.
I've forwarded this report to the devs.
Hope it goes well and you can log in CC soon!

**Comment by cjl3230** [comment] 2022-05-07 02:49
@Gultask Thx.

**Comment by acidmanifesto** [comment] 2022-05-07 14:38
> @Gultask Thx.

Thanks for the issue. Can you provide me a link to the version of the game client you are using? I am trying to rule out a few things and im not having the issue you are having.

**Comment by cjl3230** [comment] 2022-05-07 15:29
http://pan.baidu.com/s/1lBVne   @acidmanifesto 
May need to unzip the password, the password is _www.mangoscn.com_

**Comment by cjl3230** [comment] 2022-05-12 03:06
@acidmanifesto It is possible that the value of RealmZone in the server configuration causes this problem. The azethorecore I tested locally was changed to RealmZone to reproduce this problem

**Comment by cjl3230** [comment] 2022-05-12 06:46
@acidmanifesto maybe you can try this client (URL: https://pan.baidu.com/s/18TJfXy5W03AE-rhX_Q53WQ    Code: wcx1)

**Comment by cjl3230** [comment] 2022-05-18 03:38
![image](https://user-images.githubusercontent.com/2327445/168952029-fe96278c-9e4c-4a95-bce7-8c1bb7d1e848.png)
@acidmanifesto Maybe my client can log in normally only if the server returns LT_ANY or LT_EAST_ASIA
So RealmZone should only have 1, 26, 28 to allow all clients to log in.

**Comment by cjl3230** [comment] 2022-06-01 01:15
The Korean client should have the same problem.

**Comment by temperrr** [comment] 2022-07-21 16:12
Since it's a server settings, I will bring it up with the server administration. Thanks for reporting it.

**Comment by heyitsbench** [comment] 2022-08-07 04:56
As detailed in https://github.com/chromiecraft/chromiecraft/issues/3889, this affects the zhCN and zhTW clients, though I can't speak for the koKR client. There is a workaround, also described in that issue thread, but I don't know where the underlying issue is, as I couldn't reproduce this issue on my local AC.

**Comment by Rorschach91** [comment] 2024-11-05 22:00
has this problem been solved?
In case we can close it.

**Comment by cjl3230** [comment] 2024-11-12 01:23
@Rorschach91  I tested It. It's work OK now

**Comment by Rorschach91** [comment] 2024-11-12 08:43
@cjl3230 Thank you :)

**Closed** 2024-11-12 08:43 UTC
Labels: Needs Triage, Game Client Bug
