### ISSUE TITLE
guild bank stormwind bug

### ISSUE THREAD

**Issue by xabos** [chromiecraft/chromiecraft#387] opened 2021-04-09 11:21 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

go to Stormwind guild bank and try to move the item's randomly, the item show's stack randomly number's if you exit and open the guild bank again it shows them right again see the video above.

https://reccloud.com/u/hs2vz19

##### EXPECTED BLIZZLIKE BEHAVIOUR:

when you move an item you expect to see 1 item if it's armour you can't see a stack's of chest etc.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stormwind guild bank: 41912 (Entry: 187329) - [Guild Vault X:-8910.429688 Y:636.380005 Z:100.910004 MapId:0] 
2. Open guild bank 
3. Start moving item randomly 
4.Stack of wrist, chest, head etc will show with random number's

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Windows 10 pro 64bit

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment] 2021-04-10 07:32
Video is inaccessible at URL given by OP.
Correct URL is https://reccloud.com/u/hs2vz19

@xabos pretty sure this is a bug caused by one of your addons, please check again with no addons enabled.

**Comment by xabos** [comment] 2021-04-10 07:58
> Video is inaccessible at URL given by OP.
> Correct URL is https://reccloud.com/u/hs2vz19
> 
> @xabos pretty sure this is a bug caused by one of your addons, please check again with no addons enabled.

sorry, my fault I did update it^^

**Comment by xabos** [comment] 2021-04-10 08:42
what is invalid???

**Comment by eTzmNcbkrng** [comment] 2021-04-10 08:43
> 
> 
> what is invalid???

It's an addon bug.

**Comment by xabos** [comment] 2021-04-10 08:43
I see which one you know??

**Comment by eTzmNcbkrng** [comment] 2021-04-10 08:44
Absolutely no idea, not even sure what you're using.

**Comment by xabos** [comment] 2021-04-10 08:47
chromiecraft client and addons:
_NPCSCan
Addon control panel
Atlasloot
cooldowns 1.3.3
Easyloot
Friend & Ignore Share v1.4.2
Gatherer
GearScoreLite
GTFO
idTip
Prat 3.0
WIM
Recount
Deadly Boss Mods Core

**Comment by eTzmNcbkrng** [comment] 2021-04-10 08:48
Maybe idTip

Just test them.

**Comment by xabos** [comment] 2021-04-10 08:51
i just disable all addons and this keep coming you are sure that it's addon fault?

**Comment by Yehonal** [comment] 2021-04-10 10:13
Probably a GM can check it as well by temporary join the guild

**Comment by 55Honey** [comment] 2021-04-10 11:34
Tested, confirmed. It is NOT an addon bug and was reproduced with a perfectly clean enUS client.

**Comment by 55Honey** [comment] 2021-04-10 11:45
Can not reproduce it for another guild. It seems that this specific Guild bank/tab is bugged.

**Comment by FrancescoBorzi** [comment] 2021-04-10 11:48
ok closing then, the GM will solve the issue for the specific guild

**Comment by Yehonal** [comment] 2021-04-10 14:34
Shin sorry to bother you, but it's not a localized bug. I've found a way to reproduce it. Maybe there's a sort of issue with the opcode sent, cosmetic and not hight priority, but let's report it.

I've reproduced it in several guild banks:

https://www.youtube.com/watch?v=K9C4FQyh6ww&ab_channel=YehonalYehtan%C3%A9rLunthatir

https://www.youtube.com/watch?v=MMn5-ASLNN0&ab_channel=YehonalYehtan%C3%A9rLunthatir

Let's report it on AC

**Comment by fendwe** [comment] 2022-03-24 01:08
This seems to be working correctly now.

**Closed** 2022-09-06 21:47 UTC
Labels: Confirmed, Linked [AC], Generic Issues
