### ISSUE TITLE
rdruid random heal increase

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#4920] opened 2023-01-31 21:57 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

I got this weird interaction with https://wowgaming.altervista.org/aowow/?spell=26981
in my current gear rejuv will tick for 564 outside of tree form but if i cast https://wowgaming.altervista.org/aowow/?spell=33763 before rejuv, it will now tick for 578 
![WoWScrnShot_013123_164325](https://user-images.githubusercontent.com/66432845/215890837-78155531-d16d-4edf-ad48-267c69326139.jpg)

### Expected Blizzlike Behaviour

rejuv's healing shouldnt be increased because i casted a specific spell beforehand

### Source

I dont have any increase spell power on spell cast items so rejuv shouldn't be increased

### Steps to reproduce the problem

make a resto druid
cast rejuv
watch healing tick
cancel rejuv
cast lifebloom
cast rejuv
rejuv is increased

### Extra Notes

https://wowgaming.altervista.org/aowow/?talent#0ZZf0IudhxikA0sio
these are my talents 
https://www.chromiecraft.com/en/armory/?character/ChromieCraft/Mez this is my characters armory so u can see what gear i am using
I dont believe the increase is due to spell power rounding up my hots  but I could be wrong 
This happens both outside and inside of https://wowgaming.altervista.org/aowow/?spell=33891
This interaction only happens with resto.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Maria-sequel** [comment] 2023-08-31 18:54
I am unable to reproduce this.

**Comment by The-GhostRider** [comment] 2023-12-03 06:16
I did multiple tests performing the combination of spells you mentioned.
I was unable to reproduce this Bug.

[![Anteprima](https://user-images.githubusercontent.com/1884642/287500306-12046039-ee05-4ae0-ae78-8003d42703b6.png)](https://www.youtube.com/embed/69i0qoDKFaU)

Maybe you've experienced this effect because of something you have like:
- Equip,
- Enchant,
or something else that altered Rejuvenation's behavior.

In any case, as you can see from my video, this bug is not reproducible.

For this reason I am closing the report.

**Closed by The-GhostRider** 2023-12-03 06:16 UTC
Labels: Waiting for more feedback
