### ISSUE TITLE
Centipaar Tuneler stuck after using Tapped Dowsing Widget

### ISSUE THREAD

**Issue by matisskeiris** [chromiecraft/chromiecraft#2715] opened 2022-01-02 18:32 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Went to collect sample for [Gadgetzan Water Survey](https://classic.wowhead.com/quest=992/gadgetzan-water-survey) using Tapped Dowsing Widget. Noticed that there is Evading Centipaar Tunneler. When I collected my sample, 2 Centipaar Tunnelers appeared next to them and started Evading. 

https://imgur.com/a/lpJv7G8

### Expected Blizzlike Behaviour

Centipaar Tunnelers should attack me after collecting samples

### Steps to reproduce the problem

1. Start https://classic.wowhead.com/quest=992/gadgetzan-water-survey
2. Go to Sandsorrow Watch water pool
3. Gather Sample

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by matisskeiris** [comment] 2022-01-02 18:33
They stared to attack me when I left water, was standing there for a while while reporting the issue

**Comment by ishidinho** [comment] 2022-01-03 10:17
Thank you for the report, @matisskeiris.

Actually, I was not able to reproduce the problem on my local AC. I cannot observe evading Centipaar Tunnelers. After using [Untapped Dowsing Widget] two Centipaar Tunnelers appeared, started attacking me and chain-pulled all other Centipaar Tunnelers in the pool.

https://user-images.githubusercontent.com/62797536/147919667-e1f12528-651a-4211-b1f6-da634de521e9.mp4

**Comment by Gultask** [comment] 2022-04-29 23:58
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9989

**Closed by Gultask** 2022-04-29 23:58 UTC
Labels: Confirmed, Linked [AC], [40 - 49]
