### ISSUE TITLE
[Warrior] Charging in a certain location results in you falling through the map. 

### ISSUE THREAD

**Issue by ToplessMan** [chromiecraft/chromiecraft#1819] opened 2021-09-22 09:06 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

If you charge a murlock at (10.53, 65.59) you fall through the map. I have repeated this a couple of times to check. Happens every time
![WoWScrnShot_092221_095422](https://user-images.githubusercontent.com/91187467/134315059-74d96f55-ca1c-42b5-a7d6-cd0a8d5f0d3e.jpg)
![WoWScrnShot_092221_095803](https://user-images.githubusercontent.com/91187467/134315088-4735c0ed-e521-4845-ae90-5f87d32cd6e6.jpg)
. 

### Expected Blizzlike Behaviour

You don't fall through the map. 

### Steps to reproduce the problem

1. Go to location. 
2. Find murlock on or near coordinates (10.53, 65.59)
3. Charge murlock
4. Fall through map

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

- Elvui

### Server

ChromieCraft.

**Comment by Elexias** [comment] 2021-09-22 09:37
Already known issue. https://github.com/azerothcore/azerothcore-wotlk/issues/6232

**Comment by Azcobu** [comment] 2021-09-22 11:02
Thanks for the report. As @Elexias says this is a duplicate of a known issue, but you've given us another good spot to test this issue. The previously reported spot, a hill in Redridge, didn't cause this problem as often as the hill you found, so that's definitely useful.

**Closed by Azcobu** 2021-09-22 11:02 UTC
Labels: Needs Triage
