### ISSUE TITLE
NPC DBID 12979 - Makrura Clacker pathing bugged and always evade

### ISSUE THREAD

**Issue by mdawx** [chromiecraft/chromiecraft#300] opened 2021-03-26 23:09 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

NPC 12979 Makrura Clacker has pathing bugged (constantly turning arround) and always evade attacks.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should have normal pathing and should not evade attacks

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go near position -1033.208 -5000.52 -1.3625
2. Try to kill NPC Makrura Clacker
3. Observe pathing

##### EXTRA NOTES:

https://youtu.be/zc5RG1iK7NI

![image](https://user-images.githubusercontent.com/81375770/112700940-8e12db00-8e8f-11eb-85d4-87ca8220b474.png)
![image](https://user-images.githubusercontent.com/81375770/112700955-9a973380-8e8f-11eb-9d25-0c33bb69571c.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment] 2021-03-28 11:41
Can't reproduce on my local server. There have been some changes to the pathfinding and map system so I think it probably got fixed with one of those.

**Closed by Hacki95** 2021-03-28 11:41 UTC
Labels: Needs Triage

**Comment by FrancescoBorzi** [comment] 2021-03-28 11:53
@Hacki95 thanks! don't forget to remove [Needs Triage] and add [Unable to Reproduce] in this case
