### ISSUE TITLE
DISPEL RANK 2

### ISSUE THREAD

**Issue by Yphriel** [chromiecraft/chromiecraft#1159] opened 2021-07-10 19:05 UTC
DISPEL(RANK2)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Basically, dispel rank 2 only removes 1 harmful spell from friend or 1 beneficial spell from foe.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dispel (rank2) suppose to remove 2 harmful spell from friend or 2 beneficial spell from foe.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get harmful dispellable debuff
2. Use Dispel (Rank2)
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Shineslippers** [comment] 2021-07-10 22:35
Can't confirm it.  I think Dispel(rank2) is doing what it have to. After some investigation, i found a trigger to call the issue. Target of dispel should have buffs/debuffs from DIFFERENT sources. I didn't found a pattern, but it's repetable.

**Comment by Azcobu** [comment] 2021-07-11 05:43
Thanks for the report. I haven't been able to reproduce this either. I tried with 2 Horde characters and an Ally casting Dispel at them. Firstly, a Horde druid casts Mark of the Wold and Thorns on himself. Both were dispelled by the one cast of Dispel:

![WoWScrnShot_071121_145956](https://user-images.githubusercontent.com/81782124/125184091-29bb3200-e25a-11eb-8672-06df23f86cba.jpg)

Then to try @Shineslippers 's suggestion, I got a Horde mage to buff the druid with Arcane Intellect, so that the buffs came from different sources. Those two buffs were also dispelled successfully:

![WoWScrnShot_071121_150242](https://user-images.githubusercontent.com/81782124/125184113-5b33fd80-e25a-11eb-9ab0-47cc74a65c45.jpg)

So I think we're going to need more details about the specific spells you're trying with in order to nail this one down.

**Comment by Shineslippers** [comment] 2021-07-11 09:44
It looks like this. But now idk is it bug or no.
![WoWScrnShot_071121_124252](https://user-images.githubusercontent.com/85256266/125190423-bad3de00-e245-11eb-83d5-93ade9230126.jpg)

**Comment by Yphriel** [comment] 2021-07-11 14:55
Usually while running dungeons and the tank has 2 debuffs on him that can be dispelled, only one is removed.

**Comment by Shineslippers** [comment] 2021-07-11 18:10
I checked out it on local AC sever in The temple of atal'hakkar and Yphriel is right. It dispel only 1n effect.

**Comment by Azcobu** [comment] 2021-07-12 14:34
@Shineslippers thanks for the screenshots, makes it so much easier to check actual combat logs.

I've reproduced Dispel only removing 1 stack of Shadow Word: Pain at a time when you have multiple stacks on you. However, I'm still unsure if this is expected behaviour or not. Dispel says "removes 2 harmful spells" and I'm wondering if that actually means "removes 2 different types of harmful spells," i.e. 1 stack of each of 2 spells rather than a flat 2 stacks of whatever's on there. That would match current behaviour. I'm not a priest player though, so have to find a source to confirm or refute that guess, which I haven't been able to yet.

**Comment by syssneck** [comment] 2021-07-12 14:55
Hi all, I did some tests myself. I tested only with Shadow Word: Pain (rank 3) and Corruption (rank 3). I had some cases, where I dispelled both of the harmful magic spells and some cases, where one debuff wasn't dispelled and persisted, so there seems to be a chance of failing a dispel (maybe this is obvious to everyone, but it wasn't to me). See here:

https://user-images.githubusercontent.com/68868567/125309227-de745280-e331-11eb-9297-065e3a590801.mp4

However, I can't say, if this is the intended behavior or not. I hope this little test might help with the problem!

**Comment by Shineslippers** [comment] 2021-07-12 17:14
@syssneck yea, it's not a common knowledge. Regarding to topic. It definitely dispel 2 different buffs/debuffs. So without evidence there is nothing to change. Until @Yphriel or someone else can't provide more information, this is not an issue. I can agree with @Azcobu.

**Comment by syssneck** [comment] 2021-07-12 17:33
A blue posted this a few months back (WoW Classic): "In 1.12 and all of Original WoW, it was possible for dispels to be resisted. This was correct and intended in 2006, and simply went unnoticed until now in Classic. During 1.13.7 development we found the offending incorrect code and fixed the issue.

This means that offensive dispelling in pvp may not always succeed, particularly if the target you are trying to dispel is significantly higher level than you, as level disparity does affect this. Additionally, dispelling of harmful affects in certain pve encounters will also have a small chance to fail." 
Source: [Aggrend, WoW Forums](https://us.forums.blizzard.com/en/wow/t/dispells-can-resist/944750/6)

**Comment by Azcobu** [comment] 2021-07-14 10:37
In the absence of any other sources or citations that can prove this behaviour is incorrect, will close this issue. But as always, if you do find some verifiable evidence that this is not correct, feel free to let us know.

**Closed by Azcobu** 2021-07-14 10:37 UTC
Labels: Unable to Reproduce, Waiting for more feedback
