### ISSUE TITLE
Escape from Coilskar Cistern - Quest 

### ISSUE THREAD

**Issue by EzekR10n** [chromiecraft/chromiecraft#7243] opened 2024-07-31 18:08 UTC
### What client do you play on?

esES

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

https://www.wowhead.com/tbc/es/npc=21027/ensalmadora-de-la-tierra-wilda

### Expected Blizzlike Behaviour

1) Enter "Coilskar Cistern" at 52.8,25.8
2) Get to the bottom of the cave and to 51.9,18.4
3) Kill "Keeper of the Cistern"
4) Wait for "Earthmender Wilda <The Earthen Ring>" to get interactive, and accept the quest.

When I get the Mission the NPC disappears and shows me a message "not achieved" 

### Source

https://www.wowhead.com/tbc/es/quest=10451/huida-de-la-cisterna-cicatriz-espiral#english-comments

https://www.youtube.com/watch?v=8g4hbd4QnMg

### Steps to reproduce the problem

NPC

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Windows 10 64 bits

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-08-01 02:27
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/5148.

**Closed by heyitsbench** 2024-08-01 02:27 UTC
Labels: Needs Triage
