### ISSUE TITLE
Unable to Auto Attack after drinking Health Potion

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#386] opened 2021-04-09 09:48 UTC
Under some circumstances Health Potions cause a player to be unable to Auto Attack.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance (not tested)
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If a player exits WoW while under the effects of a Troll's Blood Potion (multiple tested, all affected), using a Health Potion (multiple tested, all affected) after logging back in causes Auto Attack to not work.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using a Health Potion, under any circumstances should not permanently disable a player's melee abilities.

##### STEPS TO REPRODUCE THE PROBLEM:

Setup: Add Troll's Blood Elixirs and Health Potions to inventory
```
.additem 3382 5
.additem 3388 5
.additem 3826 5
.additem 858 10
.additem 3928 10
.additem 22829 10
.additem 33447 10
```

Use one of the Troll's Blood Elixirs:
`/use Weak Troll's Blood Elixir`
`/use Strong Troll's Blood Elixir`
`/use Major Troll's Blood Elixir`

Exit game
`/exit`

Delete Cache folder: *optional*

Log into game

Now attempt to use one of the Health Potions (any will do)
`/use Lesser Healing Potion`
`/use Superior Healing Potion`
`/use Super Healing Potion`
`/use Runic Healing Potion`

If you use a potion out of combat you will notice the icon dulls (edit: ElvUI dulls icon, default UI has glowing border) as though it's been clicked but you will get no HP restored, and the cooldown will not start. Engaging a NPC in combat at this point, you will see that Auto Attack does not work.

Now `/exit` game, relaunch and attack another NPC, you will see it works fine.
While still in combat, use another Health Potion. Again, any will do.
You will again not get the effects of the potion, nor start the CD, but also, Auto Attack continue to work, but your weapons disappear.

##### EXTRA NOTES:

I found that if I engaged a NPC with the Warrior's Charge ability, Auto Attack functioned as normal, while this bug continued to affect Auto Attack on NPCs that were not engaged with Charge.

Instead of Troll's Blood Elixirs, I tried a few other items that also grant a HP5 buff.
 - Poached Sunscale Salmon
 - Book of Survival
 - Rune of Duty

Of the 3 items I tested, only Poached Sunscale Salmon actually gives a removable aura but none of them caused any issues with drinking a Health Potion.

Merely Logging out and Logging in does not clear the bugged state of a player, `/exit` is required to invoke and to clear this bug.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment] 2021-04-10 09:14
@Stifler82 why closing this?

**Comment by Stifler82** [comment] 2021-04-10 09:18
I consider it the poorly filled report even when its content is poorly explained, and for me this content is poorly explained because it is TOO long and full of useless things like the fact that I also write the GM COMMANDS !!!!
Now he has to teach me which GM commands should I use ???

**Comment by FrancescoBorzi** [comment] 2021-04-10 13:35
> Now he has to teach me which GM commands should I use ???

those are meant to HELP us reproduce the issue -_-

**Comment by Azcobu** [comment] 2021-04-10 15:04
I was able to reproduce this on my local test system. Version is AzerothCore rev. c0cb2eae38dc+ 2021-04-06 03:52:40 +0000 (master branch) (Unix, Release)

As above, drinking a troll's blood elixir and then trying to drink a health potion disabled auto attacks. The potion itself never actually gets drunk and never goes on cooldown. For me, as long as I had the troll's blood effect on me, trying to drink a health potion would disable auto attacks, even after /exiting. Auto attacks were also disabled in cat and bear forms.

I also tried Feral Charge (Bear), and that made auto attacks work for that mob only (possibly because it was copied from the warrior version?) Feral Charge (Cat) however, did not make auto attacks work again.

Here's a screenshot showing my character standing still and doing nothing while the auto attack button (first button on the lowest toolbar) is active.

![WoWScrnShot_041021_234215](https://user-images.githubusercontent.com/81782124/114274381-4a0e0180-9a5d-11eb-941a-097516b35096.jpg)

I should also mention that as a new contributor to this project, I found the GM commands given above very useful.

**Comment by orfaze** [comment] 2021-04-11 14:10
Saw someone asking about the bug on world, he says it bug with mana pot too
![Capture d’écran (24)](https://user-images.githubusercontent.com/81832274/114307539-5d15e580-9ae0-11eb-9e91-6c982c1db95d.png)

**Comment by 55Honey** [comment] 2021-04-12 18:36
![image](https://user-images.githubusercontent.com/71938210/114443945-988edd80-9bce-11eb-83e1-64b79a363ceb.png)
![image](https://user-images.githubusercontent.com/71938210/114443971-9fb5eb80-9bce-11eb-868a-41d5408a5cb7.png)

**Comment by hemanmaguy** [comment] 2021-05-14 19:46
bug happend to me put trolls blood on before a dungie in that dungie i could still auto attack but i could not pot
then i reseted my game to try to fix it but after the relog i could no longer auto attack
was fixed with a GMs help

**Comment by Undersalt** [comment] 2021-05-25 23:57
Can confirm this is still a bug. Solved it by removing (right clicking) Trolls Blood Elixir Buff and relogging. Also using Elvui.

**Closed** 2021-09-13 18:57 UTC
Labels: Confirmed, Linked [AC], Generic Issues
