### ISSUE TITLE
Blackfathom Deeps: torch event doesn't reset itself and despawns all mobs after wipe, door stays closed

### ISSUE THREAD

**Issue by 7Skidoo** [chromiecraft/chromiecraft#972] opened 2021-06-23 12:52 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After Twilight Lord Kelris there are four clickable torches, each spawning mobs. After wiping to these mobs the torches do not reset, stay lit but the mobs dissapear, results in the group not being able to progress. The door will only open after all mobs are dead.
See screenshot: 
![WoWScrnShot_062321_145051](https://user-images.githubusercontent.com/86149989/123099513-8af99d80-d432-11eb-9304-cce0b2f573a6.jpg)
Duplicate on Imgur: https://i.imgur.com/n4RYeed.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Click torches, (wipe to monsters), come back to the dungeon, torches are still lit but the monsters are still there and have not despawned.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Click all torches, wipe, see if you can click them again
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment] 2021-06-23 13:01
Enemies should not despawn, wow classic https://youtu.be/G18a3St6P0c?t=5862

**Comment by pop-pig** [comment] 2021-06-23 13:29
It seems like it is indeed blizzlike, an issue has been opened before and closed: #220

**Comment by necropola** [comment] 2021-06-23 16:26
1. Isn't this a duplicate of #220?
2. Wasn't it fixed?

**Comment by 7Skidoo** [comment] 2021-06-23 18:23
Yes, same issue but it the conclusion in https://github.com/chromiecraft/chromiecraft/issues/220 was wrong.
See temperr's video.

**Comment by necropola** [comment] 2021-06-23 18:28
Duplicate of #220

I'm closing this issue here and I'm reopening the original issue.

**Closed** 2021-06-23 18:28 UTC
Labels: Closed, Duplicate
