### ISSUE TITLE
Small, Insignificant quest visual bug with early quest giver: Eversong Woods

### ISSUE THREAD

**Issue by Estuswick** [chromiecraft/chromiecraft#7392] opened 2024-10-03 00:35 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

The turn-in quest-marker will not appear above NPC [**Lathan Perilon**](https://www.wowhead.com/npc=15281/lanthan-perilon)'s head or appear on the mini-map at the correct time for both:
[Quest: Felendren the Banished](https://www.wowhead.com/quest=8335/felendren-the-banished)
[Quest: Aggression](https://www.wowhead.com/quest=8334/aggression)

### Expected Blizzlike Behaviour

The quest is completed and there should be a visible turn-in quest-marker above [**Lathan Perilon**](https://www.wowhead.com/npc=15281/lanthan-perilon)'s head and on the mini map.

### Source

My sources are my screenshots. I go over them in the the step by step.

![WoWScrnShot_100224_173001](https://github.com/user-attachments/assets/b076a219-9450-4e79-9cda-cc731dd483f9)
![WoWScrnShot_100224_173031](https://github.com/user-attachments/assets/d6ee3512-2da6-4685-b673-5a9285ce3077)

### Steps to reproduce the problem

The first 2 screenshots is of my first encounter. The [Quest: Felendren the Banished](https://www.wowhead.com/quest=8335/felendren-the-banished) is completed and [**Lathan Perilon**](https://www.wowhead.com/npc=15281/lanthan-perilon) has no marker above his head or on the mini-map. I can still turn in the quest
![WoWScrnShot_100224_173001](https://github.com/user-attachments/assets/94611244-3004-464b-9139-5158afa28d26)
![WoWScrnShot_100224_173031](https://github.com/user-attachments/assets/93e14e76-5f67-4899-807c-0c61a752bb21)

I made a second character to test again and found that it also happens on [**Lathan Perilon**](https://www.wowhead.com/npc=15281/lanthan-perilon)'s other [Quest: Aggression](https://www.wowhead.com/quest=8334/aggression) as well. the first screenshot does not show him but he is beyond that tree and again the quest is completed I could turn it in but decided not to. I went to turn my other quests then return and it updated him and the mini-map with quest-markers.
![WoWScrnShot_100224_182052](https://github.com/user-attachments/assets/4e82a83a-666d-4678-967e-5a5ef4ae8c54)
![WoWScrnShot_100224_182311](https://github.com/user-attachments/assets/398d0f24-51e8-4d89-bd6b-2cf6925bd159)
[Quest: Felendren the Banished](https://www.wowhead.com/quest=8335/felendren-the-banished) Generally only updated every so often after progressing it. You can see that I just received his head and the quest-tracker has not updated yet. It updated as soon as I accepted another quest.
![WoWScrnShot_100224_182715](https://github.com/user-attachments/assets/df37d7a0-a6a7-4792-bf71-b0a568876e82)
The next screenshots are me recreating the last bugs with [Quest: Felendren the Banished](https://www.wowhead.com/quest=8335/felendren-the-banished) No quest-markers
![WoWScrnShot_100224_182854](https://github.com/user-attachments/assets/021479cd-b06a-40d3-8e2a-f9ac572a50c2)
Still can turn it in.
![WoWScrnShot_100224_183019](https://github.com/user-attachments/assets/745e2666-6c12-4566-a96c-367a5c4bb3f8)
When I turn in other quests it updates itself and self corrects.
![WoWScrnShot_100224_183139](https://github.com/user-attachments/assets/7a5d17fb-36c8-4823-92c7-adb363507aae)

### Extra Notes

The quests attached to **Lathan Perilon** seem to get updated when you update your questlist with other quests whether it's adding, completing, or them updating to a next step. When I turned in another quest and came back to **Lathan Perilon**, it had updated and added his quest marker above his head and to the mini-map.

https://www.wowhead.com/npc=15281/lanthan-perilon
https://www.wowhead.com/quest=8335/felendren-the-banished
https://www.wowhead.com/quest=8334/aggression

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/529e9140323edeef916bd6a1b6c97e13aa38db08

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-10-03 02:23
Possible duplicate of https://github.com/chromiecraft/chromiecraft/issues/6127.

**Comment by Estuswick** [comment] 2024-10-03 15:15
> Possible duplicate of #6127.

Do you know if the quest marker would appear above their head if other quests were turned in? That was a specific behavior with this guy's multiple quests as well.

**Comment by heyitsbench** [comment] 2024-10-03 20:10
> Do you know if the quest marker would appear above their head if other quests were turned in? That was a specific behavior with this guy's multiple quests as well.

🤷‍♀️

**Comment by Rorschach91** [comment] 2024-10-03 20:38
I've tried to reproduce the issue on my AC server and on PTR but quest markers are present on the npc.
In any case, this is a general graphic bug that randomicaly afflicts the quests.

**Closed** 2024-10-10 21:10 UTC
Labels: Confirmed, Linked [AC], Known issue, Rare Bug
