### ISSUE TITLE
First Mate Snellig

### ISSUE THREAD

**Issue by RudeCC** [chromiecraft/chromiecraft#1263] opened 2021-07-21 16:37 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Pathing is weird, see video link; https://youtu.be/b108r89bHsA

### Expected Blizzlike Behaviour

I do not have evidence to claim that his pathing should be normal, but it is clear something is wrong in my video above.

### Steps to reproduce the problem

I'm not sure what steps are required for this to be reproduced, all I have is an uploaded video by myself.
https://youtu.be/b108r89bHsA

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Windows 10, latest revision

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment] 2021-07-21 16:46
Thanks for your report, I linked it to the correct thread.

**Comment by temperrr** [comment] 2021-07-25 06:41
I cannot reproduce the issue. Probably because of this https://github.com/azerothcore/azerothcore-wotlk/pull/7034#event-5064102948 which has not yet been added to chromiecraft. I am closing the report for now. If, after this PR gets merged with ChromieCraft (Probably at the next update), you still encounter this issue, feel free to leave a comment below.

**Closed by temperrr** 2021-07-25 06:41 UTC
Labels: Needs Triage, Vmaps/Mmaps/Pathfinding
