### ISSUE TITLE
Corrupted night dragon does not work

### ISSUE THREAD

**Issue by morpez121** [chromiecraft/chromiecraft#2492] opened 2021-12-06 17:59 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

In Felwood "Corrupted night dragon" does not turn in "cleansed night dragon" when cured via Cenarion plant salve.
I tried on two different plant, more than once. The quest never worked.
![WoWScrnShot_120621_102949](https://user-images.githubusercontent.com/90974262/144881325-af1dba28-e295-4b75-bca5-2761325dcef0.jpg)

### Expected Blizzlike Behaviour

"Corrupted night dragon" should turn in "cleansed night dragon" when cured via Cenarion plant salve, to obtain the 4 Night Dragon's Breath needed for "Lesser Arcanum of Constitution" enchant for head/legs.

### Steps to reproduce the problem

Fly to Felwood, Emerald Sanctuary.
Go south, speak with Arathandris Silversky, Emerald Circle (DB Guid 39091, current Guid 21709).
The NPC gives you a quest to collect 15 shards from Warpwood Shredder in the north. After this he give you a "cenarion Beacon" an item to collect corrupted shards from all mobs that you kill in Felwood. Finally go back at same NPC and exchange the corrupted shards with "cenarion plant salve".
Use these on "Corrupted night dragon".

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=4119#see-also

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-06 18:23
Thank you for the report. Anyway it's duplicate of https://github.com/chromiecraft/chromiecraft/issues/2460 as mentioned above. For right now it doesn't work on CC. Update of server should fix it. Usually it happens every wednessday.

**Closed by Shineslippers** 2021-12-06 18:23 UTC
Labels: Needs Triage
