### ISSUE TITLE
[Hunter] Trap mastery bugs

### ISSUE THREAD

**Issue by TarekMadara** [chromiecraft/chromiecraft#3378] opened 2022-04-19 13:12 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The [Trap mastery] in the survival tree of hunter does not increase the duration of the freezing trap.

### Expected Blizzlike Behaviour

The talent [Trap mastery] should increase the duration of the freezing trap by 30%.

### Steps to reproduce the problem

- Hunter with [Trap mastery] in the survival tree.

- use it on a target.

- you will realize the duration of the trap did not increase compared to hunters without the specified talent.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by aradep** [comment] 2022-04-20 08:21
![trapmastery](https://user-images.githubusercontent.com/61268368/164173725-9cda53cf-a0cb-4d6c-b22a-3d194952e8d4.jpg)
Works as intended on https://github.com/azerothcore/azerothcore-wotlk/commit/61de612641fdf0639b447c01a3e1a677ae5685a1

**Comment by TarekMadara** [comment] 2022-04-20 11:59
@aradep did you test it on the chromie server ? or in PTR?

**Comment by Gultask** [comment] 2022-04-20 13:42
Tested in the PTR yesterday. Working as intended as well.
If you don't mind, Tarek, could you tell us the exact situation that led to you opening this issue? Was it PvP or PvE?

![WoWScrnShot_041922_195547](https://user-images.githubusercontent.com/100873791/164243452-5ddd4f4d-3f60-41c9-bc66-45f3793b4872.jpg)
![WoWScrnShot_041922_195644](https://user-images.githubusercontent.com/100873791/164243467-edba01e3-3506-48c7-9ef4-9dd724351940.jpg)

**Comment by TarekMadara** [comment] 2022-04-21 13:10
Hey @Gultask , i noticed it while doing bgs, and i became certain of it while dualing another MM hunter (i am survival).

**Comment by Gultask** [comment] 2022-04-21 13:21
I'll try it again on player characters. The problem is that PvP has many factors that could interfere with Stun/Immobilization durations such as racials, gear, talents, classes, etc

**Comment by Gultask** [comment] 2022-04-21 13:51
Ah, there we go. Freezing Trap only affects players for 10 seconds, regardless of having the talent or not. I'll check for any sources on the matter.

**Comment by TarekMadara** [comment] 2022-04-22 20:40
Y i saw some videos of hunters in warmane and it's always 10 sec, i don't know anymore if it's a global issue.

**Comment by Gultask** [comment] 2022-04-22 21:46
Yes, unfortunately it's not a good practice to take other private servers' mechanics into consideration, because they have their own interpretation of what 3.3.5 mechanics were.
The most I ever found was that Trap Mastery at the start of the expansion just lowered the chances to resist the trap, making it ok for PvP. Nothing more after that.
I'll be closing the issue then, since we both had zero evidence on this.

**Closed by Gultask** 2022-04-22 21:46 UTC
Labels: PvP, Needs second opinion, More Research Needed

**Comment by TarekMadara** [comment] 2022-04-22 23:08
i think it's very early to close this, the description of the talent speaks about itself, is it really important to know how the behaviour of the spell was in Bliz server ? in my opinion it is still a PVP issue that need to be fixed.

**Comment by Gultask** [comment] 2022-04-22 23:53
The goal of Azerothcore, and consequently, Chromiecraft, is to be as close to blizz-like as possible, so it's very important to find sources of information regarding that era of WoW.

As for the description, I know it's weird (and sometimes even quite funny) but a lot of the times talent and aura descriptions can be very misleading. Actually there are 2 examples that I've seen of this recently: https://github.com/chromiecraft/chromiecraft/issues/3340 and https://github.com/chromiecraft/chromiecraft/issues/3309. Both issues are invalid because the current behaviour is blizzlike, even though their descriptions are very misleading.

I've looked for a couple of hours now in total and found nothing that would prove that Freezing Trap could have a duration other than 10 seconds, and I legitimately thought I scoured everything I could find.
If you want me to keep it open, however, I will, it's not a problem. It's just that I thought it wouldn't have any further developments. I wasn't trying to go against you, and maybe I really was too hasty in closing the issue, if you want me to keep it open for the time being just give me a shout ^^
