### ISSUE TITLE
glyph of rake binds on pick up

### ISSUE THREAD

**Issue by bojan112** [chromiecraft/chromiecraft#4736] opened 2023-01-03 03:39 UTC
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

glyph of rake made by inscriptors is BoP

### Expected Blizzlike Behaviour

all glyphs made by inscriptors are tradeable

### Source

![WoWScrnShot_010323_043333](https://user-images.githubusercontent.com/14837349/210297132-c54aa8f2-197f-49dd-9fe8-5d300960766d.jpg)

### Steps to reproduce the problem

1. craft glyph of rake with inscirption
2. binds on pickup, can not be traded

### Extra Notes

it's not the one bought from honor, it's made by inscriptionist 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by HasieEST** [comment] 2023-01-03 05:00
Every glyph is by default BoE including Glyph of Rake.

In database those might be ticked as BoP, in which case it is a bug, if it is BoE, then fault lies in ChromieCraft Progression system, that had made TBC and WoTLK Crafting skill requiring glyphs BoP due to it being sold via custom vendors.

https://www.wowhead.com/wotlk/item=40903/glyph-of-rake for Glyph of Rake.

**Comment by davegrier** [comment] 2023-01-08 03:51
Second opinion: Glyph of Rake, when crafted via Inscription, is BoP 
![image](https://user-images.githubusercontent.com/14080595/211179674-4592d282-90cd-43c7-8bbd-b6697bc47e19.png)

**Comment by BeefSteaker** [comment] 2023-01-09 14:25
Confirmed on live. linked to the progression module

**Comment by Gultask** [comment] 2023-01-30 23:30
Fixed in Live, sorry for the long delay. It'll be active next restart.

**Closed by Gultask** 2023-01-30 23:30 UTC
Labels: Confirmed, Linked [AC], Generic Issues

**Comment by switchpants** [comment] 2023-02-21 21:05
Glyph of Rake (Ethereal ink) is still bind-on-pickup as of Feb 21. Cleared Cache/WDB -- still BoP.

Can this be revisited/reopened?
