### ISSUE TITLE
[Dungeon Finder] Roll Rules for classic doungeons

### ISSUE THREAD

**Issue by Santaria94** [chromiecraft/chromiecraft#1460] opened 2021-08-18 12:42 UTC
### What client do you play on?

ruRU

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Now classes can only roll their own type of armor in classic dungeons. For example, druid healers can only roll leather, but cannot roll cloth.

### Expected Blizzlike Behaviour

Items that do not exceed level 70 should not have class restrictions on the type of armor. For example 35 ilvl cloth can roll paladins, shamans, druids.

### Source

Blue post:
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

> The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item.
The armor proficiency of the player’s class must not be higher than the item being rolled on. If it is, the player will unable to roll “Need.” For example: A level 75 warrior would unable to roll "Need" on certain mail items. **(This restriction will only come into play for items with an iLevel above 70.)**
If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors. Druids, paladins, death knights, and shaman may still roll "Need" on spell power items, provided that the above two conditions are met.

Video:
3:09 - paladin can roll leather
https://youtu.be/tTwgdv53FrU?t=190 

upd
2:50 - Shaman press "Need" Cloth Hands
https://youtu.be/546hZW_ohzg?t=170

6:02-6:04 - Shaman press "Need" Cloth Head
https://youtu.be/G2lbPy6VN_M?t=360

upd
8:50 - Shaman Greenar press "Need" Cloth Wrist
https://youtu.be/-3Sr-0pcZkg?t=531

7:10 - 7:37 - Druids Saine and Romane press "Need" Cloth Head
https://youtu.be/86CqyD7NfeU?t=430

upd

2:26 - Resto Shaman can press "Need" Cloth Chest and do it. This is cross server party consists of prot war, **resto shaman, mage**, hunter and rogue.
https://youtu.be/s2VokcGf3M8?t=146

### Steps to reproduce the problem

Queue for a dungeon finder.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-08-18 15:35
Any wiki page doesn't have this words.

**Comment by Santaria94** [comment] 2021-08-18 18:44
2:50 - Shaman press "Need" Cloth Hands
https://youtu.be/546hZW_ohzg?t=170

6:02-6:04 - Shaman press "Need" Cloth Head
https://youtu.be/G2lbPy6VN_M?t=360

**Comment by Santaria94** [comment] 2021-08-18 19:31
8:50 - Shaman Greenar press "Need" Cloth Wrist
https://youtu.be/-3Sr-0pcZkg?t=531

**Comment by Shineslippers** [comment] 2021-08-18 20:07
> 2:50 - Shaman press "Need" Cloth Hands

It's premade.

> 8:50 - Shaman Greenar press "Need" Cloth Wrist
7:10 - 7:37 - Druids Saine and Romane press "Need" Cloth Head

There is no cloth users in party.

**Comment by Santaria94** [comment] 2021-08-18 20:49
ok, this **cross server party** consists of prot war, **resto shaman**, **mage**, hunter and rogue.
2:26 - Resto Shaman can press "Need" Cloth Chest and do it
https://youtu.be/s2VokcGf3M8?t=146

**Comment by temperrr** [comment] 2021-08-20 13:39
I read through the sources and I believe them to be valid. Thanks for your report!

**Comment by 55Honey** [comment] 2021-08-20 13:45
This working as intended.the issue can safely be closed ob AC as well as CC.

**Comment by Azcobu** [comment] 2021-08-20 14:57
@55Honey: I've asked Temperrr not to close this until we have better documentation on why - though I realise being on holiday means you can hardly produce it at the moment - which is fine, there's no rush. Perhaps some of the other senior contributors can help out there.

My reasoning in keeping this open is irrespective of who is correct. If we close an issue, it should be clearly and thoroughly documented as to why. So far we don't have any of the sources or thinking that led to the decision that this is correct behaviour. Once those are recorded and available to inform future decisions, then we can evaluate them properly, on their merits, and proceed as normal from there.

**Comment by Santaria94** [comment] 2021-08-20 16:46
> This is working as intended. The issue can safely be closed on AC as well as CC.

At the time of Wotlk current restrictions worked only in TBC and WOTLK doungeons. The reason for this is that the classic dungeons did not contain specialized equipment for each spec (Plates with spell power for Holy Paladins, Mail for Resto Shamans, Leather for Resto Druid, etc). A saved post in BlueTracker explains that this restrictions only come into play for items with an item Level above 70. A lot of videos confirm this. If the above are not enough, then I can searh more video facts.

**Comment by Azcobu** [comment] 2021-08-21 03:08
Just had a read of the staff discussion Honey referenced above, and the only other new source presented there as evidence for correct behaviour was a link from WowWiki - https://wowwiki-archive.fandom.com/wiki/Need_Before_Greed?oldid=2360130

Other than that, I didn't see a definitive consensus or a final decision reached, so leaving this ticket open.

**Comment by Santaria94** [comment] 2021-08-21 05:04
https://www.wowhead.com/forums/topic/is-druids-noobs-if-they-roll-on-cloth-148356
> By Vaeku on 2010/03/14 at 2:17 AM (Patch 3.3.2)
You can only need on your highest armor proficiency (so leather for druids) in BC and WotLK dungeons.
**You can need on any armor in vanilla dungeons.**
So this didn't happen.

https://www.wowhead.com/forums/topic/levelling-a-paladin-as-healer-ok-to-need-on-cloth-leather-156692
>By Lecksand on 2010/05/18 at 1:37 PM (Patch 3.3.3)
Actually, you can roll need on them in pre-BC instances, regardless of armor type, if I'm not mistaken.

>By nihmue on 2010/05/18 at 4:06 PM (Patch 3.3.3)
Yep, just need on it if you need it. I've been leveling a resto shaman and have to roll on cloth too, since most leather and mail gear is just not itemized for us. I'd have to go half naked if I didn't. Sometimes I ask if I can need, sometimes I don't. I've never really had trouble, and the one time someone did say something a quick explanation about gear was enough. 
When you hit Outland it's gonna be harder since the system prevents you from rolling need and you have to ask members of your pug if they would give the item to you/not roll on it when you really need it. Then again, gear drops also start getting a little better itemized for leather/mail/plate healers by then.

https://www.wowhead.com/forums/topic/anti-looting-policy-164007
>By oberondreaming on 2010/07/22 at 1:14 AM (Patch 3.3.5)
While you're leveling, up to, what BC, you can need on anything you want to. (If anything the problem while leveling is people needing on things they can't use/don't need/can't wear.)
After you hit BC, you can honestly get plenty of good gear by running a few quests in between queues.

**Comment by 55Honey** [comment] 2021-08-21 08:16
> > This is working as intended. The issue can safely be closed on AC as well as CC.
> 
> At the time of Wotlk current restrictions worked only in TBC and WOTLK doungeons. The reason for this is that the classic dungeons did not contain specialized equipment for each spec (Plates with spell power for Holy Paladins, Mail for Resto Shamans, Leather for Resto Druid, etc). A saved post in BlueTracker explains that this restrictions only come into play for items with an item Level above 70. A lot of videos confirm this. If the above are not enough, then I can searh more video facts.

Can we get a link to this bluepost? That would drastically shorten the search.

**Comment by Azcobu** [comment] 2021-08-21 08:27
The link to the specific post is https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/#5

**Comment by syssneck** [comment] 2021-08-21 09:28
If I'm not mistaken, rule one from the blue post is also not in place (yet): 

"The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item. "

I was not able to roll on plate with my warrior before lvl 40. The same goes for paladins (can't roll on plate before lvl 40 but should be able to) and shamans and hunters for mail.

**Closed** 2021-09-02 08:39 UTC
Labels: Confirmed, Linked [AC], Generic Issues
