### ISSUE TITLE
Nancy Vishas in Alterac Mountains doesn't aggro

### ISSUE THREAD

**Issue by InstructionSeeker** [chromiecraft/chromiecraft#259] opened 2021-03-20 14:09 UTC
##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

![JmIlTdooMI](https://user-images.githubusercontent.com/60620452/111872335-13792580-898e-11eb-9ff4-239aac23432e.png)
[Nancy Vishas](https://wotlkdb.com/?npc=3984) in Alterac Mountains doesn't aggro when the player gets close, neither attacks back when she's attacked by the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should aggro when the played gets too close and attack back.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Alterac Mountains and find Nancy Vishas.
2. Get close and attack her.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment] 2021-03-20 14:33
Duplicate of issue ticket [**NPC not responding to combat.**](https://github.com/chromiecraft/chromiecraft/issues/222) #222

**Comment by Helias** [comment] 2021-03-20 15:39
thanks guys

**Closed by Helias** 2021-03-20 15:39 UTC
Labels: Needs Triage
