### ISSUE TITLE
Achievement Explore Arathi Highlands is bugged

### ISSUE THREAD

**Issue by mitza987** [chromiecraft/chromiecraft#1793] opened 2021-09-19 16:27 UTC
### What client do you play on?

enUS

### Faction

- [] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Go'shek Farm and Hammerfall do not count as explored so you can't complete the achievement

### Expected Blizzlike Behaviour

Go'shek Farm and Hammerfall should be explored after you visit them once

### Steps to reproduce the problem

1. Go to Arathi Highlands
2. Go to Go'shek and Hammerfall
3. They will show as not explored on the achievement tab

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment] 2021-09-19 17:59
Works just fin for me.

Is the character in question a carbon copy by any chance?

**Comment by mitza987** [comment] 2021-09-19 18:21
No. It is my main character

**Comment by gurveleg** [comment] 2021-09-19 18:38
Try moving to different locations inside those two areas, see if it pops up.

**Comment by mitza987** [comment] 2021-09-19 19:11
Did it. Shown as discovered on the map but undiscovered in the achievement

**Comment by Azcobu** [comment] 2021-11-02 10:24
Closing as we're unable to reproduce this.

**Closed by Azcobu** 2021-11-02 10:24 UTC
Labels: Needs Triage, Unable to Reproduce
