### ISSUE TITLE
Corrupted Whipper Root in Felwood not working

### ISSUE THREAD

**Issue by Pall183** [chromiecraft/chromiecraft#2460] opened 2021-12-03 19:17 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Corrupted Whipper Roots in Felwood aren’t working. I tried to turn in 3 Cenarion Plant salves to receive Whipper Root Tubers but nothing happens.

### Expected Blizzlike Behaviour

I think a cleansed version of the plant should spawn on the location of the old plant which can be looted but this doesn’t happen.

### Source

![5D097684-EC19-4AA5-B5A4-466BF7295D6C](https://user-images.githubusercontent.com/95500411/144660149-7e5a1b97-fca8-42c0-b31f-cc33db349726.jpeg)

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hammergodx** [comment] 2021-12-04 00:39
Confirmed, also all other corrupted plants in Felwood are bugged

**Comment by cachocarne** [comment] 2021-12-04 19:39
I don't quite understand. Completing the quest does not grant you any reward other than experience. It's not a bug, it's the way it works.
AFTER you have cleansed on the plant, you can click on it –it will be healthy and colorful– and you will gain either a buff or get some food.
I have very recently done Songflower and got the buff with no problem. 
Also I could complete a few Windblossom and Whipper Roots hey are giving the Berries and Tubers.
I might still have them on my inventory, will check.

Can't confirm about the Night Dragon but probably they are working too, I don't see a reason why they wouldn't.

**Comment by Pall183** [comment] 2021-12-04 19:50
The thing is that the plant should change after being cleansed so it can be looted but mine just stays on the quest marker without any loot

**Comment by Pall183** [comment] 2021-12-04 19:53
I have turned in the quest for like 4 times and stood there each time for a minimum of 5 minutes but the plant just stays corrupted and quest marker stays there

**Comment by Pall183** [comment] 2021-12-04 19:57
> 



> I don't quite understand. Completing the quest does not grant you any reward other than experience. It's not a bug, it's the way it works. AFTER you have cleansed on the plant, you can click on it –it will be healthy and colorful– and you will gain either a buff or get some food. I have very recently done Songflower and got the buff with no problem. Also I could complete a few Windblossom and Whipper Roots hey are giving the Berries and Tubers. I might still have them on my inventory, will check.
> 
> Can't confirm about the Night Dragon but probably they are working too, I don't see a reason why they wouldn't.

How long ago did u turn in the plant quest? Can u test it now, like maybe then I definitely know it’s a problem with my client or something

**Comment by Hammergodx** [comment] 2021-12-04 21:27
I was trying to do it yesterday, needed Night Dragon for 100 health enchant. Couldn't get it to work. So I tried different spawns and different corrupted plants, but none gave me anything

**Comment by Pall183** [comment] 2021-12-05 09:53
Can a contributor confirm this or atleast tell me it’s not broken since it seems like some others have this problem as well… idk why this post gets ignored

**Comment by Shineslippers** [comment] 2021-12-05 11:01
Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear. Let me know if it will not happend.
![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)

![WoWScrnShot_120521_135954](https://user-images.githubusercontent.com/85256266/144743777-28f7f1b3-3a22-474a-b379-adcdb0ae2ed7.jpg)

**Comment by theo1143** [comment] 2021-12-08 01:20
> Thank you for the report. Unfortunatelly i can't reproduce it on local AC. We already got some other reports regarding to issues with objects on CC server. Maybe it's related to scripts update. So probably current issue will be fixed with next CC server update. Current version of CC you can see on screenshot below. When it will be changed issue should disapear. Let me know if it will not happend. ![WoWScrnShot_120521_062440](https://user-images.githubusercontent.com/85256266/144732197-434887b3-87c8-4de0-84ac-db6b5f4740c5.jpg)
> 
> ![WoWScrnShot_120521_135954](https://user-images.githubusercontent.com/85256266/144743777-28f7f1b3-3a22-474a-b379-adcdb0ae2ed7.jpg)

And when will that be?
These have been bugged after the server restart that happened 4 days ago.
It is a biggy because soon after 60 I won't be using them but right now it is helpful.
Seeing healing pots go sky high only because of these wannabe pots being bugged...

**Comment by neifion-00000000** [comment] 2021-12-08 04:41
still broken today, and this applies to all felwood plants

they used to work not too long ago

**Comment by Shineslippers** [comment] 2021-12-08 05:38
Fix is ready https://github.com/azerothcore/azerothcore-wotlk/pull/9574/files , but still not uploaded

**Comment by Pall183** [comment] 2021-12-09 14:10
Is there a date on when the fix will be uploaded?

**Comment by Shineslippers** [comment] 2021-12-09 14:14
This fix https://github.com/azerothcore/azerothcore-wotlk/pull/9574 is already merged to AC core and everything from this moment on Admins who is holding update button. I can give you futher info. Maybe some of GMs know it.

**Comment by Nitram137** [comment] 2021-12-10 13:40
The latest update went live yesterday evening, so I had a try with Night Dragon's Breath today. Turning in the salves still does nothing.

**Comment by Shineslippers** [comment] 2021-12-10 19:26
@Nitram137 well, wtill not fixed. I'm sorry i can't nothing to do with it. Devs is noticed.

**Comment by theo1143** [comment] 2021-12-11 06:33
This is chromiecraft in a nutshell ... fixing nothing and only raising problems

**Comment by Shineslippers** [comment] 2021-12-11 07:13
Even `ScriptLoadFix Branch` doesn't wanna work. Well, they're trying
![Capture](https://user-images.githubusercontent.com/85256266/145668026-c1c9ad16-d4e2-4a99-8a3a-bf2b53dd6413.PNG)
.

**Comment by morpez121** [comment] 2021-12-11 17:52
tried today because I need Night Dragon for 100 health enchant.
"Corrupted night dragon" plants remains "corrupted" when clicked.

**Closed** 2021-12-14 22:53 UTC
Labels: Waiting for more feedback, Unable to Reproduce, Bug Under Evaluation
