### ISSUE TITLE
[Fire Festival] Too many fires in Ironforge.

### ISSUE THREAD

**Issue by Nom-D-Plum** [chromiecraft/chromiecraft#5821] opened 2023-06-22 02:38 UTC
### What client do you play on?

enUS

### Faction

Alliance and Horde

### Content Phase:

Generic

### Current Behaviour

There are a lot of fires at the Ironforge Fire Festival location.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/227af7d1-3f1e-4259-b152-56c8cff9191d)

Edit: The same thing is happening in Stormwind.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/77b419de-17d5-404f-9fdc-59f6604c9bd7)

Edit: And Exodar.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/e4c05950-3b47-42bc-8c09-1ba381164a25)

Edit: And Darnasus.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/3dfd7f7a-ccd5-49a5-a7ba-01751698628c)

Edit: And Silvermoon.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/9d557549-2c1f-4728-949e-62a1ea2c7c7f)

Edit: And Undercity

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/045816d5-8c3d-4fc0-90c4-ebe005d0cc1f)

Edit: And Orgrimmar.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/e8caf076-69e7-4c5f-a61f-3234fa7eb1ea)

Edit: And Thunder Bluff.

![image](https://github.com/chromiecraft/chromiecraft/assets/137365741/4171a93f-f29c-4cec-8ac5-251bfb343b46)

So too many fires in all the capitals.

### Expected Blizzlike Behaviour

Not this many fires.

### Source

This was the only relevant screenshot I was able to find for Wrath of the Lich King.  From https://www.wowhead.com/wotlk/quest=9331/stealing-ironforges-flame

![image](https://wow.zamimg.com/uploads/screenshots/normal/85132-stealing-ironforges-flame.jpg)

### Steps to reproduce the problem

1. Enter the Hall of Explorers in Ironforge.
2. See too many fires.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-06-23 05:54
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/3677.

**Closed by heyitsbench** 2023-06-23 05:54 UTC
Labels: Needs Triage
