### ISSUE TITLE
[Spell] Faerie Fire stackable

### ISSUE THREAD

**Issue by Ziedge** [chromiecraft/chromiecraft#1133] opened 2021-07-08 13:57 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

You can stack faerie fire (feral version and normal one) on the same target.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only one faerie fire debuff should be available on the target.

##### STEPS TO REPRODUCE THE PROBLEM:

1. First player cast faerie fire (feral) on a target
2. Cast faerie fire (normal version) on the same target
3. See that both debuff are affecting the target

https://user-images.githubusercontent.com/82708448/124934441-fdf33e80-e004-11eb-87d6-73c790b82183.mp4

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by eTzmNcbkrng** [comment] 2021-07-09 08:28
Unable to reproduce this, tried on the same NPC - https://wotlkdb.com/?npc=12225

**Comment by Ziedge** [comment] 2021-07-09 08:44
Encountered it several times, not always on the same npc

**Comment by Azcobu** [comment] 2021-07-10 04:29
Did some experimenting with this, and found that the two FF debuffs do stack, but only one actually affects the target.

Here's a draeni target dummy with 11417 armour and no FFF debuffs:
![WoWScrnShot_071021_133639](https://user-images.githubusercontent.com/81782124/125151423-243fe800-e185-11eb-8ee9-1b2020c137c0.jpg)

One FFF takes it down to 11417 * 0.95 = 10846.15 armour:
![WoWScrnShot_071021_133654](https://user-images.githubusercontent.com/81782124/125151436-3e79c600-e185-11eb-816e-066ab9b1f1c7.jpg)

Second Faerie Fire stacks but doesn't affect armour total:
![WoWScrnShot_071021_134111](https://user-images.githubusercontent.com/81782124/125151465-797bf980-e185-11eb-91b1-07400aaf73b2.jpg)

Checking TBC Wowhead shows this may be intended behaviour. A comment there says "It (FFF) doesn't stack with ur own caster-faerie fire but it does stack with other druids FF." (https://tbc.wowhead.com/spell=16857/faerie-fire-feral#comments:id=2748159)

Also found a forum thread on MMO-C discussing FFF during the Wrath period, and they're complaining that the FF icons were stacking even then:

> One can now apply Imp FF, FFF regular FF and misery. Without that retarded message of more powerful spell already applied. It's just an interface glitch...Mine are all non-stacked icons.

(https://www.mmo-champion.com/threads/646710-Faerie-Fire)

So weird as it sounds, this appears to be Blizz-like.

**Comment by Ziedge** [comment] 2021-07-10 06:05
Allright, this is very weird tho, I don't remember it being stackable when I was playing official back then!

**Comment by temperrr** [comment] 2021-07-14 07:00
I could not find any other evidence regarding this as well. If you do find any evidence Ziedge that supports that this is not blizzlike, feel free to comment. Closing it now!

**Closed by temperrr** 2021-07-14 07:00 UTC
Labels: Needs Triage, Needs second opinion
