### ISSUE TITLE
[Quest] The Flesh Lies... - Withered Corpses spawn too long & not enough spawn

### ISSUE THREAD

**Issue by dieing4me** [chromiecraft/chromiecraft#4960] opened 2023-02-11 00:32 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Withered Corpses take upwards of 30 minutes to spawn and only spawn in a small part of their intended area outside the mine

### Expected Blizzlike Behaviour

Spawn time reduced and spawn throughout the mine

### Source

Video of the quest:
https://www.youtube.com/watch?v=vJL5WeoS9aw

### Steps to reproduce the problem

Accept the quest "The Flesh Lies..." at 59.34 , 45.12
Go to 61..01 , 46.06
Use the Protectorate Igniter from accepting the quest on the Withered Corpses
Wait for the rest of the Withered Corpses to spawn to complete the quest and trek through the mines to see the lack of more spawns.

### Extra Notes

There is also less hostile mobs in the mine than are supposed to be present.
Quest: https://wowgaming.altervista.org/aowow/?quest=10345
Withered Corpse: https://wowgaming.altervista.org/aowow/?npc=20561
Protectorate Igniter: https://wowgaming.altervista.org/aowow/?item=29473

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by whipowill** [comment] 2023-02-17 06:25
Can confirm.  Only 2 bodies outside the mine, none inside.  Quest is to burn 12.

**Comment by Tereneckla** [comment] 2023-02-17 07:22
Duplicate of #5023

**Closed by Tereneckla** 2023-02-17 07:22 UTC
Labels: Duplicate
