### ISSUE TITLE
[Spell][Night Elf] Shadowmeld is not working properly

### ISSUE THREAD

**Issue by Md-Knox** [chromiecraft/chromiecraft#1300] opened 2021-07-27 16:57 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Current Behaviour
Shadowmeld is not working as intended.
It will simply not drop mob aggro unless you are at minimum couple of yards away from the mobs (not melee range)
It has not worked a single time for me when mobs are in melee range.

Same issue as here: https://github.com/chromiecraft/chromiecraft/issues/153

Same problem as vanish: https://github.com/chromiecraft/chromiecraft/issues/1181

### Expected Blizzlike Behaviour

Shadowmeld and vanish are supposed to drop all aggro and reset mobs. 

### Source

https://streamable.com/lilqo1
https://streamable.com/g3wikg
https://streamable.com/r3j1pb
https://streamable.com/au8b5d

### Steps to reproduce the problem

get on chromiecraft, not azerothcore
get in melee combat with a mob (try both green, yellow and red)
press vanish/shadowmeld

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-07-29 13:23
Thanks for the report. Shadowmeld looks to have been the subject of quite a few previous issues and fixes, which is a bit concerning. I can confirm that if you get into melee range with an NPC and try SM, the NPC will almost always detect you and re-engage. The question is whether this is Blizz-like behaviour or not.

Reading the notes from the last fix to SM (https://github.com/azerothcore/azerothcore-wotlk/pull/4857) it seems the conclusion was that SM should work this way. The argument is that SM just puts you into stealth. As you are so close to an enemy NPC, the enemy then sees through your stealth straight away, as any enemy would, and attacks you again. SM has worked, but the stealth is just like any other stealth (not improved like Vanish) and can therefore be detected if an enemy is close enough. As evidence that this is expected, @Sedatyf tested this scenario in https://github.com/azerothcore/azerothcore-wotlk/pull/4857#issuecomment-820771099. 

I also found a comment on WH that seems to confirm this: "It [SM] works great, sending the nasties back to where they came from - usually. Patrols may not move far enough, and they will see through your stealth if they're right on top of you." - https://www.wowhead.com/spell=58984/shadowmeld#comments:id=1026234

So that's what I think the argument was for SM working the way it does right now. I'm not sure if that's accurate - there's a ton of ambiguity and edge cases here - but I think we'd need to see other sources that showed SM working differently on a retail server before we could be sure the above was wrong. I'll leave this ticket open, and if you can find any such sources, feel free to send them along.

**Comment by Md-Knox** [comment] 2021-07-29 15:46
Simply look at the way it acts versus neutral mob    https://streamable.com/r3j1pb
and then look at the way it acts against aggressive mob   https://streamable.com/au8b5d

It should be working as vs neutral mob for everything. 
It has nothing to do with enemy seeing you or not, it should just drop the combat if you are last on it's aggro table, as mentioned on wiki https://wowpedia.fandom.com/wiki/Shadowmeld

Regarding your wowhead comment. It's clearly related to AFTER shadowmeld has been used. It removes you from combat AND puts you into stealth. If, a mob however walks up to you while you are in stealth afterwards, it may discover you depending on level difference and position.
Also you can take a deeper look at the wowhead comments. Not a single person mentions where you have to at range of the enemy for it to work. 

This is why shadowmeld + flight form is a thing. You can shadowmeld, instantly leave combat and fly away while the mob is resetting to it's place. Or shadowmeld > cat > prowl It has never failed me on retail or any other private server I played on. Chromie is the first where I experienced shadowmeld acting like this.

The only source you need is retail. Shadowmeld hasn't changed it's functionality since wotlk. Only change was in cata when it was allowed to use in form instead of reverting you to humanoid. No changes to the way it works since wotlk.
I have re-downloaded retail just to capture this video. Compare it to above clips. (Yes it's vs same level, because of level scaling.)
My night elf is currently 49 and it hasn't worked since the start.

RETAIL CLIP  -------  https://streamable.com/ah8ijy

As you can see, it works exactly the same as VS yellow(neutral) mob on chromie.

**Comment by Sedatyf** [comment] 2021-07-30 09:39
The shadowmeld case is a bit hairy as there is a lot of test cases to consider. And when you change something, you might have a regression somewhere else. Regarding the fact is shadowmeld blizz-like in chromiecraft, I can't tell for sure. But as we discussed in the previous link, it seems current behavior is the right one. 
Is your test on retail is on current patch (ie Shadowlands)? It might have been changed since then

**Comment by Md-Knox** [comment] 2021-07-30 11:16
Any of you have yet to acknowledge the difference in behaviour between neutral (yellow) and aggressive(red) mob, as shown in clips.   
Instead, Azcobu quoted a comment on wowhead which I can't find, that he misread and misunderstood what was written, as opposed to reading every single other comment which says it drops combat.   
Go and test it. If it doesn't drop the combat from the mob, it's not working correctly. Show me another server where it works like on chromie. I have yet to find a single one, including retail.    

It's shadowlands retail, live server. Download it (only need 2% to open it) and play it, it has free trial. Shadowmeld has not changed in its mechanical functionality since WotLK, only light QoL in cataclysm for druids (form shadowmeld).  

I have made my case, you deniers have not. Just baseless assumptions. 

I don't know how many more examples and what do I need to show you to even acknowledge what I'm showing. You are not even mentioning interactions in the clips.

**Comment by Azcobu** [comment] 2021-07-31 01:27
Well, thought I'd try to be fair and listen to arguments instead of just closing the ticket as 'working as intended', and this is the result. I was actually quite willing to be persuaded the SM wasn't working properly, as I had no strong opinions either way and simply wanted to see evidence. But you've now convinced me, not that SM is faulty, but you have managed to convince me that this discussion isn't going anywhere useful.

Closing as reporter is unable to be civil or constructive.

**Closed by Azcobu** 2021-07-31 01:27 UTC
Labels: Bug Under Evaluation, WFMD

**Comment by petersaints** [comment] 2021-08-07 18:45
@Azcobu I don't think this should be closed. There is compelling evidence that the current behavior is not Blizzlike. I mean, the situation has improved compared to a few months ago, but red mobs in melee range will still break through the effects of Shadowmeld. Getting access to

**Comment by Azcobu** [comment] 2021-08-08 04:29
Well, it would be a pity to ignore an important issue for non-technical reasons. I see you had a long-running ticket for this issue as well (https://github.com/chromiecraft/chromiecraft/issues/153), with significantly more details, so I'd be more inclined to re-open that one. Though I feel I should ask, is the compelling evidence you mentioned the video links above, or did you have other sources/evidence in mind?

Anyway, I've also contacted the person who made the last fixes to SM that you mention, to get their thoughts on this and see if they have anything to add.

**Comment by petersaints** [comment] 2021-08-09 10:21
I mean there are have been various arguments towards a slightly different behavior. For instance, looking at this patch note:

> Patch 3.0.8 (2009-01-20): This ability will now properly restore threat when it is canceled. In addition, it will correctly remove a player from combat if it is active when that player is the last person left alive that the creature hates. This ability is now also unusable while affected by Spell nature faeriefire.png [Faerie Fire].

Source: https://wowpedia.fandom.com/wiki/Shadowmeld

It says that a player should be removed from combat if it is the last person that the creature hates. Right now,  it simply stealths you for a brief moment but a melee mob continues to target you and to attack you, which immediately breaks the stealth effect.
