### ISSUE TITLE
Kirtonos the Herald ability Curse of Tongues

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#2315] opened 2021-11-13 03:17 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

When fighting [Kirtonos the Herald](https://wowgaming.altervista.org/aowow/?npc=10506), he will use his ability [Curse of Tongues](https://wowgaming.altervista.org/aowow/?spell=12889). This spell is affecting my rogue's Sinister Strike and causes it to be unusable for a half second after the global cooldown. 

Here is a video of the problem: https://www.youtube.com/watch?v=aF06or1jyPo

### Expected Blizzlike Behaviour

The curse description states "reducing their casting speed by 50% for 15 sec"
Global cooldown should not be affected. 

### Steps to reproduce the problem

Go to Scholomance
Start the Kirtonos the Herald event,
Attack Kirtonos the Herald and let him curse you. 
Use an instant cast ability over and over and see the results. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-13 11:14
Well, this is serious question. Anyway this report is duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5136

**Closed** 2021-11-13 12:14 UTC
Labels: Duplicate, Closed
