### ISSUE TITLE
Shockwave hitbox

### ISSUE THREAD

**Issue by Sfaccim** [chromiecraft/chromiecraft#3946] opened 2022-08-18 03:02 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Why sometims, very frequently, even if the enemy is in the cast anymation of the spell shockwave doesent even hit  the enemy? not like a miss or a  resist just missed and clearly it doesent

### Expected Blizzlike Behaviour

.

### Source

.

### Steps to reproduce the problem

doesent exist the hitbox?

### Extra Notes

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a
.ok

### Operating system

Ubuntu 20.04
.ok

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None
.

### Server

ChromieCraft

**Comment by ishidinho** [comment] 2022-08-18 06:18
Hey @Sfaccim. Again, please be respectful.
The higher the quality of a bug report the better and faster our devs can fix it.

However, your poor description did not help me to reproduce the problem.

Can you provide screenshots or video snippets? Maybe you can reproduce the problem on train dummies. As said, I was not able to.

**Comment by The-GhostRider** [comment] 2023-06-20 19:59
I am also unable to reproduce the issue that you claim exists.
I believe it may be an (missed) effect of your client. (If I understand correctly what you are saying).
Furthermore, ishidinho requested a more detailed explanation of the problem from you 10 months ago, on Aug 18, 2022, and you have not provided any additional details since then. I believe it is sufficient time to consider closing the report due to lack of information and interest from the report creator.

**Closed by The-GhostRider** 2023-06-20 19:59 UTC
Labels: Waiting for more feedback, Unable to Reproduce, Wrongly Filled Form
