### ISSUE TITLE
Blacksmithing - Crafted 5 Golden Rods but none of them spawned in my bags

### ISSUE THREAD

**Issue by TheRiddermark** [chromiecraft/chromiecraft#1446] opened 2021-08-16 21:15 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Issue: Upon crafting a [Golden Rod](https://wowgaming.altervista.org/aowow/?item=11128) nothing appeared in my inventory.

**Explanation:**
I was leveling my Blacksmithing and the guide I was following noted to make 5 pieces of Golden Rod from 150 to 155 skill level. I went to Ironforge anvil and put the process on automatic (craft all). I had materials to make 9 Golden Rods

My inventory was closed and the only thing open on screen was my Blacksmithing window. After crafting 5 rods I went to the mailbox to send 1 to a friend and when I opened the bags - there were 0 rods inside.

Eager to reproduce it, I went back to the anvil. Please note my skill was up to 155 from 150, my materials were down so I could only make 4 more rods. The crafting did happen and consumed the mats, but the rods never spawned in my bags.

This time I had my bags OPEN while crafting and I could see the rods popping in them.

### Expected Blizzlike Behaviour

Expecting anything crafted to appear in the bags always.

### Steps to reproduce the problem

1. Craft multiple [Golden Rod](https://wowgaming.altervista.org/aowow/?item=11128)s by clicking "Create All"
2.  Have your bags closed during the process
3. Interrupt the process at 5 crafted rods by moving the character
4. Open the bags and see if the rods are there

### Extra Notes

I apologize if the report is lacking but I thought I'd better report it and risk annoying people than ignoring the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment] 2021-08-16 23:19
Did you recently equip the bag in question? Is this an empty bag or is there something already in it? I had a bag issue myself not too long ago and had trouble duplicating it. I'm curious about the specifics.

**Comment by jamadaha** [comment] 2021-08-17 09:41
Tested on local server(AC 28a764641)
I could not reproduce it on my local server. Followed the steps, with only the starting bag equipped, but closed. And received the 5 out of 5 rods.

**Comment by TheRiddermark** [comment] 2021-08-17 10:00
@Stump876 , I did get the last bag (number 5) in my only run in BRD (if I'm not mistaken) earlier that day. But it wasn't 5 minutes ago, more like a few hours later, when I did the crafting thing. I want to say it was only the last bag that had free space.

This is my bag configuration:
1.Base
2.[Thawpelt sack](https://wowgaming.altervista.org/aowow/?item=9587) F11
3.[Journeyman's Backpack](https://wowgaming.altervista.org/aowow/?item=3914) F10
4.[Journeyman's Backpack](https://wowgaming.altervista.org/aowow/?item=3914) F9
5.[Traveler's Backpack](https://wowgaming.altervista.org/aowow/?item=4500) F8

* Here's how the bags [look](https://pasteboard.co/KghOSIa.png). I'm using the addon - Bagnon_2.13.3
* [A video clip here](https://imgur.com/5JbvciT) of me trying to reproduce and record the bug - as u can see it works and they show up, but at least you can observe the bag configuration and space.

**Comment by Stump876** [comment] 2021-08-17 17:40
I'm assuming you didn't log out in between obtaining the new bag and seeing this issue. Did these items disappear completely, or did they appear when you logged in again?

**Comment by TheRiddermark** [comment] 2021-08-17 22:42
> 
> 
> I'm assuming you didn't log out in between obtaining the new bag and seeing this issue. Did these items disappear completely, or did they appear when you logged in again?

No I haven't done any re-logging prior to the incident. As far as I know they never appeared in my bags. After creating them I ran straight to the mailbox because I was chatting with 2 people to possibly send them a piece. Then when I opened the bags I discovered the items weren't there. I told global chat, they advised me to /reload. That didn't help so I re-logged. But they still weren't there.

Then I went straight back to the forge and recorded the video I linked above in hope of reproducing it.

**Comment by Stump876** [comment] 2021-08-18 01:03
I've noticed on CC, items placed in some newly acquired bags tend to not show anything in them. The items _are_ there in the bag, they just do not show up for whatever reason. This goes for anything in the bag. Using a bag add on in this case isn't really helping because you cant tell which bag is causing the problem. 

I haven't nailed down exactly what causes it. I've mostly noticed it from bags taken from a guild vault. I haven't confirmed bags bought off the auction house, or bags rolled for. It doesn't seem to work with bags bought with Chromie points, bought from a bag vendor, or straight looted (at least not the ones I've looted) Bags rolled for might be different.

Moving the bag positions in your backpack will show them temporarily, and a relog will fix it. I haven't been able to reproduce this in a clean AC server either, so it might be CC specific. But I've never had items completely disappear. Unfortunately without a way to reproduce it there really isn't much we can do.  I'm going to close this for now, but if anyone finds something new please put it in here, and we can re-open it.

**Closed** 2021-08-18 01:04 UTC
Labels: Unable to Reproduce
