### ISSUE TITLE
Fell thru the floor upon dismounting from a flight, Stormwind

### ISSUE THREAD

**Issue by Aleksiye** [chromiecraft/chromiecraft#1625] opened 2021-09-04 14:30 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Upon taking a flight from Westfall to Stormwind I found myself falling thru the floor and onto the ground underneath Stormwind 
![Screenshot_2](https://user-images.githubusercontent.com/89442337/132097901-c059cc2d-e78d-4ed2-84c5-e59990a8b9eb.png)

### Expected Blizzlike Behaviour

I expect not to fall thru the floor

### Steps to reproduce the problem

Take a flight from Westfall to Stormwind

### Extra Notes

I was playing on 4G mobile connection, there's a very slight possibility it might be related to that, but, I wasn't the only player that fell thru.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment] 2021-09-06 10:47
I heard and saw this now from some players, so I will set it to confirmed.

**Comment by VFaleiro** [comment] 2021-09-22 05:45
Just happened to me. Took a flight to Undercity (from Silverpine), alt-tabbed, and I when I alt-tabbed back I was in the middle of the floor (could see the green water when looking down).
Not a big deal though, a single jump got me to where I should have been.

**Comment by lsevoDev** [comment] 2021-10-16 10:01
Happened to me 2 flying from IF to Stormwind using client with warlords of dranor models

**Comment by Shineslippers** [comment] 2021-11-24 16:42
Since it's client side issue we can to do nothing. Have to close this report.

**Closed by Shineslippers** 2021-11-24 16:42 UTC
Labels: Closed, Game Client Bug
