### ISSUE TITLE
[Achievement] Looking For More

### ISSUE THREAD

**Issue by armchairrockstar1** [chromiecraft/chromiecraft#7377] opened 2024-09-25 09:43 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Looking For More (Also nested achievements: Looking For Many and Looking For Multitudes) isn't getting any credit when a party member is vote-kicked and replaced before finishing the random heroic dungeon. 

### Expected Blizzlike Behaviour

Normally finishing the the random heroic dungeon correctly yields 4 credits. Kicking and replacing someone before the last boss shouldn't change this behaviour.

### Source

![Screenshot (271)](https://github.com/user-attachments/assets/53c4836f-4bbd-4261-8caa-6a6ed59c3657)

### Steps to reproduce the problem

1. Join a random heroic dungeon
2. Vote-kick and replace a player (maybe also happens when someone leaves and is replaced)
3. Kill the last boss
4. Check the achievement progress (+0)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/78cc255f43fd382df6629a315bf2486cf075ea8a

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-09-25 13:15
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/6013.

**Closed by heyitsbench** 2024-09-25 13:15 UTC
Labels: Needs Triage
