### ISSUE TITLE
Chains of Naberius bug

### ISSUE THREAD

**Issue by bruhboy22** [chromiecraft/chromiecraft#6152] opened 2023-09-17 20:59 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

in the quest "Destroy Naberius!", you're to slay Naberius at 62.7, 79 in Netherstorm, Kirin'Var Village.
Naberius has a few abilities, but the ability there is an issue with is his ability called "Chains of Naberius"
Chains of Naberius is an instant-cast spell with unlimited range that is only expected to be used by Naberius whenever there is more than one other player fighting Naberius.
The bug at hand is that "Chains of Naberius" triggers even when you are fighting Naberius solo, and there are no other toons around. This is an issue because Naberius has 21.6k HP and when he casts Chains, you are MC'd and are automatically moved by his side, releasing you from combat for a short amount of time. During of which, Naberius heals back to full due to him being out of combat. This bug practically makes Naberius invinicible unless you're able to deal enough damage before he uses his Chains.
![Wow_UFeRSIq3pG](https://github.com/chromiecraft/chromiecraft/assets/42710676/b806ea41-9d40-4e3c-b3bf-b7a92ae5144a)

### Expected Blizzlike Behaviour

It is expected that Naberius shall not cast "Chains of Naberius" when there is only one character/player fighting Naberius. 

### Source

https://www.wowhead.com/tbc/quest=10320/destroy-naberius#comments
https://www.wowhead.com/wotlk/spell=36146/chains-of-naberius

### Steps to reproduce the problem

1. Fight Naberius solo

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-09-18 14:41
Duplicate of #5981.

**Closed by heyitsbench** 2023-09-18 14:41 UTC
Labels: Needs Triage
