### ISSUE TITLE
Body and Heart quest does not show on map

### ISSUE THREAD

**Issue by smartypantsali** [chromiecraft/chromiecraft#1288] opened 2021-07-25 08:39 UTC
Accept body and heart quest, go to darkshore and it doesnt show on minimap. (Alliance)

**Comment by smartypantsali** [comment] 2021-07-25 08:48
Looks like its happening with other quests randomly as well.

**Comment by necropola** [comment] 2021-07-25 09:23
Duplicate of #275
And please use the template and provide a bit more detail, e. g. quest id next time.

**Closed by necropola** 2021-07-25 09:23 UTC
Labels: Closed, Duplicate
