### ISSUE TITLE
Multiple Hunter bugs

### ISSUE THREAD

**Issue by anonymousbugreporter2602** [chromiecraft/chromiecraft#3135] opened 2022-02-26 10:46 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Hello!
My lvl 20 hunter is missing the ["Beast training"](https://wowgaming.altervista.org/aowow/?spell=5149) spell:
![WoWScrnShot_022622_095939](https://user-images.githubusercontent.com/100464468/155838384-d836a6e4-2571-4178-9af5-cd344f482c82.jpg)
![WoWScrnShot_022622_095944](https://user-images.githubusercontent.com/100464468/155838390-a0069523-0edb-4373-803a-13c7d9ad5598.jpg)
As you see, the spell is not in the spellbook... but as far as I know - it should be there. Also, the "Steps to reproduce" section contains a list of other bugs.

The pet trainer also does not show any spells to learn (screenshot after "How do I train my pet" question):
![WoWScrnShot_022622_114626](https://user-images.githubusercontent.com/100464468/155838453-3b22bfb3-6bd2-4761-8acf-781be7f79efb.jpg), but when I tame a new pet - there are messages in logs, that new pet's spells are learned successfully.

### Expected Blizzlike Behaviour

Either the final "Taming the beast" or "Beast training" quest should teach the hunter's "Beast training" ability (I don't know exactly, which one).

### Steps to reproduce the problem

1. Create a dwarf hunter on test server
2. ".level 9", to be able to take class quest
3. Get the "Taming the beast" quest from Grif Wildheart in Kharanos.
4. Tame a boar, and complete the quest. Get the next quest part to tame a snow leopard.
5. Approach the snow leopard, and wait for the boar to be killed by it - cause there is no other way to get rid of the animal (must be a bug?).
6. Tame snow leopard, complete the quest, then do the same for bear.
7. Complete the final "Taming the beast" quest - the bear stays with you, as expected, but it's running speed is slow, and size is big (must be another bug!). 
8. Get the final "Training the beast" quest.
9. Now open the spellbook, and call "Dismiss pet" spell: after the spell is cast - the bear still stays with you! This is also a bug.
10. Finish "Training the beast" quest in Ironforge - the ["Beast training"](https://wowgaming.altervista.org/aowow/?spell=5149) spell is not added to spellbook.
11. Now re-log: the pet is missing! And Call/Revive pet spells have no effect (bug).

### Extra Notes

On main ChromieCraft realm, the aggro during Taming the beast quest was bugged, but there is already a [bug report](https://github.com/chromiecraft/chromiecraft/issues/2894) for that. Now on test realm this bug is not reproducible, but I doubt that it was fixed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment] 2022-03-06 20:53
Beast Training was removed in patch 3.0.2. Link: https://wowwiki-archive.fandom.com/wiki/Beast_Training

**Comment by Kosiak** [comment] 2022-03-06 21:15
Quest chain Taming the beast:
Everything works as intended on check.
U can dismiss pet by clicking pet icon near yours
![tame leopard](https://user-images.githubusercontent.com/791788/156942402-fc0adf81-74df-4d6b-80e6-081fcd8537c9.png)
.
Dismiss from spell book won't work on beasts tamed with quest tamed road u need to use dismiss function from screenshot.
Pet will dissapear on re-log as u already finished the quest.
And call or revive pet wont work untill u tame pet with spell from spell book.

**Comment by Nyeriah** [comment] 2022-03-06 21:17
Yes, beat training is a vanilla thing. Pets learn their spells automatically. closing.

**Closed by Nyeriah** 2022-03-06 21:17 UTC
Labels: Needs Triage

**Comment by anonymousbugreporter2602** [comment] 2022-03-11 00:21
Really sorry for the Beast training - pet talent tree was a surprise for me, as I (almost) did not play hunter on official and completely missed LK. 

Just one more question. You say that pet which disappears on logout is okay - are you serious? Isn't hunter supposed to be left with a real pet after the quest? As I remember, this is the blizz-implemented behavior on official server in classic and TBC. And comments from internet also say, that dwarf hunter should have a real bear after the quest.

As I understand, the pet, which is tamed by the quest item (taming rod) - technically is not a true hunter pet, that's why it's size is not changing, and that's why it disappears. The last quest should have a step to turn the bear into true pet, and save it into database, no?

**Comment by Kosiak** [comment] 2022-03-11 01:35
Just watched couple videos of classic lauch on official servers from couple years ago and old videos from wowhead. It works same as on chromi server. So i dont know who says that pet should stay.  Sorry i cant help u further in here :)

**Comment by anonymousbugreporter2602** [comment] 2022-03-11 16:21
Then sorry for trouble, and thank you!
