### ISSUE TITLE
(DB): Two Cenarion Hold Infantry stacking together

### ISSUE THREAD

**Issue by Si1ker** [chromiecraft/chromiecraft#3860] opened 2022-07-28 13:37 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Two Cenarion Hold Infantry stacking together

![image](https://user-images.githubusercontent.com/61223313/181518748-e296ce8d-9eb4-4cdd-bdcc-5fffc50c07d9.png)
![image](https://user-images.githubusercontent.com/61223313/181518755-6289fb55-fbd0-4554-bfb2-794fa73c3799.png)

### Expected Blizzlike Behaviour

Separate

### Source

.

### Steps to reproduce the problem

1. Go Cenarion Hold in Silithus
2. Chech the main road

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3ea74e26190e3a62b76128298cac98f83ae5ba34

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment] 2022-10-08 17:03
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/2445 It's another issue of reports getting buried :C 
But it's technically triage so you should get points :)

**Closed by Gultask** 2022-10-08 17:03 UTC
Labels: Needs Triage
