### ISSUE TITLE
NPC combat

### ISSUE THREAD

**Issue by Knewklear** [chromiecraft/chromiecraft#24] opened 2021-01-31 03:29 UTC
##### SMALL DESCRIPTION:

NPC's still move in their pathing behaviour upon combat.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When engaged in combat, the NPC stops their pathing and begins its attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Continue fighting NPC's.
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment] 2021-02-01 11:07
duplicate of https://github.com/chromiecraft/chromiecraft/issues/27
I am closing this because that issue have screen and more details.
Anyways we appreciate this report because now we know that the issues is worldwide and not related to one NPC.

**Closed by Helias** 2021-02-01 11:07 UTC
Labels: needs triage
