### ISSUE TITLE
[NPC Pathing] Darnassus Sentinel falls through the raised walkway from Rut'theran Village Flightmaster to Teldrassil

### ISSUE THREAD

**Issue by ntrna** [chromiecraft/chromiecraft#1650] opened 2021-09-07 06:54 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The sentinel seems to get stuck underneath the pathway for awhile, before reappearing & continuing its patrol. Then, it gets stuck again. The corners & section between them seem the most troublesome.

### Expected Blizzlike Behaviour

The sentinel should walk the whole path on top of the path, not disappearing underneath it.

### Steps to reproduce the problem

Go to Rut'theran Village.
Watch the sentinel patrolling the raised walkway to/from flight master.

### Extra Notes

idk what AC rev.hash/commit or modules are

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment] 2021-09-07 07:57
duplicate of #789

**Comment by jamadaha** [comment] 2021-09-07 13:33
Thanks for the report! But, as @gurveleg states, it is a duplicate.
Unless you mean any other NPC than GUID 46825, seen below (Found with typing .npc info — while targeting the NPC)
![image](https://user-images.githubusercontent.com/53914190/132353594-f62b34da-dd61-463a-a5fe-c98eb43d4325.png)

For now, I'll be closing it as a duplicate, but if you mean another NPC, please feel free to comment with that NPCs GUID.

**Closed** 2021-09-07 13:33 UTC
Labels: Duplicate, Closed
