### ISSUE TITLE
Overlapping Food/Drink boxes Elwynn Forest above Cat Lady

### ISSUE THREAD

**Issue by temperrr** [chromiecraft/chromiecraft#898] opened 2021-06-19 07:07 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/20357406/122634193-0975d880-d0dd-11eb-8771-000c6cb5e6de.png)

Food + drink spawned in eachother. This is not blizzlike behaviour.
 29276 [entry 3658] water barrel and 30687[entry 3719] food crate

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only 1 of them should be spawned at a time 
##### STEPS TO REPRODUCE THE PROBLEM:

1. go to x-9258.879883 y 355.378998 z 76.693001 mapid:0
2.  See both of the items spawned in eachother
3.  They keep respawning in same spot. (after some time ofcourse)
4.

##### EXTRA NOTES:

https://wowpedia.fandom.com/wiki/Water_Barrel
https://wowpedia.fandom.com/wiki/Food_Crate
https://www.wowhead.com/object=3658/water-barrel
https://www.wowhead.com/object=3662/food-crate

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment] 2021-06-19 13:08
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6414

**Closed by anguaive** 2021-06-19 13:08 UTC
Labels: Needs Triage
