### ISSUE TITLE
[Midsummer Fire Festival] Torch Catching, More Torch Catching

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#931] opened 2021-06-21 02:24 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quests: [Torch Catching]( https://www.wowhead.com/quest=11923/torch-catching), [More Torch Catching](https://www.wowhead.com/quest=11925/more-torch-catching)
It work as intended while you're near quest giver area. If you're going outside this area, let's say 100+ yards, you start getting credits for this quest for free. Quest item is lost animation and stop working how it should.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Idk should it work outside the quest giver area or not, but atleast quest item should work too.

##### SOURCE:

Free credits fort quests is evil.

##### STEPS TO REPRODUCE THE PROBLEM:

Done this quest with several characters. This bug fully repetable for any horde city.

##### EXTRA NOTES:

[Unlit Torches](https://www.wowhead.com/item=34833/unlit-torches)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by temperrr** [comment] 2021-06-24 14:14
Thanks for your report! Sadly, this has already been reported. 

Duplicate of #930 @FrancescoBorzi

**Closed** 2021-06-24 15:47 UTC
Labels: Needs Triage
