### ISSUE TITLE
Wailing Caverns - Last Boss Bug

### ISSUE THREAD

**Issue by Smithy125** [chromiecraft/chromiecraft#1562] opened 2021-08-27 22:55 UTC
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

This just happened and a GM called 'Construct' helped us with it.

The bug is with the event for the last boss of the Wailing Caverns where you have to talk to Naralex at the start of the dungeon.
I died on the previous boss and as soon as I entered they started the event, he then immediately vanished and we could not see him, we called in the GM and he started the event for us, he could see it but we couldnt. Naralex spawned the mobs like he should have when he walks through the dungeon and we saw those but we could not see him, so we followed the gm who could and we all managed to do the last boss.

If it wasnt for the GM's help with starting the event for us, the run would have died and we couldnt have done anything about it.

I apologise about the formatting of this bug report, I dont know how to use this website.

Hope this description of the bug helps you solve this problem.

### Expected Blizzlike Behaviour

After talking to Naralex at the start of the dungeon, he should not instantly vanish, but walk slowly to the last boss.

### Extra Notes

I think its because i died and someone started the event as soon as re-entered the dungeon. I dont know how you can fix this issue but i hope you find a fix

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by stickymouse1** [comment] 2021-08-27 23:03
i should also note that its for both horde and alliance as i was there too and apperntly me (the only alliance guy at that dung) was the only one who is able to read narlex dialogues the other team mates werent able to read em

**Comment by Pindasek** [comment] 2021-08-27 23:41
i was in dungeon as Lubo. I also cant see Naralex, but i can see dialogues in chat.

**Comment by stickymouse1** [comment] 2021-08-29 08:48
i just wanted to mention that the gm didnt do anything speical in order to start the event (didnt respawn the diciple or something like that ) he said he can see him normaly so ye there is that

**Comment by Yukizara** [comment] 2021-08-31 23:07
Our group had a similar issue where the NPC wasn't there upon returning to the beginning of the dungeon. 
No one died during any boss fights, although in the fight with Serpentis we also pulled Verdant without exiting combat so i don't know if this may have caused an issue.

**Comment by temperrr** [comment] 2021-09-07 11:06
Tried the duplicate both cases (dying and starting during resurrect and pulling last 2 bosses together) but cant get the disciple to disappear). If any of you encounter this issue again, please reply below with a pretty exact write down of what exactly happened so we can see where the issue is.

**Comment by Si1ker** [comment] 2021-09-07 19:22
Unable to repro on both cases mentioned. Closing until new sources are provided.

**Closed by Si1ker** 2021-09-07 19:22 UTC
Labels: Unable to Reproduce
