### ISSUE TITLE
Iron Bound Trunk stays in inventory after being opened

### ISSUE THREAD

**Issue by gurveleg** [chromiecraft/chromiecraft#592] opened 2021-05-09 18:25 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Sometimes Iron Bound Trunk (https://wowgaming.altervista.org/aowow/?item=21150) stays in inventory after trying to open them and rightclicking on it does nothing, has to be manually removed from inventory.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to open Iron Bound Trunk and get its loot.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have find fish learned (https://wowgaming.altervista.org/aowow/?spell=43308)
2. Fish/Add Iron Bound Trunks (https://wowgaming.altervista.org/aowow/?item=21150) and open them
3. See if any stays in inventory

##### EXTRA NOTES:

Perhaps this is related problem as in #444  and the fix would be of the same nature?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-05-09 19:59
Duplicate of #444
Only happens when you have already learned how to **Find Fish**.

**Closed by necropola** 2021-05-09 19:59 UTC
Labels: Closed, Duplicate
