### ISSUE TITLE
Visual bug in guildbank

### ISSUE THREAD

**Issue by Nyapaweon** [chromiecraft/chromiecraft#1765] opened 2021-09-16 13:02 UTC
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

![WoWScrnShot_091621_141855](https://user-images.githubusercontent.com/79753117/133616399-477701bf-ce6f-450f-9e67-b5dd54a9500a.jpg)
![WoWScrnShot_091621_142321](https://user-images.githubusercontent.com/79753117/133616448-53f83280-788f-4e9a-93e0-4ab3a56e3d55.jpg)
![WoWScrnShot_091621_142425](https://user-images.githubusercontent.com/79753117/133616481-db05537c-a4cf-4ea2-ac40-6c6088c5f2c7.jpg)
![WoWScrnShot_091621_143846](https://user-images.githubusercontent.com/79753117/133616668-de85a5f9-18c4-4e8d-9ad6-1aca7461d220.jpg)

### Expected Blizzlike Behaviour

This should not happen.

### Steps to reproduce the problem

Move items until visual bug occurs.

### Extra Notes

Basically
https://github.com/chromiecraft/chromiecraft/issues/387
https://github.com/chromiecraft/chromiecraft/issues/1000

Was told to report here tho.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Synful-Syn** [comment] 2021-09-16 14:50
As you did mention in your extra notes, this bug report is a duplicate of #387 and #1000 and thus is already reported. We want to avoid having multiple bug reports of a single bug since it would cause a headache to close all the associated bug reports to a single bug (since someone may forget to associate the other bug reports of the same bug), making it hard for the triaging process.

**Comment by jamadaha** [comment] 2021-09-17 15:14
This does indeed appear to be a duplicate of 387, so I'll close this. If you disagree, please comment.

**Closed by jamadaha** 2021-09-17 15:14 UTC
Labels: Needs Triage, Triaging in progress
