### ISSUE TITLE
Gathering profession perks require relog to show in spell book

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#83] opened 2021-02-15 21:32 UTC
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
When you reach skill level 75 in Mining, Skinning or Herbalism the corresponding profession perk  
[Toughness (Rank 1)](https://wotlkdb.com/?spell=53120), [Master of Anatomy (Rank 1)](https://wotlkdb.com/?spell=53125) or [Lifeblood (Rank 1)](https://wotlkdb.com/?spell=55428) is not added to your spell book until you relog. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Gathering profession perk spells should be added immediately (and a system message should be shown in chat)

##### CURRENT BEHAVIOUR:
Only the stat increase (+3 Stamina for Mining and +3 Crit Rating for Skinning) is applied immediately. The spell isn't added to the spell book until relogging.   
 
##### STEPS TO REPRODUCE THE PROBLEM:
1. Reach skill level 75 in Mining, Skinning or Herbalism
2. Inspect the character sheet (to verify the stat increase for Minig/Skinning)
3. Check the the chat window and your spell book
4. Relog
5. Check your spell book again

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment] 2021-02-16 13:42
When you check the chat, it appears the announce of the new skill? Because I can't reproduce it, also if the skill is announced as new in the chat, then it is a cache problem.

I remember a player told me that a while a go, and was the same, can't reproduce, very random and with clean cache never happened.

**Comment by Stifler82** [comment] 2021-02-16 18:15
https://user-images.githubusercontent.com/1884642/108104226-f39acd00-7082-11eb-8d75-58ab0a7e63ba.mp4

**Comment by necropola** [comment] 2021-02-16 18:53
Have you tested Mining and Skinmning, too? Have you tried on a character that did not already have that skill? Using a GM command to reduce the skill to 74 and then skill up again is not the same thing as reaching 75 for the first time.

Players don't have GM commands and suggesting to (simply) do this again and clear the Cache right before (accidently) hitting 75 on another character just shows how little you actually care about your players.

I'm done with reporting bugs. You managed to piss off another player. Congratulations!

**Comment by FrancescoBorzi** [comment] 2021-02-16 19:11
>  Using a GM command to reduce the skill to 74 and then skill up again is not the same thing as reaching 75 for the first time

yes, it's the same. GM commands are designed for testing purposes in order to allow developers to reproduce and fix bugs. If we cannot reproduce a bug, we can never fix it.

> just shows how little you actually care about your players
> I'm done with reporting bugs. You managed to piss off another player.

I'd like to remind you that @Stifler82 (as well as the other contributors) is not being paid for checking the reports. He does it as a volunteer in his own free time. I believe that already tells how much he cares about the project (and of course the players). He might be right or might be wrong in closing an issue, but that doesn't mean he does not care. If he didn't, he wouldn't do this for free.

-- Shin

**Comment by Stifler82** [comment] 2021-02-17 07:24
@necropola 
**Video:** [Gathering profession perks 2](https://youtu.be/SxMre2-p8T8)

So, I made this video for 3 Reasons:
**1 - To apologize, as the Bug is Existing.
2 - To Show how much I care about the server.
3 - To prove that I AM ALWAYS right.**


 Explanation of the 3 Points

1 - To apologize, as the Bug is Existing.
-
_I apologize because the Bug actually exists, (even if, however, I consider it a minor Bug), because this Bug does not prevent the Player from playing his game, as it is sufficient to log out and log back in, to get those skills. But I probably had to be more thorough in checking the other professions you mentioned.._


2 - To Show how much I care about the server.
-
_I farmed (as you requested) both Herbalism and Skinning up to 75 as a player would (more or less), except for the fact that I used super speed and some ".damage 10000" here and there.
Just to show you that if a Player raises a doubt in my mind that can be attributed to my bad judgment, I always do a 2nd Check to make sure that my 1st Decision was correct or not._


3 - To prove that I AM ALWAYS right.
-
_And now the 1st and 2nd Points lead us directly to the 3rd Point._
_You see, I based my Initial Judgment on what **YOU** have reported to me._
_So I based on the **"Title"** of your Report where you wrote: **"Gathering profession perks require relog to show in spell book"**
So for **ME** it was a report of something **YOU** had **ALREADY TRIED**, but it isn't, because you probably had only tried **Skinning and Mining**, or even **ONLY SKINNING** or **ONLY MINING**. and you took for granted and obvious that all 3 professions were bugged in the same way, in fact then in the description of your report you wrote: **"When you reach skill level 75 in Mining, Skinning or Herbalism the corresponding profession perk Toughness (Rank 1), Master of Anatomy (Rank 1) or Lifeblood (Rank 1) is not added to your spell book until you relog."**
Consequently, having given me this **WRONG INFORMATION**, I have based **ALL MY RESEARCH/TEST** on **WRONG INFORMATION**, because fate wanted me to try the only profession that was not buggy, in fact the only 2 professions that give this defect are **MINING and SKINNING** STOP!_

_And in the video at the end I also prove to you that the **GM's commands can simulate** the daily actions of the Players and therefore simulate both the Bugs and the correct game operations._

In conclusion..
-

**This is Stifler's Bible**

✔ **1 -** _When Stifler says that something works a certain way, he says it because he is SURE of the information he has, otherwise he would say "I don't know", "Maybe", "I'm not sure" (and other synonyms that describe the sense of uncertainty regarding the topic in question).
So if Stifler says "this thing is: in this way", the correct answer **is not "/Cry"** or **insult the Staff**, but instead the correct answer is **"AMEN"** and **"HALLELUJAH STIFLER"**._

✔ **2 -** _If you want precise work from Stifler, you have to give precise information to Stifler.
Otherwise, inaccurate information will generate inaccurate work._

✔ **3 -** _Send monthly: 1kg of Mary Jane to the following address: Stifler's House N °69 with a note saying: "Forgive us, because we do not deserve the work you do for us"_

**Comment by necropola** [comment] 2021-02-17 08:33
I should have probably said that I was 100% sure about Mining and Skinning but not 100% sure about Herbalism since I only had one character with Herbalism at > 75 when filing the report, but 3 Skinners and 2 Miners. Sorry.
The order of events and what I was thinking with 1 Herbalist, 2 Miners and 3 Skinners on my Horde account:
0. I was wondering whether those WotLK (gathering) profession perks are (already) enabled on ChromieCraft or not, because they are considered to be OP.
1. At some point I reached skill level 75 on a Skinner and did neither got the perk spell (Master of Anatomy) nor the system the message in chat. **So I deduced: It's probably disabled**
2. I reached level 50 in Alchemy on another char, could learn Mixology and wondered, why this is available when the gathering perks are not.
3. I did not check my **only** Herbalist, who was probably above skill 75 already, but went back to my Skinner, checked the char sheet and noticed that the +3 crit rating was there. **So I deduced: The perks are applied but not shown in the spell book.**
4. At some point later I accidently noticed that "Toughness (Rank 1)" was in the Spell Book of one of my Miners and I checked my other chars to see that "Master of Anatomy (Rank 1)" and "Lifeblood (Rank 1)" were also in the spell book. **So I deduced: The perks are applied immediately but not shown in the spell book until relogging**
5. At this point I only had a Miner and a Skinner available to verify my hypothesis. I did and filed the bug report wrongly assuming that the same happened to my Herbalist.

You can see that I went through quite some effort before filing the bug report. And I always do this, because I don't want to waste developer time. I know the other (your side) very well, too. I further know from experience that **quality bug reports** are a rather rare case and it's wise to not piss off users who contribute in this way.

But as I said already: It's your project and therefore your choice.

**Comment by Stifler82** [comment] 2021-02-17 09:05
So, you have to understand one thing, I am NEVER rude to people, I am just "whimsical" and I respond with "Sarcasm" because I believe that sarcasm is effective in making people understand what the point is, so I don't use it "In the sense of Offense", but I use it in the sense of "Effectiveness for understanding", I am a USER, like you, I also have a Character (which is still at level 12 I think, if I remember correctly), because I'm always here doing "The Job" that NO ONE pays me for.

So I'm a user like you, who though! (Unlike you),
He is 38 years old, and a passion for WoW that goes back to 2007, because I have been playing WoW since 2007 (albeit intermittently).
I have seen BUGS that you HUMAN BEINGS cannot understand!
I have seen/met people who I did not believe were "Possible".
I blasphemed on improbable DBs!
I fixed a lot of things in my life, quests, NPCs, Spell, and so much more..
Consequently, I "BELIEVE" that I can define myself as an EXPERT user at 360°, so I volunteered to submit myself considering these skills I possess.
End of the story..

It would be nice and motivating for us to have Players who instead of discouraging us and make us pass the desire to do the good things that (INSTEAD WE DO) would instead give us encouragement, perhaps collaborating (in a useful way though), because they would help, (but it is not a help) = It is not a help

As you can see, it's basically math, and that's brutally honest, it never lies.
I see it like this ..

**Comment by necropola** [comment] 2021-02-17 09:09
The nicest thing I can say at thsi point is that I liked the **Bladerunner** reference
https://youtu.be/EOSIj_AxxX0

**Comment by Stifler82** [comment] 2021-02-17 09:13
I mean..
it is a "CALLABORATION" what we do "Users" and "Devlopers", so 100% of the result depends on the 50% we give, and the other 50% you give, if one of the two collaborations gives the "45 %"(for example) the final result will be 95% it can never be 100%, as I told you, it's math.

**Comment by Stifler82** [comment] 2021-02-17 09:14
> The nicest thing I can say at this point is that I liked the **Blade Runner** reference
> https://youtu.be/EOSIj_AxxX0

🤣

**Comment by FrancescoBorzi** [comment] 2021-02-17 09:52
> But as I said already: It's your project and therefore your choice.

@necropola this is a community-lead project. Stifler helps checking the issues, the players help reporting them, everyone has his/her role in it. This is not just Stifler's or Shin's project.

And of course, everyone can make mistakes, including regular contributors or admins.
That said, I'm glad that you guys solved it.

**Comment by necropola** [comment] 2021-02-20 09:10
Just wanted to note that I got [Master of Anatomy (Rank 2)](https://wotlkdb.com/?spell=53662) on my level 19 Orc Hunter without needing to relog and [Lifeblood (Rank 2)](https://wotlkdb.com/?spell=55480) on my level 19 Tauren Druid, too.
Though my Tauren needed to get to skill level 165 (instead of 150), i. e. he got *punished* for his **+15 Herbalism racial trait** which I think is not correct. Also the system message **You have learned a new spell. Lifeblood (Rank 2)** appeared twice in chat.

**Comment by ReynoldsCahoon** [comment] 2021-03-11 21:34
Piggybacking on this, I just discovered on ChromieCraft that if I unlearn a profession, I do not lose the perks of my previously held profession. I still have [Master of Anatomy (Rank 2)](https://wotlkdb.com/?spell=53662) even though I've unlearned skinning.

This introduces the ability to gain all profession perks, without needing to have those professions.

**Comment by necropola** [comment] 2021-03-11 22:03
It woudl be interesting to know whether you lost the crit rating stat bonus immediately upon  unlearning the skill (which I would guess). So that in both cases it's more or less only the spell book that doesn't get updated until you relogging.

**Comment by FrancescoBorzi** [comment] 2021-04-28 11:09
the issue has been fixed, thanks all

**Closed by FrancescoBorzi** 2021-04-28 11:09 UTC
Labels: Confirmed, Linked [AC], [1 - 19]
