### ISSUE TITLE
Bloodgem Crystals completion bugged

### ISSUE THREAD

**Issue by Mixilplik** [chromiecraft/chromiecraft#6324] opened 2023-11-13 05:21 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

The Scryer quest for the Bloodgem Crystals in Netherstorm is bugged. When you click on the crystal in your inventory it auto interrupts if you are not facing towards a crystal. Then even when you are facing a crystal it still will auto interrupt and not allow you to channel the cast to get the buff. The quest is not able to be completed if you cannot get the channel to finish and get the buff.

This is the quest I am referring to 

https://www.wowhead.com/wotlk/quest=10204/bloodgem-crystals

I have tried 6-7 crystals so far. I asked in chat and was told it has been bugged for awhile and that you have to face a crystal. I did that and it turned me towards another crystal and interrupted.

### Expected Blizzlike Behaviour

If it is working as intended it would just channel the cast when you click the crystal in your bags and give you the buff. 

### Source

https://www.wowhead.com/wotlk/quest=10204/bloodgem-crystals

### Steps to reproduce the problem

Click the gem in you bag once you get one from the mobs.

The channel will be interrupted even if you do nothing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment] 2023-11-13 11:12
duplicate of https://github.com/chromiecraft/chromiecraft/issues/4943

**Closed by avarishd** 2023-11-13 11:12 UTC
Labels: Needs Triage
