### ISSUE TITLE
Dark Coffer Door open without dark keeper key

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1697] opened 2021-09-11 06:30 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Dark  coffer door open without dark keeper key

### Expected Blizzlike Behaviour

Players need the consumable dark keeper key to open the dark coffer door.

### Source

https://classic.wowhead.com/object=160845/dark-coffer#comments

### Steps to reproduce the problem

Try and open the door without key

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment] 2021-09-11 08:52
Could not reproduce.
As can be seen in the below picture, it requires the key.
![image](https://user-images.githubusercontent.com/53914190/132942281-cd4ebf0f-7918-4081-afc9-7657d2c9fa61.png)

**Comment by baranzadeoglu** [comment] 2021-09-11 10:05
> Could not reproduce.
> As can be seen in the below picture, it requires the key.

Maybe another key in my inventory functioned to open the door. I tried to go through the database but I am not as apt in mysql as one could.

**Comment by syssneck** [comment] 2021-09-11 11:04
It also doesn't work with the Shadowforge Key for me.

**Comment by Azcobu** [comment] 2021-09-11 11:05
Checked with Shadowforge Key in inventory, but that didn't open the coffer either.
Had a look at lock.dbc, and for entry 659, it points towards item id 11197, which is the Dark Keeper Key, so that looks as expected.

Trying with Shadowforge Key:
![WoWScrnShot_091121_203453](https://user-images.githubusercontent.com/81782124/132945753-240c127a-44a4-4017-9515-5c53081f169f.jpg)

**Comment by baranzadeoglu** [comment] 2021-09-11 11:40
Okay. I will rerun brd and try to figure out what happened then...

**Comment by syssneck** [comment] 2021-09-13 16:42
I will close this now, but feel free to post any information you can find, if this should happen again, and we will open it again.

**Closed by syssneck** 2021-09-13 16:42 UTC
Labels: Needs Triage, Unable to Reproduce
