### ISSUE TITLE
[SPELL] Dash now gives bonus movement speed outside of cat form

### ISSUE THREAD

**Issue by UndoUreche** [chromiecraft/chromiecraft#6204] opened 2023-10-02 18:52 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Dash provides its movement speed benefit outside of cat form as well.

Note: The numbers shown on screen are returned by a call of GetUnitSpeed("player").

https://github.com/chromiecraft/chromiecraft/assets/50205200/af4aa649-7042-4bba-a10c-07f9c9c34b6f

### Expected Blizzlike Behaviour

Dash should only increase movement speed while in cat form.

### Source

![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/91c8ebc6-30ff-4f9b-a762-c53c6aae9412)

### Steps to reproduce the problem

Have a druid that can use Dash
Switch into cat form
Cast Dash
Switch out of cat form (either into a different form or caster)
Notice that the dash movement speed remains

### Extra Notes

This happened after the last changes to dash: https://github.com/azerothcore/azerothcore-wotlk/pull/17343/commits/09c4e1e45f85c0f72d6b3c4df343ff07db02d7c5

It seems that the ability should have both scripts attached to it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-10-02 22:56
Duplicate of https://github.com/chromiecraft/chromiecraft/issues/6197, should be fixed with the next server restart. Please re-open the issue if it persists after the update.

**Closed by heyitsbench** 2023-10-02 22:56 UTC
Labels: Needs Triage
