### ISSUE TITLE
Hillsbrad Yetis can't be looted

### ISSUE THREAD

**Issue by Gizmoh** [chromiecraft/chromiecraft#172] opened 2021-03-07 21:43 UTC
##### ISSUE: Horde:

 ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Yetis in Darrow Hill cave can't be looted or skinned. See attached image for a clearer picture

NPC: https://wow.gamepedia.com/Ferocious_Yeti

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Yetis should be lootable and skinned

##### CURRENT BEHAVIOUR:

Yetis are marked as having loot, but can't be looted or skinned most of the time.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Kill Yetos
Step 2: ???
Step 3: Profit

![WoWScrnShot_030721_183302](https://user-images.githubusercontent.com/4155081/110255930-04997880-7f75-11eb-8d8d-5d937e661bed.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-03-10 08:39
Related to or duplicate of #86 and #180

**Closed** 2021-03-10 10:56 UTC
Labels: Closed, Duplicate
