### ISSUE TITLE
Captain Skarloc

### ISSUE THREAD

**Issue by Never6** [chromiecraft/chromiecraft#5045] opened 2023-02-15 15:17 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

https://wowgaming.altervista.org/aowow/?npc=17862#links
seems to softlock whenever a rogue is in stealth when the rp starts
im assuming this is due to them trying to detect stealth but they are non hostile

### Expected Blizzlike Behaviour

NPC shouldn't softlock because the rogue is in stealth

### Source

https://www.youtube.com/watch?v=IJIDJuJlZS4&ab_channel=CostinGaming
RP starts at 39:20
rogue is in stealth but rp doesnt break

### Steps to reproduce the problem

make a rogue
do durnholde
get to 2nd boss
enter stealth
rp starts
npc breaks

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment] 2023-02-15 15:22
I would appreciate if this was fixed asap because if durnholde bomb skip is gonna be fixed while you still have massive core issues
Durnholde bomb skip shouldnt take prio over https://github.com/chromiecraft/chromiecraft/issues/4927 https://github.com/chromiecraft/chromiecraft/issues/4837 (the 2nd report is how every ranged mob works which makes stacking for cleave without LoS a huge hassle when it shouldnt be)

**Comment by Nyeriah** [comment] 2023-02-15 16:55
Dupe of https://github.com/chromiecraft/chromiecraft/issues/4989

**Closed** 2023-02-15 17:00 UTC
Labels: Needs Triage
