### ISSUE TITLE
[Stormwind - Midsummer] [More Torch Catching] - Touches tally without catching

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#932] opened 2021-06-21 02:24 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Torch tally's outside of event zone without catching. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Torch will required catching to tally.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get quest
2. Go outside of event zone or in a building
3. Attempt to throw torch [auto tallies]
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Jinmcx** [comment] 2021-06-21 02:25
![WoWScrnShot_062021_202051](https://user-images.githubusercontent.com/19652090/122698927-9c119700-d205-11eb-98ea-e4059c561a13.jpg)
![WoWScrnShot_062021_202055](https://user-images.githubusercontent.com/19652090/122698931-a03db480-d205-11eb-8a1d-df69b2940e88.jpg)

**Comment by temperrr** [comment] 2021-06-24 14:14
Thanks for your report! Sadly, this has already been reported. 

Duplicate of #930 @FrancescoBorzi

**Closed** 2021-06-24 15:47 UTC
Labels: Needs Triage
