### ISSUE TITLE
Two quest's strange or bugged drop rate in Loch Modan

### ISSUE THREAD

**Issue by nolt** [chromiecraft/chromiecraft#40] opened 2021-02-04 20:58 UTC
##### SMALL DESCRIPTION:
Very low or bugged drop rate
1st quest is: 
Thelsamar Blood Sausages
2nd quest is: 
Rat Catching

##### EXPECTED BLIZZLIKE BEHAVIOUR:
1st quest Thelsamar Blood Sausages:
Drop rates reported:
Elder Mountain Boar for Boar Intestines (32%/37% drop rate)
Elder Black Bear for Bear Meat (39%/42% drop rate)
Forest Lurker for Spider Ichor (35% drop rate) (in this case both drop rate reports was the same)

2nd quest Rat Catching
Tunnel Rat Vermin, Tunnel Rat Forager, Tunnel Rat Kobold for drop 12x  Tunnel Rat Ear (37%/40% drop rate)

##### CURRENT BEHAVIOUR:
Thelsamar Blood Sausages
Poor drop rate, killed 10bears - 1 quest item, killed 11 boars - 2 quest item, killed 10 spiders - 1 quest item.
Also near main road guards kills Elder Black Bears, maybe bears there are too close to road or guards have to big area of attack.

Rat Catching
Very poor drop rate about 2 quest item per 10kills, also sometimes mobs drops 2x quest item.

##### STEPS TO REPRODUCE THE PROBLEM:
Go to Loch Modan, take quest and try to finish them.
Bears are killed by guards here:
https://imgur.com/MLRlDle

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment] 2021-02-06 16:34
Thanks @nolt for the report.

Here are my tests so far:
- cross-checked drop loot tables for all the creatures required for [Thelsamar Blood Sausages](https://wowgaming.altervista.org/aowow/?quest=418) and [Rat Catching](https://wowgaming.altervista.org/aowow/?quest=416) with our database version (with Keira3) and it seems they are correct.

- noticed that the guards indeed kill some of the required mobs (this can be an optional task in an up-coming pull-request)

@FrancescoBorzi, @Helias  I intended to close this since the drop loots are the same, however, I killed 10 bears and no meat has dropped. 
To me 42% means if I kill 2-3 creatures I expect to get that loot.
Could it be some internal cpp logic that would change the drop chances?

In the past we closed this https://github.com/chromiecraft/chromiecraft/issues/10 which was a bit similar, in game drop rates too low, affecting the overall gameplay, but 1:1 rates with wotlk databases.
How should we proceed with this ticket ?


##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

**Comment by FrancescoBorzi** [comment] 2021-02-06 16:54
> To me 42% means if I kill 2-3 creatures I expect to get that loot.

usually yes, but it's always a matter of chance. So to see if it's really working as intended, you should try with more NPCs.

Which creature IDs have you checked specifically?

**Comment by Hacaw** [comment] 2021-02-06 17:09
> > To me 42% means if I kill 2-3 creatures I expect to get that loot.
> 
> usually yes, but it's always a matter of chance. So to see if it's really working as intended, you should try with more NPCs.
> 
> Which creature IDs have you checked specifically?

Killed 10 of those: https://wowgaming.altervista.org/aowow/?npc=1186#drops

**Comment by Helias** [comment] 2021-02-07 16:11
Thelsamar Blood Sausages
killed 6 boar and dropped 3 boar intestines
killed 6 bear and droppd 3 bear meat
killed 6 and dropped 3 spider ichor

hehe, it was really a coincidence but after the sixth I dropped the last.
I think that you had no luck :(

For a similar quest "Westfall Stew" I encountered a similar issue for the goretusk liver, I think it can happen but it should not be considered a bug.

Note: the items are not "quest items" so it's normal to not drop them all times


About Rat Catching
I killed 24 NPCs and looted 12 quest item BUT:
- after 13 kills I get only 3 quest item
- the 14th looted me 2 quest items instead of one
- it happened another time that one rat looted me 2 quest item


I think that it is balanced.

**Closed by Helias** 2021-02-07 16:11 UTC
Labels: needs triage
