### ISSUE TITLE
Rain of Fire warlock

### ISSUE THREAD

**Issue by blecaplol** [chromiecraft/chromiecraft#2598] opened 2021-12-16 03:04 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The effect of Rain of fire is persistent even after channeling ended. This does not always appear each cast. Just randomly at times.

### Expected Blizzlike Behaviour

Effect of RoF should end as soon as channeling ended. 

### Steps to reproduce the problem

Im not sure how to reproduce as its random to me. If u wanna try just RoF a pack of mob in dungeons.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-12-16 19:18
Thank you for the report. Anyway i don't understand what you mean by `The effect of Rain of fire`. You have to clarify it. On local AC i can't find issues with RoF

https://user-images.githubusercontent.com/85256266/146434668-73daa80f-7638-4512-8f4e-c8176aa3bcc4.mp4

**Comment by Focusmighty** [comment] 2021-12-16 22:49
I will try and take a video of it as I mentioned it is not every cast. So
it will take time to reproduce it.

**Comment by Venom0fGod** [comment] 2021-12-20 03:16
I have noticed this aswell, also with mage blizzard and paladin consecrate. It appears to be a visual bug only. Damage ticks are not applied after initial time / channel has stopped, however the visual effect will persist occasionally.

**Comment by Focusmighty** [comment] 2021-12-20 09:46
Yeah. that's what I mentioned just visual.

**Comment by Shineslippers** [comment] 2021-12-20 10:53
Well, tbh i can't reproduce anything like this. Without it i can't report issue to devs. Because we don't know where to look at. Also this is can be `game Client Bug` that is unfixable. Do you using HD patch?  Where last time you saw this bug(Instance, NPCs name)?

**Comment by Focusmighty** [comment] 2021-12-20 13:32
Yea I used the HD patch but its not that. The RoF itself isnt default texture should be Chromie own texture. It can happen in any instance. If you got move the ticket its fine. U can close it after this.

**Comment by Shineslippers** [comment] 2021-12-20 15:56
It's not about move or not move. As i said before i can't reproduce it >>> i can't report it to devs. I will leave it open. Maybe i will meet it somewhere else.

**Comment by ishidinho** [comment] 2022-02-21 09:57
Duplicate https://github.com/azerothcore/azerothcore-wotlk/issues/5910.

**Closed by ishidinho** 2022-02-21 09:57 UTC
Labels: Unable to Reproduce, Bug Under Evaluation
