### ISSUE TITLE
[AQ20] Ossirian the Unscared ROOM - People dying before boss is pulled by SOMETHING

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#3994] opened 2022-08-24 18:10 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

![WoWScrnShot_082422_200559](https://user-images.githubusercontent.com/80590226/186491634-2011c7a6-ced9-4640-a447-9f1257897c69.jpg)

People are dying by something before boss is pulled. Looks like invisible TORNADOS that are maybe spawned even if boss is not pulled? Their death logs are clear.

### Expected Blizzlike Behaviour

People shouldn't be killed by invisible triggets :D

### Source

-

### Steps to reproduce the problem

1. Not sure
2. But people dying in raid for no reason before last boss in AQ20 is pulled

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e0b7c7d0d3b1ea65860439add2c676b3e18f8f8b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment] 2022-08-24 18:20
![image](https://user-images.githubusercontent.com/80590226/186493883-3f100f03-2a7a-4b51-a6d3-bd319546a30d.png)

**Comment by Gultask** [comment] 2022-08-25 00:31
Thanks for the report! The issue is caused by the Sand Vortex npcs not despawning properly. There's a fix for this already in the works :)

**Closed** 2022-08-25 01:56 UTC
Labels: Confirmed, Linked [AC]
