### ISSUE TITLE
Shattered halls rogues not stealthed

### ISSUE THREAD

**Issue by Kirishiki** [chromiecraft/chromiecraft#5726] opened 2023-06-07 06:34 UTC
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

sometimes the rogues aint stealthed, they just walk around

### Expected Blizzlike Behaviour

they should be stealthed.

### Source

????

### Steps to reproduce the problem

1. go to shh
2. get to the corridor with rogues after the ogre boss
3. u might see them sometimes

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kirishiki** [comment] 2023-06-07 06:37
![image](https://github.com/chromiecraft/chromiecraft/assets/22181175/fcc66235-421a-495c-8f4f-670da5a186c6)

**Comment by gchekenny** [comment] 2023-06-15 18:17
Tested, I cannot reproduce it.
Shattered Hand Assassins were all stealthed and they returned to stealth when they were forced to get out of combat.
![WoWScrnShot_061523_151526](https://github.com/chromiecraft/chromiecraft/assets/65800273/7fa9ba10-1761-49dd-a25e-5fed0eef74c7)
![WoWScrnShot_061523_151544](https://github.com/chromiecraft/chromiecraft/assets/65800273/b819bf42-b883-418e-8eba-36a0e64fd5df)
![WoWScrnShot_061523_151555](https://github.com/chromiecraft/chromiecraft/assets/65800273/ecce2fe3-f58d-4fc5-abbf-1d1dd3a2b7d0)

**Comment by Rorschach91** [comment] 2024-08-12 14:55
I Tested the dungeon on PTR and I can confirm that It's a rare bug.

I close this issue. Thank you for report, if you find other bug feel free to report them.

**Closed** 2024-08-12 14:56 UTC
Labels: Closed, Rare Bug
