### ISSUE TITLE
[Rogue] Auto attack bug

### ISSUE THREAD

**Issue by Ulpen** [chromiecraft/chromiecraft#5789] opened 2023-06-17 09:07 UTC
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

sometimes when I attack or get caught in stealth, the auto attack bugs, it doesn't start, once it bugs it never starts again until I relog.

### Expected Blizzlike Behaviour

/

### Source

/

### Steps to reproduce the problem

/

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment] 2023-06-18 19:21
Did you drink any potions or anything cause this sounds similar to a bug that happens with noggenfogger elixir [or any potion :)] But if it just happened for no reason not even potion bug than that is kekw

**Comment by Stump876** [comment] 2023-06-24 16:28
Hi @Ulpen. Thanks for the report. Can you please include some steps to reproduce the bug? Yes the current behavior sounds self explanitory, but it helps when the person doing the triage knows exactly what you did to make it happen.

**Comment by Never6** [comment] 2023-06-25 02:25
> Hi @Ulpen. Thanks for the report. Can you please include some steps to reproduce the bug? Yes the current behavior sounds self explanitory, but it helps when the person doing the triage knows exactly what you did to make it happen.

Just perspective from a 3rd party but I'm guessing he didn't really do anything outside of normal gameplay in order for the bug to occur 
So he doesn't know what caused the bug to occur 
My guess is it was a health potion because this exact same situation happens with noggenfogger elixir and health pots

**Comment by heyitsbench** [comment] 2024-05-06 23:13
Closing this as author has not provided steps and it likely is a duplicate of the aforementioned issue or similar.

**Closed by heyitsbench** 2024-05-06 23:13 UTC
Labels: Needs Triage
