### ISSUE TITLE
error en entrega de mision 

### ISSUE THREAD

**Issue by olmarfreddy** [chromiecraft/chromiecraft#5718] opened 2023-06-04 21:58 UTC
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

al entregar la misión llamada la petición de Rohok en el npc no permite completar dicha misión
![captura de wow](https://github.com/chromiecraft/chromiecraft/assets/135555449/884b63a4-e673-48a2-949f-fa8646dd105c)

### Expected Blizzlike Behaviour

debería poder completar la misión al interactuar con el npc 

### Source

![captura de wow](https://github.com/chromiecraft/chromiecraft/assets/135555449/7c818f2e-7863-40a3-8f46-b65bad671edb)

### Steps to reproduce the problem

1.2.3.4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2023-06-06 16:46
Are you sure you actually have the items required for the quest?

**Comment by gchekenny** [comment] 2023-06-15 02:09
Tested, quest works as intended.
![WoWScrnShot_061423_230913](https://github.com/chromiecraft/chromiecraft/assets/65800273/efd6ac3e-a71d-4421-84aa-d3a0179236ea)

**Comment by heyitsbench** [comment] 2023-06-15 02:36
@olmarfreddy Please feel free to re-open the issue if you can reproduce, but neither gchekenny nor I can, so I'm closing the issue for now.

**Closed by heyitsbench** 2023-06-15 02:36 UTC
Labels: Needs Triage
