### ISSUE TITLE
Onyxia's Lair - Onyxia loot table adjustment

### ISSUE THREAD

**Issue by godnesso** [chromiecraft/chromiecraft#3180] opened 2022-03-07 00:58 UTC
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The level 60 version of Onyxia in Onyxia's Lair has a loot table that differs from the retail version:
Pieces of gear can drop in combinations that would be impossible in the retail version (an example of such impossible combination would be Vis'kag and Deathbringer).
Certain items from Onyxia drop more frequently than intended.
It is impossible for 2 identical Tier 2 heads to drop.
No blue and green items drop.
Sack of Gems do not drop.
Only one 18 slot bag can drop.

### Expected Blizzlike Behaviour

When reviewing videos of boss kills from both current WoW classic and Pre 3.2 WotLK, you can make the observation that the item pools from Level 60 Onyxia appear to be seperated into the following:
Pool A: One of the Tier 2 heads
Pool B: One of the Tier 2 heads
Pool C: Eskhandar's Collar, Ancient Cornerstone Grimoire, Ring of Binding, Sapphiron Drape
Pool D: Vis'kag the Bloodletter, Deathbringer, Shard of the Scale

It appears that it should be possible that two identical Tier 2 heads can drop.
Items in Pool D are not guaranteed.
Onyxia should drop two additional blue quality pieces of gear and a random class book that teaches group buff spell (example item id 17413). There should also be a chance a high-level crafting recipe and up to 2 additional green-quality pieces of gear can drop. It should also be possible that two 18 slot bags can drop instead of only one.

### Source

classic
https://www.youtube.com/watch?v=zt-GMnX_q_Q
https://www.youtube.com/watch?v=Qz6Ka82K9w8
https://www.youtube.com/watch?v=NDHt_VYkUEM
https://www.youtube.com/watch?v=zRG6nVoI13U
https://www.youtube.com/watch?v=N0c_9CEkbdI
https://www.youtube.com/watch?v=T0J2GZw6Z-c

tbc
https://www.youtube.com/watch?v=BOKlXklfzzE
https://www.youtube.com/watch?v=aljMIXkgaKg

wotlk
https://www.youtube.com/watch?v=Zpx4liKIfJY
https://www.youtube.com/watch?v=IRdvFOe1uI8
https://www.youtube.com/watch?v=GvXfWQxkMYc
https://www.youtube.com/watch?v=cRIPmnm0XDQ
https://www.youtube.com/watch?v=uRW80u5qnSk
https://www.youtube.com/watch?v=fhTKEDqyYk4
https://www.youtube.com/watch?v=jGyXYNH_GS4
https://www.youtube.com/watch?v=xkW_zeJw8tE
https://www.youtube.com/watch?v=a9ysY65_ELQ
https://www.youtube.com/watch?v=G8q8-ntYR6M
https://www.youtube.com/watch?v=_pW6TXpraF4
https://www.youtube.com/watch?v=2RecvF8Oe0A

### Steps to reproduce the problem

Kill Onyxia and loot

### Extra Notes

Personally, I'd argue the most important adjustment would be the epic loot because healer trinkets and melee weapons drop far too often at the moment.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d6823989429c5762eac9ea99bf0e9cb3d3b6b7af

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment] 2022-04-02 14:21
duplicate of https://github.com/chromiecraft/chromiecraft/issues/2956

**Closed by temperrr** 2022-04-02 14:21 UTC
Labels: Needs Triage, Loot
