### ISSUE TITLE
[Silithus] Vish Kozus NPC missing, quest ender and giver

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1952] opened 2021-10-03 07:48 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

NPC is removed by staff for no good reason. Honey told me that he got removed till patch 1.6. This NPC takes no part in Ahn'Qiraj gate opening. No reason not to have him he ends and starts few leveling quests. Literally you made Silithus without quests now.

### Expected Blizzlike Behaviour

He is present in every patch and every content

### Steps to reproduce the problem

1. Go to Silithus at Cenarion Hold
2. Cry

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment] 2021-10-04 04:14
If you've made AC devs aware of this issue and they've confirmed it's deliberate, then this is not a bug. I don't know the reasoning that went into the decision, although my guess would be it's because this NPC awards Cenarion Logistics Badges, which can be turned in for ilvl 66 gear, which is better than anything in Scholo or Strath. (They're mostly ilvl 61-63 with a few 65s.) Either way, closing as this is intended behaviour.

**Closed by Azcobu** 2021-10-04 04:14 UTC
Labels: Needs Triage
