### ISSUE TITLE
Black Morass, First boss not spawning, 2nd break delayed.

### ISSUE THREAD

**Issue by SwedishRat** [chromiecraft/chromiecraft#5397] opened 2023-04-11 19:16 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

During a run of Black Morass, the first boss never spawned, it just continued doing the normal Rift lord/keeper portals. The break that is supposed to happen after the first boss also never ocurred. After killing the 2nd boss there was also no break but instead after finishing the wave after the boss (wave 13) the break happened.

### Expected Blizzlike Behaviour

There should be a first boss and a break after it, the 2nd break should also happen right after the 2nd boss.
https://www.youtube.com/watch?v=nlvi1Mho3uY&ab_channel=DistrictGamers  (TBC classic)
https://www.wowhead.com/wotlk/zone=2366/the-black-morass#comments:id=30403 (Comment from Vanilla TBC)

### Source

Previous runs on CC.
TBC classic runs.
WoWhead comments from OG TBC

### Steps to reproduce the problem

1. (Uncertain) Start the waves/portals while someone is outside dungeon. (this was the only thing different from a normal run)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment] 2023-04-12 09:41
Caused by someone entering while the event is already in progress, yes

**Comment by Rorschach91** [comment] 2024-08-11 18:05
I tried to reproduce it two times, without results.
Or it is a rare bug or has been fixed.

I close this report. Thank you for your report.

**Closed** 2024-08-11 18:08 UTC
Labels: Closed, Unable to Reproduce
