### ISSUE TITLE
bash spell auto-toggle, (shaman feral spirit)

### ISSUE THREAD

**Issue by migena8** [chromiecraft/chromiecraft#6196] opened 2023-09-30 12:18 UTC
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

As soon as the shaman's feral spirit spell is used, Bash is automatically cast and there is no way to block it. If you try to block it (removing the shiny gold frame from the spell), the next time you use feral spirit, bash is automatically cast again

### Expected Blizzlike Behaviour

Bash, like any other pet skill, should be able to be "locked" to be used at the player's discretion

### Source

https://www.wowhead.com/wotlk/spell=58861/bash#comments

### Steps to reproduce the problem

- Use Feral Spirit
- You see Bash autocasted
- Disable pet autocast
- use Feral Spirit again
- You still see Bash autocasted

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment] 2024-01-20 23:48
Duplicate of #2593.

**Closed by heyitsbench** 2024-01-20 23:48 UTC
Labels: Needs Triage
