### ISSUE TITLE
Druids stay shapeshifted on FP after leaving RDF

### ISSUE THREAD

**Issue by Zerkenn** [chromiecraft/chromiecraft#1437] opened 2021-08-15 17:59 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When in a RDF dungeon in any druid shapeshift form when you leave a dungeon while on a flight path you stay in your shape shifted form.
![bugimg](https://user-images.githubusercontent.com/88915224/129487881-11245b08-2b27-4538-ad18-ab7dda5221c0.png)

### Expected Blizzlike Behaviour

If you are in any shapeshifted form as a druid and you leave a dungeon from the RDF tool your character should shift back to their normal un shapeshifted form while on a flight path.

### Steps to reproduce the problem

1. Join a RDF dungeon on a druid while on a flight path to anywhere.
2. Shape shift into any form while inside the dungeon.
3. Leave the party or use the teleport out of dungeon option while in any shapeshift form

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment] 2021-08-15 21:29
Hey, thank you for the report! This is a duplicate of [#1329](https://github.com/chromiecraft/chromiecraft/issues/1329). A fix is already on the way, but not yet live on Chromiecraft: [see here](https://github.com/azerothcore/azerothcore-wotlk/pull/7292

**Closed by syssneck** 2021-08-15 21:29 UTC
Labels: Needs Triage
