### ISSUE TITLE
Blackfathom Deeps -> Barzers at Kelris spawn more mobs

### ISSUE THREAD

**Issue by OA350** [chromiecraft/chromiecraft#3211] opened 2022-03-17 18:23 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Blackfathom Deep Braziers at Kelris spawn more mobs then needed -> 6 water elementals instead of 2 and 8/12 tortoises instead of 4.

Started happening today (2 out of 2 runs). Never seen before

### Expected Blizzlike Behaviour

Spawn 2 water elementals and 4 tortoises

### Steps to reproduce the problem

1. Go to Blackfathom Deeps
2. Light Braziers at Kelris

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nueschts** [comment] 2022-03-17 23:39
[PTR]
I was able to reproduce this by very fast double-clicking the brazier.
This first image is from clicking a brazier once, shortly after which it lights up and you cant interct with it anymore.

![WoWScrnShot_031822_002053](https://user-images.githubusercontent.com/61170874/158910364-11e6008b-4e4a-49d4-bcf2-33b525d3da78.jpg)

The second image is with double-click, as several ppl in a group might click within a short timeframe or one person clicking several times (i think that's how the 6 elementals might have been spawned).
![WoWScrnShot_031822_002414](https://user-images.githubusercontent.com/61170874/158910704-02fa7171-c5b4-40a1-a3bb-8f3eb9288d76.jpg)
![WoWScrnShot_031822_002520](https://user-images.githubusercontent.com/61170874/158910711-d0f83365-7188-4ac1-92d3-602133ad03b3.jpg)

On a side note, using a macro to simulate 2 clicks at the very same time (like .gobject activate 32930
.gobject activate 32930), you get the brazier to go inactive permanently without spawning adds. It can be activated with a command, but in a group you would be stuck, because you had no way to open he door.

Maybe the problem has sth to do with infomation getting to the server and then back to the clients, and whatever indow of time that creates?

**Comment by OA350** [comment] 2022-03-18 06:27
Regarding the clicking, it was our tank who lighted the brazzierts both times, and it was both times the same guy. So I cannot know if he was klicking it twice/ three times or using some macro or having some lag unfortunately

**Comment by damnablebear** [comment] 2023-09-18 20:46
This was closed in the AC issue as "could not reproduce" last year, and I cannot reproduce this on my local AC environment.

**Closed by damnablebear** 2023-09-18 20:46 UTC
Labels: Confirmed, Linked [AC], [20 - 29]
