### ISSUE TITLE
Ardent Defender not proccing

### ISSUE THREAD

**Issue by ICarebear** [chromiecraft/chromiecraft#4522] opened 2022-12-02 16:43 UTC
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

When you hit 0 as a prot paladin Arden Defender doesn't save you and instead you die. No proc, no debuff

### Expected Blizzlike Behaviour

Ardent Defender prevents death and heals you

### Source

![image](https://user-images.githubusercontent.com/110199518/205342241-aa71ba26-8236-46d0-bb0c-e4346125d896.png)

### Steps to reproduce the problem

Make paladin
Take talent Ardent Defender
Tag mobs
Die

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment] 2022-12-02 23:41
[ad test.webm](https://user-images.githubusercontent.com/62584589/205409559-a4e885e1-9ec9-412d-8430-093bb176ee0e.webm)

Seems fine to me. Two things I can think of why your AD might have not worked were 1) you had the AD debuff up still, 2) you took damage instantly equal to the amount healed after it proc'd.
Combat logs show it working, and visual spell goes off correctly. You'd have to provide more proof (video or SS of log) to see if it's player issue or error in logging.

**Comment by Gultask** [comment] 2022-12-03 02:25
Thanks for checking, Cooties!
Carebear was there a specific location where you saw it happen? Maybe it would be possible to replicate in certain conditions, depending on the cause.

**Comment by Pyromanihack** [comment] 2023-01-06 15:48
I tested it and obtain the same result ad Cooties. I am gonna close this issue, but if anyone has any proof about it can comment below

**Closed by Pyromanihack** 2023-01-06 15:48 UTC
Labels: Unable to Reproduce
