### ISSUE TITLE
Alliance brewfest revelers are unfriendly to alliance

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#1862] opened 2021-09-26 06:51 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Alliance brewfest revelers are now unfriendly and can be targeted for attack. Ironforge guards will kill them as well.

![image](https://user-images.githubusercontent.com/68164076/134796953-7b278839-8f35-4d46-865f-f4223eb8b0c8.png)

### Expected Blizzlike Behaviour

NPC Faction ID is set to 775 which I believe is the Horde ID 
Alliance faction ID should be 1934

### Source

No source, just went off my local AC where this problem doesn't exist.

![image](https://user-images.githubusercontent.com/68164076/134796522-f953edd1-286c-4f20-90e2-b1114ecdc42f.png)
![image](https://user-images.githubusercontent.com/68164076/134796671-1d52385a-4808-43d6-859d-c7a27ee3df42.png)

### Steps to reproduce the problem

1. .event start 24 (if brewfest not acive)
2. .go c 88889
3. .npc info
4. .gm off 
5. Repeat as opposite faction, Notice unfriendly for alliance, friendly to horde
6. .go c 84899
7. .respawn
8. watch gaurds kill them

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment] 2021-09-26 07:54
Cant replicate on no module local AC on 792b99cbc9a6 Seems like a CC issue?

**Comment by Stump876** [comment] 2021-09-26 08:12
Agreed, I'm going to leave this here for now so people know it's been reported.  I'll look more into it tomorrow if someone doesn't beat me to it.

**Comment by cachocarne** [comment] 2021-09-28 06:13
The strangest thing for me is that this was not like that just some days ago. It happened now, few laters in the event. Maybe some mistake on one of the last restart/updates?

**Comment by gurveleg** [comment] 2021-09-28 08:42
Indeed. I cannot reproduce on local AC either, but they definately are attackable on CC.

**Comment by Gultask** [comment] 2022-04-29 19:26
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/9264

**Closed by Gultask** 2022-04-29 19:26 UTC
Labels: Confirmed, Linked [AC], Generic Issues
