### ISSUE TITLE
Mithril Bound Trunk not getting off from bags after opened

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#560] opened 2021-05-07 16:17 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Item ID 21228

Referred to this item, if you get more than one on your bags, with auto-loot set to enabled, and you right click multiple items 21228 one by one, sometimes empty trunk not getting off from bags after loot is looted.

Result: Empty trunk in bag to be dragged off bags or sold (empty).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Open, get all loot. Get off from bags. End.

##### STEPS TO REPRODUCE THE PROBLEM:

Video test example of the bug:  https://youtu.be/YHGJ-aaJ4QY

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by lovelord83** [comment] 2021-05-07 16:58
Yes, in  my example I got 4 trunks. 
Right clicked all of them inside bags.
1 has been removed from bags after autoloot has loot all the items and set them into bags (OK).
3 of them remained in bags (empty) ... (BUG)

they should be removed all, the same way.

**Comment by necropola** [comment] 2021-05-07 17:24
Duplicate of #444 
Only happens when you have already learned how* to *Find Fish**.

**Closed by necropola** 2021-05-07 17:24 UTC
Labels: Closed, Duplicate
