### ISSUE TITLE
[Zul'Farrak] Killing bosses downstairs on stairs event before friendly NPCs walk down stops the event

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#1838] opened 2021-09-24 16:31 UTC
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

If you manage to kill spawned bosses Nekrum Gutchewer and Shadowpriest Sezz'ziz (they spawn when every mob downstairs is killed) before friendly NPCs starts going down, event will stop and you won't be able to finish friendly NPCs as part of event.

### Expected Blizzlike Behaviour

Friendly NPCs should walk down the stairs no matter if you kill bosses or not before they arrive. Event should continue at the point that you kill those friendly NPCs and get key and items from Sergeant Bly.

https://www.youtube.com/watch?v=N1a5hc4Uh-M&ab_channel=DcarrGaming

You can see friendly NPCs helping out party members to kill bosses, if you kill bosses before they start helping it bugs out here

### Steps to reproduce the problem

1. Go to dungeon Zul'Farrak
2. Get to the stairs Event
3. Kill adds fast and kill two bosses that spawns before friendly NPCs reaches down the stairs
4. Event will stop

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-19 14:02
I guess it was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/7855. Right now i'm unable to reproduce it. I will close it acordingly.

**Closed by Shineslippers** 2021-11-19 14:02 UTC
Labels: Needs Triage, Unable to Reproduce
