### ISSUE TITLE
Hunters can roll need on shields with RDF dungeon "Need before Greed" System

### ISSUE THREAD

**Issue by torrenteeselkmanda** [chromiecraft/chromiecraft#470] opened 2021-04-26 15:00 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In RDF hunters are elegible to roll need on shields even if they cannot use them

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Greed/Disenchant/Pass should be the options available for hunters when rolling for shields

![Screenshot_2](https://user-images.githubusercontent.com/68659490/116105820-fa147900-a6b1-11eb-8dff-ecc5d54cbf7c.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to RDF
2. Be a Hunter
3. A shield droops

##### EXTRA NOTES:

Elflady, Germ, Amuro and Surtur can confirm it's a bug

![Screenshot_3](https://user-images.githubusercontent.com/68659490/116105815-f97be280-a6b1-11eb-9d9d-31369d955134.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment] 2021-05-15 18:55
Duplicate of #190

**Closed by necropola** 2021-05-15 18:55 UTC
Labels: Closed, Duplicate
