### ISSUE TITLE
Gift of Arthas duration not affected by Mixology passive

### ISSUE THREAD

**Issue by valery445** [chromiecraft/chromiecraft#4025] opened 2022-09-01 13:26 UTC
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

30-39

### Current Behaviour

The Gift of Arthas duration even with Mixology and learnt recipe stays 30 min.

### Expected Blizzlike Behaviour

The Gift of Arthas duration with Mixology and learnt recipe should be increased to 1 hour. i.e. by two times.

### Source

Articles on Mixology passive:
https://wowgaming.altervista.org/aowow/?spell=53042
https://www.wowhead.com/wotlk/spell=53042/mixology

### Steps to reproduce the problem

1. Create a character
2. `.character level 60`
3. `.learn all recipes alchemy`
4. `.additem 9088`
5. Observe the duration of the Gift of Arthas

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment] 2022-09-02 22:55
Duration confirmed on PTR. buff timed out after 30 mins afk.

looking into intended behaviour
https://user-images.githubusercontent.com/11332559/188244194-b1344ca3-ed84-4442-820d-1576c3489e4a.mp4

**Comment by avarishd** [comment] 2023-04-03 11:40
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/12982

**Closed by avarishd** 2023-04-03 11:40 UTC
Labels: Confirmed, Linked [AC], Generic Issues
