### ISSUE TITLE
[Redridge Mountains] Practice Lockbox in Alther's Mill cast while despawning

### ISSUE THREAD

**Issue by Blackmane11** [chromiecraft/chromiecraft#1345] opened 2021-08-06 09:12 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Hi,
While i was leveling up lockpicking in Alther's Mill (roughly [52.0, 45.3]) i was able to double cast the picklock during the spawn phase and on the despawning phase.
Basically if you are quick enough you can click just as the last cast finishes and on the despawning phase you start another cast that skills up and can eventually drop something because it opens the loot table, the chest itself doesn't drop anything so that's why you can go so fast probably if you shift+click.
First cast:
![WoWScrnShot_080121_203207](https://user-images.githubusercontent.com/88534145/128486220-fd976792-98f6-43be-a013-45fc96021154.jpg)
Second cast:
![WoWScrnShot_080121_203213](https://user-images.githubusercontent.com/88534145/128486245-4fd05ab4-c34c-4f37-9db4-e47bb8e3e570.jpg)
Also the respawn timers are quite quick but correct, as of WoWHead the chests should spawn in 5seconds.

### Expected Blizzlike Behaviour

After the first cast the chest should not be interactable.

### Steps to reproduce the problem

1. Be rogue with the lockpicking skill (1).
2. Continuously click on the chest and you should be able to trigger it.

### Extra Notes

Remember that the chest are under the Lumberjack Mill, there are 3 or 4 of these.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment] 2021-08-07 03:27
Hello. Thanks for the report! I can confirm this behavior, and you are correct- it should be one cast to one box. But what I believe you're seeing is you clicking on the next chest before it phases in completely. Sometimes it will fail (because the box hasn't fully spawned yet) and sometimes it will open the next box the second it spawns, and the process starts all over again. 

https://user-images.githubusercontent.com/68164076/128585892-e9e63f5b-29dc-458b-9b5b-1d1d6ab3a2d6.mp4


Ultimately this really has zero effect on the game as these chests spawn very quickly, and serve no other purpose other than leveling lock picking. Ironically this does not work with `Glyph of Pick Lock` Which opens boxes instantly without the cast bar.

Lastly, I can find no evidence showing that this is not blizzlike. Feel free to look and post anything in here you may find that shows otherwise. But for now I'm going to close it.

**Closed** 2021-08-07 03:28 UTC
Labels: Invalid, Closed, Class Issue
