### ISSUE TITLE
Focused Assault Debuff from WSG Persists after Battleground has ended

### ISSUE THREAD

**Issue by zwillan** [chromiecraft/chromiecraft#738] opened 2021-05-30 17:26 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Focused Assault debuff https://wowgaming.altervista.org/aowow/?spell=46392 stays after the WSG battleground ends.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Focused Assault should not remain on your character after the battleground ends. I can't find any evidence about this issue specifically, but patch notes at the bottom of this page: https://wowpedia.fandom.com/wiki/Warsong_Gulch state that the timer for the debuff should reset when both flags are returned to their bases, which I assume happens when a battleground ends. Also it just doesn't make sense for it to remain when you don't have the flag anymore.

##### STEPS TO REPRODUCE THE PROBLEM:

1. join WSG
2. carry flag until you get debuffed with Focused Assault
3. wait until battleground ends
4. observe the debuff still being there

##### EXTRA NOTES:

<a href="https://ibb.co/6rT8t31"><img src="https://i.ibb.co/BcQG6Xr/CCbug.jpg" alt="CCbug" border="0"></a>

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment] 2021-05-31 14:46
Just tried replicating this by having two enemies cap each other's flags and stand around for 25 minutes, waiting for WSG to time out. However, the debuff (it was Brutal Assault rather than Focused because they'd been standing around so long) did disappear once the BG eventually timed out. Also tried getting the debuff and then getting kicked out by going AFK, and that didn't do it either.

Was WSG timing out how you ended up with the debuff? Judging by your chat window you logged out and back in again, how long did it last afterwards?

**Comment by zwillan** [comment] 2021-05-31 16:12
Yes, if I remember correctly I was holding the flag while in bear form and the match timed out. I relogged multiple times trying to get rid of the debuff but it only went away after my character died.

Each team scored once then we just held out till the match ended since my team capped last.

**Comment by Azcobu** [comment] 2021-06-01 15:02
Should have found this before. Same issue, just a different variation on the debuff: https://github.com/azerothcore/azerothcore-wotlk/issues/5157

It also seems likely druid forms are involved - note the original reporter was a bear druid as well. However, I've run WSG half a dozen times now with a pair of druids and still haven't been able to make the debuff persist past the end of the match. Can you remember if crossfaction/faction change was involved at all?

**Comment by zwillan** [comment] 2021-06-01 19:28
I believe I was faction changed to a night elf during that game but I can't remember for sure. I do remember a shaman was with me when the game ended, so maybe one of the totem buffs has something to do with it?  

I play WSG pretty frequently and I'm often the flag carrier so if it happens again I'll make sure to make note of what happened and probably get some screenshots as well.

**Comment by Azcobu** [comment] 2021-06-02 13:02
Finally reproduced this after installing the Cross Faction BGs mod, although oddly enough it was the non faction-changed bear that was tagged with the debuff. Thanks for the report and answering various questions, and hopefully a fix will be on the way.

**Comment by overflowz** [comment] 2021-11-23 12:17
Can confirm, happened right now to me. Two of us were holding flags, BG was timing out due to the low amount of players and debuff stayed after it ended.

**Comment by Shineslippers** [comment] 2021-11-24 16:26
@overflowz Can you please provide more info. Trying to repeat it and nothing.
- What classes was?
- Where you was at the end of BG? Place
- Which button you pressed to move out from BG
- Maybe something else what you can specify

The issue is when BG stats show up at the end all debuffs is removing.

**Comment by overflowz** [comment] 2021-11-24 16:37
I'll post everything I remember.

1. The BG was 2v2 (10-19 levels)
2. There were me and rogue vs the other two players (enemy rogue and some class I don't remember, let's call it X).
3. Me and X were holding flags for more than 5+ minutes.
4. X quit the game and the enemy rogue took it (not sure if it was from a disconnect or gave it to him).
5. Game announced that BG will be over in N minutes because of the lack of players.
6. I was waiting at my base to capture the flag (exactly at our flag position so I would capture it immediately if our flag would be returned)
7. My rogue was chasing the enemy rogue, probably fighting too (not remember correctly).
8. Then the game ended, and I clicked the leave button on the score screen.
9. The debuff was kept.
10. If I remember correctly, when I left, I was in the middle of the air (flying to Lakeshire by taxi).

This is all I remember.

**Comment by Shineslippers** [comment] 2021-11-24 16:51
Yes, rebuff is remiving on death or ofc server crash xD. Appreciate for the info. I will try again.

**Comment by overflowz** [comment] 2021-11-24 16:52
> Yes, rebuff is remiving on death or ofc server crash xD. Appreciate for the info. I will try again.

Yea, but only when the worldserver crashes (authserver should not affect that I guess).

**Comment by Nefertumm** [comment] 2022-01-28 20:17
Fixed by ab121e246e93e440cacba4b4b5e9e47a58b8a9f6

**Closed by Nefertumm** 2022-01-28 20:17 UTC
Labels: Confirmed, Linked [AC], Generic Issues, PvP
