### ISSUE TITLE
Potential quest item counter issue

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#2057] opened 2021-10-11 09:03 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

For quest “Buzzbox 525” in Darkshore, looting quest items (grizzled scalp) when there are quest items in bank and then retrieving the quest items from the bank confuses the quest item counter. Here are details:

I worked on quest “Buzzbox 525” a while ago. After I got the first grizzled scalp (a total of four are needed), I decided to go to a different zone. So, I kept the quest in my quest log, left the grizzled scalp in the bank, and did not return to Darkshore until recently. I continued to work on this quest. After I killed some grizzled thistle bears and looted the second grizzled scalp (out of four, first one of this trip), I remembered that I had one in the bank. So I retrieved the grizzled scalp from the bank. Now I had two grizzled scalps in my bag, zero in the bank. After I looted the third one, the grizzled thirle bears stopped dropping the scalp. I killed about 20 of them and just could not loot the fourth scalp. Then when I patrolled in the area looking for bears, I ran by the Buzzbox 525 and there was a yellow question mark above it. I right clicked the buzzbox, the “complete” button was gray.

In my quest log, it correctly showed that I had 3/4 scalps. If I showed quest on map, there was no yellow question mark on the map. If I moved cursor over a grizzled thistle bear, the tooltip also correctly showed that I have one more scalp to go.

I abandoned the quest, accepted it again, and looted four scalps within the first several kills of grizzled thistle bears, and turned it in without any issue.

My guess is: there are two quest item counters in the game, one controls whether a quest item drops and whether the ending NPC has yellow question mark above it; the other one controls what is displayed in quest log, quest tracker, and tooltips. When I looted a quest item with quest item existing in the bank, and then retrieved the existing one, the first one got confused. It believed that I’ve got all four quest items when I only had three. Then the mobs stopped dropping the quest item and it was impossible to complete the quest unless I abandoned the quest and did it from beginning.

If my guess is correct, this issue could occur in other quests with similar requirement (collect some items x n).

### Expected Blizzlike Behaviour

No idea whether same bug exists in retail.

### Steps to reproduce the problem

1. Accept “Buzzbox 525” in Darkshore.
2. Go to south Darkshore, kill “grizzled thistle bear”, loot one “grizzled scalp”.
3. Leave the “grizzled scalp” in the bank.
4. (You may need to log out for some time and back.)
5. Loot one more “grizzled scalp”.
6. Retrieve the first “grizzled scalp” from the bank.
7. Loot one more “grizzled scalp” so that you have three in your bag, none in the bank.
8. Go to Buzzbox 525 and verified that there is a yellow question mark above it but you cannot turn in the quest.
9. Check quest log and built-in quest tracker to verify that they correctly indicate that you have three scalps and need one more.
10. Find a grizzled thistle bear, move cursor over it to verify that the info in tooltip correctly indicate that you have three scalps and need one more.
11. Kill a few more grizzled thistle bear to verify that they don’t drop the scalp anymore.
12. Abandon the quest, accept it again, go to kill the grizzled thistle bears and loot grizzled scalps, verify that it can be completed without issue.

I already reproduced the issue with another of my chars.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment] 2021-10-12 01:32
If the item was in your bank, then this is a duplicate of #902, #1200 and azerothcore/azerothcore-wotlk#6442

**Comment by discorder0** [comment] 2021-10-15 04:04
No, it is a different issue. In my case, some counter in the game believe that the requirement has been fulfilled while some other does not WHILE THE REQUIREMENT IS NOT FULFILLED.

**Closed** 2021-11-05 23:02 UTC
Labels: Confirmed, Linked [AC], Generic Issues
