### ISSUE TITLE
[Item] Satchel of Helpful Goods for levels 46-55 drops gold instead of items

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#2288] opened 2021-11-08 19:05 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59

### Current Behaviour

Satchel of Helpful Goods item for completing Random Dungeons via Dungeon Finder, while being level 46-55 (https://wowgaming.altervista.org/aowow/?item=52002), stopped from dropping corresponding items https://wowgaming.altervista.org/aowow/?item=52002#contains and instead drops the random amount of gold within range 1 to 2 gold per satchel.

### Expected Blizzlike Behaviour

Satchel of Helpful Goods item for completing Random Dungeons via Dungeon Finder while being level 46-55 (https://wowgaming.altervista.org/aowow/?item=52002) drops corresponding items https://wowgaming.altervista.org/aowow/?item=52002#contains, one per satchel.

### Source

https://wowwiki-archive.fandom.com/wiki/Satchel_of_Helpful_Goods_(level_55)
https://wowgaming.altervista.org/aowow/?item=52002#contains

### Steps to reproduce the problem

1. Prepare character with level within range 46-55
2. Queue for Random Dungeon via Dungeon Finder
3. Complete the dungeon to receive Satchel of Helpful Goods (or use command .additem 52002)
4. Open recently obtained Satchel of Helpful Goods
5. Pay attention to the reward inside the satchel

### Extra Notes

The issue might be caused by the fact that on 10/18/2021 loot of https://wowgaming.altervista.org/aowow/?item=52003 (satchel for RDFs 56-60) was changed in accordance to
![obraz](https://user-images.githubusercontent.com/71841180/140801594-e06e2d60-fb07-4581-8688-8dcf74054e56.png)
but the rule just spilt over to one bracket lower.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/27b880876dd411b2433ec227d69f6f79dc0c3ce4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment] 2021-11-09 00:03
Unfortunately it's not a bug. I have to close this report accordingly. You can leave your opinion about this feature in our Discrod https://discord.gg/sfGbtgcq. There is exist suggestion channel.

**Closed** 2022-01-18 12:08 UTC
Labels: Confirmed
