### ISSUE TITLE
[Quest] Third part of Wetlands quest chain "Ormer's Revenge" doesn't grant reward nor XP

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#2054] opened 2021-10-10 19:59 UTC
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I did the Wetlands quest chain "Ormer's Revenge" - and the first two parts worked flawlessly.

For the third part Ormer asked me to kill Sarltooth and bring him his talon.

I did, but when I turned in the quest all I received was Ironforge reputation - no reward and no XP.

![Bildschirmfoto 2021-10-10 um 21 45 44](https://user-images.githubusercontent.com/91610030/136711248-bc2f975a-632a-4b26-a526-bd624978e64b.png)

### Expected Blizzlike Behaviour

Turning in the quest should grant the selected reward + XP.

### Steps to reproduce the problem

1. Start the quest chain "Ormer's Revenge" in Wetlands.
2. On part 3 of the chain notice when you turn in the quest you receive nothing but Ironforge reputation - no reward, no XP.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment] 2021-10-11 04:28
works fine for me. local ac

**Comment by jamadaha** [comment] 2021-10-11 06:21
Works fine for me locally as well:
![image](https://user-images.githubusercontent.com/53914190/136741965-4bc7292f-44b7-4888-9c58-fb212edbb728.png)
![image](https://user-images.githubusercontent.com/53914190/136742073-09fd06b3-6b1e-47f6-a73a-d0440bec5697.png)

**Comment by syssneck** [comment] 2021-10-11 06:35
Same for me, works fine:
![grafik](https://user-images.githubusercontent.com/68868567/136743393-1b208b23-8ead-44aa-8411-fa48a4ba5ef9.png)
You can't even finish the quest, before choosing a reward. Sorry, I'm closing this now, it is not a general issue.

**Closed by syssneck** 2021-10-11 06:35 UTC
Labels: Needs Triage, Unable to Reproduce, Needs second opinion

**Comment by Snufflenose** [comment] 2021-10-11 07:48
Well, it's nice that it works for you guys.

I'm still curious why it didn't work for me (as you can clearly see from my screenshot) - or are you doubting that it happened?

Syssneck wrote: "You can't even finish the quest, before choosing a quest reward."

Well, I did choose a quest reward before turning in the quest.

The quest was finished, I received Ironforge reputation, but nothing else.

To be honest, it kinda leaves a bad taste in my mouth if stuff like this can occasionally happen on this server.

**Comment by jamadaha** [comment] 2021-10-11 07:54
@Snufflenose It's more of an issue of: if we can't reproduce it, we can't fix it. Simply because it isn't possible to fix something without knowing what causes it, and as an extension how to make it occur.
I don't think anyone doubts that it occured for you, more that we wouldn't be able to fix it.
