### ISSUE TITLE
Resetting instance after you died in an instance means you cannot ressurect in that instance.

### ISSUE THREAD

**Issue by ndnd123** [chromiecraft/chromiecraft#687] opened 2021-05-23 12:41 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you die in an instance, e.g. SM GY and reset the instance before resurrecting you won't be able to resurrect in there again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to resurrect in an instance that you died in even if you reset it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Die in SM GY (works with any)
2.  When you release spirit click on reset instances
3.  Try to enter the dungeon to rez
4. See that it doesn't work

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment] 2021-05-23 13:04
Pretty sure this is a duplicate of https://github.com/chromiecraft/chromiecraft/issues/577

**Closed** 2021-05-23 20:31 UTC
Labels: Duplicate
