### ISSUE TITLE
Earthbind totem doesn not DR.

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#7540] opened 2024-11-22 23:35 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Earthbind's root does not DR when talented into Storm, Earth and Fire.

### Expected Blizzlike Behaviour

Earthbind's root should DR when talented into Storm, Earth and Fire.

### Source

https://youtu.be/hYX6CejzNUI?t=124

### Steps to reproduce the problem

Level a shaman to level 50.
Spec into Storm, Earth and Fire.
Use Earthbind Totem.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment] 2024-11-23 04:36
I'm not sure what are you refering here to. Including what you mean by `DR` Damage Reduction?

Correct me if wrong. The earthbind totem doesn't (it should) root, when you've "Storm, Earth and Fire" talent

**Comment by amed80** [comment] 2024-11-23 05:03
I think he is talking about Diminishing Returns but also i think this need a better source?
The video that is given is from a private server.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-23 05:06
If DR he means Diminishing Returns can confirm is working as intended, for the root.

**Comment by Sunnypotato** [comment] 2024-11-23 09:19
The opposite of this issue was fixed on TrinityCore: [[Spell] Earthbind Totem](https://github.com/TrinityCore/TrinityCore/issues/7037)
The arenajunkies link waybacked: [Arenajunkies](http://web.archive.org/web/20181224032543/http://www.arenajunkies.com/topic/170817-earthbind-root-dr/)

**Comment by TheSCREWEDSoftware** [comment] 2024-11-23 15:37
I've corrected my comment above, i did more totem testing. If it's supposed to not have DR, than its working as intended a fixed timer for the CC.

About the slow, it worked for me always but the slow has a tick of update so you could be luckly and not getting slow-refresh right before the root ends.

But until @Mikel0ke provides more feeback in the information testing above, we are only working speculation and attempt to interept the issue. 

@amed80 and yes the source isn't valid. Even if it was from official server it's hard to make anything out of a old video that's speed up.

**Comment by Mikel0ke** [comment] 2024-11-23 15:53
If my source is wrong, and it does not have DR the ticket is pointless, thought it would have DR.

**Comment by TheSCREWEDSoftware** [comment] 2024-11-23 15:57
Thanks for the confirmation.

**Closed** 2024-11-23 15:57 UTC
Labels: Unable to Reproduce
