### ISSUE TITLE
[Winter Veil] Quest completion resets

### ISSUE THREAD

**Issue by Tereneckla** [chromiecraft/chromiecraft#4580] opened 2022-12-17 09:04 UTC
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Can do all the quests available at Ironforge again after doing them on the 15th

### Expected Blizzlike Behaviour

Completion state does not reset

### Source

Quests stay completed

### Steps to reproduce the problem

Do the quests
Wait?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment] 2022-12-26 18:39
Hi Tereneckla. I don't believe this is a bug- rather a case of the event resetting. There was a server crash on the 15th and the world event quests reset when the event restarted. 
![image](https://user-images.githubusercontent.com/68164076/209575415-7cdc8019-c324-45fb-b17e-936e362b9538.png)


I believe it resets when the event "starts". The reason for that being so you can complete the quests every year. It's the same set of quests for each event. Once you've completed them, the quest is flagged complete on your character's log. Take the halloween candy buckets for example. You can do them again next year, but those same buckets you looted in vanilla will not give additional gold or exp, even if quest says it does. Just the candy.  If I remember right, we had a similar issue with those resetting daily in some inns, but without a reset.

**Comment by Tereneckla** [comment] 2022-12-26 20:57
Well, the halloween buckets could be reset simply by relogging
I have not tested that much for this event though

**Comment by The-GhostRider** [comment] 2023-12-01 17:28
I checked, it's not a bug.
it is the natural mechanism of events.
Every time an event is restarted, the quests connected to the event restart along with it.

So if the server crashed on day 15, there was a rollback or anything else that triggered the event again it's natural for the quests to reappear again.

For this reason I am closing the report.

**Closed by The-GhostRider** 2023-12-01 17:28 UTC
Labels: Invalid, Closed
