### ISSUE TITLE
Mobs running away and finishing casting their spells while walking away

### ISSUE THREAD

**Issue by pop-pig** [chromiecraft/chromiecraft#658] opened 2021-05-16 19:34 UTC
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There seems to be a bug where a mob which has started casting a spell and starts to flee before finishing the cast, will continue casting the spell while running away.
I've only encountered this issue in dungeons currently, a few times in Uldaman with the Stonevault Oracle casting their Healing Wave and in Scarlet Monastery - Armory with the Scarlet Protector casting their Holy Light.
Both cases seem to be healing spells and mobs who will melle attack (as in they don't cast ranged damage spells).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Cast should be cancelled once the mob moves.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get in Uldaman (easier to test I guess since the Oracles are close to entrance).
2. Start hitting a Stonevault Oracle, get him to start casting Healing Wave.
3. Damage him so that his HP is low enough to trigger the running away / fleeing mode, while he hasn't finished casting Healing Wave.
4. Watch as the mob runs away and finishes casting Healing Wave.

##### EXTRA NOTES:

I will try to provide video evidence but as I do not record everytime I play, I'll try to reproduce it and it might take some time.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/0d699222de92185681f9a78822a0e5d9898294f4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pop-pig** [comment] 2021-05-17 11:25
Seems like it has been fixed? Will keep trying to investigate tho

**Comment by Azcobu** [comment] 2021-05-17 12:12
Thanks for the report. I thought at first this may have been a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5515, which is a similar animation glitch in a fleeing mob, but this one is different. This involves an action that should be cancelled when the mob starts to run away, whereas the other error has the fleeing mob stop and perform an animation. 

However, just had a quick run through Ulda first few rooms and didn't spot them doing it. I did get footage of one breaking his Healing Wave in order to flee:

https://user-images.githubusercontent.com/81782124/118486046-50785300-b758-11eb-90af-cf076c41e63b.mp4

This seems to show correct behaviour with the heal stopping and failing as he runs. So from this and your follow-up comment, I'm going to close this as 'could not reproduce,' but feel free to follow up if you find anything more.

**Comment by pop-pig** [comment] 2021-06-29 12:18
Since some people talk about this issue on CC discord, I tried to reproduce it on a local AC server.
Here is a video of it happening: https://youtu.be/pp_0tF5KuZ0

It is not an easy issue to reproduce as sometimes the mob will not run and cast.

AzerothCore rev. 63b48a9 + 2021-06-29 08:58:28 +0000 (master branch)

**Comment by Shineslippers** [comment] 2021-12-09 13:54
Should be fixed by this https://github.com/azerothcore/azerothcore-wotlk/issues/8843

**Closed by Shineslippers** 2021-12-09 13:54 UTC
Labels: Bug Under Evaluation, Needs second opinion
