### ISSUE TITLE
Sharpening stone and weightstone don't add  dmg to ranged

### ISSUE THREAD

**Issue by Proxig** [chromiecraft/chromiecraft#5928] opened 2023-07-13 21:08 UTC
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

70

### Current Behaviour

When i use weightstone on blunt weapon (staff, fist weapon) or sharpening stone
Then for weightstone only crit is increased for ranged
And for sharpening stone nothing is increased or added

### Expected Blizzlike Behaviour

When i use weightstone on blunt weapon (staff, fist weapon) or sharpening stone
Then for weightstone both crit and +damage should be increased / added to ranged
And for sharpening stone only +damage should be added to ranged

### Source

https://www.wowhead.com/tbc/guide/classes/hunter/dps-consumables-raid-buffs-pve
https://www.reddit.com/r/classicwowtbc/comments/n28p5d/adamantite_weightstones_and_hunters_on_first/

### Steps to reproduce the problem

1. Enchant your fist weapon with weightstone create in blacksmithing
2. attack dummy with white lvl 1 bow and check dmg
3. check your stats in character

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UnicornManure** [comment] 2023-08-06 14:27
Can confirm got no increased dmg with weightstone or sharpening stone on ranged attacks. Tested on the PTR

![DWfist](https://github.com/chromiecraft/chromiecraft/assets/94157725/e26aa46d-7fd2-4c88-96d0-7f61ac81fca6)
Testing with just weapons



![dwfiststones](https://github.com/chromiecraft/chromiecraft/assets/94157725/804c9cdc-9571-4939-bd1e-582d14805c9d)
Testing with weightstones



![dagger](https://github.com/chromiecraft/chromiecraft/assets/94157725/439f744c-5dd2-4d04-9712-5f7becb7c9fd)
Testing with just weapons



![daggerstone](https://github.com/chromiecraft/chromiecraft/assets/94157725/66fad91e-0abe-4602-a9da-9be813f5ada7)
Testing with sharpening stone

**Comment by Salehyn** [comment] 2023-08-19 02:28
I believe this is working as intended. It used to be a bug on old TBC that the damage boost applied to ranged weapons, which really made no sense. How would sharpening your sword make your bow shoot harder?
Anyway,it was fixed around patch 2.4.
From wowhead: https://www.wowhead.com/tbc/item=23529/adamantite-sharpening-stone#comments


<html><body>
<div class="comment-header">

By RadioBandit (2,020 –  19·33)  on 2008/06/09 (Patch 2.4.1) |   |  
-- | -- | --


</div><div class="text comment-body" lang="en">As of last patch, no longer increases ranged weapon damage. Sorry hunters!</div>
</body>
</html>By [RadioBandit](https://www.wowhead.com/tbc/user=RadioBandit) (2,020 – 19·33) [on 2008/06/09](https://www.wowhead.com/tbc/item=23529/adamantite-sharpening-stone#comments:id=302173) (Patch 2.4.1)		
As of last patch, no longer increases ranged weapon damage. Sorry hunters!

**Comment by Salehyn** [comment] 2023-08-20 10:20
http://web.archive.org/web/20081026213551/http://elitistjerks.com/f31/t15179-hunter_help_me_please/p18/
Further evidence from the 2.1-2.2 patch era that confirms hunters stopped using these stones mid expansion.
"Dual Mana Oils. Dual Wielding allows me to double up on Mana Oils on the longer fights, getting twice as much mana regeneration out of my weapon slot than other classes. If Adamantine Sharpening Stones still worked on range, you could cite that as a rather large benefit as well."

As I understand this was a
blizzlike bug, which made a return on the 2022 classic TBC iteration on live as well (as per your source from the beta discussion), so your report is perfectly sensible, however CC aims for a 3.3.5 patch experience and as such these stones work as intended.

**Comment by BeefSteaker** [comment] 2023-08-20 11:04
Closed as blizzlike

**Closed by BeefSteaker** 2023-08-20 11:04 UTC
Labels: Closed
